### ISSUE TITLE
Menu bars

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1003]
Tomviz 0.9.4 release, windows 10

When first started the menu lists don't render properly. If you select the data transforms menu then the last part of the list is cut off. I can't attach a picture right now but I can later if needed.

The second time you select the menu it renders properly.

**Comment by yijiang1** [comment]
I don't see the problem on my windows 10.

**Comment by ercius** [comment]
Thanks for testing. I closed/reopened it a couple of times with the same
result. I'll double check a couple of other systems tomorrow.

**Comment by cryos** [comment]
I haven't seen this, but will see if I can reproduce it locally.

**Comment by ercius** [comment]
This is only happening on my windows 10 laptop. It did not happen on a win10 desktop at my lab with a discrete Nvidia graphics card. So, its based on hardware. My Dell XPS 13 laptop runs on a Intel HD Graphics 5500.

This is only aesthetic. If you launch the same menu twice then you have access to the entire list.

See the attached phone picture. Getting a screen shots was non-trivial.
![img_20170307_151230](https://cloud.githubusercontent.com/assets/15657108/23716501/58bb61cc-03e5-11e7-87ab-c8b92af97d93.png)

**Comment by Hovden** [comment]
It probably makes sense to create a "Segmentation" top level menu and put the segmentation routines there..

**Comment by cryos** [comment]
Great minds, I was just saying to @cjh1 that splitting off segmentation would shorten this, and possibly avoid some of the issues that may be due to the menu being quite long.

**Comment by cryos** [comment]
#1014 separates the menus out, and will probably help with this issue.

**Comment by cryos** [comment]
This should now be resolved, please reopen if the latest binaries from this evening are still causing issues.
