### ISSUE TITLE
QWindowsWindow::setGeometry warning when opening some UIs

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1004]
binary v0.9.4 on windows 10

When I mark a dataset as tilt series, tomviz prints out this message:

QWindowsWindow::setGeometry: Unable to set geometry 100x30+437+365 on QWidgetWindow/'tomviz::EditOperatorDialogClassWindow'. Resulting geometry:  120x30+437+365 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215). (:0, )

**Comment by cryos** [comment]
Confirmed on one of our test machines here too, this doesn't happen on other platforms, and is a little strange. The interface all shows up as normal, if it wasn't for ParaView displaying all console errors you would never know.

**Comment by cryos** [comment]
This is now resolved in the latest binaries, forgot about the issue, thanks for reporting.
