### ISSUE TITLE
File->Reset doesn't close dialogs

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1005]
File->Reset only deletes everything in the pipeline.
Shouldn't it also close all active dialogs and terminate ongoing transforms?
tomviz crashes if I reset the pipeline when a transform is running...

**Comment by mathturtle** [comment]
You seem to have found another way to delete a running operator.  I'll look into it.

**Comment by mathturtle** [comment]
@cryos Would it be a good enough solution to disable the reset action when there is an operator running similar to how we disable the delete actions?

**Comment by cryos** [comment]
Yes, I think that would be reasonable.

**Comment by cryos** [comment]
This should be resolved now.
