### ISSUE TITLE
Coloring Contour by label map has some glitches

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1009]
* Load SMALL_PtCu_NanoParticle.tif
* Apply Binary Threshold, Lower Threshold = 150, Upper Threshold 255
* Add Contour to SMALL_PtCu_NanoParticle dataset
* Set "Color By" to Thresholded Segmentation and "Value" to 200. The contour should be yellow because it is entirely inside the thresholded region, but it is blue.
* Adjust the color bar scalar range to [0, 1]. No effect.
* In the Contour module, check "Select Color", and uncheck it. Now the contour is yellow as expected.
* Set the "Value" in the Contour module to 135. You should get a mix of blue and yellow cells on the surface, which makes sense.

If I am misunderstanding something, please do let me know.

**Comment by tjcorona** [comment]
@cquammen Thanks for pointing this out! This is definitely not what it should be doing, but I'm not exactly sure what the appropriate behavior should be (when we switch "Color By", should the histogram change?). When following your recipe, another way to get the color to fix itself is to select the "Reset Data Range" (the automagic one, not the manual one). @cryos What do you think the right reactions should be for this set of instructions?

**Comment by cryos** [comment]
So I think we went over this in person and came up with a good plan, let me know if not.

**Comment by tjcorona** [comment]
This should be addressed in the following MR: https://github.com/OpenChemistry/tomviz/pull/1038

**Comment by cquammen** [comment]
Looks like it is all fixed up now. Thanks for fixing, @tjcorona !
