### ISSUE TITLE
Manual axis shift and rotation finding tool (Basic Framework)

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#101]
tomviz should have a tool to help users manually find the rotation and shift of the tilt axis in a tilt series for fine adjustments and when automatic routines do not work.

This could work by showing the user back-projection reconstruction slices from select parts of the tilt series, and the letting them position the axis to minimize artifacts in the reconstruction visually.

**Comment by yijiang1** [comment]
Here is a basic mock-up of the UI. I'll be writing a reconstruction function in C++ so the UI can use it.
![axisalignui](https://cloud.githubusercontent.com/assets/13088588/10553948/d8a71290-742c-11e5-806a-e56ee415c1fa.png)

**Comment by Hovden** [comment]
For this issue, lets just get the basic GUI framework in place.

**Comment by mathturtle** [comment]
The UI shouldn't be too hard to throw together.  Connecting up all the actions and the reconstruction will be the tricky part.

So if I have this right:
The large image in the upper left is an x-y slice of the current data with the z-value controlled by the 'Projection No.' text field.
The yellow line shows the 'center'.  So is this just a static line I can hard code as halfway up the scene or does it move?
The three red dashed lines positions are controlled by the 'slice No.' text fields.  So these text fields are values along the horizontal (X?) axis?
Rotation axis position is a vertical (Y?) offset to the rotation axis (which presumably is a parameter to your reconstruction).
Rotation angle is a rotation about the Z axis applied before reconstruction?
Are rotation angle and rotation axis different for each slice?
What information do you need to generate the reconstruction slices?
What does the create aligned data button do?  Just generate a new dataset that is a copy with this applied similar to the translation align already present in tomviz?

**Comment by Hovden** [comment]
Pretty close, which is good given the minimal set of instructions.

Yes. Large image is x-y slice with z-value controlled by Proj. Number.
No. Yellow line will move up and down by the axis position (in pixels).
Yes. Three dashed lines are controlled by the slice number (in pixels).
Yes. Rotation axis is vertical offset and moves yellow line.
No. Rotation angle will change the angle of the yellow line.
We need the axis position and angle to reconstruct. The gui will run mini reconstructions of the three slices (dashed red lines).
Create aligned data will call a python transform that uses axis position and angle to shift and rotate the data.

Every time the yellow line is adjusted (i.e. rotation axis and angle) we will refresh the three reconstructions using C++ reconstruction code.

Also: A pop-up window might be easiest, and also best. But I'd like your input on how you think this window should behave. For example, should it be a simple pop-up? Or embedded in as a tab in main tom-viz panel? Or as a QT panel that can be moved around and popped out. It shouldn't be modal though.

**Comment by mathturtle** [comment]
I think I'll make it a simple pop-up window for now.  You'll be able to get to it from a menu item on the 'Tomography' menu.  If I just make it a widget, we should be able to move it around fairly easily if we decide that is not the right place for it later.  Unless you expect to spend a lot of time working with this feature, I don't think a tab or a QDockWidget are appropriate.

I think I have enough to get started on this now.  I'll let you know if I think of anything else.

**Comment by yijiang1** [comment]
@mathturtle Sounds good. A pop-up window is enough for now. Thanks!

**Comment by ElliotPadgett** [comment]
@mathturtle Either the yellow line should move (as the user adjusts the axis position and rotation) and the image be static or the image should move and the line be static.  From a user's point of view I don't think it matters so if one of those is much easier to code than the other we should go with that.

**Comment by mathturtle** [comment]
@Hovden I've put up a work-in-progress version of my code for you and @yijiang1 to try out.  Yi has already given me some good feedback (including several bugs I hadn't caught).

**Comment by Hovden** [comment]
Basic framework is good. Closing this. Will open a new issue for the final polish and testing.
