### ISSUE TITLE
Eye icon does not update

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1019]
Binary: 0.9.4-35-g807197b on Mac

The eye icon for visualization modules do not update automatically.

**Comment by cquammen** [comment]
Could you provide more details?

**Comment by cryos** [comment]
I see it on my local Linux build if you just click the eyeball but don't move the mouse. I suspect this is related to @cjh1 fixing the bug where the animation timeout was always running (and causing redraws). I think we have always missed an updated/changed signal for item state.

**Comment by yijiang1** [comment]
> I see it on my local Linux build if you just click the eyeball but don't move the mouse. 

I have the same problem on my local Mac build.

For binary version, I see the problem when there are multiple RenderViews. 
For example, I load a sample tilt series in the first RenderView and a sample reconstruction in the second RenderView.
When the second RenverView is active, I can still turn on/off the Orthogonal Slice module in the first RenderView. However, I can't do the same for Outline module and the eye icon does not update automatically.
<img width="600" alt="screen shot 2017-03-10 at 10 03 35 am" src="https://cloud.githubusercontent.com/assets/13088588/23800067/e0930c50-0578-11e7-8b8c-2b048da88ed8.png">
