### ISSUE TITLE
Improve Gradient Opacity Defaults / UX

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1025]
The gradient opacity feature is an interesting was to visualize volumetric data. Right now it is fairly opaque to it's inner workings.

-There is no clear explanation of what the gradient opacity is doing. My understanding is that it is the gradient magnitude (not the laplacian, or a weighted Fourier filter right?) with a transparency map that is multiplied with the volumetric visualization. If so, shouldn't the x-axis on the histogram be in units of inverse length? Shouldn't the histogram contain values?

-The default check box for gradient opacity should be off in the volume visualization.
-Right now, when the check box is clicked on or off, nothing changes in the visualization because the gradient opacity defaults to a constant. If possible, we should create a default opacity curve that will work for many datasets.

**Comment by alvarosan** [comment]
That is correct, it is the gradient magnitude mapping opacity values (in addition to the scalar opacity of the regular HistogramWidget).  Internally, the volume mapper computes the gradient magnitude on-the-fly and fetches an opacity value from this table.  The gradient magnitude histogram is currently not computed so it is left empty (this is also why the gradient magnitude range is unknown, so the value range is used).

I will do the following:

- Add a label to the lower axis.
- Set gradient opacity default to off.
- Change the default transfer function (currently all ones).
- Verify that the range is what the shader expects.
