### ISSUE TITLE
Screen shots are 2x requested size in each dimension on Retina macs

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1033]
Same behavior is observed in ParaView when high-resolution capable display is enabled.

**Comment by cryos** [comment]
I am going to call this close enough, as the screen shot sizes are passed in as an integer, dividing by 2 leads to a rounding, meaning that any odd number will be rounded down on retinal Macs. Who really wants a 269x100 screenshot? If they do I think a more elegant fix will be required, but this rounds any odd pixel down by one pixel at worst in my testing.

**Comment by cquammen** [comment]
Confirmed, it works reasonably well.
