### ISSUE TITLE
Volume rendering cropped for snapshot data

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1039]
Binary v0.9.4-77-g569e1a9 on Mac

1. Load sample tilt series dataset.
2. Mark it as tilt series.
3. Snapshot the transform.
<img width="261" alt="screen shot 2017-03-14 at 11 07 52 am" src="https://cloud.githubusercontent.com/assets/13088588/23907263/f07be9e4-08a6-11e7-8dd0-4a0366df2860.png">
4. Hide visualizations of the parent data and start a volume rendering for snapshot data.
<img width="247" alt="screen shot 2017-03-14 at 11 08 18 am" src="https://cloud.githubusercontent.com/assets/13088588/23907298/09a96bda-08a7-11e7-965a-b70f32f4ceaa.png">
5. The volume rendering seems clipped.
<img width="451" alt="screen shot 2017-03-14 at 11 08 47 am" src="https://cloud.githubusercontent.com/assets/13088588/23907321/1dee8120-08a7-11e7-8ef6-7aa392bf3ec7.png">

**Comment by cryos** [comment]
I don't see any different in the data, looking at extents, values, isosurfaces. It is possible you are seeing issues with clipping planes, in playing with the data I was able to find some states where it looked like the near/far clipping planes for the volume render alone (with no other modules activ
