### ISSUE TITLE
Make the basic user guide accessible 

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1040]
tomviz comes with a good user guide made by @bdalevin (https://github.com/OpenChemistry/tomviz/blob/master/docs/TomvizBasicUserGuide.pdf).
We should make it easily accessible through the software.

**Comment by yijiang1** [comment]
bump

**Comment by cryos** [comment]
I will take a look, and see about adding this to the packaging process/application menu.

**Comment by cryos** [comment]
@mathturtle if you would like to take a stab at this it is likely to be something I get to late Friday/Saturday.

**Comment by cryos** [comment]
Tested in the latest binaries, and it works great.
