### ISSUE TITLE
Color bar in HistogramWidget shrinks when data range changes.

### ISSUE THREAD

**Issue by alvarosan** [OpenChemistry/tomviz#1057]
1. Load MEDIUM_CoP dataset.
2. File Menu -> Reset
3. Load SMALL_PtCu.

![bug_color_bar](https://cloud.githubusercontent.com/assets/767484/24124450/2bcb713e-0d9a-11e7-94af-c3c664950392.png)

**Comment by cryos** [comment]
Resolved.
