### ISSUE TITLE
Multiple box widgets can be created for Crop operator

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1060]
* Add a Crop operator to a data set. Apply it.
* Double-click the pipeline entry to edit it. Do not apply the edited settings.
* Double-click the pipeline entry again. A second box widget will appear.

You can get as many box widgets as you want by double-clicking the Crop operator as many times as you wish.

**Comment by cquammen** [comment]
You also get multiple dialogs

**Comment by Hovden** [comment]
I would just emphasize that the crop tool is one of the most used features for our analysis in tomviz.

**Comment by cquammen** [comment]
This actually is true for any Operator that has a custom editor widget, not just the Crop editor.

**Comment by cquammen** [comment]
Fixed in #1062.
