### ISSUE TITLE
Color bar does not resize with window

### ISSUE THREAD

**Issue by alvarosan** [OpenChemistry/tomviz#1074]
1. Load dataset.
2. Click on the edge of the window and drag to resize.

![screenshot from 2017-03-22 17 30 57](https://cloud.githubusercontent.com/assets/767484/24221631/79421364-0f25-11e7-884a-515bf4ec2390.png)

**Comment by cryos** [comment]
Confirmed, and it looks like a new regression, I will try to track this down later. I was actually testing a branch and couldn't reproduce, but this issue is present in master...

**Comment by cryos** [comment]
Should be working as expected now.
