### ISSUE TITLE
Crash when opening "About tomviz" dialog

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1081]
Binary v.0.9.4-197-g8a9c881. Mac

**Comment by cjh1** [comment]
This is because of #1064 this package is broken.

**Comment by cquammen** [comment]
Yep. It consults Python, and once Python is fixed in the Mac package, this will be fixed.

**Comment by cryos** [comment]
We had everything working in one of the recent builds, just some warnings.

**Comment by cryos** [comment]
As in the other bug, we would appreciate confirmation but it should be working as expected in recent builds.

**Comment by cryos** [comment]
This is fixed in the latest binaries, 0.9.4-220 or later should work without issue.
