### ISSUE TITLE
Camera position wrong when loading state file with slice module

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1095]
Create a state file where the only visible module is a non-orthogonal slice.  When loading it back in, the camera position (either default or reset) is not useful for seeing the module.  (in my testing the slice was offscreen completely).  Probably not a big deal since most people will leave the outline visible when slicing and the outline will help the camera find a good position.

**Comment by cryos** [comment]
This works fine now, much has changed, closing.
