### ISSUE TITLE
Colormap: "Rescale to custom range" does not work for zero lower bound

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#111]
This probably needs to be fixed upstream in Paraview.  

If I use the "Rescale to custom range" tool I can set any value but zero for the colormap lower bound.  If I pick zero the tool does nothing.  This does not appear to be a problem for the upper bound.

I checked that this happens for both contours and orthoslices.  Can someone else confirm this behavior?

**Comment by Hovden** [comment]
I am not having this problem. I can set any value in the colormap bounds to any value, including negative values.

**Comment by ElliotPadgett** [comment]
Ok, I don't have it always either.  It doesn't happen with the sample data for me.  I am testing on OSX.

**Comment by Hovden** [comment]
@ElliotPadgett Any updates with this? Can you test if this issue remains in the latest builds?

**Comment by ElliotPadgett** [comment]
Yes, I just checked it out a little more.  The problem still occurs on the latest OSX nightly, but I can only make it happen under special conditions.  To reproduce the problem I think you need a volume that has only 0 and 1 values.  Move the lower bound of the color map from zero and then you can't get it back.

I tried it with a three-value (0,1,2) discrete data set and more typical data sets and it worked fine.

**Comment by mathturtle** [comment]
@ElliotPadgett can you share your dataset with only 0 and 1 values?

**Comment by ElliotPadgett** [comment]
No problem.  I will try to get this to you today or tomorrow.

**Comment by ElliotPadgett** [comment]
I just verified that this is still a problem in the 0.6.1 binary and the behavior looks the same.  I will email you a test data set.

**Comment by mathturtle** [comment]
@ElliotPadgett did you ever send the dataset?  I just checked my spam filter and didn't find it there.  Was it too large to email?

**Comment by Hovden** [comment]
Yeah he sent it. I just forwarded it again.

**Comment by mathturtle** [comment]
It turns out this is a bug in ParaView.  I'll put an update when I have a fix.

**Comment by Hovden** [comment]
:ok_hand:

**Comment by mathturtle** [comment]
ParaView merge request is [here](https://gitlab.kitware.com/paraview/paraview/merge_requests/372)

**Comment by mathturtle** [comment]
The ParaView change has been merged.  I have a superbuild PR to update paraview [here](https://github.com/OpenChemistry/tomviz-superbuild/pull/51).  Building against ParaView master should also fix this.

**Comment by mathturtle** [comment]
@ElliotPadgett This should be fixed in today's binaries (which may not have finished building yet...)

**Comment by Hovden** [comment]
@ElliotPadgett Can you test / verify this and we will close the issue.

**Comment by ElliotPadgett** [comment]
Looks fixed in latest binary!
