### ISSUE TITLE
Histogram font is tiny on Mac retina display

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1122]
Almost all other text and icons are fine, but the text labels on the histogram are very small on my Mac retina display.  Update: Looks fine on a Mac with regular displays.

**Comment by cquammen** [comment]
Confirmed.

**Comment by ElliotPadgett** [comment]
Actually I found that the outline axes labels are impacted by this as well.

**Comment by Hovden** [comment]
I don't mind it. But I was the person that cranked the CRT pixel density to an obscene value.

**Comment by cquammen** [comment]
#1126 was merged, so this should be fixed now.
