### ISSUE TITLE
Setting current image = 0 crashes in manuel alignment tomviz

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1130]
1. Open manual alignment tool
2. Setting current image to 0 
Tomviz crashes

[Windows]

**Comment by mathturtle** [comment]
I'll look at this.

**Comment by mathturtle** [comment]
Hmmm, doesn't happen here on Linux.  I'll try on Windows.

**Comment by mathturtle** [comment]
It doesn't happen on Windows either.  I'm not sure what you did but I can't reproduce it.

**Comment by cquammen** [comment]
Could not reproduce on macOS either. @Hovden If you could specify step-by-step directions you took that led to the crash (data set loaded, menu items selected, etc.)? That might get us closer to reproducing the issue.

**Comment by cryos** [comment]
I also failed to reproduce this, and looking at the code I don't see an obvious bad path.

**Comment by yijiang1** [comment]
I can't reproduce this either.

**Comment by Hovden** [comment]
Ok. We were using a dataset from nat.data paper. I guess just close this until I can provide more details.

**Comment by cryos** [comment]
Closing for now, please reopen if you have a recipe to reproduce
