### ISSUE TITLE
Data Transform Dialogues (progress bars) do not appear when loading states

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1132]
1. Create a pipeline of data steps (e.g. auto alignment (XCORR).
2. Save State.
3. Clear and reload state.
Progress bars do not appear and you are left guessing the time it takes to calculate.

**Comment by cjh1** [comment]
Should be fixed by #1142

**Comment by cjh1** [comment]
#1142 resolves the progress issue, however, the color map and control points are not restored until the execution of the pipeline is complete. Fixing this up will require a little more work.

**Comment by cryos** [comment]
Thanks @cjh1, glad we could find a simple fix.
