### ISSUE TITLE
Adjust camera perspective

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#114]
It is important to be able to adjust the camera perspective. [probably good in both Paraview and tomviz view properties]

The best solution would be in the view properties having a perspective slider or input that allows the user to pick the level of perspective wanted. Exploring data with no perspective is a useful task for producing interpretable scientific visualization or looking down a high-symmetry zone axis.

For the simplest solution, this would be enabling rotation in the 2D camera view mode, where the user can flip between no perspective (2D mode) and some perspective (3D mode).

**Comment by cryos** [comment]
We would normally label it parallel projection or orthographic projection - it is still 3D but with no perspective applied. It shouldn't be a problem to offer a switch between the two modes.

**Comment by mathturtle** [comment]
So to be clear: Is what we want this slider in the view properties or for the interactor style when that button says 2D to allow 3D rotation?   Do we want to relabel that button (I'm not sure ParaView exposes this)?

**Comment by cryos** [comment]
In the first instance I want to expose the the tick box for "Camera Parallel Projection", but we should have two entries in the view menu for view mode - perspective and orthographic is what I am used to seeing (and what many other applications use).

**Comment by cryos** [comment]
It is in the view menu, but the same as the axes visibility - hidden, and using terms that aren't as easily recognized.

**Comment by mathturtle** [comment]
Notes to self (can't think of anywhere else to put this): You can disable all of the little buttons above the view by putting `<StandardViewFrameActions default_actions="none" />` in the Hints for the view proxy.  We'd have to override the default view.
