### ISSUE TITLE
"Separate color map" feature broken for contour

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1145]
The "separate color map" check box appears to be broken for contour renderings.  to replicate the problem:
1) open sample data (and leave up slice rendering)
2) add contour rendering
3) check "separate color map" and change the color map
When this is done the contour does not change color, but the pre-existing slice will change color!  Also, the colormap histograms change for the dataset and the slice, but if you click away and click back to the contour rendering, it keeps the default colormap.  It looks like changing the colormap impacts all objects except the selected one.

**Comment by cryos** [comment]
I will see what  I can do, we added some special features to contour, and they are causing this off behavior. Thanks for reporting the issue.
