### ISSUE TITLE
"Show legend as cube" menu item crashes tomviz

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1146]
I don't know what this thing is supposed to do, but when I click it the program crashes.

**Comment by yijiang1** [comment]
I don't have see this bug on Windows 10. Maybe it only crashes on Mac.

**Comment by Hovden** [comment]
It works ok on the osx 1.0 release I have.

**Comment by ercius** [comment]
This crashed for me on Windows 10 after playing with an RC1 install
yesterday. However, with a fresh tomviz instance it worked. So, it's not a
trivial thing to reproduce.

**Comment by ElliotPadgett** [comment]
Ok, let me check again and see if I can reproduce the conditions.

**Comment by cryos** [comment]
I don't see a crash, but do see some issues where it doesn't always render. I will see if I can get to the bottom of it.

**Comment by Hovden** [comment]
Crashes on my OSX (10.12.5)

**Comment by cquammen** [comment]
I couldn't reproduce on macOS 10.11 or Ubuntu 16.04 on a recent master (33a4b94234040a7558415d07319be77a0ccdd8b2).

**Comment by Hovden** [comment]
No longer crashes. However, a check does not appear on the menu "show legend as cube". Add check and close this issue.
