### ISSUE TITLE
font size too big on histogram - numbers overlap

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1153]
When we fixed the font size for the histogram it was made too big. We need that Goldilocks font size. Maybe 1/2 the current size.

<img width="960" alt="screen shot 2017-04-04 at 10 55 04 am" src="https://cloud.githubusercontent.com/assets/6197997/24663261/64ba61bc-1925-11e7-96f4-d6b5ad2f49db.png">

**Comment by cquammen** [comment]
I would say the font size is reasonable, but the overlap is not. That's a bug in the axis implementation that should be fixed in VTK.

**Comment by Hovden** [comment]
This screenshot loses some context. The axis font is larger than the other text in the program. I would say the axis should have a font no bigger, and probably smaller than the rest of the application.

**Comment by cryos** [comment]
I will take a look, I tend to agree that the text should be on bigger than what we have in the application and it feels a little big to me too. The overlap should be handled by the vtkAxis, but reducing the font size will at least alleviate issues a little.

**Comment by cryos** [comment]
I have merged a few changes tweaking the DPI passed to VTK, we took a look on a retinal iMac, and on my Dell Linux laptop running a hi-DPI screen. It is not perfect, but I think it is a good workaround. It looks like there are some issues with the DPI code, as the fonts seem to get too large as the DPI increases. The latest builds should show the new behavior.

**Comment by cryos** [comment]
I think this was resolved for 1.0.0, and I just added a few tweaks for the upcoming 1.0.1 bug fix release. Let me know if the nightly binaries still exhibit issues, there are a few chart bugs I need to dig into at the VTK level to assure that tick labels do not overlap.
