### ISSUE TITLE
WebExport does not support Python 3

### ISSUE THREAD

**Issue by thewtex** [OpenChemistry/tomviz#1158]
`File -> Export to Web...` is currently broken:

```
Traceback (most recent call last):
  File "/home/matt/bin/Tomviz-1.0.0-32-ge065431-Linux-64bit/lib/tomviz/site-packages/tomviz/web.py", line 64, in web_export
    export_contours_geometry(dest, **kwargs)
  File "/home/matt/bin/Tomviz-1.0.0-32-ge065431-Linux-64bit/lib/tomviz/site-packages/tomviz/web.py", line 458, in export_contours_geometry
    for key, value in simple.GetSources().iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by cryos** [comment]
Thanks @thewtex, must have missed these in last minute changes as we were preparing the release. We will hopefully get it fixed up soon.

**Comment by cryos** [comment]
The #1160 PR fixed the code in Tomviz, but the [VTK](https://gitlab.kitware.com/vtk/vtk/merge_requests/2666) PR (merged), and the [ParaView](https://gitlab.kitware.com/paraview/paraview/merge_requests/1530#note_249521) PR are needed. This will require bumping ParaView once the outstanding PR has been merged.

**Comment by cryos** [comment]
Should be fixed in the latest binaries, there were a few levels to work through, apologies for the delay.

**Comment by thewtex** [comment]
@cryos great, thanks!
