### ISSUE TITLE
Opacity entries in the animation timeline have no effect

### ISSUE THREAD

**Issue by thewtex** [OpenChemistry/tomviz#1159]
A camera entry in the animation timeline works, but opacity on a Volume, Contour, or Orthogonal Slice have no effect.

**Comment by Hovden** [comment]
I noticed this too, but I wasn't sure if I was using the animation tool correctly.

**Comment by cryos** [comment]
This needs some work, the view the animation tool has on the scene is rather limited right now due to the advanced features not being exposed to the proxies.

**Comment by cryos** [comment]
Closing this, will track updated animation tool work in another issue.
