### ISSUE TITLE
Export orthoSlice and nonOrthoSlice as TIF

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1164]
I wanted to revisit #419. Extracting a slice as an image file is a common task I want to complete using tomviz. This is very useful for making figures for journal articles.

I wrote a VTK script in python to implement [vtkImageReslice()](http://www.vtk.org/doc/nightly/html/classvtkImageReslice.html) and [vtkImageSlabReslice](http://www.vtk.org/doc/nightly/html/classvtkImageSlabReslice.html). I want to take the point/normal output from tomviz and recreate the exact slice of the data. Then I can set the sampling and extract a slab as well.

The issue I have is that vtkImageReslice uses a SetDirectionCosines() function. It is not exactly clear to me how to determine this Matrix only using the point and normal reported by tomviz. I think vtkNonOrthoImagePlaneWidget.cxx uses 2 points (SetPoint1 and SetPoint2) to determine the imageReslice plane, but its hard for me to follow exactly how these points are determined to keep the slice from rotating around the normal.

Looking through the source code of vtkNonOrthoImagePlaneWidget.cxx there exists a GetResliceOutput(). Is there a way to call this from a python console within tomviz? Or can I get the Matrix4x4 used to set the direction cosines in vtkImageReslice?

Lastly, tomviz needs a GUI button in the Properties panel of the Slice and OrthoSlice modules to export the slice to an image file. I think we just need to connect a Writer to GetResliceOutput() and implement a GUI button.

**Comment by cryos** [comment]
Totally agree, it was on my list to connect more of the visualization modules to writers. You can also write out the triangles of a contour to an STL file for 3D printing, and of course slices to images. Thanks fro bringing this up, I will see if we can get this added soon.

**Comment by mathturtle** [comment]
See #1242.

**Comment by cquammen** [comment]
#1242 is merged. Can we close this?
