### ISSUE TITLE
Leaks reported when tomviz is quit

### ISSUE THREAD

**Issue by utkarshayachit** [OpenChemistry/tomviz#117]
If you build ParaView with VTK_DEBUG_LEAKS ON, simply starting and quitting tomviz reports the following leaks.

    vtkDebugLeaks has detected LEAKS!
    Class "vtkPVXMLElement" has 2 instances still around.

**Comment by mathturtle** [comment]
@utkarshayachit That was a pain to track down, but I have a fix pushed up.

**Comment by utkarshayachit** [comment]
+2
