### ISSUE TITLE
Segfault with ParaView 5.4

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#1170]
```
ERROR: In /home/cjh/work/source/paraview/ParaViewCore/ClientServerCore/Rendering/vtkPVDataDeliveryManager.cxx, line 404
vtkPVDataDeliveryManager (0x21712e0): Invalid arguments.


Generic Warning: In /home/cjh/work/source/paraview/Qt/Core/pqOutputWindow.cxx, line 99
pqOutputWindow was deprecated for ParaView 5.4 and will be removed in a future version.


ERROR: In /home/cjh/work/source/paraview/ParaViewCore/ClientServerCore/Rendering/vtkPVDataDeliveryManager.cxx, line 404
vtkPVDataDeliveryManager (0x21712e0): Invalid arguments.


ERROR: In /home/cjh/work/source/paraview/ParaViewCore/ClientServerCore/Rendering/vtkPVDataDeliveryManager.cxx, line 404
vtkPVDataDeliveryManager (0x21712e0): Invalid arguments.


ERROR: In /home/cjh/work/source/paraview/ParaViewCore/ClientServerCore/Rendering/vtkPVDataDeliveryManager.cxx, line 404
vtkPVDataDeliveryManager (0x21712e0): Invalid arguments.


ERROR: In /home/cjh/work/source/paraview/ParaViewCore/ClientServerCore/Rendering/vtkPVDataDeliveryManager.cxx, line 404
vtkPVDataDeliveryManager (0x21712e0): Invalid arguments.


ERROR: In /home/cjh/work/source/paraview/ParaViewCore/ClientServerCore/Rendering/vtkPVDataDeliveryManager.cxx, line 404
vtkPVDataDeliveryManager (0x21712e0): Invalid arguments.


Segmentation fault (core dumped)
```

**Comment by cjh1** [comment]
@jourdain @utkarshayachit Any ideas what might be causing this?

**Comment by jourdain** [comment]
Was it when starting Tomviz? Or else?

**Comment by cquammen** [comment]
I believe this is related to https://gitlab.kitware.com/paraview/paraview/issues/17471. I get the same `vtkPVDataDeliveryManager` error when working around the segfault in that issue. It seems to have to do with the recent addition of `vtkPVGridAxes3DRepresentation`.

**Comment by cryos** [comment]
Thanks for the info @cquammen

**Comment by cryos** [comment]
@cjh1 any hints on reproducing it, I haven't been able to make it happen with latest master.

**Comment by utkarshayachit** [comment]
@jourdain does ParaViewWeb use `InteractiveRender`?

**Comment by jourdain** [comment]
Yes PVW use InteractiveRender, but normally not within the export scripts of Tomviz.

**Comment by cryos** [comment]
I am going to close this for now as I have been unable to replicate the segfault. We should keep an eye out, but hopefully this won't present major issues.

**Comment by jourdain** [comment]
(FYI) The final release of PV 5.4 does include the fix for interactive render.

**Comment by cryos** [comment]
Thanks for the confirmation, that is what I used for our 1.0.1 release so we should be great.
