### ISSUE TITLE
"processing tilt image" no. misleading?

### ISSUE THREAD

**Issue by CSchank** [OpenChemistry/tomviz#1176]
When performing an auto alignment, the bottom-left displays "Processing tilt image No.180/180" for example, but since it did the alignment out of order and seems to display the current image you're working on, it could be confused with displaying how many images have been processed. In the case of 180/180, this could be interpreted as almost being done (on last image), only to jump back to 90/180.

**Comment by cryos** [comment]
We should figure out what we want to do here, I think it is more informative to know how far through it is, than give the number of the image in the stack as most of us assume this is a measure of progress.

**Comment by CSchank** [comment]
Yes, those were precisely my initial reactions / thoughts.
