### ISSUE TITLE
manual axis of rotation screen - delay to reduce lag?

### ISSUE THREAD

**Issue by CSchank** [OpenChemistry/tomviz#1177]
UI can seem laggy because of rebuilding reconstruction on each UI input, especially on lower-power computers. Would it perhaps be possible to, for example, wait half a second between inputs (pressing arrows, etc) before reconstructing so that the UI feels snappier? Or some other method, such as cancelling the current reconstruction as soon as a button is pressed?

**Comment by cryos** [comment]
That is a good idea, we should look into it. We could push these things into a timer, and keep resetting until nothing is changed for a second perhaps. I will see about getting to this.

**Comment by cryos** [comment]
This should now be resolved, and should have been in the 1.1.0 release. Please reopen if this is still an issue.
