### ISSUE TITLE
Mac 10.9.5 Tomviz not showing volume

### ISSUE THREAD

**Issue by dakotamarieb** [OpenChemistry/tomviz#1178]
When inputting in my own or sample data I cannot see a visualization. Anyone know what's up? 

![screen shot 2017-05-31 at 4 22 57 pm](https://cloud.githubusercontent.com/assets/29106542/26652496/15e59d06-461e-11e7-91ba-be60fbab4690.png)

**Comment by cryos** [comment]
Can you paste a screen shot of the tomviz -> About dialog, it will contain information about your graphics card as the application sees it. The chart is all white too, what kind of Mac is this?

**Comment by cryos** [comment]
This looks like it is an issue with the graphics card/graphics card driver. Without further information there is little we can do to help. Closing this issue, please reopen if you can supply more information. Tomviz 1.2.0 is out, and 1.2.1 will be released shortly, but we have no known bugs causing behavior such as shown above.
