### ISSUE TITLE
Web export

### ISSUE THREAD

**Issue by rqus** [OpenChemistry/tomviz#1180]
![tomviz_err](https://user-images.githubusercontent.com/29566092/27355516-95ee7962-560b-11e7-90e6-92ba87ad4d86.jpg)
The web export does create images for the viewer, however, the .js file is not created correctly. (Tomviz 1.0, Windows)

**Comment by cryos** [comment]
Could you give more details, and confirm this is still the case with Tomviz 1.0.1. I can give this a try on Windows, it would be good to know what web export options you were using.

**Comment by rqus** [comment]
Thank you for the reply. This is what I did and the errors I received on 1.0.1 version. However, my colleague tried to do this on Linux and to no success as well…

File -> Export to web…

**Comment by cryos** [comment]
So just default web export, if you click on the file export and choose a directory do things work better? We may need to improve the dialog, I am tied up today, but will see if I can reproduce this. I think there are a few ways to improve the dialog, and appreciate your feedback.

**Comment by rqus** [comment]
The options don’t change the result. I have sent you two screenshots previously – did you receive that? The images are exported correctly, but the actual web viewer is not created. Anyway – take your time.

**Comment by cryos** [comment]
I don't see any screen shots, they are possibly lost through the email to web interface. You can paste them into the form on the web page, but if you look at the issue all there is here is text. We will look into it.

**Comment by Tokariew** [comment]
to fix this isue lines 119-120 and 159-161 should look like this:
` 
        with open(srcHtmlPath, mode='r', encoding="utf-8") as srcHtml:
            with open(dstHtmlPath, mode='w', encoding="utf-8") as dstHtml:
			
                with open(srcHtmlFile, mode='r', encoding="utf-8") as srcHTML, \
                        open(srcJsFile, mode='r', encoding="utf-8") as srcJS, \
                        open(dstHtmlFile, mode='w', encoding="utf-8") as dstHTML:`
otherwise python probably try to use system encoding

**Comment by cryos** [comment]
Hadn't thought of system encoding getting in the way here, thanks for the tip. We can take a look at this, I will see if I can reproduce by changing the system encoding too.

**Comment by cryos** [comment]
If you get a chance it would be good to take a look at this too @cjh1
