### ISSUE TITLE
Add Color Legend Button for Views

### ISSUE THREAD

**Issue by rqus** [OpenChemistry/tomviz#1181]
Colorbar in the visualization view, which normally works in Paraview is not available in Tomviz. This feature would be extremely useful for optical diffraction tomography / tomographic phase microscopy reconstruction data.

**Comment by cryos** [comment]
I think this is the issue tracking the #1360, it didn't come up when searching for color or legend, I will update the title a little so that they are easier to correlate.

**Comment by cquammen** [comment]
Basic color legend functionality is in place. Please open new issues for requests to modify the appearance of the color legend.
