### ISSUE TITLE
Problems installing tomviz 1.0.1 on Windows 7

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1182]
Trying to install tomviz 1.0.1 on Windows 7 using the .msi file.  The installer starts and gets partway through before throwing this error: "The System Administrator Has Set Policies to Prevent This Installation”.

I tried several common suggestions found through Google for this error, but nothing worked for tomviz.  In any case, it would be best if users didn't have to mess around with registry hacks to get tomviz installed.

This does not appear on Windows 10.

**Comment by ElliotPadgett** [comment]
I got it to install in an administrator command line with "msiexec /i" but that may be a little much for most windows users.

**Comment by cryos** [comment]
That is odd, I tested the install on Windows 7, but I think the account was an administrator. I take it you are running with a limited account? Nothing changed with the MSI installer that I am aware of, but I can look into how we might make this simpler. It will need admin rights to install, and this is why we provide a .zip file that can be used from the home directory.

**Comment by mathturtle** [comment]
Same here, the account I used was administrator.  But I think you have to have admin privileges to writer to `Program Files` or some of the other things touched by the MSI installer.  If your account is not admin, then you should be using the .zip.

**Comment by cryos** [comment]
I think to install into Program Files you need admin rights, if you want to install elsewhere we offer the .zip file that contains a relocatable install tree, this can even be run out of your home directory/from a flash drive.
