### ISSUE TITLE
Program Slows to a Crawl under Volume Visualization

### ISSUE THREAD

**Issue by michaelccao** [OpenChemistry/tomviz#1184]
Most visual renders seem fine, but once I enable the volume visualization, the program runs extremely slow and there is a significant lag in responding to any commands.  Everything returns to normal by just disabling the volume view.  What I find strange is that despite the program running very slowly, other programs run fine, so it doesn't seem like it's due to the computer's resources being used up.

Here are my relevant specs:

Windows 10
Intel 4000 HD Graphics
4 GB Ram (Tomviz used about 700 MB)

I have tried updating the graphics driver as well as running the program as administrator to no avail.

**Comment by mathturtle** [comment]
I suspect that when doing volume rendering, tomviz is detecting that the volume won't fit into your graphcis card's memory and falling back to CPU-based volume rendering which is very computationally expensive.  I'm not very familiar with the inner workings of the volume rendering code though, @alvarosan might be able to give more details.

**Comment by michaelccao** [comment]
In that case, would the increased CPU usage show up in the task manager?  I opened up the task manager and viewed it while toying with the volume rendering and the CPU usage didn't go above 4%.

**Comment by michaelccao** [comment]
Additionally, even a weighted back projection with N = 10 still resulted in a very slow volume render.

**Comment by Hovden** [comment]
This lag looks like an onboard graphics card limitation (intel i5, ~5years old). It is behaving like our older versions of tomviz. I'm concerned this may be a hardware limitation.

**Comment by cryos** [comment]
Tomviz always uses the GPU volume renderer, the fallback is no longer available. Older Intel GPUs have quite poor performance for volume rendering, I am not sure there is much that can be done to improve it.

**Comment by Hovden** [comment]
I think we should close this, it is challenging to support older graphics cards. Michael said he would not be offended.
