### ISSUE TITLE
(Manual Alignment) Focus needs to be reset by clicking on image

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1187]
In the manual alignment tool, the keys will not be responsive unless the user clicks on the image.

**Comment by mathturtle** [comment]
This has bothered me for a while.  It has to do with how the Qt's focus works and that any text field you edit eats the key events even if it is prohibited from displaying anything but numbers.

**Comment by mathturtle** [comment]
I can make this a bit better, but the main issue is that the QSpinBoxes for slice number and such already have actions for the arrow keys.  Up/down change the number in the spinbox and the left and right arrows change the cursor position.  While the spin box has focus, these actions take precedence.  If I start stealing events from the spin boxes to grab these it will make the UI very strange compared to other UIs with the same widget (I tried it out and it does work).

**Comment by cryos** [comment]
This should now be resolved.
