### ISSUE TITLE
Pipeline: Vis associated with parent dataset should appear above children.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1189]
The viz items in the pipeline should appear above all of the child datasets. Maybe above the transforms too.

**Comment by yijiang1** [comment]
Basically this is same as #907

**Comment by ercius** [comment]
This caused a lot of confusion with users during the tutorial. I think it's
important to change.

Also, I suggest automatically selecting the reconstruction in the pipe line
after the recon finishes. Adding a bounding box and orthoslice to the
reconstruction might also help.

**Comment by cryos** [comment]
It would be great to be there for the next tutorial to see more of this firsthand. I think there are a number of updates planned for the pipeline in the next phase of development. It would be good to gather ideas in this bug report, or a tracking report. I would love to learn more about the tutorial in general, what kind of users were there, workflows, any slides you might be able to share.

**Comment by cryos** [comment]
Driving issue being tracked in #1322, that issue will resolve this once it is complete.

**Comment by cjh1** [comment]
Just to clarify that we are all on the same page here. We are say that the following  pipeline:
![screen](https://user-images.githubusercontent.com/1031053/37540345-f583f1f0-292c-11e8-9871-7d6dd79c97bc.png)

Should become:

![screen2](https://user-images.githubusercontent.com/1031053/37540357-02d2dad8-292d-11e8-91b2-1998f71a704a.png)

Is that correct?

**Comment by cryos** [comment]
That is correct.

**Comment by Hovden** [comment]
Yes.

**Comment by cjh1** [comment]
Fixed by #1443
