### ISSUE TITLE
Tomviz will not launch while using Windows Remote Desktop

### ISSUE THREAD

**Issue by CSchank** [OpenChemistry/tomviz#1192]
OS: Windows 10 Pro (fully up to date as of June 26th, 2017)
Tomviz 1.0.0 installed with Windows installer will not launch when launched with Microsoft Remote Desktop Connection -- seems to open process for a small amount of time (~2s) (can see it briefly in Task Manager) then crashes before the loading screen or icon on the taskbar even comes up. Running as administrator also behaves the same way.

However, it seems to work as usual if you launch the program BEFORE connecting with Remote Desktop. Then when you connect, you can use it fine. Strange indeed, and perhaps not super high priority for you, but we do have powerful workstations that we use remotely, so perhaps there's an easy fix?

**Comment by mathturtle** [comment]
This has to do with the version of OpenGL that Windows gives tomviz when running normally vs remote desktop.  Basically Windows pretends it doesn't have a graphics card when running under RDP and tomviz isn't handling that correctly: it shouldn't crash, it should give you an error and exit.  There was some work on this recently to at least give better error messages in this case, and I think that it is in 1.0.1.

The workaround that was suggested by someone on the ParaView list is to write a batch file that kills your RDP session and then starts the application (in this case tomviz) on the normal desktop where it has a connection to the graphics card.  Then you can RDP in again and use it.  Here is the relevant thread: http://vtk.1045678.n5.nabble.com/OpenGL-backend-1-1-vs-2-0-td5743167.html#a5743175

**Comment by CSchank** [comment]
Ah, thank you very much! I should have done more research. Perhaps this can somehow be integrated into the menu that tells you about the error? So you detect that they're on RDP and then offer a button that would perform the workaround (ie runs that .bat).

**Comment by ercius** [comment]
I had this same problem: #927 . I was unable to get this suggested fix to work with tomviz using the following batch file in Windows 10:
``` batch
tscon 1 /dest:console 
start "C:\Program Files\tomviz\bin\tomviz.exe" 
```
Im not sure if there is a way to get around this problem currently.

**Comment by mathturtle** [comment]
So I got some more details on this from the ParaView team last week.  It seems that when you first log in, Windows sets up its graphics environment based on how you logged in.  If you logged in to the machine locally it will use whatever graphics card hardware is available and RDP-ing in later will keep the graphics card initialized, but if your initial login is via RDP then you get an environment with no OpenGL support because Windows skips the initialization of the graphics hardware.

**Comment by cryos** [comment]
This is a general issue with OpenGL in Windows RDP, hopefully they will improve this someday. Closing for now, it may be useful to add some documentation in the future to help people if there are workarounds.
