### ISSUE TITLE
-1*values in manual alignment widget and properties window

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1193]
tomviz 1.0.0 on windows 10 64-bit.

The values shown in the Tilt axis alignment (manual) widget are the negative value compared to those shown in the properties panel after the tilt axis alignment has been applied.
1) Correct the tilt axis alignment with these values:
![image](https://user-images.githubusercontent.com/15657108/27751131-b765c10a-5d8f-11e7-95bd-f0dc7a209ec5.png)
2) Press Transform Data to Axis of Rotation
3) Click on the Shift (or Rotate) transform in the pipeline
4) The properties panel shows -1*value entered in Tilt axis widget boxes
![image](https://user-images.githubusercontent.com/15657108/27751185-f83dff4e-5d8f-11e7-88b1-0f8ceafa444c.png)
![image](https://user-images.githubusercontent.com/15657108/27751209-0f924632-5d90-11e7-8bfa-1013661c2f93.png)

I am not sure which is "correct" according to the conventions of the ndimage.interpolation.shift() and ndimage.interpolation.rotate() functions actually applied.

**Comment by mathturtle** [comment]
I can flip the sign shown in the dialog so that it matches the properties panel as a short-term solution.  But I think in the long term we want to change the shift and rotate operators to something else so that you can get the manual rotation alignment UI back after closing it.

**Comment by cryos** [comment]
This was addressed in #1219, it would be great to hear if this feels/looks more consistent. Closing for now, please reopen if this doesn't look right when you get a chance to look at the updated binaries.

**Comment by ercius** [comment]
checked this in tomviz 1.0.1-68 and it looks consistent to me. Thanks for implementing this fix.
