### ISSUE TITLE
Cant save TIFF as double precision

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1194]
tomviz 1.0.0 on windows 10 64-bit.

The save data function when using TIFF as the contained file type does not work for data which is type double. The best option is to cast to float32 before saving to TIFF in the save data function. Double precision is probably not needed.

**Comment by Hovden** [comment]
This has caused a lot of problems for users. We could drop double precision.

**Comment by cryos** [comment]
I think defaulting to single precision would be good for many reasons, but had it on my mind to make our save feature a little more intelligent by offering some conversions for formats that do not support all types (such as TIFF).

**Comment by cryos** [comment]
This should be resolved in master, and the next binary that gets built soon. It silently converts to float, we can certainly modify the behavior further but I think this is better than warning and refusing to save the data.
