### ISSUE TITLE
No suitable VTK data type for np.sqrt() transform

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1196]
tomviz 1.0.0, windows 10, 64-bit

A strange issue occurs when running the default custom transform np.sqrt() on the sample tilt series. Apparently, applying np.sqrt() to an uint8 dtype produces a float16 dtype. VTK does not have such a dtype (not surprisingly).

This error might appear for other datasets in the future with the same dtype. Adding data type checking in tomviz.utils.set_array() could fix this.

To reproduce:
1) Load sample tilt series
2) Click Data Transforms --> Custom Transform
3) Press OK

The error:
```
Traceback (most recent call last):
  File "Transform Data", line 24, in transform_scalars
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\utils.py", line 101, in set_array
    vtkarray = np_s.numpy_to_vtk(arr)
  File "C:\Program Files\tomviz\lib\paraview\site-packages\vtk\util\numpy_support.py", line 144, in numpy_to_vtk
    vtk_typecode = get_vtk_array_type(z.dtype)
  File "C:\Program Files\tomviz\lib\paraview\site-packages\vtk\util\numpy_support.py", line 70, in get_vtk_array_type
    'Could not find a suitable VTK type for %s' % (str(numpy_array_type)))
TypeError: Could not find a suitable VTK type for float16
Failed to execute the script. (:0, )
```

**Comment by mathturtle** [comment]
We should probably handle unsupported types (I doubt this is the only one) by converting them into some default.  Maybe float32 as the default?

Do we also want to handle datatypes that tomviz doesn't handle well like this?  I know some parts of tomviz don't like double/float64 data (I think that is only the tiff writer though).

**Comment by cryos** [comment]
I think double is only really an issue for the TIFF writer, as it only supports single precision. In that case we should warn the user it is being converted to float, and save it as such. I can't think of any other parts that have issues with double precision numbers.

I think I remember @cquammen did some work mapping types for ITK in the Python world. We should probably extend that/mirror it for VTK. I think we support the integer types, but if it is integer type and we need to convert it should be a more accurate integer type. If it is float and we need to convert a more accurate float type would work - in this case float32.

**Comment by ercius** [comment]
It would be good to at least change the custom transform to work properly "as is" if the datatype conversions are not finished for 1.1.0. It looks bad when default transform fails.

**Comment by cryos** [comment]
I have a proposed fix that works well locally, we should hopefully have something merged very soon that is more generally robust.

**Comment by cryos** [comment]
This is now merged, thank you for the report this should make the default experience much better. Agreed on making example scripts robust.
