### ISSUE TITLE
Issue when changing custom transform function name

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1198]
tomviz 1.0.0, windows 10 64-bit

Changing the name of the custom transform after the def statement can give strange behavior causing the transform to run a "cached" version or not at all.

- Simple workaround is to **not change the function name**.

To reproduce:
1) Load sample data
2) Open custom transform
3) Replace all code with simple print('Hello world'):
```
def transform_scalars(dataset):
    print('Hello world')
```
4) Apply transform and get output: Hello world
5) Change name and code:
```
def transform_scalars2(dataset):
    print('Hello world2')
```
6) Apply transform and get incorrect output: Hello world
7) Change function name to original:
```
def transform_scalars(dataset):
    print('Hello world2')
```
8) Apply transform and get correct output: Hello world2

To avoid future confusion:
If users are not supposed to change the function name then either ignore it or dont let the user change it.

**Comment by mathturtle** [comment]
> If users are not supposed to change the function name then either ignore it or dont let the user change it.

Given how the python interpreter works and how we define the transforms to work, this is the right solution.  That said, how do you prevent it?  We want the user to be able to define helper functions and then use them in the transform, so they have to be able to edit above the `def transform_scalars` line.  Probably the best solution is to clear the defined function before reloading the python code so you don't get a cached version and then warn/error when the function name has been changed (we can't find the symbol).  But I'm not sure how possible that is.

**Comment by ercius** [comment]
Are you sure that the user needs to be able to edit above the first transform? In tomviz 1.0.0 I was able to define a transform below the default ` def transform_scalars` and use it in the transform_scalars function.

In the short-term, I suggest adding a comment near the function name to indicate that it should not be changed. Also adding a warn/error if the transform is not found would also help in case a coder does change the name. Most coders would recognize that problem and (I believe) most non-coder users are not defining their own transforms.

**Comment by cryos** [comment]
I think adding a comment is reasonable and can be done immediately, it shouldn't be too hard to confirm that the entry point we expect to be able to call is also present. Some of what @cjh1 did may help to add that check, and as we move to support user-local scripts it would be good to add some more sanity checking.

**Comment by cryos** [comment]
This should now be resolved, please reopen and let us know if you see any other flaws with this functionality.
