### ISSUE TITLE
Open Stack of Images

### ISSUE THREAD

**Issue by oliveirarodolfo** [OpenChemistry/tomviz#12]
Hi,

Apparently if I select a stack of images from a folder, it only ends up loading the last one. There should be a way to set the spacing manually or fetching it from either a summary file. I thought that it should be automatically recognized from a ``DICOM`` input, but it didn't work on my end...

**Comment by utkarshayachit** [comment]
Indeed. A fix is already in development in ParaView. Once that lands, the next version of TomViz will inherit it.

**Comment by oliveirarodolfo** [comment]
Perfect, thanks!

**Comment by cryos** [comment]
Thanks @utkarshayachit, just got back from a trip to see this was already answered. Thanks for reporting the issue @oliveirarodolfo!

**Comment by utkarshayachit** [comment]
Here's the [ParaView Merge Request](https://gitlab.kitware.com/paraview/paraview/merge_requests/50) that fixes this issue.

**Comment by cryos** [comment]
Very cool - thanks @utkarshayachit!
