### ISSUE TITLE
Location of custom data operators?

### ISSUE THREAD

**Issue by Tokariew** [OpenChemistry/tomviz#1202]
Is it possible at current stage to add user data operators to tomviz?
It's hinted here, that such functionality will appear in future versions: https://blog.kitware.com/data-operators-in-tomviz/

And if it possible what is location of folder where i should put python and jason files?

**Comment by cryos** [comment]
There is a little more work to do in order to make this possible, I want to get to it very soon. I will update this issue once the work is ready for review/merged.

**Comment by cquammen** [comment]
#1274 is working towards this.

**Comment by cryos** [comment]
@cjh1 used <home_dir>/.tomviz as one standard location, I think others are possible too. We can add further documentation, but I think this is resolved and you should be able to use standard locations in the current nightly builds or the next release.
