### ISSUE TITLE
minor typo in auto alignment code

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1204]
I know Im crazy but:

There a typo in auto alignment python code:
`def corssCorrelationAlign(image, reference, rFilter, kFilter):`
should be
`def crossCorrelationAlign(image, reference, rFilter, kFilter):`

Change corss to cross for the function calls too.

**Comment by Hovden** [comment]
Good catch.

**Comment by ercius** [comment]
Thank you! I will no longer cringe when I open this transform up. :)
