### ISSUE TITLE
Request: child dataset right click menu

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1228]
Can you add the 4 options also available for the main dataset "Clone/Save data/Mark as.../Delete" to the right click menu of a child dataset? Currently only Clone is available.

**Comment by mathturtle** [comment]
Save Data -> certainly, this should be there already if not it is a bug.
Mark as... -> the operator that produced the child data should have marked it as a tilt series or not as appropriate.  I suppose it doesn't hurt to let the user override it though.
Delete -> the child data is part of the operator that produced it.  What does it mean to delete it while leaving the operator?  Does it come back if the operator re-runs?  We don't want to delete the operator when you right clicked on the child data (users will be upset at the unintuitive behavior).

**Comment by yijiang1** [comment]
For tomography, deleting a child data should automatically deletes its reconstruction operator, and ideally tomviz can restore data before reconstruciton without re-running every operators.

**Comment by ercius** [comment]
in tomviz 110, child data sets only show clone.
1. Save Data should definitely be available
2.  Mark as... is probably not necessary.  I checked that snapshotting a tilt series after an operation keeps the data set as a tilt series. 
3. Delete is needed for all data sets. Deleting the data set can clear memory without deleting the operator or you might want to clear the recon and all associated operators/viz modules connected to the recon. The data should come back if you re-reun the operator as expected. I dont think the operator should delete with the data set. (its unintuitive). In the end, to make things more intuitive all of the data sets should be treated the same or indicated as something different.

**Comment by cquammen** [comment]
This appears to have been implemented in the refactorization of the pipeline.

![image](https://user-images.githubusercontent.com/360056/34799944-cc3bd7fc-f62f-11e7-90fd-b57985fb8aae.png)

My tests show that all of @ercius requested functionality has been implemented. @ercius if you have a chance, could you test out the nightly to see if what you want implemented is there?

**Comment by mathturtle** [comment]
This should have been closed when #1293 was merged (or tested).

**Comment by cquammen** [comment]
I tested, it all seems to be there as requested. Closing.

**Comment by ercius** [comment]
Sorry but I never got a chance to current this out. Thanks for implementing!

**Comment by cquammen** [comment]
No worries. Please reopen in the future if something is amiss.
