### ISSUE TITLE
Weighted backprojection reconstructed size option

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1229]
In the Weighted Backprojection GUI there is available an option to change the reconstructed size:
![image](https://user-images.githubusercontent.com/15657108/28936379-6ae745ac-783c-11e7-9eb8-109b72251683.png)

In my opinion, this does not do the sensible operation. I changed the reconstructed size to 128 for the Star particle tilt series and this only reconstructs a volume of 256x128x128. Half of the object is cut off, but all 256 slices along the tilt axis are reconstructed properly.
![image](https://user-images.githubusercontent.com/15657108/28936743-7f2a4400-783d-11e7-9baf-d3a1cc208d17.png)

@Hovden I expected this option to reduce the size to 128x128x128 to speed up the calculation and bin the original data (trade resolution for signal). Is the current behavior the expected behavior?

**Comment by yijiang1** [comment]
The current implementation is similar to Matlab's iradon funciton. The output size is expected to pad zeros or crop reconstruction without changing its scaling.

It does make sense to add an option that allows users to resize the data.

**Comment by ercius** [comment]
I am not sure how useful that is, but its good that it does what is expected.

We have the option to change the size by the binning options for both volume and image tilt series. I think this is ok to leave as is for now.
