### ISSUE TITLE
Visualization are not always updated / deleted

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1230]
There are various instances where changes in the pipeline do not update the visualization.

In particular, if you run a reconstruction and visualize it then delete the pipeline associated with that dataset the visualization remains. This visualization cannot be deleted (to my knowledge) without reseting the program.

[OSX v1.0 and current nightly]

**Comment by cryos** [comment]
I think I missed this bug report, but fixed the issue described here. Is this still an issue in the 1.1.0 release/master?

**Comment by mathturtle** [comment]
This is the bug report I was remembering when I pointed that issue out to you.  I think it is fixed in 1.1.0, but @Hovden should confirm.

**Comment by cryos** [comment]
Marking as closed for now, Rob can reopen if not, but this was fixed. If there are specific examples to reproduce in master please reopen and let me know.
