### ISSUE TITLE
State files do not restore visualization modules

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1231]
* Load data file
* Apply **Binary Threshold** operator
* Add **Orthogonal Slice** module to child data set produced by **Binary Threshold** operator
* Save state
* Reset session
* Load previously saved state.

The **Orthogonal Slice** module on the child dataset is not restored.

This is a blocker to providing state files with examples showing the use of segmentation operators.

**Comment by cryos** [comment]
This works now
