### ISSUE TITLE
Update checking

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1235]
I've noticed that a few people are not aware of updates to tomviz. Is there a mechanism for version checking to help push updates.

**Comment by cryos** [comment]
Not right now, but you raise a good point. We should look at adding something to at least optionally check for new versions, it can be tricky as people don't always like automated phone home style requests to check for updates.

**Comment by ercius** [comment]
Can we have it turned on by default so that novices get told about updates and "tinfoil hat" people ;) can easily turn it off? Maybe it can be added to the splash screen when tomviz first starts up.
