### ISSUE TITLE
2D color opacity confusing

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1240]
Often the 2D color opacity is inoperable for my datasets. The sample data (0-255) seems to work, but most other datasets do not - or I cannot figure out how to use it.

Some examples of what the 2D map looks like (be default)
<img width="1329" alt="screen shot 2017-08-10 at 12 09 55 pm" src="https://user-images.githubusercontent.com/6197997/29182528-daf890b6-7dc4-11e7-97f6-8f11baf70016.png">
:
<img width="1373" alt="screen shot 2017-08-10 at 12 04 57 pm" src="https://user-images.githubusercontent.com/6197997/29182517-cec0631e-7dc4-11e7-88ec-5c84b059d40c.png">

**Comment by cryos** [comment]
We just merged a patch that @alvarosan added that improves the interaction quite a bit in my opinion. A casual user may not spot it, and it reclaims much of the lost space. I think the interaction is improved, and the default experience reverts back to what we had in 1.0.

**Comment by alvarosan** [comment]
From the images above, the current open issues are:
  * The initial dimensions of the transfer function box, which seem to be wrong in the first image (top-right corner of the chart; control points too close to each other while the box should appear in the center by default).
  * Any clues @Hovden  on how to reproduce the bug in the second image? (wrong position of the top-right control point)

**Comment by Hovden** [comment]
1)
Load "sample data" > "Star Particle Tilt Series"
Then use the 2D gradient transform
2)
Load a dataset with float values (e.g. 0 - 1). Also test for data with negative values.
Example: https://drive.google.com/open?id=0B8t3fBhIw9-VaER6bWp3YWVSUkE

The new organization of interface looks good. Font size consistency would offer a small improvement.

**Comment by cryos** [comment]
I think this is resolved, and so marking as closed, I fixed most of the font size issues. It would be good to track specific issues with different data types in a new issue.
