### ISSUE TITLE
Apply/Ok buttons can cause multiple instances of the same pipeline running

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1247]
Load a tilt series.  Mark as tilt series.  Reconstruct it with backprojection C++.

Double click on the "Set Tilt Angles" operator to open its editor window.  Click Apply (the reconstruction should start re-running).  While the reconstruction is running go over to the operator dialog and click apply again.  There will now be two reconstructions running (you can see this in the UI, the current slice will jump around as they fight over which is running).

**Comment by mathturtle** [comment]
What is the correct behavior here?  Cancel the currently running pipeline in favor of the updated one?

**Comment by cryos** [comment]
Yes

**Comment by mathturtle** [comment]
Ok, I'll work on this then.

**Comment by ercius** [comment]
This could be tricky. I would not want to accidentally stop an hour long
reconstruction by pressing ok/apply by accident. Maybe a warning box should
be thrown up?

**Comment by mathturtle** [comment]
Good point @ercius.  That should be doable.

**Comment by mathturtle** [comment]
I think we can close this now.

**Comment by mathturtle** [comment]
ping

**Comment by cryos** [comment]
Agreed, closing.
