### ISSUE TITLE
Manual alignment values read zero at all times

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1249]
The values in the table of the manual align tool are not changing, but it appears they are being correctly saved.

<img width="811" alt="screen shot 2017-08-21 at 12 06 03 pm" src="https://user-images.githubusercontent.com/6197997/29528544-6d2d7318-866a-11e7-93b5-b4438a466ea0.png">

**Comment by mathturtle** [comment]
@Hovden You are aligning slice 39 with 38, both of which are off the screen and you can find them if you scroll down in the table.  If you can reproduce this with slices that are onscreen in the table, then let me know and I'll dig in and see what is missing in the update logic.

**Comment by Hovden** [comment]
I'm sorry about this bad bug report. Haven't broken v1.1. Looks to be a good release.
