### ISSUE TITLE
Color Table Widget at top of window contains garbled pixels.

### ISSUE THREAD

**Issue by imikejackson** [OpenChemistry/tomviz#1254]
I have the same problem with ParaView version 5.4 on Mac OS 10.10. I am running an AMD 7950 Graphics card inside a Mac Pro 5,1 machine. 
![screen shot 2017-08-24 at 2 38 35 pm](https://user-images.githubusercontent.com/5182396/29682956-c4f79962-88da-11e7-9901-076c0501c17c.png)

**Comment by cryos** [comment]
Is this fixed by updating macOS? You posted a related message to the ParaView list that seemed to indicate it was.

**Comment by cquammen** [comment]
I have seen this in ParaView in the charts-based rendering windows on other Macs with 10.10 installed.

**Comment by cryos** [comment]
I think this is a Mac driver issue, it looks like updating your OS will fix it, Apple have not been the greatest at OpenGL drivers, and don't backport fixes to older OSes....
