### ISSUE TITLE
Look at replacing our custom "separate color map" code with ParaView's feature

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#1260]
https://blog.kitware.com/separate-color-map-feature/

**Comment by cryos** [comment]
Looking at the way it is implemented there, and the different structure of visualization modules in Tomviz I am not convinced that it would be a wise use of our time. We have a global for a data set, and then separation possible at the visualization module, with support for using label maps too. ParaView seems to offer a toggle at the view level. We should keep an eye on possible reuse, but I think most of the value for this is in the user interface/how it is exposed.

If there is anything more concrete you think we should be reusing please point it out, closing for now but you can reopen. I think it is great to see the support added in ParaView.

**Comment by cquammen** [comment]
Yeah, this won't be possible anyhow as the **Slice** module does not use a real ParaView representation, and one of the keys in the ParaView implementation is a representation object.
