### ISSUE TITLE
Tomviz Start Up Crash

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1280]
Hi everyone, 
I'm having trouble loading Tomviz at the moment and encounter a crash every time I open the program. I'm currently operating on Paraview _"v5.4.1-609-g2b5d6611ec"_ and Python version "3.6.2".

I get the following error in my terminal when the program crashes:

Traceback (most recent call last):
  File "/Users/jon/tomviz-build/lib/site-packages/tomviz/_internal.py", line 20, in <module>
    import tomviz._wrapping
ImportError: dlopen(/Users/jon/tomviz-build/lib/site-packages/tomviz/_wrapping.so, 2): Symbol not found: __Py_ZeroStruct
  Referenced from: /Users/jon/tomviz-build/lib/site-packages/tomviz/_wrapping.so
  Expected in: flat namespace
 in /Users/jon/tomviz-build/lib/site-packages/tomviz/_wrapping.so
"Failed to import tomviz._internal module."
Segmentation fault: 11 

This issue occurred after I switched from cory's multicomponent_image branch back to the current master.

**Comment by mathturtle** [comment]
cc: @cjh1 @cquammen

**Comment by jtschwar** [comment]
The source of this issue is due to Cory's multicomponent_images pull request branch.

**Comment by cquammen** [comment]
According to this [1], this may be the result from mixing Python 2 and 3. I am having difficulty seeing how the changes in this branch could lead to the error you reported in #1280.

[1] http://pybind11.readthedocs.io/en/stable/faq.html
