### ISSUE TITLE
Physical pixel size issues

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1284]
The physical size (voxel size) is not set properly for some data sets. A couple examples below:
1) EMD files do not have the proper physical size scaling or units.
2) The example data sets for the star particle do not have proper physical dimensions set.
3) MRC files are read properly. However, loading an MRC and saving as TIFF and loading the TIFF loses the z-axis scaling. This seems connected to the saving operation because of 4) below.
4) Downloading data from Hovden's data set paper in TIFF format (tiltser_180.tiff) seems to get the correct scaling.

I do not have many more examples to try and load. These are some possible issues to look into though.

**Comment by mathturtle** [comment]
There may be two issues here, only one of which can be solved.

1. Not all image formats support storing physical size of the pixels.  For example, TIFF does not have a field for pixel size and so tomviz has to guess when loading a TIFF what the pixel size should be.  I don't remember which formats support storing the physical size off the top of my head although I know OME-TIFF does store the size.  MRC may have it or you may have gotten lucky with the initial size guess.

2. I **think** EMD files should store the physical size of the pixel and if they are not reading it correctly that could be a bug.

**Comment by cryos** [comment]
EMD should store/read the size, I don't think it does at present, but I can fix that. TIFF has poor support, the standard can store a spacing in x and y, but not z. We improved it slightly by having z match x I think (rather than being left at 1). If there is a way of using z spacing in TIFF I don't think our reader/write code is aware of it.

**Comment by ercius** [comment]
This is why I dislike TIFF files for microscopy data. The header and pixel sizes are not well supported. ImageJ seems to have a decent handle on the XY size, but the third dimension is difficult to calibrate (i.e. I dont know how). OME-TIFF is a good way to go, but I am not sure how to implement it.

It seems odd to have example data that does not import a physical size. Maybe we should change the example data to a format that supports pixel sizes correctly (MRC)? Just a though.

MRC definitely supports pixel sizes although the standard vs. FEI header information sometimes gives headaches for where to get the correct information. tomviz correctly reads MRC file headers as far as I know.

For EMD I suggest using the first element of the dim_n vector as the offset and the dim_n[1] - dim_n[0] as the pixel size along that direction. Some dim directions will only consist of those 2 elements.

**Comment by ercius** [comment]
A little update on the pixel size issue. MRC files are read in properly, but the units is incorrect. All MRC files are assumed to have 'Angstroms' as their units for physical size. tomviz currently adds 'nm' in the units column without dividing by 10 ( to convert Ang --> nm) which is incorrect.

**Comment by ercius** [comment]
see #1288 but need to test

**Comment by cryos** [comment]
This is resolved, and will be in the release. Please reopen if you see related issues, thanks for pointing this out Peter!
