### ISSUE TITLE
Remember the application current directory

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1287]
Tomviz should remember the current directory, i.e. the last directory used in the open/save dialog. I think this should be across all open/save dialogs, and in trying a few other applications that seems to be the case.

In my testing on Linux we always go back to the current working directory the application started from, which is really irritating when opening/saving. When I open several things they are usually in the same directory, when I save something it is often intended to be saved next to the input data. Same with when I want to save state, etc.

We should examine the current behavior on Windows and macOS, but I think the right thing would be a process wide working directory that is updated each time the open/save dialog is used. This could be centralized through a helper that each call point can use to get/save the application working directory.

**Comment by mathturtle** [comment]
Which dialogs were you seeing this behavior with?  I have been trying this and they all seem to respect the last directory that was used  (Linux w/ Qt 5.9.1).  The only dialogs that behave as you describe are "Save Debugging State" and "Save Movie" both of which still use the ParaView save dialogs.

**Comment by cryos** [comment]
This is Arch Linux using Qt 5.9.1 on the KDE desktop. I wondered if there was some dependence on operating system and/or desktop environment. I guess you are on Unity?

**Comment by mathturtle** [comment]
I'm using XFCE/Xubuntu.  I'll try it on Unity this morning on my laptop.

**Comment by mathturtle** [comment]
Unity behaves the same way as XFCE.
