### ISSUE TITLE
MRC pixel size read as nan

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1291]
Recently I had an MRC file which populated the header incorrectly. So the physical dimensions of the object were 0 and the pixel size in tomviz was calculated as nan. This caused tomviz to not show any object on the screen since there is no physical size.

This is an edge case that would be useful to take care of properly. If the pixel size is nan or not known then set it to 1.

**Comment by mathturtle** [comment]
You are right, this is a case that would be good to handle.  I'll put up a branch in a bit.

**Comment by mathturtle** [comment]
I added this to my MRC spacing branch (#1288) since it needed to change the same place in the code.  If the input data spacing (length) is 0 or NaN, it is reset to 1.  Of course if other parts of the header are corrupt too it may not help much...

**Comment by mathturtle** [comment]
This should be merged now.
