### ISSUE TITLE
tomviz hard crash when printing out to messages panel

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1294]
Windows 10, tomviz 110-102 (with custom transforms)

I recently spent a few days debugging a complex script in tomviz that works perfectly outside tomviz in a separate python environment. This script would cause tomviz to hard crash every time on some computers and randomly on other computers. There might be some issue with allowing custom scripts.

We tracked the issue down to some print commands in a for loop. The print command would print very often to keep track of the script during debugging.

I then tried to just use print commands in the default custom script (sqrt of data) and got tomviz to crash as well. I can get it to crash consistently with this nightly version (102) of tomviz.

I get an error when trying to print the first time:
> Object::connect: Cannot queue arguments of type 'QTextCharFormat'
(Make sure 'QTextCharFormat' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)

I tried to get 110 release to crash in the same way but was not able to. I dont see the QT message above either.

**Comment by ercius** [comment]
The newest nightly (104) is not stable with respect to print commands either.

**Comment by cryos** [comment]
Thanks Peter, @cjh1 has a Windows 10 machine we can hopefully verify this on. We will look into it.

**Comment by cjh1** [comment]
@ercius @cryos I am seeing the same behavior on my machine. This looks like a generic error not specific to custom operators. I will dig into it.

**Comment by cjh1** [comment]
Fixed by #1295, please reopen if that is not the case.

**Comment by cryos** [comment]
Thanks @cjh1 for the quick fix, and thanks @ercius for reporting the issue. Please let us know if you spot any other related issues.
