### ISSUE TITLE
Import tilt angles from a text file

### ISSUE THREAD

**Issue by ricounet67** [OpenChemistry/tomviz#1297]
I would like to know how I can import the tilt angles from a text file and also if it will be possible to implement the Saxton scheme.
Thank you
Best regards

**Comment by cryos** [comment]
I don't think this is currently supported, but is certainly something we could (and should) make available. I will see what we can do, I am not familiar with the Saxton scheme, but it is certainly quite feasible to add support for other angle specifications.

**Comment by ricounet67** [comment]
Is there a possibility to import the angles values with a python script?
How the tilt angles are stored into Tomviz ?

**Comment by cryos** [comment]
I think we expose the tilt angles in Python, @mathturtle do you have any pointers, this would be a nice one to document in an upcoming course as an advanced option. I also checked on the set individual angles and pasting doesn't work - we should address that too. They are stored with the underlying data object.

**Comment by mathturtle** [comment]
tomviz provides `get_tilt_angles` and `set_tilt_angles` to get and set the tilt angles as numpy arrays.  See the python script for the operator created by Data Transforms -> Bin Volume x2 for an example for using these.

**Comment by ricounet67** [comment]
how is the dataset named? If I follow the script, the command is something like tilt_angles = utils.get_tilt_angles(dataset) to read the angles and utils.set_tilt_angles(dataset, result) to set the angles values. If I understand well, the image stack is named dataset. But if I do this with an image stack that I loaded from a TIFF stack named HAADF for example, I have an error. How do I proceed to know the name of the variable that contains my tilt serie ?

**Comment by mathturtle** [comment]
So the `dataset` object is a `vtkImageData` object.  `get_tilt_angles` and `set_tilt_angles` are placing/reading the array of tilt angles into/from the image data's metadata (field data for those familiar with VTK).  To get/set the actual image stack as a numpy array, you use `get_array` and `set_array`.
