### ISSUE TITLE
Saving video as Ogg not working

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#13]
Exporting animation as ogg video not working. It currently throws the following error on Mac OSX:

ERROR: In /Users/kitware/Dashboards/MyTests/NightlyBinary/MatVizSuperbuild-Release/paraview/src/paraview/ParaViewCore/Animation/vtkSMAnimationSceneImageWriter.cxx, line 385
pqAnimationSceneImageWriter (0x11c2c4990): Unknown extension .ogv

**Comment by Hovden** [comment]
@cryos Can we close this? 

Both *.ogv and *.avi animations are now working in the latest OSX build.

I believe it was solved when ffmpeg was included in the make.

**Comment by cryos** [comment]
Yes - this is resolved.
