### ISSUE TITLE
Application crashes during manual alignment

### ISSUE THREAD

**Issue by ricounet67** [OpenChemistry/tomviz#1300]
When I perform a manual alignment, when I arrive at the last image and I type S to go to the next one that in fact doesn't exists, the program crashes everytime.
It is very painfull because you loose all the work done. Maybe a test on the number of slices will avoid this problem

**Comment by cryos** [comment]
Thanks for reporting, we will look into this and get it fixed ASAP.

**Comment by cryos** [comment]
I just checked this in master, (tomviz 1.1.0-115) and do not see this issue. Our code does bounds checking, and wraps when pressing S to go to the next one. Can you confirm what version you are using, and see if you observe this issue in the latest [nightly build](http://www.tomviz.org/downloads/).

**Comment by cryos** [comment]
I was unable to reproduce in master, no response, closing, please reopen if this is still an issue and you can supply more details on how to reproduce if it is still present in master/the latest release.
