### ISSUE TITLE
State file does not save the 2D gradient transfer function for volume rendering

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1302]
Nightly build 1.1.0-115-g14f1e3c

**Comment by cryos** [comment]
On Linux I am seeing a new bug with the 2D gradient transfer function, any adjustment in our widget causes the rendering to disappear, and a failure to compile the GLSL shader.
```
ERROR: In /home/marcus/src/paraview/VTK/Rendering/OpenGL2/vtkShaderProgram.cxx, line 462
vtkShaderProgram (0x55c8e7bb6d50): 0(165) : error C1008: undefined variable "g_gradients_0"
0(223) : error C1008: undefined variable "g_gradients_0"
0(233) : error C1008: undefined variable "g_gradients_0"
0(476) : error C1008: undefined variable "g_gradients_0"
```
It looks like something shifted in VTK, I will dig into it, but without the ability to modify the restoration of the state will not work.

**Comment by mathturtle** [comment]
@cryos I'm going to start updating my branch for this unless there is something else you'd rather I worked on.  IIRC, you wanted it refactored so there is a TransferFunction2D object that contains the boxes etc. rather than passing around a list of box items.

**Comment by cryos** [comment]
There is only one box, I think this should be a new branch (we can abandon the old one). It should expose a set and a get on a vtkRect, along with with restoring the mode to transfer 2D correctly. Let's go for minimal extra code/classes, enough to enable setting and getting the single rectangle we support. If we augment this in future, the state can also be augmented then.

**Comment by cryos** [comment]
This should be resolved now, we can open new issues to track further improvements.
