### ISSUE TITLE
Save data as numpy array

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1305]
This is a request to add the ability to save Numpy arrays ([like np.save()](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.save.html)) using File-->Save data menu item. It would be useful for compatibility with other Python implementations (tomopy, ASTRA, etc.).

This can be done with custom script, but it would be nice to have in File-->save data file menu.

**Comment by cryos** [comment]
This is a great point, I think once we add the ability to save/load from a Python script this becomes very simple. Agreed on adding it for compatibility with other codes.

**Comment by cryos** [comment]
We should try and take a look at saving/loading data using a Python snippet - source/sink to our pipeline from Python using NumPy.

**Comment by cryos** [comment]
Consider MATLAB and other microscopy formats that have good Python support.

**Comment by alesgenova** [comment]
This feature is now implemented in #1586 !
