### ISSUE TITLE
Pipeline item not highlighted (Minor UX bug)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1306]
Often there is no item highlighted in the pipeline, yet there are properties displayed in the properties panel. It often happens when new datasets are loaded or objects from the pipeline are removed.

<img width="307" alt="screen shot 2017-10-19 at 12 47 40 pm" src="https://user-images.githubusercontent.com/6197997/31783518-7d68db2e-b4cc-11e7-9cb2-1d969a027400.png">

**Comment by cryos** [comment]
This is fixed in master.
