### ISSUE TITLE
Add "View Code" Button to Properties Panel

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1307]
Often users are not aware that you can view and edit the Python code of some transforms in the pipeline. Adding a "View Code" button to the properties panel would make this more clear and offer another form of discovery.

**Comment by cryos** [comment]
This is improved, it still doesn't function as expected when the operator has no custom UI. Keeping this open until we resolve that, #1368 moved us closer.

**Comment by cryos** [comment]
This was resolved in master.
