### ISSUE TITLE
Make a default animation when loading.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#131]
Currently the user must create an animation in order for it to show any functionality. Having a default animation, such as a simple rotation, will add a lot of value to new users trying to learn the animation tool. It will also make the play button functional when the software is first loaded.

Suggestion:
Make a default animation that rotates about each axis sequentially.

**Comment by bdalevin** [comment]
A single axis orbit animation being loaded up by default would be a nice touch!
A multi-axis orbit will have to wait until #66 is fixed.
