### ISSUE TITLE
tomviz operators subclassing

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1310]
Im trying to get a script to use the subclassing of tomviz.operators based on [this information](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/python/Operators.md).

Simply copying and pasting the examples on that page does not work. I clicked on Data transforms --> Custom transform and then pasted this in:
```python
import tomviz.operators

class MyOperator(tomviz.operators.Operator):
    def transform_scalar(self, data):
        print('Output')
```

I get this message:

> Traceback (most recent call last):
> File "C:\Users\Peter\Desktop\Tomviz-1.1.0-121-gede97d8-Windows-64bit\lib\tomviz\site-packages\tomviz\operators.py", line 89, in transform_scalars
> raise NotImplementedError('Must be implemented by subclass')
> NotImplementedError: Must be implemented by subclass
> Failed to execute the script.

Any idea what I am doing wrong?

**Comment by mathturtle** [comment]
It looks like you left the final `s` off of `transform_scalars`.

**Comment by cjh1** [comment]
:eagle: :eye:  @mathturtle

**Comment by ercius** [comment]
Got it! [This page](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/python/Operators.md) describing the operators needs to be updated then. Thanks!

**Comment by cjh1** [comment]
Oops, sorry about that! Here's the update #1313
