### ISSUE TITLE
Tomviz 1.2.0 crashes on macOS

### ISSUE THREAD

**Issue by zezhong-zhang** [OpenChemistry/tomviz#1311]
Hello,
I am trying to run the tomviz (version 1.2) on my mac (OS version 10.13) but it shuts down automatically. The previous verison tomviz 1.1 works fine

Here are the error found in the console. Any suggestions?

> Oct 24 18:11:05 dyn-49-127-97-23 com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
> Oct 24 18:11:09 dyn-49-127-97-23 com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000000d.tomviz[1339]): Service exited with abnormal code: 1

**Comment by mathturtle** [comment]
I don't have a 10.13 machine here to test on, but the version 1.2.0 binaries work fine on my mac (10.11) and our build machine (10.12).

According to the Apple forums the _DirtyJetsamMemoryLimit is more of an operating system level error where Apple's porting code from iOS to macOS is causing problems.  But all the threads that discuss it are for Yosemite (10.10).  See [here](https://discussions.apple.com/thread/6686011?tstart=0) for a few more details.  It seems like this is a fairly normal error for 10.10+ to have in the console and will not tell us why tomviz crashes.

Are there any lines below the one about 'Service exited with abnormal code: 1' that mention tomviz?  Do you get the 'This application has experienced an error' dialog?  If you get that, then the information there (If you click Details) is generally more helpful than the system console.  Can you paste that in a comment here?  I will see if anyone else here has a 10.13 machine I can borrow to test this.

**Comment by cryos** [comment]
Could you take a look at the 1.1.0 release, and see if that presents the same issue for you too, see https://github.com/OpenChemistry/tomviz/releases for previous releases.

**Comment by cryos** [comment]
It isn't clear if this is specific to 10.13, did you try rebooting the machine @zezhong-zhang? @mathturtle is it possible to push the Qt back to what was used for the 1.1 release, and we could see if that helps @zezhong-zhang, we have not been able to reproduce this, I used a clean 10.12 machine in my testing and saw no such issue there either.

**Comment by mathturtle** [comment]
Bob says I can test on his 10.13 laptop when he gets back from travel on Thursday.

Until then.... yes I can make a test build with the older Qt to see if that works.

**Comment by mathturtle** [comment]
I've queued a build with the older version of Qt.  It looks like there are only a few VTK builds ahead of it, so it should be pretty quick.

**Comment by mathturtle** [comment]
Here is the version with the older Qt we used for 1.1.  http://www.tomviz.org/files/tomviz_nightly_bin/Tomviz-1.2.0-Darwin-64bit.dmg  @zezhong-zhang Can you try this version and see if it crashes?

**Comment by zezhong-zhang** [comment]
Thanks @mathturtle and @cryos for looking into this. 

@cryos, tomviz (1.2) also did not work on my previous MacOS (10.12) before the upgrade. Is it 
@mathturtle, the older Qt built tomviz 1.2 does not work, showing the same problem.  Here are the errors during launching.

> default	09:55:39.639023 +1100	launchservicesd	UNIX error exception: 22
> default	09:55:39.642898 +1100	launchservicesd	MacOS error: -67062
> default	09:55:39.648093 +1100	launchservicesd	CHECKIN:0x0-0xc60c6 27550

Another issue about the abnormal exit. The tomviz 1.1 opens fine. However, the program crashes for many operations on the loaded tilt series, like data binning x2. The manual shift alignment works fine bu the automatic shift alignment crashes the program.

**Comment by mathturtle** [comment]
> Another issue about the abnormal exit. The tomviz 1.1 opens fine. However, the program crashes for many operations on the loaded tilt series, like data binning x2. The manual shift alignment works fine bu the automatic shift alignment crashes the program.

That sounds like something with Python may be broken... Again, that worked fine when I tested the 1.1 binaries when we released it.  I'm not sure what might be happening and I need more details to figure it out.

https://developer.apple.com/library/content/technotes/tn2004/images/tn2123_CrashReporter105f1.png

Do you get a dialog like this?  If so, then clicking Report will show some details about the crash which are typically more useful than the system console messages.

**Comment by cryos** [comment]
The 1.0.1 binary had some issues with Python, but they were fixed in  1.1.0. We had a lot of testing on macOS for 1.0.0 and 1.1.0 that didn't highlight any issues like this. It would be good to get some more detailed debugging information from the crash report dialog as @mathturtle suggests. We are testing this functionality on macOS, and not observing these issues. 10.12 would be best tested at this point, we will move more machines forward to 10.13 soon.

Anything unusual about the macOS machine you are trying this on that you can think of? I have an old Macbook Pro I have been testing on, a new Mac Pro, several iMacs, and I know several collaborators are using newer Macbook Pro laptops.

**Comment by Hovden** [comment]
It is not crashing on my macOS 10.13. However the application is unverified and requires right clicking.

**Comment by Hovden** [comment]
Nevermind. I re-downloaded the 1.2 version and it appears to be verified and executes with a double click on OS 10.13 . tomviz runs ok on my other OS 10.13 machine as well.

On old macs (running older OSX) we saw lots of crashes upon loading. On old windows machines we saw rendering problems.

**Comment by zezhong-zhang** [comment]
@mathturtle The only thing I can think of is I am using anaconda python3. Sometimes it may affect homebrew applications. But other than that, the Mac behaves fine.

Here is the crash log when binning the data by 2 in tomviz 1.1. 

Sorry for the delayed response because of microscopy experiments today...
[tomviz_2017-10-24-212338_Zezhongs-MacBook-Pro.crash.txt](https://github.com/OpenChemistry/tomviz/files/1417418/tomviz_2017-10-24-212338_Zezhongs-MacBook-Pro.crash.txt)

**Comment by cryos** [comment]
We saw the 1.2.0 release working on a number of Macs at the short course yesterday, and today. It looks like a crash in the OpenGL code making the OpenGL context current - this is unusual but looks like it could be a driver issue.

**Comment by zezhong-zhang** [comment]
It is python causing the problem. The anaconda on my mac default `python` into `python3`.

> Setting PYTHONHOME and PYTHONPATH: "/Applications/tomviz.app/Contents/MacOS/../Python"
> Failed to import the site module
> Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
>      PYTHONPATH is currently: "/Applications/tomviz.app/Contents/MacOS/../Python"
>      You should `unset PYTHONPATH` to fix this.

**Comment by mathturtle** [comment]
tomviz comes with its own Python builtin (Python 3) and python packages built for Python 3 to run with it.  It shouldn't care about your anaconda installation unless you are setting the python path before running tomviz (in which case you should use a `python3` virtual environment, but this is not recommended if you are running the packaged version).  The .app is set up to run as a self-contained unit...  You may need to unset your `PYTHONPATH` and `PYTHONHOME` entirely so that the application uses its internal python though.

**Comment by zezhong-zhang** [comment]
I have unset `PYTHONPATH` and `PYTHONHOME`, but it did not work. When I `echo $PYTHONPATH`, there is no pre-existing python path.  I was wondering since python3 is the builtin for the application, why would the error suggest 

> Your PYTHONPATH points to a site-packages dir for Python 2.x ...
>PYTHONPATH is currently: "/Applications/tomviz.app/Contents/MacOS/../Python"

**Comment by cryos** [comment]
It is possible that you have a corrupted installation, macOS is supposed to keep if you want to replace the application when you drag it into /Applications, it should then ensure that it is cleanly installed with no old files remaining from previous versions. You may want to remove the tomviz.app from your /Applications folder, and then once done try again. We used to use Python 2.7, but never bundled it in the app directory on macOS (we were able to use the system version). We now bundle Python 3.6 with the application.

**Comment by zezhong-zhang** [comment]
I have tried installed several times, but it does not work. I suspect it might due to the fact that my `python` is defaulted to `python3`. I think the issue is relevant to [Homebrew/#2958 (comment)](https://github.com/Homebrew/brew/issues/2958).

**Comment by zezhong-zhang** [comment]
Problem fixed by simply removing `sitecustomize.py` in `/usr/local/lib/python2.7/site-packages/`. Now tomviz starts normally.

**Comment by mathturtle** [comment]
I'm glad you figured it out.  I have no idea why that would have been causing the error though.
