### ISSUE TITLE
Non-orthogonal slice doesn't save its position and orientation

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#132]
The non-orthogonal slice module doesn't save its state.  The serialize and deserialize functions are stubbed out with a `//FIXME: implement later` comment.  When loading a state file with a non-orthogonal slice, the slice is reset to the default position.

@cryos @Hovden @utkarshayachit Since this is a reproducibility bug, is it worth trying to get into 0.6?  I don't think it will take very long to fix.

**Comment by utkarshayachit** [comment]
@mathturtle Yes please. Let's get this fixed esp since it shouldn't take too long.
