### ISSUE TITLE
Contour module does not work with multicomponent images

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1335]
From @jtschwar in #1266:

I've come across [a] when an RGB dataset is implemented in Tomviz version 1.1.0-34-g63f87d6. [W]hen I select the contour option I get the following error: "ERROR: In /Users/jon/paraview/VTK/Filters/Core/vtkProbeFilter.cxx, line 164. vtkCompositeDataProbeFilter (0x7fe11cd9d9b0): Source scalars have more than one component! Cannot categorize!".

**Comment by cquammen** [comment]
ParaView does not support contouring by a specific component of a multicomponent image. However, the underlying vtkFlyingEdges3D filter does support contouring by a component, so we should be able to support it, likely in `tomvizExtensions.xml`. This is the first step to supporting contouring by a multicomponent image.

**Comment by cquammen** [comment]
Correction: `vtkFlyingEdges3D` does not appear to work with multicomponent image data. By work, I mean contouring by a component you can specify via `vtkFlyingEdges3D::SetArrayComponent()`.

For now, I propose to disable the Contour module if there are no single-component arrays in the data set. Then we can implement contouring by a component if that turns out to be desired. @cryos @Hovden

**Comment by cryos** [comment]
Agreed, it should be disabled, before putting more time into it we should ensure it is actually of interest. I am not sure it is.

**Comment by cquammen** [comment]
#1351 disables the Contour module for datasets that have more than one component.

**Comment by cquammen** [comment]
#1351 was just merged.
