### ISSUE TITLE
failed to run BinaryThreshold under Mac OS X

### ISSUE THREAD

**Issue by yxqd** [OpenChemistry/tomviz#1337]
Got this error when running tomviz 1.2.1 under Mac OS X 10.12.6.
```
Problem encountered while running BinaryThreshold
Traceback (most recent call last):
  File "Binary Threshold", line 85, in transform_scalars
  File "Binary Threshold", line 41, in transform_scalars
  File "/Applications/tomviz.app/Contents/Python/tomviz/itkutils.py", line 272, in convert_vtk_to_itk_image
    dst_type = vtk_cast_map()[src_type]
KeyError: 15
Failed to execute the script.
```

**Comment by mathturtle** [comment]
OK, this sounds like you are using a data type the ITK wrappers don't support.  What kind of data are you using (integer or floating point and what precision)?

**Comment by yxqd** [comment]
signed char

**Comment by yxqd** [comment]
I changed them to unsigned chars and it works now

**Comment by mathturtle** [comment]
I found the bug.  It is a missing case when converting data types in our python code.  You can either wait until #1338 is merged and use a nightly binary, or you can apply the patch to the python code in your current application bundle (Edit `/Applications/tomviz.app/Contents/Python/tomviz/itkutils.py` and add the same block of code I added in the merge request).

**Comment by yxqd** [comment]
Thanks! Got another question: what does "Segment Pores" output? Is it binary data that differentiate pixels that are inside/outside of the pores? Sorry I am not sure where to post this kind of question. Is there a user mailing list or forum of some sort?

**Comment by cquammen** [comment]
Hi @yxqd. There is a mailing list for tomviz: https://public.kitware.com/mailman/listinfo/tomviz

**Comment by cquammen** [comment]
@yxqd With regards to your question about "Segment Pores", here is the description from the commit message in commit 0c4705e5e03d3d955fbe38701c52d77498f49be2:

    commit 0c4705e5e03d3d955fbe38701c52d77498f49be2
    Author: Matt McCormick <matt.mccormick@kitware.com>
    Date:   Mon Feb 27 14:39:59 2017 -0500

        Add Segment Pores transform

        This does some pre-processing on the input image, then does automatic
        thresholding to find the basis for the pores. Next, the particles are
        identified and encapsulated to distinguish internal pores and even pores
        that are exposed to the surface. A morphological watershed filter applied to
        the encapsulated pores distance map separates pores based on the minimum
        radius. Thresholded components smaller than the minimum radius are also
        removed.

**Comment by cryos** [comment]
As I said at the meeting, you can make use of issues like this, as Cory pointed out there is a mailing list, and we can always look at other methods. I want to improve the usability and documentation of the segmentation stuff in future, and will see if we can come up with some improvements in that area.

**Comment by yxqd** [comment]
Thanks @mathturtle @cquammen @cryos for the help!  I think the new plugin-like feature is great and it will make it much easier for me to work with tomography data in tomviz by quickly adding python functions as custom menu items. And yes, some more detailed documentation in the user guide on how to use the segmentation tools will be very helpful!
