### ISSUE TITLE
OpenGL2 errors when non-orthogonal slice widget visible

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#134]
When the non-orthogonal slice's plane and arrow widget is visible, OpenGL2 errors appear on OSX.

ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/OpenGL2/vtkOpenGLPolyDataMapper.cxx, line 2524
vtkOpenGLPolyDataMapper (0x7fdfb21ae800): failed after BuildBufferObjects 1 OpenGL errors detected
0 : (1281) Invalid value

@Hovden @utkarshayachit 
VTK patch for OpenGL2 errors here:
https://gitlab.kitware.com/vtk/vtk/merge_requests/461

**Comment by Hovden** [comment]
VTK patch appears merged but still seeing an error when using non-ortho slice.

**Comment by mathturtle** [comment]
I'm working on getting the patch into ParaView right now.  The ParaView patch is here:
https://gitlab.kitware.com/paraview/paraview/merge_requests/253
But it is blocked by an unrelated issue introduced into VTK by someone else.  I've put up a patch for that which is here:
https://gitlab.kitware.com/vtk/vtk/merge_requests/463

**Comment by mathturtle** [comment]
Waiting on ParaView's builds to test new VTK commit.

**Comment by mathturtle** [comment]
The ParaView branch is (finally) merged.  If you update your local build to ParaView's master branch, you should see this is fixed.  I'm holding off updating superbuild for one more ParaView branch that will fix #135.

**Comment by ElliotPadgett** [comment]
When I try this now I don't get any errors on OSX.  Is this ready to close?

**Comment by mathturtle** [comment]
The ParaView fix is pulled into the binaries, so if you're not seeing the errors anymore, go ahead and close it.

**Comment by ElliotPadgett** [comment]
Checked Windows too, everything works smoothly.
