### ISSUE TITLE
Link to mailing list on tomviz web page

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1342]
Should there be a link to the tomviz mailing list [1] on the tomviz.org web page?

[1] https://public.kitware.com/mailman/listinfo/tomviz

**Comment by ercius** [comment]
There's a mailing list?

**Comment by cquammen** [comment]
Yep.

**Comment by cryos** [comment]
I think a link on the web page is more appropriate, I will get something added soon. I want to expand things out a little, and make it clear how people can communicate with us.

**Comment by cryos** [comment]
Added https://www.tomviz.org/discuss/ which I think covers this well, and gives a few viable options.
