### ISSUE TITLE
Rendering incorrect when objects are moved

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1353]
Sometimes when objects are moved in the rendering new visualizations do not appear with the translation applied (see below).
<img width="634" alt="screen shot 2017-11-21 at 12 27 21 am" src="https://user-images.githubusercontent.com/6197997/33056326-082de4bc-ce53-11e7-84be-65c56f9c881f.png">

**Comment by mathturtle** [comment]
Is this specific to Volume visualization modules?  Or does it seem to randomly affect any visualization module?

**Comment by cryos** [comment]
This is quicker to test yourself, taking a look this affects the volume visualization, the scale cube, and it looks like slice was a little affected but calls an update. The other modules appear to work, and volume will move when you click in the right spot to trigger an update it appears.
