### ISSUE TITLE
Python operator with spin boxes fail with TypeError

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1356]
Load a dataset, try applying any python operator whose JSON-defined UI contains an integer or double with a spinbox as its UI.  (This was found with DataTransforms -> Gaussian Filter).  The transform fails to run and gets this error:
```
TypeError: transform_scalars() got an unexpected keyword argument 'qt_spinbox_lineedit'
Failed to execute the script.
```

Some initial diagnosis during the call with @jtschwar:
This is related to #1348, commenting out lines 136-139 of OperatorWidget.cxx "fix" it while breaking the file and directory types.  I think it is grabbing the SpinBox's internal LineEdit and trying to use that as if it were a parameter widget we created.  @cjh1

**Comment by cjh1** [comment]
I will take a look.

**Comment by cquammen** [comment]
#1357 appears to fix the problem.
