### ISSUE TITLE
Weird colormap output for Linear green (Gr4L)

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1367]
tomviz 1.2.1, windows 10.

I think that the Linear Green (Gr4L) color map is incorrect. It briefly goes brownish on the lower end of the histogram. You can also see this error (?) in the preset window. See screenshots below:
 - histogram of a dataset:
![lineargreen_gr4l_hist](https://user-images.githubusercontent.com/15657108/33862508-f25d63e2-de97-11e7-9688-c8c724f7cae5.jpg)
 - preset window:
![lineargreen_gr4l_preset](https://user-images.githubusercontent.com/15657108/33862541-15e35006-de98-11e7-929d-2bbfb340e4c7.jpg)

**Comment by cquammen** [comment]
I cannot replicate on my Mac in my development build. I don't have a good explanation for why you are seeing the blue and brown.

**Comment by cryos** [comment]
I don't see this on Linux, we should look at the 1.2.1 binaries when we are back in the office tomorrow.

**Comment by ercius** [comment]
I replicated it on another windows machine. So, its not specific to my computer.

**Comment by cryos** [comment]
@cjh1 is there any chance you could give this a try on your Windows 10 machine? I think just trying the 1.2.1 binary would be great, then we may want to take a look at a ParaView binary to see if the same issue presents there.

**Comment by cjh1** [comment]
@cryos Sure, I will take a look.

**Comment by cjh1** [comment]
As you can see I am seeing the same on my window 10 box:

![screen](https://user-images.githubusercontent.com/1031053/34495295-92b20484-efc2-11e7-8fee-17b5196f51e0.png)

I will check ParaView as well ....

**Comment by cryos** [comment]
If you look in the Tomviz directory I think we actually bundle the ParaView binary in there too, so you can just take a quick look using that I think.

**Comment by cjh1** [comment]
Looks like ParaView doesn't have this problem:

![screen](https://user-images.githubusercontent.com/1031053/34497946-7fd00f9a-efcd-11e7-902d-f053fa3067ec.png)

**Comment by cryos** [comment]
That is unexpected, the ParaView widget in Peter's screenshot for picking the color map has the splodge in it too, so I had expected to see the issue in ParaView. Is this the Tomviz provided binary, or a ParaView upstream binary you are testing with? I assume there is no splodge in the color map picker in ParaView either. Very strange to see it in the color bar, the histogram, and the picker but not in PV.

**Comment by cjh1** [comment]
That is with the ParaView executable shipped with tomviz.

**Comment by cryos** [comment]
That is so strange, thanks for the confirmation.

**Comment by cryos** [comment]
Documenting that we looked at this a little more on Chris' windows 10 machine using the 1.2.1 binary. It seemed to happen most when looking at the color map chooser before loading data, but there seemed to be an element of randomness to it. We only observe the issue with this color map, and once it appears it stays until the application is restarted. 

Looking at the color map the actual color points appear to have reasonable values, but the interpolation between them is off. We will have to try and get a debug build to dig deeper into this, it appears to be an initialization issue or perhaps something writing to a memory location it should not.

It is unclear whether it would also randomly happen in ParaView, it is harder to get to the color map, you must load some data first. We should probably disable the button until data is loaded too, as there is nothing useful to be done. I will see if we can find some more time to look into this soon.

**Comment by cquammen** [comment]
Utkarsh seems to have found the likely culprit in ParaView. See the discussion in https://gitlab.kitware.com/paraview/paraview/issues/17933.

There is a bad color space in the JSON defining the `Linear Green (Gr4L)` color map (`CIELAB` instead of `Lab`) and uninitialized memory in the JSON processing code.

**Comment by cjh1** [comment]
@utkarshayachit Good catch!

**Comment by cryos** [comment]
That is great, I had been meaning to circle back to this, but had no solid plan of attack. Thanks for letting us know.

**Comment by ercius** [comment]
Mystery solved!

**Comment by cryos** [comment]
Resolved - PV bump will fix this.
