### ISSUE TITLE
Re-running Python Transforms

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1371]
Hi, 
The _Apply_ button on JSON dialog for python transformations only work once.  After running the transformation, the button no longer works for the dialog. But if you switch to the Script tab the button works as intended.

**Comment by cjh1** [comment]
It should be noted that the pipeline will only be re-executed if something has changed i.e. Either the source code or a parameter value. #1413 fixes the issue that changing a parameter value doesn't cause re-execution.

**Comment by cjh1** [comment]
This should be resolved by #1413
