### ISSUE TITLE
State file rewrite: serialization/deserialization

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1373]
Issue #1322 deals with separating out original and transformed data, these changes precipitate the need to rewrite the state file infrastructure, which was already planned as part of the Phase IIB project. The proposal was to use JSON as a basis for saving/restoring the data pipeline, and now seems like a great time.

**Comment by cryos** [comment]
Documenting where I am going with this, the old state file code effectively serializes a number of lists, and then deserializes those lists. We found that fragile, and it didn't reliably work for deeper pipelines, I am still working on the details, but moving to a situation where the top level data sources are serialized, they in turn serialize their children, making it easier to ensure the ordering is correct.

This does mean that more code is moving around, but it at least keeps the code close to the things it is most concerned with.

**Comment by cquammen** [comment]
Are you planning to strip out the XML serialization from ParaView and taking care of all state loading/saving from within tomviz? Having attempted to work with the ParaView serialization/deserialization, I think it may be easier to just skip using it altogether. What are your thoughts on that?

**Comment by cryos** [comment]
I am working on mapping it to JSON, and then bridging where it makes sense. I was just talking with @cjh1 as he added the Pipeline and PipelineManager classes about this. I think the ideal sequence goes:

1. Have PipelineManager serialize all top-level Pipeline objects
2. Pipeline objects serialize their DataSource objects
3. DataSource objects serialize their Operator objects
4. This recurses all the way to the bottom
5. Need a map of DataSource IDs for modules accessible to ModuleManager
6. ModuleManager serializes the Module objects at the end

Then repeat this process on loading state. That takes care of the pipelines, the complicating factor being the views, splits, etc, and remapping/restoring those. I would like to figure that out, but figure I will worry about it once I have the pipeline save/restore working. Taking the opportunity to make things more logically map to the new pipeline.

**Comment by cryos** [comment]
Rough (one-sided as it only saves right now) example showing a simple pipeline, with a child data source, modules attached to that child.
```
{
    "dataSources": [
        {
            "fileName": "/home/marcus/build/tomviz/myemd.emd",
            "modules": [
                {
                    "id": 2,
                    "type": "Volume",
                    "useDetachedColorMap": false,
                    "view": "3209"
                }
            ],
            "operators": [
                {
                    "childDataSource": {
                        "fileName": "Output",
                        "modules": [
                            {
                                "properties": {
                                    "gridColor": [
                                        0.8,
                                        0.8,
                                        0.8
                                    ],
                                    "gridLines": false,
                                    "gridVisibility": false,
                                    "visibility": true
                                },
                                "type": "Outline",
                                "view": "2178"
                            },
                            {
                                "type": "Orthogonal Slice",
                                "useDetachedColorMap": false,
                                "view": "2178"
                            }
                        ],
                        "spacing": [
                            1,
                            1,
                            1
                        ]
                    },
                    "type": "Python"
                }
            ],
            "spacing": [
                1,
                1,
                1
            ]
        }
    ],
    "tomviz": {
        "paraViewVersion": "5.4.1",
        "version": "1.2.1",
        "versionExtra": "141-g2e23e7f"
    }
}
```

**Comment by cryos** [comment]
I am going to merge what I have for some wider testing (PR #1458). It saves/restores all modules, pushes state files to the recent file menu, in adding color-opacity I noticed a bug (#1460) that will need to be fixed, it saves/restores Python-based operators, and child module logic is working with thanks to Chris and Shawn for their input on various pieces. I am going to keep this open, but will see if we can break the rest into smaller PRs.

**Comment by cryos** [comment]
I made two equivalent state files for 1.2.1 and master to look at raw file size. This was pretty simply, three points on the opacity map, default color map, invert data operator with outilne, orthogonal slice and volume module with default settings.
```
$ ls -lth
-rw-r--r-- 1 marcus users 7.4K Apr  2 14:22 tomviz-1-2-1-278-simple.tvsm
-rw-r--r-- 1 marcus users  70K Apr  2 14:22 tomviz-1-2-1-simple.tvsm
```
Still working through some bugs we have discovered, and rounding out support in follow up branches. The binaries should now contain a preview, and I will test these out on different platforms too.

**Comment by cryos** [comment]
This is more for my benefit right now, the following classes need serialize/deserialize methods:
- [ ] ConvertToFloatOperator
- [ ] CropOperator
- [ ] TranslateAlignOperator
- [ ] SetTiltAnglesOperator
- [ ] ConvertToVolumeOperator
- [ ] SnapshotOperator
- [ ] RecontructionOperator

Make sure to convert these over...

**Comment by cryos** [comment]
The crop operator restore is broken, need to investigate why, #1485 has conversion of all remaining operators.

**Comment by cryos** [comment]
Once these branches are merged I plan on removing more of the XML state code

**Comment by cryos** [comment]
A few more notes on state file features that need to be restored:

- [ ] Animation cues in Module
- [ ] The AxesGrid on the view (was in ModuleManager)

**Comment by cryos** [comment]
PR #1532 looked at animation cues, that is also broken in the last release (I discovered it after looking through the code, and then comparing behaviors in 1.2.1 and my working master).

**Comment by cryos** [comment]
Marking this issue as complete, the majority of functionality has been restored, with some new functionality such as child data/more advanced pipelines now working. We can track individual bugs in their own issues.
