### ISSUE TITLE
Deleting cloned data can delete the child data source from which it was copied

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1382]
* Load a dataset
* Segmentation -> Binary Threshold
* Right-click on Thresholded Segmentation dataset, choose Clone
* Delete the cloned dataset
* The Thresholded Segmentation dataset under Binary Threshold disappears, and the status indicator remains a green checkmark.

Expected behavior: the Thresholded Segmentation dataset should remain instead of being deleted.

**Comment by mathturtle** [comment]
After several hours of debugging: this is a pipeline display bug I think.  It seems to be deleting only the correct data source.  This can be seen by the following steps

* Load a dataset
* Segmentation -> Binary Threshold
* Data Transforms -> Square Root Data
* Right-click on Thresholded Segmentation dataset, choose Clone
* Delete the cloned dataset
* All child datasets on the original dataset and their visualization modules vanish, but the visualizations are still in the render view and they reappear if you add a new invert/square root operator to the pipeline.

**Comment by cryos** [comment]
@cjh1 Do you have any ideas on this? I can look at the pipeline code, but remember you working on similar issues.

**Comment by cjh1** [comment]
No ideas off hand, but can take a look.

**Comment by cquammen** [comment]
This seems to be resolved in Tomviz 1.3-rc2. There are additional crashes happening though. I will open up other issues to report them.
