### ISSUE TITLE
Combine Data Range and Dimensions in Data Properties Appearance

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#139]
The Data Properties panel is overfull, but there is unused space in the three lines used for Dimensions and Data Range at the top.

Combine this into two lines, e.g.:
"Original Dimensions & Range"
240 x 180 x 261 ,   0:255
"Transformed Dimensions & Range"
170 x 160 x 241 ,   0:16
<img width="372" alt="screen shot 2015-07-29 at 11 00 17 am" src="https://cloud.githubusercontent.com/assets/6197997/8961052/09b4e568-35e1-11e5-8ee1-59d00a7ebf92.png">

**Comment by cryos** [comment]
I like it, that sounds like a great idea to me.
