### ISSUE TITLE
Properties Panel UX and JSON

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1395]
The properties panels require large scroll bars. Properties panels should be designed such that scroll bars are not necessary (especially in the horizontal direction). We are unable to achieve this with the existing JSON examples. We would like to be able to place text above, below, and right of inputs.

Example UX Property Panels:
"Pad Volume"
"Shift Volume"
"Resample Volume"

@cryos @mathturtle @jtschwar

**Comment by cryos** [comment]
Thanks Rob, we should prioritize this, I have been guilty of a few hackish fixes to make the issue less pronounced in a few places.

**Comment by cquammen** [comment]
I have made some progress on this one. PR soon.

**Comment by cryos** [comment]
I think we need to figure out a way to avoid the need to manually wrap the lines too, we should be able to have one line and let it reflow as needed in the space allotted. We should then adjust code to avoid manual line breaks that were added.

**Comment by cquammen** [comment]
`QLabel::setWordWrap(true);` largely takes care of that issue. The remaining issue is that the `QGridLayout` wants column widths to match by default, so there can be a lot of extra empty space if one of the widgets is wide. My focus is to get rid of that extra space.

**Comment by cryos** [comment]
Sounds good, although getting word wrapping working would fix some of the worst offenders. Which ones have really wide columns, and what approach are you thinking of using to minimize that?

**Comment by cryos** [comment]
Looking at Rob's examples, I would remove the repetition in pad volume labels, i.e. just before, after, mode, and resampling could just use factor, and then ensure the spin boxes aren't super wide.

**Comment by cquammen** [comment]
I thought about using `QFormLayout`, but that has the restriction that you cannot have a widget span multiple columns, and it supports only two columns. I may be mistaken that `QGridLayout` wants columns to be the same size by default. I mocked up an example in Designer and the columns can be only as wide as needed. That doesn't seem to be the case in tomviz currently. **Pad Volume** has a wide combo box.

Alas, after trying to get the perfect layout for a while, it seems I can't yet find the perfect combination of size policies to minimize extra space. I'll push up a PR with some of the improvements I have so far.

**Comment by cquammen** [comment]
Actually, I'm completely wrong about `QGridLayout` wanting columns to be the same width. The first column is set to take up all the extra horizontal space, which is fine, but we may want to revisit this behavior in the future.

**Comment by cryos** [comment]
Having some ideas would be good, I think sticking with grid is likely best, and looking at ways to minimize the minimum size of elements horizontally. I would love to test out something with wrapping turned on, and then fixes to use one long line, and then see how much we can reduce what look like some overly large spin boxes in several places.

**Comment by cryos** [comment]
Taking a look at this, it would appear the major reason that Shift Volume and Resample Volume require such a large minimum size is due to their range being so huge. 
```
{
  "name" : "ShiftVolume",
  "label" : "Shift Volume",
  "description" : "Shift the volume. Voxels that roll beyond the last position in each dimension are re-introduced at the first position.",
  "parameters" : [
    {
      "type" : "xyz_header"
    },
    {
      "name" : "shift",
      "label" : "Shift",
      "description" : "The shift to apply",
      "type" : "int",
      "default" : [0, 0, 0],
      "minimum" : "negative_size",
      "maximum" : "size"
    }
  ]
}
```
The negative_size string does not occur in the Tomviz codebase as far as I can see, and size does not appear to have anything processing it. They then default to a range of -2147483648 -> 2147483647. I am improving the defaults, and changing the JSON a little.

**Comment by cquammen** [comment]
Nice. The "size" and "negative_size" were meant to set bounds on the widget range based on the data. Looks like I never implemented anything to look at those attributes.

**Comment by cryos** [comment]
I wondered if it was something like that. Closing this issue, I think master now fixes this, or makes it far better than it was.
