### ISSUE TITLE
Delete data and transforms is non-obvious

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#14]
“Delete data and modules” right now is hidden in the “data transforms” menu. This should be somewhere more obvious. It was one of the first things I looked for in the interface since I loaded my data wrong several times and wanted to clear it without restarting. I expect this will be a common experience.
--Elliot

Proposed solution: Users should be able to delete the data from the pipeline. This would include pressing the delete key and possibly right clicking and selecting 'delete'.

**Comment by mathturtle** [comment]
I was just trying to figure out how to do this...

**Comment by cryos** [comment]
Yes, it is there but it is not obvious or intuitive!

**Comment by ElliotPadgett** [comment]
A natural place to move this to would be the "Data properties" panel, since this mirrors the design for the delete module button in the module properties box.

**Comment by Hovden** [comment]
Can we close this?

**Comment by ElliotPadgett** [comment]
Should that wait for the solution to get merged?  I haven't had time to build it for myself to test.
