### ISSUE TITLE
Compiling Tomviz - error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by SirSharpest** [OpenChemistry/tomviz#1403]
Hi,

I followed the build instructions, compiled ITK and Paraview myself and yes they are build with the same python librarys, I checked the 3 variables mentioend by cmake. 

I'm on Arch Linux ```gcc (GCC) 7.2.1 20180116```, if there's any specific software versions that would be helpful, or output that could help please say and I'll supply it too. 

```
Scanning dependencies of target tomviz
[ 96%] Building CXX object tomviz/CMakeFiles/tomviz.dir/AboutDialog.cxx.o
[ 97%] Building CXX object tomviz/CMakeFiles/tomviz.dir/main.cxx.o
[ 98%] Building CXX object tomviz/CMakeFiles/tomviz.dir/WelcomeDialog.cxx.o
[ 98%] Building CXX object tomviz/CMakeFiles/tomviz.dir/MainWindow.cxx.o
[ 99%] Building CXX object tomviz/CMakeFiles/tomviz.dir/tomviz_autogen/EWIEGA46WW/qrc_resources.cpp.o
[100%] Building CXX object tomviz/CMakeFiles/tomviz.dir/tomviz_autogen/mocs_compilation.cpp.o
[100%] Linking CXX shared module ../../lib/site-packages/tomviz/_wrapping.so
[100%] Linking CXX executable ../bin/tomviz
/usr/bin/ld: libtomviz.a(PythonUtilities.cxx.o): undefined reference to symbol 'PyDict_SetItem'
/usr/lib/libpython3.6m.so.1.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tomviz/CMakeFiles/tomviz.dir/build.make:340: bin/tomviz] Error 1
make[1]: *** [CMakeFiles/Makefile2:115: tomviz/CMakeFiles/tomviz.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target _wrapping
make: *** [Makefile:130: all] Error 2
```

**Comment by SirSharpest** [comment]
From what I've read, this sounds like a library might be missing in the cmake config? I'm unsure, if anyone more familiar with function could lend a suggestion I'm more than happy to work on it.

**Comment by cryos** [comment]
My main development machine is Arch Linux, so it gets a fair bit of testing on that platform. Did you follow our guide to building everything in BUILDING.md? It looks a lot like errors I have seen when there has been a Python version mismatch. I can try a fresh build later today, I am on the same Python/GCC version as you.

**Comment by SirSharpest** [comment]
Quite possible - I'll have another go from scratch, I assume [this](https://github.com/OpenChemistry/tomviz/blob/master/BUILDING.md) is still the up-to-date instructions that I followed? Shall update this in the next day or two.

**Comment by cryos** [comment]
Yes, that's the one. I haven't done a fresh build in a while, so if you keep having trouble I can see if any recent changes might have affected things. I know they were making changes in VTK/ParaView that I haven't been focused on, and out version is getting a little old now.

**Comment by SirSharpest** [comment]
Yeah that might be helpful  - I've had a load of trouble with ITK too. Got everything compiled and then Tomviz itself would segfault due to a Py_Dict error. But I think that has more to do with how I compiled ITK. If you're able to confirm it's not just me that's a huge help.

**Comment by cryos** [comment]
I did a fresh compile, I got this error when I went to compile Tomviz,
```
-- Checking ParaView and ITK were built against the same Python
CMake Error at CMakeLists.txt:112 (message):
  The Python library is not the same for both ParaView and ITK.  Please
  ensure ParaView and ITK are being built against the same Python.  ParaView
  Python library: //lib/libpython3.6m.so, ITK Python include directory:
  //lib/libpython3.so
```
I enabled the skip check option to see if things would build, it is unclear if this is a local issue on my machine, but those files are not the same/symlinking to the same thing:
```
$ ls -l //lib/libpython3.so
-rwxr-xr-x 1 root root 5592 Jan  4 21:36 //lib/libpython3.so
$ ls -l //lib/libpython3.6m.so
lrwxrwxrwx 1 root root 20 Jan  4 21:36 //lib/libpython3.6m.so -> libpython3.6m.so.1.0
```
I do end up with:
```
$ ./bin/tomviz 
Traceback (most recent call last):
  File "/home/marcus/build/tomviz/lib/site-packages/tomviz/_internal.py", line 20, in <module>
    import tomviz._wrapping
ImportError: /home/marcus/build/tomviz/lib/site-packages/tomviz/_wrapping.so: undefined symbol: _Py_ZeroStruct
"Failed to import tomviz._internal module."
Segmentation fault (core dumped)
```
On further inspection the Tomviz cache is using Python 2.7, if you use cmake-gui, and check the advanced box, then search for 'python' you can then replace the 2.7 with 3.6. This was not necessary before, I will see if we can make this smoother.

**Comment by cryos** [comment]
It looks like our inheritance of Python from ParaView changed with recent changes in master, so the above patch restores that behavior (and will also work fine with older ParaView versions).

**Comment by apryor6** [comment]
I'm receiving a similar error on Ubuntu 16.04 

> Traceback (most recent call last):
>   File "/home/aj/tomviz/rebuild/tomviz-build/lib/site-packages/tomviz/_internal.py", line 20, in <module>
>     import tomviz._wrapping
> ModuleNotFoundError: No module named 'tomviz._wrapping'
> "Failed to import tomviz._internal module."
> Segmentation fault (core dumped)

This looks like a Python version mismatch, however it appears to have correctly linked to 3.6:

>$: ldd bin/tomviz | grep python
> libpython3.6m.so.1.0=> /usr/local/lib/libpython3.6m.so.1.0 (0x00007ff4fba15000)

>$: ldd ../paraview-build/bin/paraview | grep python
> libpython3.6m.so.1.0=> /usr/local/lib/libpython3.6m.so.1.0 (0x00007ff475688000)

I also got the same warning about python mismatch between ITK and ParaView, but I edited the CMakeCache.txt file so that they pointed to the same versions and rebuilt. Any other insights?

**Comment by cryos** [comment]
My laptop runs Ubuntu 16.04, and I tested our build instructions there too. I am puzzled as once I fixed the Tomviz and ParaView versions things worked fine. ITK isn't actually linked, it is loaded in Python if a segmentation operator is executed so it should really be down to Tomviz and ParaView at startup. I am guessing looking at the CMakeCache in cmake-gui, toggling advanced, searching for PYTHON that the Tomviz and ParaView Python library/includes are consistent?

**Comment by apryor6** [comment]
Per usual, a clean build directory + double-checking the paths matched solved the issue. Thanks

**Comment by cryos** [comment]
Glad to hear you managed to get it working. I am going to close this issue as it seems that things are resolved. ParaView's build system has changed quite a bit, and so I have had to create fresh build trees locally too. I will see if there is more we can do in future, but hopefully they are done making larger changes that leak out to us.
