### ISSUE TITLE
Histogram curve not rescaled

### ISSUE THREAD

**Issue by edobez** [OpenChemistry/tomviz#1410]
Hi,
I noticed a bug regarding the curve over the histogram.
The curve (normally a line) doesn't rescale properly when resetting the histogram zoom to normal.
To reproduce the problem:
1. open the NanoParticle demo (I guess it can reproduced with any volume)
2. zoom in the histogram using the middle-button selection
3. restore the 1:1 zoom by double-clicking either the middle or right button.

At this point the histogram curve will kept the scaled factor as during the zoom.

**Comment by cquammen** [comment]
Thanks for the report. I can confirm that the opacity function editor does not get rescaled in the Y direction when the histogram is reset.
