### ISSUE TITLE
Automatic Rescaling of Colormaps

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1420]
Automatic rescaling should not be hidden from the user or toggled within popups.

If we want to allow users to turn on or off automatic scaling, it should be present as an toggle icon in the histogram. This will also prevent the user from having to answer another question when changing the colormap range.

Below is the current dialogue:

<img width="695" alt="screen shot 2018-02-19 at 12 14 41 pm" src="https://user-images.githubusercontent.com/6197997/36389898-e6cd3148-156e-11e8-9080-08f70e488bd1.png">

**Comment by cryos** [comment]
If you just want to rescale the range to the complete data you should click the button above (reset data range) and you will not have to answer any questions. This dialog is from ParaView, and I have been meaning to develop a simpler one for Tomviz - they added the options but this will be simple to fix up. I will see if I can get to it soon.

**Comment by cryos** [comment]
I opened up #1589 to track the dialog update, not sure if we want to disable automatic rescaling - it is not something I am aware of people requesting.

**Comment by cryos** [comment]
Fixed.
