### ISSUE TITLE
Reduce Python vtk import time

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1426]
Instead of having

    import vtk

at the top of Python files, see if we can import a smaller subset containing only what we need.

**Comment by cquammen** [comment]
Things don't look very promising. Importing `vtk` is slightly faster than trying to import just a subset! I timed each import on three separate runs with a freshly launched tomviz on macOS.

```
import timeit
timeit.timeit('import vtk')

```
2.213054895401001
2.2654471397399902
2.335766077041626

```
import timeit
timeit.timeit('from vtk import vtkCommonCore')
```
2.4440670013427734
2.5159530639648438
2.459810972213745

```
import timeit
timeit.timeit('from vtk import vtkCommonDataModel')
```
2.5419509410858154
2.4953420162200928
2.471592903137207

```
import timeit
timeit.timeit('from vtk import vtkCommonExecutionModel')
```
2.4442391395568848
2.4563398361206055
2.5827600955963135

**Comment by cryos** [comment]
That is pretty shocking, does it reduce the memory footprint at all? Is it as bad from a simple vtkpython terminal too? I am surprised, and wonder if something is going wrong a little under the surface, such as still importing all modules. When this was implemented was any timing/memory testing performed for VTK and/or ParaView?

**Comment by mathturtle** [comment]
Cory, I think you are still importing all of VTK... From what I recall to import a subset, you do:
```
from vtkmodules import vtkFOO
```

Importing from vtk will import all of VTK.

**Comment by cquammen** [comment]
Ah, thanks, Shawn, that is indeed the way. Updated results to come.

**Comment by cryos** [comment]
Sounds good, fingers crossed you observe some improvements to load time and memory footprint. This is primarily about load time to be honest.

**Comment by cquammen** [comment]
That's more like it!

Import time has improved substantially:

```
import timeit
timeit.timeit('from vtkmodules import vtkCommonCore')
```
0.8280603470047936
0.7973260990111157
0.7687423750176094

```
import timeit
timeit.timeit('from vtkmodules import vtkCommonDataModel')
```
0.798640510009136
0.7889008759520948
0.7780052300076932

```
import timeit
timeit.timeit('from vtkmodules import vtkCommonExecutionModel')
```
0.8417072599986568
0.7615318640018813
0.7746472590370104

Memory footprint is affected just a little bit:

Memory: Memory before importing VTK 161 MB
`import vtk` 179.7 MB
`from vtkmodules import vtkCommonCore`: 164.4 MB
`from vtkmodules import vtkCommonDataModel`: 164.8 MB
`from vtkmodules import vtkCommonExecutionModel`: 163.6 MB

**Comment by cryos** [comment]
I was hoping for more out of vtkCommon*, but I will take it. I guess the memory is less affected as most of the shared objects for VTK/ParaView will already be loaded in. Nearly halving the time is great, looking forward to seeing the patch and trying it out locally.

**Comment by cquammen** [comment]
I will push a patch after testing the changes, but some bugs need to be fixed first (e.g., #1466).

**Comment by cquammen** [comment]
#1472 makes some progress toward reducing VTK import time.
