### ISSUE TITLE
Manual Alignment: Toggle mode alignments incorrect

### ISSUE THREAD

**Issue by hdevyldere** [OpenChemistry/tomviz#1430]
While Manually aligning a data set I found that aligning two images in Toggle mode does not give the correct (x,y) translations. Manual alignment using the Difference mode does give correct (x,y) translations.

When I created my own test case with two identical images shifted 11 pixels in x and 21 pixels in y, in difference mode to align the images the translations were (11,21). In toggle mode to make the images appear aligned the translations were (2, 4). Additionally in toggle mode, the two identical images (shifted in integer amounts of pixels) couldn't be perfectly aligned at all. The image appeared to be ~1/2 a pixel off on either side. 

Here is the test file I was using: 
   [File.zip](https://github.com/OpenChemistry/tomviz/files/1772657/File.zip)

Screenshot 1: The two squares aligned in Toggle mode
![screenshot 1 _li](https://user-images.githubusercontent.com/35352799/36868435-27f8654e-1d4d-11e8-9531-498f1392483b.jpg)

Screenshot 2: The two squares when I switch to difference mode. Notice, I didn't move the image at all between screenshot 1 and screenshot 2. The number of pixels that the image has been translated has not changed. 
![screenshot 2 _li](https://user-images.githubusercontent.com/35352799/36868525-712de702-1d4d-11e8-887b-dbea55ebe3c5.jpg)

Screenshot 3: After aligning the two images in difference mode. The x,y shifts are correct (the square cannot be seen because it is perfectly aligned).
![screenshot 3 _li](https://user-images.githubusercontent.com/35352799/36868628-c7919a1c-1d4d-11e8-8376-65de9fd4e6d2.jpg)

Suggestions?

Tomviz ver. 1.2.1 (I believe the most recent)

**Comment by ercius** [comment]
I can confirm something is not right with the toggle alignments. I just tried this out after creating my own similar object of size (128,128,10). The size of the shifts are different in Toggle and Difference mode. I can not get something aligned in Toggle mode but I can align it in Difference mode.

I also just realized the problem. Toggle mode is using the size of a pixel from the Units and Size boxes. An easy way to reproduce this is:
1.  Load the sample data set (starticle)
2. Set the size to 1/10th as indicated (originally 127,127,73)
![image](https://user-images.githubusercontent.com/15657108/37060794-306ff690-2146-11e8-897f-02408cf239ed.png)
3. Select Tomography --> Image alignment (manual)
4. Try to align the data set in Toggle mode. Single presses of the arrow keys make large jumps (10 pixels probably)
5. Try to align in difference mode. Single presses of arrow keys are 1 pixel as expected.

**Comment by cryos** [comment]
Thanks for the report (and confirmation). We will look into this, and make sure it is fixed for the next release.

**Comment by cryos** [comment]
This should be fixed by #1440, closing this issue, if you still see problems with the latest nightly builds please comment here/reopen.

**Comment by ercius** [comment]
This looks fixed now in the nightly build.
