### ISSUE TITLE
Passive Acquisition on Mac

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1433]
Hi, 
I've been having trouble to run the passive Acquisition on my mac. It causes Tomviz to crash whenever I run it. I tried working with @mathturtle and we ran the debugger to get this response. 

* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff9b4f3d42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff9b5e1457 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fff9b459420 libsystem_c.dylib`abort + 129
    frame #3: 0x00007fff9390afbf libGPUSupportMercury.dylib`gpusGenerateCrashLog + 158
    frame #4: 0x000000011549e09b AppleIntelHD5000GraphicsGLDriver`gpusKillClientExt + 9
    frame #5: 0x00007fff9390c524 libGPUSupportMercury.dylib`gpusSubmitDataBuffers + 560
    frame #6: 0x0000000115003d2a AppleIntelHD5000GraphicsGLDriver`IntelCommandBuffer::getNew(GLDContextRec*) + 178
    frame #7: 0x00000001150e698b AppleIntelHD5000GraphicsGLDriver`intelSubmitCommands + 171
    frame #8: 0x00000001154a3fe4 AppleIntelHD5000GraphicsGLDriver`glrFlushContextToken + 196
    frame #9: 0x0000000100f0ccb0 QtWidgets`___lldb_unnamed_symbol731$$QtWidgets + 58
    frame #10: 0x0000000100ef1a16 QtWidgets`QWidgetPrivate::sendComposeStatus(QWidget*, bool) + 46
    frame #11: 0x0000000100ef1a64 QtWidgets`QWidgetPrivate::sendComposeStatus(QWidget*, bool) + 124
    frame #12: 0x0000000100ef1a64 QtWidgets`QWidgetPrivate::sendComposeStatus(QWidget*, bool) + 124
    frame #13: 0x0000000100ec7d9f QtWidgets`___lldb_unnamed_symbol124$$QtWidgets + 613
    frame #14: 0x0000000100ec804f QtWidgets`___lldb_unnamed_symbol129$$QtWidgets + 197
    frame #15: 0x0000000100ecc0bb QtWidgets`___lldb_unnamed_symbol154$$QtWidgets + 3649
    frame #16: 0x0000000100eede57 QtWidgets`QWidget::event(QEvent*) + 2455
    frame #17: 0x0000000100ec08a9 QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 231
    frame #18: 0x0000000100ec1a9a QtWidgets`QApplication::notify(QObject*, QEvent*) + 394
    frame #19: 0x0000000107e788c5 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 157
    frame #20: 0x0000000107e7952c QtCore`QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 558
    frame #21: 0x000000010bf29de6 libqcocoa.dylib`___lldb_unnamed_symbol754$$libqcocoa.dylib + 190
    frame #22: 0x000000010bf2a4c3 libqcocoa.dylib`___lldb_unnamed_symbol767$$libqcocoa.dylib + 33
    frame #23: 0x00007fff85c5e321 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #24: 0x00007fff85c3f21d CoreFoundation`__CFRunLoopDoSources0 + 557
    frame #25: 0x00007fff85c3e716 CoreFoundation`__CFRunLoopRun + 934
    frame #26: 0x00007fff85c3e114 CoreFoundation`CFRunLoopRunSpecific + 420
    frame #27: 0x00007fff8519eebc HIToolbox`RunCurrentEventLoopInMode + 240
    frame #28: 0x00007fff8519ecf1 HIToolbox`ReceiveNextEventCommon + 432
    frame #29: 0x00007fff8519eb26 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 71
    frame #30: 0x00007fff83735a54 AppKit`_DPSNextEvent + 1120
    frame #31: 0x00007fff83eb17ee AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
    frame #32: 0x00007fff8372a3db AppKit`-[NSApplication run] + 926
    frame #33: 0x000000010bf2974f libqcocoa.dylib`___lldb_unnamed_symbol747$$libqcocoa.dylib + 2301
    frame #34: 0x0000000107e75557 QtCore`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 321
    frame #35: 0x0000000107e78dd9 QtCore`QCoreApplication::exec() + 265
    frame #36: 0x0000000100024f83 tomviz`main(argc=1, argv=0x00007fff5fbff890) at main.cxx:63 [opt]
    frame #37: 0x00007fff9b3c5235 libdyld.dylib`start + 1

**Comment by cjh1** [comment]
@jtschwar When is it crashing? When a new image is received?

**Comment by jtschwar** [comment]
Shortly after I click 'Introspect' on the Aquisition interface.

**Comment by cjh1** [comment]
Ok, the stack doesn't really help. I will see if I can recreate the crash on a Mac here.

**Comment by cryos** [comment]
We are tracking some issues with the OpenGL widget used by Tomviz on macOS, the Intel drivers are among the most prone to GL issues, and the trace looks like a GL issue to me. I would try updating the operating system to the latest available, we will also move to a dialog without the visualization by default which may alleviate this issue in the short term.

I know at the time @cquammen took a quick look and was able to open the acquisition dialog, there is a new OpenGL widget in development that is more robust, but it has bugs that are being figured out right now. It should hopefully replace what we have in the next month or two.

**Comment by cryos** [comment]
The new dialog removes the render widget, and has now been merged.

**Comment by cryos** [comment]
I don't think this is a general issue, and we have removed the GL window. Closing.
