### ISSUE TITLE
Check Memory Usage and Stability

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1435]
Check that the memory usage in tomviz is reasonable (i.e. does not fill up over time).

**Comment by cjh1** [comment]
![mem](https://user-images.githubusercontent.com/1031053/37793876-422c190c-2de6-11e8-81cc-68c6b3c98e67.png)

**Comment by cjh1** [comment]
The chart above shows 10 executions of the invert operator.

**Comment by cjh1** [comment]
Looks like we have some leaking VTK object: 

```
vtkDebugLeaks has detected LEAKS!
Class "vtkCellData" has 1 instance still around.
Class "vtkPointData" has 1 instance still around.
Class "vtkPoints" has 1 instance still around.
Class "vtkInformation" has 3 instances still around.
Class "vtkInformationIntegerPointerValue" has 1 instance still around.
Class "vtkIdList" has 1 instance still around.
Class "vtkDoubleArray" has 1 instance still around.
Class "vtkInformationIntegerValue" has 1 instance still around.
Class "vtkImageData" has 1 instance still around.
Class "vtkVoxel" has 1 instance still around.
Class "vtkFieldData" has 1 instance still around.
Class "vtkUnsignedCharArray" has 1 instance still around.
Class "9vtkBufferIdE" has 1 instance still around.
Class "vtkCommand or subclass" has 1 instance still around.
Class "9vtkBufferIhE" has 1 instance still around.
```

**Comment by mathturtle** [comment]
Rats... I thought I'd got that one with the pipeline fixes last week. :(

**Comment by cquammen** [comment]
I have tracked down one memory leak of the image allocated at https://github.com/OpenChemistry/tomviz/blob/943e0b25d1aa04215ae79f9da6d1cda2f9fd4697/tomviz/Pipeline.cxx#L115 when applying the Binary Threshold transform to original data. I did not see how to fix it, though.

**Comment by cryos** [comment]
It looks like the ITK-based operators are leaking, I just talked with @cjh1 and that data should flow through the pipeline and become the result, or if the operation is cancelled the result gets deleted. I am guessing this logic is breaking down in the ITK-based pipeline somewhere.

**Comment by cryos** [comment]
It may be more general than that, the reconstruction operators too, so anything where it makes its own child data I guess. There are also some odd behaviors for reconstruction where the modules are moved to the output but they are showing the original data still.

**Comment by cryos** [comment]
Any operator creating a child data set is overriding what we see in the pipeline as the result - that should be the same vtkImageData that was passed in to the start of the pipeline. We should either make the pipeline take ownership of the data during execution, deleting it upon completion (without relying on it being passed through), or have the operator creating the child data set delete the input data once it has completed/take ownership.

I see in the live update logic why things were made the way they are now, we should also probably document these expectations a little better in the code. We are in good shape, and can get this straightened out soon.

**Comment by cryos** [comment]
I solved the simple problem quite some time ago :1st_place_medal:, but have been tracking a leak that I thought was related to volume operators. It now looks like it is related to the set tilt angles operator... So I am on it, but it has been a little twisty.

**Comment by cryos** [comment]
I am going to mark this as closed, there may be some lingering issues, if so we can open new reports. The general concern of memory leaks introduced by the pipeline changes has been resolved, along with some leaks related to child versus non-child data, and the getCopyOfImagePriorTo functionality used by set tilt angles and similar.
