### ISSUE TITLE
Pipeline layout issue

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#1444]
I am seeing the following layout issue if I add more than a single operator: 

![screen](https://user-images.githubusercontent.com/1031053/37617027-35d0c53c-2b88-11e8-9795-6b3b1ce7e773.png)
It seems like the tables columns widths are being truncated.

**Comment by cjh1** [comment]
Can anyone confirm they are also seeing this?

**Comment by cryos** [comment]
I mentioned this, but thought it was a local issue at the time. I think something in the live Python pipeline update branch broke it - it worked before that merged for me, but then scrunched on adding operators after.

**Comment by cjh1** [comment]
@cryos I have done a bit of bisecting and as far as I can tell its unrelated to the live update changes. I will keep digging.

**Comment by cjh1** [comment]
This appears to be a Qt bug. The layout is fine with 5.9.3.

**Comment by cjh1** [comment]
I have a work around that I will push.

**Comment by mathturtle** [comment]
I know ParaView backed off from Qt 5.10 due to some bugs (but I think they were mostly macOS specific).

**Comment by cquammen** [comment]
Yep, see https://gitlab.kitware.com/paraview/paraview/issues/18013 for some of the problems in 5.10.

**Comment by cryos** [comment]
Yeah I worked with Utkarsh a little on narrowing them down, but they look quite unrelated to the pipeline layout issue. Glad it looks like you might have a workaround for this, I guess they broke a few things in the Qt widgets module.

**Comment by cjh1** [comment]
Fixed by #1445
