### ISSUE TITLE
Downsampling crashes for large volumes

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#146]
[Ubuntu] The scipy interpolation works well for small datasets, but crashes on large datasets.

**Comment by ElliotPadgett** [comment]
What counts as small and large here?

**Comment by Hovden** [comment]
I'm using the star particle data set at full res: 471x957x1057

I actually, am making the assumption about the size of the dataset being the issue, it just works on my smaller datasets (256^3) and not this larger one.

**Comment by mathturtle** [comment]
What are you doing in scipy?  Just applying the Rotate or Downsample x2 transforms?

**Comment by Hovden** [comment]
The downsample x2 transform. I haven't tested the rotate on a large dataset.

**Comment by mathturtle** [comment]
I just tried both downsample x2 and rotate on the 471 x 957 x 1057 dataset
and it worked fine for me.

**Comment by Hovden** [comment]
Ok. Maybe we just close this and reopen after I test it more and can provide specifics to the crash.
