### ISSUE TITLE
Binary Threshold segmentation operator producing empty child data

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1466]
* Load small test data set
* Segmentation -> Binary Threshold
* Child data is created, but it has dimensions (0x0x0) and no arrays

**Comment by cquammen** [comment]
Same with Ostu Multiple Threshold operator

**Comment by cryos** [comment]
Sounds like something amiss with the ITK-based operators.

**Comment by cjh1** [comment]
I get the following error when I try to reproduce this: 

```
cerr not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
cin not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
clog not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
cout not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
cvar not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
endl not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
ends not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
flush not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
ios not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
ios_base not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
ios_base_sync_with_stdio not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
ios_base_xalloc not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
iostream not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
istream not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
ostream not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
str not loaded from module ITKPyBase because of exception:
 Can't convert 'bool' object to str implicitly
Problem encountered while running BinaryThreshold
Traceback (most recent call last):
  File "Binary Threshold", line 85, in transform_scalars
  File "Binary Threshold", line 41, in transform_scalars
  File "/home/cjh/work/build/tomviz/lib/site-packages/tomviz/itkutils.py", line 280, in convert_vtk_to_itk_image
    dst_type = vtk_cast_map()[src_type]
  File "/home/cjh/work/build/tomviz/lib/site-packages/tomviz/itkutils.py", line 164, in vtk_cast_map
    itk.Vector
  File "/home/cjh/work/build/ITK/Wrapping/Generators/Python/itkLazy.py", line 42, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "/home/cjh/work/build/ITK/Wrapping/Generators/Python/itkBase.py", line 118, in LoadModule
    LoadModule(dep, namespace)
  File "/home/cjh/work/build/ITK/Wrapping/Generators/Python/itkBase.py", line 190, in LoadModule
    pyClassName, cppClassName, swigClassName = template
ValueError: too many values to unpack (expected 3)
Failed to execute the script.
```

@cquammen Do I need to push my ITK version forward?

**Comment by cquammen** [comment]
I do not believe so. I just started seeing this after pushing tomviz forward after our intermediate data update changes. I'll see if I can track it down.

**Comment by mathturtle** [comment]
Binary threshold was working 2 or 3 weeks ago when I updated ParaView and the OSX packaging scripts.  I use that as my test that ITK is working.

**Comment by cjh1** [comment]
Recent pipeline updates could well have broken it :frowning:

**Comment by cquammen** [comment]
It's not just ITK-based operators - I get the same result with Tomography -> Simultaneous Iterative Recon. Technique (SIRT). The child is empty.

**Comment by cryos** [comment]
So stuff from the Data Transforms menu appears to work pretty well, not surprising as I was using them as test cases while developing out some of the state file logic, but many of the others have this issue with zero-size array. Are they all using the same API, different to the Data Transform operators? I was going to branch out soon to the more exotic operators to ensure state was working too.

**Comment by cjh1** [comment]
@cquammen Let me know if I can assist.

**Comment by cquammen** [comment]
I suspect the changes we made to when child datasets are created for the live update work. I never checked that other transforms that produce child data continued to work. Now, operators are expected to make child datasets early in the script, and updated at least once via `self.progress.data`. It used to be that child data was set in a dictionary returned by the python operator. Such operators need to be updated to use the new child data approach, and the approach in general may need a little refining.

**Comment by cquammen** [comment]
By the way, I am currently working on updating the `BinaryThreshold.py` script to use the new child data mechanism.

**Comment by cryos** [comment]
Excellent, great to hear you got to the bottom of it!
