### ISSUE TITLE
Contour transformed data restores contour value to properties panel but not the view

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1475]
Steps to reproduce:

* Load a dataset
* Apply a transform (invert, square root or something else simple)
* Add a contour module and change the contour value to something other than the default
* Save State
* Reset/restart tomviz
* Load the state: the properties panel will have the correct value to contour by, but the displayed contour will be the default value

**Comment by cjh1** [comment]
Fixed by #1479
