### ISSUE TITLE
View color palette is not saved/restored by the state file

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1477]
* Load a dataset
* change the color palette
* Save a state file
*Reset/restart tomviz and load the state.... still the default color palette

From looking through the state file, I think this information is not saved.  I'm not sure if this worked even for the old state files.

**Comment by cryos** [comment]
I do not see this behavior, and worked on this feature. You may have to be more precise, if you change the palette in the selection this is saved and restored here (along with the opacity), but if you change an individual color there is a bug. Or are you referring to the background color, in which case I had not looked at that yet, maybe add view palette.

**Comment by mathturtle** [comment]
> Rereading, I am pretty sure you mean the view color palette, and we refer to the other as a color map. This, along with where items are translated is not saved or restored yet.

Yes, that is what I meant.
