### ISSUE TITLE
Histogram shows wrong transfer function limits when operators change range of data

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1497]
* Load a dataset
* Apply Square Root
* Click on the original data at the top of the pipeline
* The histogram shown has the full range, but the transfer function has the square rooted range (see image)

![tomviz_histogram_bad_bounds](https://user-images.githubusercontent.com/553788/39008931-20e1391e-43d8-11e8-9fea-ca00ff8fd40f.png)

**Comment by cryos** [comment]
I looked at the behavior with @cjh1, and was able to show that the color-opacity is for the transformed, and you can see it being manipulated if you add a volume visualization. My thinking is that clicking on the original data source, the operator, or a module visualizing the original would show the histogram and color-opacity for the original data.

Clicking on Output, operators below it, or the modules would show the tranformed/output data color-opacity and histogram. Modules may modify that by showing a detached color-opacity function. There is a PR working towards improving this, I think it is a remnant of old logic.

**Comment by cryos** [comment]
Resolved in master by #1546
