### ISSUE TITLE
Bad operator parameters cause GUI Freeze

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1498]
I haven't reproduced this with sane parameters yet... but essentially you need to run a binary threshold with a lower bound above the data's maximum or an upper bound below the data's minimum. A simple recipe:

* Load the sample dataset
* Square root
* Binary threshold, accepting the default parameters
* the binary threshold will hang at 100% progress

@cryos looked at this a bit and it seems we are deadlocked on the Python GIL.  ParaView's SMTrace stuff is trying to access the GIL in the foreground thread.  Why this only happens when you give bad parameters to binary threshold I have no idea... Probably low priority unless someone finds a more common recipe to cause it.

**Comment by cryos** [comment]
This is now resolved in master
