### ISSUE TITLE
Raw reader requires .raw extension to load file

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#15]
When importing a .raw file, the "Open File" interface will only display files with *.raw extensions. Often binary files will be stored as a variety of alternative extensions (such as *.bin and *.dat ).

Suggested Solution: when importing raw, either display all files (.) or at least add *.bin and *.dat

**Comment by Hovden** [comment]
Paraview currently assigns .dat to TecPlot files. The .dat file extension does not belong to TecPlot but rather is a generic extension for any kind of binary data. In both Paraview and tomviz, it would make more sense for .dat to default to the raw reader or not belong to any particular reader.

**Comment by mathturtle** [comment]
Did you try loading the files or just confirm that they showed up properly in the File -> Open dialog.  I'm still not sure it will use the correct reader for the other extensions.

**Comment by Hovden** [comment]
It appears to only load the .raw reader when a .raw file extension is opened. I haven't tried opening actual binary data yet. I will dig some up.

**Comment by mathturtle** [comment]
Alright, I can confirm that this doesn't work in the current version, but I have a patch in progress that will fix it.

@cryos The patch also adds the ability to add readers (and other things) to tomviz without going through VTK/ParaView first.  I just need to talk to Utkarsh about the plugin loading code and the patch will be done.

**Comment by mathturtle** [comment]
This should be fixed now.  @Hovden can you confirm?

**Comment by Hovden** [comment]
@yijiang1

**Comment by yijiang1** [comment]
I can confirm this works. Tomviz can read .raw, .bin, and .dat.

**Comment by Hovden** [comment]
Great. Closing.

We should add GUI labels to tell the reader of the bitdepth of the raw file-types. It is confusing.
