### ISSUE TITLE
Recon operator freezes at 100%

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1500]
Tomviz-1.2.1-430-gdbe1944-Windows-64bit

Any reconstruction operator freezes at 100% if you bin a dataset and then reconstruct. This might be related to #1498 but it gets a little more complex.

This ALSO happens when you bin the data set, save the data set (tried EMD and TIFF), reset tomviz, load binned data and reconstruct.

Worth checking out in tandem with #1498.

**Comment by cryos** [comment]
This is resolved in master, please reopen if you still see it.
