### ISSUE TITLE
Qt looks ugly/dated on Windows

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1502]
Tomviz-1.2.1-430-gdbe1944-Windows-64bit

In this nightly the interface looks "ugly" and blocky. Not sure what happened?

- tomviz 1.2.1
![tomviz121](https://user-images.githubusercontent.com/15657108/39016432-45c3972a-43d5-11e8-97b9-bb52c445eb1f.jpg)
- tomviz nightly:
![tomviz121_nightly](https://user-images.githubusercontent.com/15657108/39016434-496bc9d8-43d5-11e8-9815-121c08aa51ef.jpg)

**Comment by cryos** [comment]
This is probably a Qt change, but it does look quite a bit uglier/dated. We should look at what changed, and if we can select a better UI style on Windows.

**Comment by cryos** [comment]
I had a look into this, and the [Qt style gallery](http://doc.qt.io/qt-5/gallery.html) looks like we have been hit by a change in the default. I think the previous was `QWindowsVistaStyle`, and we are now `QWindowsStyle`

**Comment by cryos** [comment]
That did not work, I wonder if this is an issue with packaging plugins for styles rather than a new default.

**Comment by cryos** [comment]
I suspect this change is actually not necessary, it appears that Qt decided to make the Windows Vista style into a plugin, and embed/keep the ugly Windows style in the Widgets DLL. See this [bug report](https://bugreports.qt.io/browse/QTBUG-65177) for someone seeing the same issue, @mathturtle it looks like we will need to update the superbuild to account for this, and it may ripple out to other platforms.

**Comment by cryos** [comment]
This was changed in Qt 5.10, and there is nothing we are specifically interested in from 5.10, @mathturtle if the fix isn't obvious we should just move back to Qt 5.9 (whatever ParaView is using). We can track this as a longer term thread, maybe create an issue for the superbuild referencing this issue.

**Comment by cryos** [comment]
With Qt 5.10.1 on Windows 10 Pro I see with 1.2.1:
![image](https://user-images.githubusercontent.com/42214/39312693-2dae99dc-493e-11e8-944a-69c7d5fb372c.png)
and with the most recent nightly:
![image](https://user-images.githubusercontent.com/42214/39312740-41c733ca-493e-11e8-9738-efe9c5cd8baa.png)
It looks better, but the palette is different/darker.

**Comment by cryos** [comment]
After reverting my change I can verify 1.2.1-509 and later should look just as modern as before, setting windowsvista as the style added some ugly colors that didn't fit as well, but the basic widgets looked the same. Closing this issue for now, and using [this packaging bug](https://github.com/OpenChemistry/tomviz-superbuild/issues/237) to track the issue.
