### ISSUE TITLE
Scale cube

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1503]
Scale cube text can be hidden inside the cube

Also can not change the position of the scale cube text. This is hard coded in the scale cube properties. Im not sure if we want this to be changeable. Just mentioning.

**Comment by mathturtle** [comment]
@ercius The only time I was able to hide the text inside the cube is while interacting with the view.  As soon as I released the mouse button, the text position/orientation was recomputed and the text was on top of the cube again.  I can hide it behind the data, but then the scale cube is mostly hidden too.

**Comment by ercius** [comment]
Maybe that was there problem but I don't remember now. I tried to reproduce on 1.3.0 but couldn't. I'll close this issue and reopen if I notice it again.
