### ISSUE TITLE
Opening multiple TIFFS, check for same size

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1507]
Selecting multiple TIFFs in file open dialog can cause a crash.

How this happened is I saved the example Nanoparticle tilt series with different binnings (x1, x2, x4) as test0.tiff, test1.tiff, test2.tiff.

Then I tried to load them all at once by shift+clicking on them in the file dialog menu. This hard crashed tomviz.

tomviz crashes probably because these are considered a "tiff series" but have different sizes.

Need to check that tiff series all have the same size.

**Comment by cryos** [comment]
The core issue has been resolved by @alesgenova, there is also an improvement to this in the works to show which image(s) are inconsistent.
