### ISSUE TITLE
Crop operator on top

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1508]
Usability request:
Keep crop operator on top of the tomviz window. Its easy to get lost if you click+drag on the main window.

**Comment by mathturtle** [comment]
Are you on MacOS?  Then this is that MacOS "bug".  On other platforms QDialogs do always stay on top of their parent window, but MacOS doesn't support that.

**Comment by ercius** [comment]
I added this from my memory of working with a user on Mac OS yesterday. On Windows the crop operator stays on top. Sorry for the confusion.
