### ISSUE TITLE
Loading state file "erases" current state

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1509]
This might surprise some users. Loading a new data set does not make the current tomviz state fully reset. Probably should warn the user that loading a state file will overwrite all current work.

**Comment by cryos** [comment]
This isn't new, but you make a good point. We can add a warning with the option to cancel I think.

**Comment by cjh1** [comment]
Fixed by #1537

**Comment by cryos** [comment]
This should not be resolved, please reopen if this is not the case in the builds 1.2.1-509 or later.
