### ISSUE TITLE
Deleting reconstruction after state file load crashes tomviz

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1510]
Tomviz-1.2.1-430-gdbe1944-Windows-64bit

1. Reconstruct a data set successfully:
load data, set tilt angles, apply simple BP (C++) method
2. Save a state file (includes set tilt angles)
3. Reload the state file
4. Delete the reconstruction operator
5. Crash

It seems to hang on "Set tilt angles" in the pipeline. Then it fully crashes.

**Comment by cjh1** [comment]
This should be fixed by #1526 ( as in I don't see the crash with that fix ). Thanks for great recreate steps.

**Comment by cryos** [comment]
This does not crash, restores from the state file, and shows the correct volume now. Closing, please reopen if you still see crashes @ercius.
