### ISSUE TITLE
Passive acquisition usability

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1511]
Can this be used now for testing? I get a dialog box asking for where the server is located:
![image](https://user-images.githubusercontent.com/15657108/39018388-bc4e4f48-43da-11e8-9941-8d98bf0ec2d4.png)

File name regex is very complex for a non-expert. Can you add an example filename which would be properly formatted? Or a button to "test" read a directory to see if the regex matching works properly?

![image](https://user-images.githubusercontent.com/15657108/39018228-4d26ad54-43da-11e8-86df-191abd446d94.png)

**Comment by cryos** [comment]
This is getting more usable, @cjh1 developed a lot of this, I think that a tutorial document would help, trying to remember if we have an up to date one. Hopefully Chris will chime in.

**Comment by cjh1** [comment]
I think have a test button is a good idea. I think in the future we will move the regex's into an advanced view and just provide a few "canned" formats that will match common file naming conventions. Regex's give us the maximum flexibility but I agree they are a little intimidating to the end user so we should provide them with a little more help.

**Comment by alesgenova** [comment]
@ercius 
I have almost finished redesigning the passive acquisition dialog, you can find some screenshots of the current status at #1585 
Let me know if you have further suggestions on the interface

PS:
The old dialog will still be available when clicking the "advanced" option in the dropdown (not implemented yet)

**Comment by ercius** [comment]
The new dialog looks excellent. Thanks for the work on this and for the feedback. Ill have to test it out to make more suggestions. I think this goes a long way to making this useful for non-expert users. Ill close this now and open a new issue for other suggestions.
