### ISSUE TITLE
Loading state file with BP C++ reconstruction

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1512]
1. Reconstruct NP tilt series with BP C++ operator
2. Save state file
3. Load state file

Messages panel outputs:
> We need to do something with this: QJsonValue(array, QJsonArray([{"colorOpacityMap":{"colors":[3.0523931980133057,0.050383,0.029803,0.527975,24.687701725219487,0.193374,0.018354,0.59033,46.32301025242567,0.299855,0.009561,0.631624,67.95831877963185,0.399411,0.000859,0.656133,89.59362730683803,0.494877,0.01199,0.657865,111.22893583404421,0.584391,0.068579,0.632812,132.8645891745188,0.665129,0.138566,0.585582,154.49989770172502,0.736019,0.209439,0.527908,176.1352062289312,0.798216,0.280197,0.469538,197.77051475613737,0.853319,0.351553,0.413734,219.40582328334355,0.901807,0.425087,0.359688,241.04113181054976,0.942598,0.502639,0.305816,262.67644033775593,0.973416,0.585761,0.25154,284.3117488649621,0.991365,0.675355,0.198453,305.9470573921683,0.993033,0.77172,0.154808,327.58236591937447,0.974443,0.874622,0.144061,347.86566162109375,0.940015,0.975158,0.131326],"points":[3.0523931980133057,0,0.5,0,347.86566162109375,1,0.5,0]},"gradientOpacityMap":{"points":[]},"reader":{"fileName":"Reconstruction"}}]))

**Comment by cryos** [comment]
This is part of the general issue in #1513, we are handling it for normal pipelines, I added that debug statement, thanks for catching it as we should address this before the next release.
