### ISSUE TITLE
Reconstruction returns tiltseries not reconstruction

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1521]
1. Load Sample Data "Star Nanoparticle (tiltser)"
2. Mark Data as Tilt Series
3. Run recon Simple Back Projection C++
> Returned volume is not reconstruction, it is a tilt series

**Comment by cryos** [comment]
It looks like we never see the reconstruction in this case @cjh1, it looks like the original data just gets passed through.

**Comment by cryos** [comment]
This is resolved now, thanks for reporting it.
