### ISSUE TITLE
Reconstruction not executing (Direct Fourier)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1522]
1. Load tiltseries
2. Set Tilt angles.
3. Execute Direct Fourier Reconstruction.

"ModuleNotFoundError: No Module named 'pyfftw'

**Comment by mathturtle** [comment]
What platform, MacOS?

**Comment by Hovden** [comment]
MacOS

**Comment by cryos** [comment]
This works as expected on Windows latest installer.
