### ISSUE TITLE
Default Lighting Tweak

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1525]
Reduce the Azimuth on the backlight from 110 to 60.

After (60)
<img width="1001" alt="screen shot 2018-04-24 at 9 55 21 am" src="https://user-images.githubusercontent.com/6197997/39191831-cd7f421c-47a5-11e8-93af-ffa5e8c4ce94.png">

Before (110)
<img width="1002" alt="screen shot 2018-04-24 at 9 56 21 am" src="https://user-images.githubusercontent.com/6197997/39191838-cf57f6a6-47a5-11e8-93a2-dc52527d6cea.png">

**Comment by cryos** [comment]
I think I preferred the mood lighting, but it also looks good. Merging once the last bot comes back.

**Comment by cjh1** [comment]
Fixed by #1548
