### ISSUE TITLE
Save Data default should NOT be .csv - probably tiff

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#155]
When saving data the default should not be .csv

Tiff might be the most sensible default.

**Comment by cryos** [comment]
Agreed, will look into reordering this/tidying it up.

**Comment by Hovden** [comment]
<img width="1121" alt="screen shot 2015-08-13 at 10 18 08 am" src="https://cloud.githubusercontent.com/assets/6197997/9252103/b3f201a4-41a4-11e5-9e18-0178a47c2761.png">

**Comment by Hovden** [comment]
To reproduce:
1) Load tiltseries data that is included.
2) Run the reconstruction.
3) Save data
4) Load data

It ends with a crash.
