### ISSUE TITLE
Orthogonal Slice producing warning message

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#1558]
* Open Tomviz 1.3-rc2
* Load a data set
* Apply Invert Data. Orthogonal Slice will be moved under the transformed result.
* Apply Binary Threshold to the inverted data. The Orthogonal slice will now start producing the warning:

```
Warning: In /Users/kitware/dashboards/buildbot-slave/tomviz-bigmac-osx-shared-release_clang_osx10_9_superbuild/build/paraview/src/paraview/ParaViewCore/ClientServerCore/Rendering/vtkPVImageSliceMapper.cxx, line 146
vtkPVImageSliceMapper (0x7fd14bc09630): Failed to locate selected scalars. Will use image scalars by default.
```

**Comment by cryos** [comment]
This is something we noticed, pull requests welcome :smile:

**Comment by cquammen** [comment]
It has to do with the scalar array name used by the `ModuleOrthogonalSlice` being set based on the original data. When the child data set is created, the child data does not have an array with the same name, hence the warning. The fix should be to check when the module is moved below the child data and update the array name to something that does exist.

**Comment by cquammen** [comment]
Actually, that is not exactly the case because the scalar array name for coloring is not serialized/deserialized in `ModuleOrthogonalSlice`. Note that this means the state file does not store the color array name, either, so that won't be restored when loading a state file.

**Comment by cquammen** [comment]
Sorry, I'm getting confused. There is no notion of a color array for the `ModuleOrthogonalSlice`. There is just the active scalars in the `DataSource`. The warning message is still caused by the name of the color array in the `ModuleOrthogonalSlice` not existing in the child data set, however.

**Comment by cryos** [comment]
The update method causes the same warnings, when I was looking at some of this it seemed to be the live update infrastructure, which commonly gets called for anything that produces a child data source in the second code path. So the pipeline below gets a bunch of these warnings too:
![image](https://user-images.githubusercontent.com/42214/39576971-fdc7851a-4ead-11e8-9d53-4265f0251c0b.png)
If you have concrete ideas on a fix let me know, I just checked again and the slice mapper is indeed showing the right data, but spitting out many warnings. These are all single component images, and so we should be able to set the array to be visualized without any doubt. Agreed in future this will need to be extended to track different components.
