### ISSUE TITLE
Manual alignment results should be included in the auto save state

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#1562]
The manual alignment process can take some time so the intermediate results should be saved in the state file in case its interrupted for some reason. We can probably add the operator to a paused pipeline at which point the state should be preserved.

**Comment by cjh1** [comment]
Related #1133

**Comment by cryos** [comment]
I think we should circle back to this @cjh1 and @alesgenova to see what needs fixing before we merge the topic.

**Comment by cjh1** [comment]
Will do
