### ISSUE TITLE
Transparency for slice tools (opacity transfer function)

### ISSUE THREAD

**Issue by cophus** [OpenChemistry/tomviz#1565]
Slices (both orthogonal and arbitrary directions) do not support the opacity transfer function (of intensity) the way the volume render does.  This feature would be extremely useful for us!  

<img width="1717" alt="screenshot 2018-05-04 16 01 31" src="https://user-images.githubusercontent.com/796309/39656414-73498a16-4fb4-11e8-9913-a7144519ebcf.png">

**Comment by cryos** [comment]
Just to make sure I am understanding, in this example you have zero opacity assigned to the blue and blue/purple, so you would want them to be transparent, with increasing opacity as you moved into the red. Some level of per-pixel opacity mapping for slices?

**Comment by cryos** [comment]
So, in a surprising twist, after asking on our VTK developer list, this is already implemented, and it looks great (to my untrained eyes at least). Should this be enabled by default? Should we add a toggle for it? They are probably going to take most of the development time. The color transfer function also then reflects the opacity mapping.
![image](https://user-images.githubusercontent.com/42214/40624198-1f0f87ca-6279-11e8-9b4d-82a60e721236.png)

**Comment by ercius** [comment]
My opinion is to not enable this by default. I want to see the full opaque
slice, but have the option to enable this if wanted. This is definitely a
useful feature though!

**Comment by mathturtle** [comment]
I don't like it on the histogram, but that is just me.  I feel like the histogram's coloring shouldn't change as you adjust opacity so that you to see the counts of values that are currently transparent.

**Comment by ercius** [comment]
Most users I show tomviz do not understand the opacity. They don't quite understand that you move the linear line on the histogram which makes voxels more or less transparent. I think that having the histogram also look transparent would get this point across more easily.

Also, people do not understand that the transparency currently only affects volume renders. The addition of mapping transparency should help with this.

**Comment by cryos** [comment]
I share your feeling on this @ercius, you accurately see what will be rendered, and what the color ends up looking like. The question kind of remains for me though - should we globally enable this, and then manipulate the color map (possibly detached) to be opaque by default? I think that would give a better preview, but may be confusing - you could still see the opaque slice by setting all opacity to 1.0.

**Comment by cryos** [comment]
We could also get slightly fancy and show a gray histogram behind the main one that would show populations not being rendered.

**Comment by cryos** [comment]
In case we forget, discussion over hangout we decided to take the simpler path where mapping opacity would not be the default, if enabled it will force a detached color map for the slice module, and enable opacity mapping for that slice. We will need to grey out the detach check box while opacity mapping is enabled (but mark it enabled to make it clear what is happening).

**Comment by cryos** [comment]
@alesgenova can you look at implementing what we agreed upon for this, basically force a detach of the color map if opacity mapping for the two slice tools is enabled. It likely needs some improvement to the global detach color map check box as I don't think modules can directly access it - managed by the superclass.

**Comment by alesgenova** [comment]
#1594 implements this feature.
Closing
