### ISSUE TITLE
Reconstruction is very slow

### ISSUE THREAD

**Issue by ricounet67** [OpenChemistry/tomviz#1581]
Hi,
I would like to knox if Tomviz is optimized for GPU reconstruction. Indeed, on my PC or my Mac, reconstructing a 1024x1024x512 volume take several hours. It seems that it doesn't uses my GPU. Is it normal ?
Thank you
Best regards,
Eric

**Comment by cryos** [comment]
I think that 1.6 has some great improvements in speed, reducing temporaries, and other things. It doesn't use the GPU, but future integration of packages using the GPU should help there too.
