### ISSUE TITLE
The Preview menu entries in View do not work

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1591]
The Preview menu entries in the view menu do not work, they are a nice addition inherited from a new feature in ParaView. We should ideally make these work as expected, it may just be a few render/update calls that are missing. If not we should hide the entry for the next release, and look at what might be missing on the Tomviz/ParaView side.

**Comment by cryos** [comment]
This still doesn't work for me, the View -> Preview entries end up with disconnected views stuck at a size, and I cannot get back to filling the widget as normal without exiting and restarting the application.

**Comment by mathturtle** [comment]
Weird.  It is working fine for me.  Qt 5.9.2 and ParaView SHA b9a216aa78b1570bbd6e73133730782f4a6efdae

**Comment by cryos** [comment]
Maybe it is flaky with newer Qt version, ParaView also appears broken on my machine in a similar way with previews. This suggests the implementation might not be robust across Qt versions, but it does seem to test out on the Windows binary too. If ParaView or Tomviz move to a newer Qt this may hit us, or maybe it is related to the KDE desktop...

**Comment by cjh1** [comment]
@psavery Can you see if you see this issue. If not then we can probably put it down to Qt version and close it off.

**Comment by psavery** [comment]
It seems to work fine for me on Ubuntu 18.04, Qt 5.9.5, and ParaView SHA b9a216aa78b1570bbd6e73133730782f4a6efdae

**Comment by cryos** [comment]
Closing for now, it isn't solved, but it isn't as widespread as I had feared.
