### ISSUE TITLE
Contour default value can freeze tomviz for long periods

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1596]
Currently, the Contour default value is set to half of the histogram range. This can produce very long computations with no feedback to the user. I suggest 1 or both of the following:
1) Add a progress bar for this computation
2) Add a dialog box to allow the user to pick the value before the calculation proceeds

**Comment by cryos** [comment]
Ideally we should actually thread the calculation of the contour, then it would take place in a background thread without freezing the main UI. We had an experimental feature doing this with streaming using Dax way back, without moving it to a background thread it will be tough to show progress. Popping up a dialog would be relatively easy.

**Comment by cryos** [comment]
@psavery @cjh1

**Comment by cryos** [comment]
Digging deeper, there was a huge performance regression where the resample filter is running unconditionally. It causes memory use spikes too, and should have only ever run for segmented/labeled data. Removing that gets rid of the performance issue, and enables much faster contouring. We will be simplifying the contour module, and removing that first.

**Comment by cryos** [comment]
The regression is fixed, I think we may want to think a little about better use of background threads for some of this, or confirmation dialogs, but with typical data sizes this seems less critical now.
