### ISSUE TITLE
Custom Transforms menu item seeming redundant

### ISSUE THREAD

**Issue by willlllla** [OpenChemistry/tomviz#1598]
Right now custom transforms can be performed through: menu bar, data transforms, custom transforms, and imported through: menu bar, custom transforms, import custom transforms

The top menu bar item "custom transforms" and its sub item "import costom transforms" doesn't seem parallel to the other high-level items; it makes more sense if it's a part of the "data transforms" drop-down menu.

<img width="219" alt="screen shot 2018-05-31 at 11 03 45 am" src="https://user-images.githubusercontent.com/26354622/40790218-56df9fb4-64c2-11e8-8ee4-624dba0d9ab5.png">

<img width="266" alt="screen shot 2018-05-31 at 11 03 40 am" src="https://user-images.githubusercontent.com/26354622/40790219-56f96408-64c2-11e8-9fe4-e22912d56e44.png">

**Comment by mathturtle** [comment]
These menu items do two different things...

The Data Transforms -> Custom Transform creates a dialog where the user can put code for their custom transform.  The transform is then created, but the code is not saved anywhere for easy reuse.  This is for things you want to do only once.

The Custom Transforms -> Import Custom Transform... menu item imports preexisting custom transforms from disk and adds an item to the Custom Transforms menu for each of them.  These custom transforms are saved and will stay in the Custom Transforms menu even after exiting and reopening tomviz.  This is for custom transforms you or your group have put together that are considered generally useful and you just want to have available without pasting into the dialog.

**Comment by willlllla** [comment]
@mathturtle 
I see! Thank you for the explanation! Sorry I didn't know earlier. Feel free to mark this issue closed, thanks!
