### ISSUE TITLE
Export slice as image usability

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1608]
Having the ability to export ortho and non-ortho slices in Tomviz is really useful. However....

1) The ability is buried in the right click menu of the object in the pipeline. Would this be better placed in the Properties of the object as a GUI button?
2) The default option to export to is PNG. But PNG only allows 8-bit output (it warns you). Should we change this to TIF so that users dont get weird output the first time?
3) The exported data does not have the colormap applied. However, the right click menu says "Export as Image" and thus I expect to get the same thing that I see in the tomviz window (colormap applied, 8bit).
4) The data exported is probably the raw data from the interpolation or array slicing in VTK. I personally like having this option, but its not an "Image". We could allow the user to export an image or the raw data.

**Comment by cryos** [comment]
Good points, I had not thought about the color-opacity map being applied versus not applied. If exporting the raw data we should support TIFF as it supports a larger portion of the scalar types that we are interested in. If supporting PNG, then it should export full RGB(A) images, and set the DPI to 72 or 100 perhaps. I am not sure how much work it is to export the color mapped slice, but it would be a nice addition.
