### ISSUE TITLE
Exporting data and information from tomviz

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1609]
The options to export data and other information from tomviz (v1.3.1) are somewhat scattered. There is no coherent workflow/setup/concept (for lack of a better term) for exporting data. As a few examples:
1) The user can File -- Save or File -- Export a few things.
2) Data can be cloned or saved in the pipeline from a right-click menu for some modules and data sets. 
3) There is also the option to export a slice by right clicking on the (ortho-)slice pipeline module.
4) Manual alignment values can only really be exported from the state file

I think there are a few powerful things that tomviz can do which are currently hidden or hard to stumble on. This is especially true for users who use tomviz as part of a larger workflow incorporating other programs and software.

A new tutorial video or updated tutorial (as mentioned by @Hovden on Hangouts) will help. Not sure if something needs to change, but I wanted to mention this as the software is maturing. A decision on this could help new users or guide future decisions.

**Comment by cryos** [comment]
It might be good to outline the vision you have for how this might work, and whether changes to the interface are needed or more improvements to the documentation.
