### ISSUE TITLE
crash after changing python transform inputs in the Properties panel

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1628]
tomviz (binary v1.3.1 on mac) crashes if I change the argument of a transform in the Properties panel.
For example,
1. Load a sample dataset.
2. Do Rotate transform.
3. Modify the parameter in the Properties panel and then click apply.
4. crash.

**Comment by mathturtle** [comment]
Notes to self:  This is basically a case of the same pipeline running concurrently with itself.

Somehow the transformModified signal is getting connected to twice and triggering two separate instances of the pipeline to run.  tomviz/Pipeline.cxx:369
