### ISSUE TITLE
crash when deleting child dataset

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#1639]
binary 1.3.1 on Mac.
tomviz crashes when I delete a child dataset in the pipeline.
For example, 
1. Load the sample tilt series.
2. Do a reconstruction.
3. Right click the child dataset and click "Delete". 
<img width="318" alt="screen shot 2018-06-19 at 11 13 30 am" src="https://user-images.githubusercontent.com/13088588/41610099-f12c7314-73b1-11e8-8f2c-2bac8d53589c.png">
4. Crash.

**Comment by mathturtle** [comment]
I found the bug... it is a double free in `PipelineModel`.
