### ISSUE TITLE
Animation window: Add button missing

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1640]
Ubuntu 16.04, old Vaio laptop, tomviz 1.3.1

Note: This issue is most likely an issue with old hardware or drivers.

A user asked me how to make an animation using an old laptop with Ubuntu installed to replace Windows 8. (Im not sure of the specs of the laptop, but tomviz ran really well!)  However, the animation pane looked strange. And I was unable to add a camera using the "plus" button in the lower left.

I attach a screenshot of what it SHOULD look like from my Windows machine. I dont have a screen shot of the user's machine.

Can someone confirm (@cryos?) on a more current linux machine whether the plus button in the lower left is there or not. It the Animation pane looks good then its most likely an old hardware/driver issue.

![image](https://user-images.githubusercontent.com/15657108/41624493-be873354-73ca-11e8-9661-6c1ee0eb01a2.png)

**Comment by psavery** [comment]
I can confirm that on my Ubuntu 18.04 laptop, the plus button is missing as well. But this is a relatively old laptop as well (Dell Precision M4600).
![animation-pane](https://user-images.githubusercontent.com/9558430/41654195-ab6bba38-7456-11e8-8ddf-f28476a33628.png)

**Comment by psavery** [comment]
However, upon resizing the render window to give the animation pane more room, the plus button does appear.
![resized-animation](https://user-images.githubusercontent.com/9558430/41654677-34907564-7458-11e8-842c-6a0f4c363206.png)

**Comment by psavery** [comment]
It looks like this is actually caused by a bug in ParaView. If I follow the same steps above in ParaView, it also chops off some of the animation widget in the same way. 

We are using ParaView's classes for this animation widget.

**Comment by psavery** [comment]
I submitted an issue report of this for ParaView [here](https://gitlab.kitware.com/paraview/paraview/issues/18305).

**Comment by psavery** [comment]
Looks like they fixed this issue in ParaView via [this merge request](https://gitlab.kitware.com/paraview/paraview/merge_requests/2719).
