### ISSUE TITLE
Opacity Controller interactive Histogram Widget API required

### ISSUE THREAD

**Issue by Praz-3** [OpenChemistry/tomviz#1641]
I am trying to develop software for my specific purpose and I want to use the interactive Histogram widget from Tomviz in my project. So, does tomviz provides any API for this ?? Or from source code which files/classes should I import ?!
Does that widget is provided by VTK itself?
Thank you.

**Comment by mathturtle** [comment]
> So, does tomviz provides any API for this ?

Unfortunately no, we don't.  You'll have to copy the widget out of our source.

> Or from source code which files/classes should I import ?!

I think the parts you will be interested in are in the following files (all paths relative to the root of the source):

The widget itself with the histogram and the buttons:
* tomviz/HistogramWidget.cxx
* tomviz/HistogramWidget.h (Qt Widget)
* tomviz/vtkChartHistogramColorOpacityEditor.cxx
* tomviz/vtkChartHistogramColorOpacityEditor.h (VTK chart code for the widget)

The code to create and cache the histograms is currently (1.3.1) in tomviz/CentralWidget.cxx, but there is a branch (hopefully merged soon) to move it to tomviz/HistogramManager.cxx.

**Comment by mathturtle** [comment]
cc: @cquammen @cryos I think this is the guy on the mailing list this morning (he made this issue yesterday).  I've replied but if there is anything you want to add...

**Comment by cryos** [comment]
That looks correct, there are also some related Qt classes. Tomviz is not designed as a library, we may move some of these pieces into shared locations at some point, but at this stage this is application code. We build a static library, and so you could in theory link to that, but we are not focused on providing a stable C++ API at this point.

**Comment by Praz-3** [comment]
Thanks... It really helped in giving me a clear idea..
