### ISSUE TITLE
Handle different clang-format versions

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1642]
@cryos I have found a few cases where clang-format 6.0 and 3.8 disagree.  (See #1631 for an example case, I think it was `ModuleVolume.cxx` that had the problem).  It seems mostly to be dealing with lambdas.  Do we want to update the version we check with or is this another style file fix?

**Comment by cryos** [comment]
We should see if we can update clang-format, these are relatively minor/isolated so I don't think it is a big priority. I will take a look late this week/early next week. At the end of the day the robot wins, and we should all be looking at the output from the CI to verify formatting, proper building, but it would be good to move to a more recent CI clang-format.
