### ISSUE TITLE
Slice and orthoslice look different

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1649]
tomviz 1.3.1, Windows 10.

I noticed that the colormapped values of the Slice and OrthoSlice modules look completely different even for exactly the same slice. I made sure that they are using the data and colormap.

To recreate:
1. Load example reconstruction data set
2. Set orthoslice to YZ slice 50
3. Add a slice and set Point on Plane X value to 50 (I added the slice to a separate render window)
4. You might have to toggle each on/off to avoid overlaps between the two slices
Screenshot:
![clipboard01](https://user-images.githubusercontent.com/15657108/42058214-8ddd6104-7ad4-11e8-9434-e89005f1a6e8.jpg)

I have seen this same behaviour regardless of whether a separate colormap is enabled or the slices that I use. The intensity values of the Slice are not fitting within the values of the original data (i.e. the histogram). I cant make them look the same either.

As one more test I exported the orthoslice and Slice as tiff images. These images are different sizes (OK) and rotated by 90 degrees from each other. Otherwise, they are identical as far as I can tell:

orthoslice:
![ottho](https://user-images.githubusercontent.com/15657108/42058595-c3aa74c4-7ad5-11e8-8243-f28e3ddd08fd.jpg)

slice:
![slice](https://user-images.githubusercontent.com/15657108/42058609-c8711b3e-7ad5-11e8-97f2-cdc7492b5e02.jpg)

**Comment by cryos** [comment]
That is odd, and I do not remember that being the case. I see it locally too. We should look into what is happening, it looks like differences in lighting perhaps.

**Comment by mathturtle** [comment]
Looks like it is a simple lighting property fix.  Commenting out the line that calls SetAmbient(1) on the property makes the two look very similar.  I'll put up an MR for that.
