### ISSUE TITLE
Nightly old version number - not updating

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1654]
The zip file exe has the version 1.3.0-12.

Are the Windows nightly builds broken?

**Comment by cryos** [comment]
Thanks for adding this issue, we are looking into it. When we simplified the file suffix for the binary installers there was a regular expression that relied on the '-' after the git describe string to replace it with latest.

I updated the links on the download page, but there is still an issue with the Windows binaries at this point - the symlink isn't there. We will hopefully have this all working soon. We will update this issue once all latest binary links are working again with current installers.

**Comment by cryos** [comment]
Just about to leave, but it looks like the Windows latest links are also correctly resolving at least. I have not had a chance to open any of them and verify they correspond to the current master, we should do that for all four before closing this issue.

**Comment by mathturtle** [comment]
I've verified OSX and Linux so far.  I'll check the Windows ones this afternoon.

**Comment by mathturtle** [comment]
Windows has the new version too for both zip and msi.

**Comment by cryos** [comment]
Thank you for verifying, closing this issue.
