### ISSUE TITLE
Inconsistency in properties panel GUI and "Double click" GUI lead to hard crash

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1670]
tomviz 1.3.1 windows 10

I can make a python operator report inconsistent states by changing the value in the user interface that pops up when I double click the operator in the pipeline and when I use the Properties panel. If you use both ways of changing the transform value then tomviz hard crashes. The example here is for a Gaussian blur.

Hard crash:
1) Load volumetric data (Star NP example reconstruction)
2) Select Data Transforms -- Gaussian blur and apply the default (2.0)
![image](https://user-images.githubusercontent.com/15657108/42788115-8030b14a-8912-11e8-8b2c-9cd707076b63.png)
3) Now single click on the Gaussian blur transform in the pipeline
4) Change the value in the properties panel and press Apply
![image](https://user-images.githubusercontent.com/15657108/42788359-e7b295c6-8913-11e8-997c-de57f2a10a74.png)
5) Hard crash of tomviz

Inconsistency:
1) Load volumetric data (Start NP example reconstruction)
2) Select Data Transforms -- Gaussian blur and apply the default value (2.0)
3) Now double click on the Gaussian blur transform in the pipeline
4) Change the value to a different value (e.g. 1.0) and press ok
5) Single click on Gaussian blur transform in pipeline
6) Properties panel still reports original default value (2.0)

This also happens for Pad volume and Clip edges. Not sure if there are others.

**Comment by mathturtle** [comment]
I'm fairly sure this is a general problem with all Python operators.  The inconsistency is because we never consider the case where two editors are open at once for the same operator, so we don't have a mechanism for an updated operator to update its editor widget.  I'm not sure why it would crash though.

**Comment by cryos** [comment]
I was able to successfully reproduce your crash on Windows 10 with the 1.3.1 release. Using 1.3.1-218 on Windows 10 the crash no longer happens. The inconsistency in values is still present in my testing, and the initial run isn't opening the dialog for me to choose a value. It doesn't look like any of the Python-based operators are opening the initial dialog - I will create a new issue to track that as it was not intended.
