### ISSUE TITLE
Physical Pixel/Voxel Size Issues and suggestion for easy solution

### ISSUE THREAD

**Issue by bdalevin** [OpenChemistry/tomviz#1678]
I have recently been contacted by some scientists who are having an issue using tomviz. They are not able to work out how to tell tomviz what the physical size of a voxel (i.e. the scale) is supposed to be in their data, and hence all of their scale bars are wrong. 

I have been playing around with tomviz this morning, and I can't seem to find a way to set the voxel size either. I have tried loading tiltser_180 and recon_180 from the datasets published in Scientific Data, but the scale bars in tomviz (version 1.3.1 on Windows) are not correct for these datasets. Tomviz reads in 1 voxel = 1 nm, which is wrong. There is a Units and Size feature, but changing these numbers shrinks or expands the visualization, which is not very helpful (particularly if, for example, you want to switch scale from nm to microns).  

This is a major, major issue. The ability to accurately set the physical voxel size is crucial for using tomviz to publish data. 

I see that a similar problem was discussed in issue #1284 (now closed), but the solution focused on better reading the scale from metadata associated with files. 

A much, much better solution would be to add a simple feature to tomviz that gives users the ability to manually set the physical voxel size. ImageJ does this very well with pixels (see attached image). You can manually tell ImageJ what the physical size of a pixel is, to ensure that all scale bars are accurate. 
![imagejscale](https://user-images.githubusercontent.com/12704237/43089381-4fb6b7de-8e59-11e8-9a58-e18809fae77c.PNG)

Can we implement a feature like this in tomviz? (If one already exists, can we expose it so that it is easier to find?)

**Comment by alesgenova** [comment]
@bdalevin 

I have been playing around to see if something similar could already been done with Tomviz, and it looks like all of the pieces are already there.

As you noticed, there is a 'Units and Size' option in the datasource panel, where you can set the extent of the data source in terms of physical sizes (and can do so independently for each direction).

I noticed that when changing these options the image can become tiny/huge, and this can be puzzling for a user. By clicking on the 'reset camera' button you can fix this.

For this reason I opened a small merge request to reset the camera automatically upon changing any of the size values. This would prevent the image from becoming tiny/huge without any additional input from the user. #1681

Attached is a screenshot of a 256x256x64 px image mapped to 2.56x2.56x0.74 ang in the physical world. As you can see, both the ruler and the axis tool are now showing the correct size/units.

Hope this helps

![screenshot from 2018-07-23 16-01-06](https://user-images.githubusercontent.com/15913822/43100434-53759f54-8e93-11e8-9207-1e2db411618a.png)

**Comment by ercius** [comment]
I will add one quick comment:
The Reset Camera and Zoom to Data buttons
![image](https://user-images.githubusercontent.com/15657108/43106791-142b7048-8e8f-11e8-989d-9b807828d14b.png)
 are very convenient when anything looks or acts strange in a the render window. Click them often!
