### ISSUE TITLE
Outline "show axes" and Volume visualization

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1682]
tomviz 1.3.1, Windows 10

The Volume visualization does not show when the Outline "Show axes" checkbox is clicked first.
1) Load example Reconstruction dataset
2) Click on Outline --> Show Axes. The white outline will have scale markers drawn.
3) Click on Volume visualization. Nothing is shown
4) Delete Volume visualization
5) Unclick "Show axes"
6) Add a Volume visualization. It is now shown
7) Click on Outline --> "Show Axes" and the axes do not hide the visualization

The Volume visualization is not shown when the Show axes checkbox is on and the Volume is added to the pipeline. Otherwise, there is no issue.

**Comment by psavery** [comment]
@alesgenova and I were taking a little bit of a look at this issue this morning. My windows computer has two graphics cards: an nvidia GeForce GTX 950M, and integrated Intel HD Graphics 530.

If I run tomviz with my nvidia graphics card, the problem **does not** occur.
If I run tomviz with my intel graphics card, the problem **does** occur.

@alesgenova's windows computer has an integrated intel HD graphics 5500 graphics card. He has dual boot with Ubuntu.

If he runs tomviz on his windows 10 OS, the problem **does** occur.
If he runs tomviz on his Ubuntu 16.04 OS (with the same graphics card), the problem **does not** occur.

Are you using an intel graphics card, Peter? It looks to me like the problem may be specifically for intel graphics cards on Windows computers.

**Comment by ercius** [comment]
Yes. I am using a laptop with an Intel graphics card. So, it looks like
this is an issue with Intel cards and/or drivers. I think this can safely
be ignored due to that and the strange set of steps to get it too occur.
