### ISSUE TITLE
Pipeline glitchy when deleting items from pipeline

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1691]
The new pipeline has become sensitive glitches when items are deleted. In particular, the pipeline often gets confused as to whether or not it has been marked as a tiltseries:

This image shows a tiltseries that thinks it is a volume:

<img width="734" alt="screen shot 2018-08-05 at 9 32 11 pm" src="https://user-images.githubusercontent.com/6197997/43692646-49404048-98f7-11e8-9c82-5d400d3fd657.png">

**Comment by mathturtle** [comment]
> In particular, the pipeline often gets confused as to whether or not it has been marked as a tiltseries

I think this was part of supporting other types of tomography.  We removed the "must be run on tilt series" from many of the operators in the Tomography menu.
