### ISSUE TITLE
Failed to execute the script: AttributeError: 'NoneType' object has no attribute 'size' 

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1692]
WBP Reconstruction fails to execute:

<img width="1038" alt="screen shot 2018-08-05 at 9 36 49 pm" src="https://user-images.githubusercontent.com/6197997/43692737-f09d2554-98f7-11e8-9fad-956ecf9d763e.png">

**Comment by cryos** [comment]
Testing 1.4.0-58 (nightly from today) on macOS Mojave latest release shows no issue in reconstructing the tiltser_180 data set downloaded from the Nature Data paper (single TIFF). I will mark this as resolved unless you are still seeing issues, we have made a number of fixes to the reconstruction pipeline. It is pretty slow, I will wait for it to complete.

**Comment by cryos** [comment]
I can reliably reproduce this with the following recipe, which works on macOS and Linux binaries from today confirmed (1.4.0-58):

1. Load sample tilt series data set
2. Perform weighted back projection
3. Hit cancel
4. Click on re-execute pipeline from the context menu on the reconstruction operator
```
Traceback (most recent call last):
  File "Reconstruct (Back Projection)", line 48, in transform_scalars
  File "Reconstruct (Back Projection)", line 77, in wbp2
AttributeError: 'NoneType' object has no attribute 'size'
Failed to execute the script.
```
On first run things work fine, but once in this state it is necessary to double click on set tilt angles after deleting the operators after it. Not sure if this is what you were doing, but the above recipe reliably gets me to the point you describe. Any ideas @cjh1? This is definitely a bug, and I think it will require some pipeline updates. We may want to prioritize getting a release out with crasher fixes soon, and then looking at fixing this in a 1.5.1.
