### ISSUE TITLE
WBP recon fails to execute (OSX)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1693]
(1) loaded dataset (2) marked as tiltseries (3) changed live update for %4 iterations (4) click execute:
<img width="1042" alt="screen shot 2018-08-05 at 9 40 11 pm" src="https://user-images.githubusercontent.com/6197997/43692805-6a02bcf6-98f8-11e8-94f2-ce001bd0bf8b.png">

ERROR: In /Users/kitware/dashboards/buildbot-slave/tomviz-bigmac-osx-shared-release_clang_osx10_9_superbuild/build/paraview/src/paraview/VTK/Rendering/Volume/vtkGPUVolumeRayCastMapper.cxx, line 347
vtkOpenGLGPUVolumeRayCastMapper (0x7fc8b7784200): No scalars named "" or with id -1 found on input.

**Comment by mathturtle** [comment]
> changed live update for %4 iterations

The only way I know to do this is by editing the script to change the update frequency.  If there is some control I am missing please let me know.

**Comment by mathturtle** [comment]
I didn't see the error message in this issue, but I reproduced #1692 by setting the update frequency down to `%2`.
