### ISSUE TITLE
System Crashes during live reconstruction

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1694]
(1) Load dataset (2) Mark as TiltSer (3) Run WBP and change to update %2 iterations (4) interact with dataset continuously during reconstruction. (5) System crashes.

OSX

**Comment by cjh1** [comment]
I am unable to recreate this on Linux. I will now try on OSX. I am assuming that in step 3, you are saying update the python code at line 59 to change 40 to 2? i.e. increasing the update rate?

**Comment by cjh1** [comment]
I am unable to recreate on OSX 10.12.6. Is there some specific interaction that causes the crash? I am adding a volume module and rotating the dataset.

**Comment by Hovden** [comment]
Chris,

I would test on larger datasets ( ca 512 or greater).

When the pinwheel appears, there is a 50/50 it will crash. Typically happens when interacting with high refresh (eg changing 40 to 2).

RH

**Comment by cjh1** [comment]
@Hovden I am using TiltSeries_NanoParticle_doi_10.1021-nl103400a.tif, can I get access to the data set you are using?

**Comment by Hovden** [comment]
There are several datasets in the Nature Sci Data Article published in 2016, google nanomaterial datasets for tomography hovden.

Also, cancel and delete reconstructions midway to set tomviz up for crashes or glitchy pipeline- it won’t take much.

You can also generate projections from the generate nanoparticles datasets.

I can sit down this afternoon for a skype call to get a patch release out.

**Comment by cjh1** [comment]
I have tried with a couple of other datasets and still can't recreate this crash.

**Comment by Hovden** [comment]
I have been using: "tiltser_180.tif"

But I can get a crash or an error, ~20% of the time on any reconstruction >256. For example (1) Generate Random Nanoparticles (2) Project Tilt Series (3) Create Volume Render (4) Weighted Back Projection.

Produces the following error:
<img width="687" alt="screen shot 2018-08-07 at 9 07 30 am" src="https://user-images.githubusercontent.com/6197997/43777696-8d0aca3e-9a21-11e8-9d83-ca64cd1194a8.png">
