### ISSUE TITLE
Remove prompt from contour viz

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1696]
When adding a contour, tomviz prompts the user with a popup to select a contour value. We should avoid popups in the software. Also, if the user selects, do not show again, it is not clear how to reverse this decision.

A media intensity from the histogram should be used as the default value. The user can adjust after in the properties panel.

**Comment by ercius** [comment]
This was added via my suggestions in #1595 and #1596. You can read the conversation and reasoning there. I dont think this was meant to be in 1.4.0 though.

**Comment by Hovden** [comment]
Right. If the wrong value is chosen, you can get into a bad place. The median, should resolve the issue for most datasets, unless it is white noise. Until a more elegant UX design is determined, I suggest defaulting to the median.
