### ISSUE TITLE
Improve Python Development Code Structure

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#170]
Python development is now ramping up. It is worth thinking about the best way to organize the tomviz code for development and addition of many new python routines and menu items.

**Comment by mathturtle** [comment]
@cryos Essentially we want to install the python files instead of compiling them in right?

**Comment by cryos** [comment]
Pull request #272 makes a few tweaks to the Python files - switch to symlinks on OSes that support them for the Python files in the build trees, and make the Python files show up in IDEs.

I have a simple JSON sample that would be read in to construct the menu entries below, and a branch where some of this is being read in.

  {
    "name": "Tilt Series",
    "description": "Do a tilt series",
    "category": "Tomography",
    "priority": 5
  }

How are you determining the ordering for the menu entries right now - they look somewhat arbitrary. I thought each top level menu could simply fall into a category, but what about separators, absolute ordering? We could insert a separator if the entry passes a 100 line, use the priority number, and alphanumeric sorting as a secondary.

This pushes towards having drag and drop Python files, with separate JSON files (same name, .json and .py file endings).

**Comment by cryos** [comment]
I think we addressed the major points I was concerned about here.
