### ISSUE TITLE
Add support for tilt angles in the EMD format

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1700]
The [EMD spec](https://emdatasets.com/format/) has support for expressing dimensions in the three dimensions, with tilt angles we should support x, y using n_m, etc and then angles in the z dimension. We need to ensure we can round trip EMD files (save with angles, load with angles). Also ensure that units/size is round tripped correctly.

Once that is working we need some code to mirror this in Python to support the Docker reconstruction. This should be done and verified to ensure that we can pass angles, and we can loop @cjh1 in at this stage to ensure it can be passed in without modifying reconstruction code too much.

**Comment by cryos** [comment]
Yes this is why I wanted to do some verification work. All saving/loading should be in C order, while not explicitly stated that is the preferred ordering.

**Comment by cryos** [comment]
We merged #1701, but I am going to push this back to the next release to track further verification work that I suspect we should do.

**Comment by psavery** [comment]
The Fortran/C ordering issues (mentioned also in #1808) are being fixed in #1814. The EMD X and Z axes will be swapped for tilt series via #1816.

**Comment by cryos** [comment]
I think we can close this now.
