### ISSUE TITLE
Screenshot window does not keep aspect ratio

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1715]
tomviz 1.4.0, Windows 10

In the "save screenshot" window there is a button to the right of the X,Y size boxes. It looks like it should toggle to keep the aspect ratio of one size when the other size is changed. However, this button seems to not do anything currently. 

![image](https://user-images.githubusercontent.com/15657108/46308364-489b1e80-c56e-11e8-848e-6d1256f840a6.png)

Can we add an option to scale X,Y by for example 2x and 4x automatically as in the "save animation" window? In fact, using the same relevant parts of the layout of the animation window would be very nice and consistent (the scale button, the lock button and the rest button).
![image](https://user-images.githubusercontent.com/15657108/46308479-9ca60300-c56e-11e8-8463-efb6d27f9f7f.png)

**Comment by cryos** [comment]
Fixed, it took a little more work than expected, but it should work as expected and uses the lock icon to be more consistent with other dialogs.
