### ISSUE TITLE
Segfault when opening (any) TIF image file

### ISSUE THREAD

**Issue by maxf130** [OpenChemistry/tomviz#1721]
Hi,
sometimes tomviz will segfault when opening any TIF image file.

Steps required to reproduce:
1. Place attached state file at ~/.config/tomviz/tomviz1.4.0.ini
2. Open tomviz
3. Open any TIF (through the dialogue or through Open recent)
4. Segfault

Errata:
Initially tomviz will behave just fine.  After some amount of use (over several days or even weeks) any attempt to open a TIF will result in a segfault.  Once this starts happenening, it will continue to happen indefinetely, however deleting the state file in ~/.config/tomviz resolves the problem until it happens again.

This has occured both with tomviz 1.3.1 and 1.4.0.  I have also tried compiling tomviz 1.4.0 from source, it also crashes with the (broken?) state file.  I do not know if the self compiled version of tomviz will produce a broken state file after some time. 

I have attached a state file that causes this issue, as well as a stacktrace from gdb.

[tomviz_stacktrace.txt](https://github.com/OpenChemistry/tomviz/files/2525709/tomviz_stacktrace.txt)
[tomviz1.4.0.ini](https://github.com/OpenChemistry/tomviz/files/2525712/tomviz1.4.0.ini.txt)

This is happening on Ubuntu 18.04, though one of my collegues has reported a similar problem on Windows 7.

I'm happy to provide additional information or do some additional debugging at my end.

Many Thanks

Max

EDIT:

Maybe this is related to  #1646?

**Comment by cryos** [comment]
It doesn't look related to #1646, but we will look into it. Thank you for the detailed report, there are some good clues in the stack trace.

**Comment by cryos** [comment]
I can't reproduce your crash with your state file here, but it could be because I do not have the files/mounts you have in place. One thing that really sticks out for me is `RecentlyUsedResourcesList`, I think that is leaking through from the ParaView code, and that seems to be where the crash is coming from. If you keep the config file that causes the crash, and delete that whole block (basically that line in the file) does it stop Tomviz from crashing?

**Comment by cryos** [comment]
The binary version 1.4.0-71 will contain the fix mentioned above, I could not reproduce your crash, but I am pretty sure the key deleted was causing you issues, by clearing it in our code upon loading recent files it should resolve the issue locally. Please reopen this issue if that does not seem to be the case. Thanks for reporting this issue!
