### ISSUE TITLE
Cannot Delete Reconstructions From Pipeline

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1722]
Reconstructions in the pipeline cannot be deleted after partially executed (OSX).

<img width="390" alt="screen shot 2018-10-30 at 10 35 10 am" src="https://user-images.githubusercontent.com/6197997/47725954-f2ce9a80-dc2f-11e8-9aad-d320f56899dd.png">

**Comment by cryos** [comment]
This is working on macOS Mojave with the 1.4.0-58 binary from yesterday. I loaded the data, tried running direct fourier and weighted back projection. In both cases canceled part way into exection, was able to delete, the delete entry was not disabled as in the screenshot.
