### ISSUE TITLE
Fatal crash when using data transform.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#173]
System crashes (OSX) when calling a simple transform (square root)

Reproduce:
1) Open sample tilt series
2) Data Transforms > Reconstruct
3) Data Transforms > Square Root

**Comment by mathturtle** [comment]
Your sample tilt series wouldn't happen to have negative values would it?  I think I've seen a crash with applying sqrt to a dataset with negative values before...

**Comment by Hovden** [comment]
You're right, I'll fix this in the Python code.

The system shouldn't crash though. Users will probably make mistakes when coding.

**Comment by mathturtle** [comment]
Digging into the code a bit, it seems that the python code is correctly producing NaN when taking the square root of a negative number.  However, our histogram code is then converting this into an index of -2147483648.

My proposed solution to this is to have the create histogram code ignore NaN (or infinite to be thorough) floating point values.  Does that seem reasonable?

**Comment by Hovden** [comment]
Ignore NaN is a good option.

**Comment by mathturtle** [comment]
@Hovden I put up a branch to stop tomviz from crashing even if there is a NaN value in the dataset.
