### ISSUE TITLE
Constrained DFT Crashes

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1735]
**Describe the bug**

I get this error: 

`IndexError: boolean index did not match indexed array along dimension 1; dimension is 166 but corresponding boolean dimension is 167
Failed to execute the script.`

Whenever I run the 'Constrained-Based Direct Fourier Method'. There is consistently a mismatch of one value between the two arrays. 

**To Reproduce**
1. Go to: Tomography - Constraint-based Direct Fourier Method after marking the dataset as a tilt series. 
I use the default values when I run this reconstruction. 

**Desktop (please complete the following information):**
 - Operating system: MacOS High Sierra (Version 10.13.6)
 - Tomviz version: 1.3.1-263-g84bbecbd and 1.4.0-49-g80b6c695.

**Hardware (please complete the following information):**
 - Device: Macbook Pro

**Comment by cjh1** [comment]
Can you please try on the latest nightly ( seems like you are using 1.3.1 ), which can be found [here] 
(https://tomviz.org/files/tomviz_nightly_bin/tomviz-latest.dmg). This operator works for me on Linux with the latest.

**Comment by cjh1** [comment]
I tried the latest nightly on the Mac this also works.

**Comment by jtschwar** [comment]
I've downloaded the latest nightly (tomviz 1.4.0-92-g5a97beaa) and I'm still getting the same error message. 
<img width="1050" alt="screen shot 2018-11-09 at 12 15 43 pm" src="https://user-images.githubusercontent.com/32110921/48277636-3fc52480-e419-11e8-8a91-d6af24655a65.png">
<img width="1051" alt="screen shot 2018-11-09 at 12 15 03 pm" src="https://user-images.githubusercontent.com/32110921/48277649-4784c900-e419-11e8-8de4-b2e31e9c4c2b.png">

**Comment by cryos** [comment]
It looks like another from the Nature [Data paper](https://figshare.com/collections/Nanomaterial_datasets_to_advance_tomography_in_scanning_transmission_electron_microscopy/2185342) hosted by FigShare.

**Comment by jtschwar** [comment]
Hi, yes is the first dataset. [Here] (https://figshare.com/articles/tiltser_PtNP_tif/2075239) is the second one.

**Comment by cjh1** [comment]
Ok, I can recreate with that dataset. However, I also tried with 1.2.1 and still see the problem, so this is not a new issue. So this is probably an issue with the algorithm code. I am not familiar will the algorithm but will take a look.
