### ISSUE TITLE
Python Warning bin images x2

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1745]
**Describe the bug**
Python warning thrown when using bin images x2

<img width="517" alt="screen shot 2018-11-20 at 2 54 06 pm" src="https://user-images.githubusercontent.com/6197997/48799368-f2786b00-ecd4-11e8-9131-00eefc39667f.png">

**To Reproduce**
Load dataset. Mark as tiltseries. Bin Images x2.

**Desktop (please complete the following information):**
 - Operating system: OSX
 - Tomviz version: 1.5.0

**Hardware (please complete the following information):**
 - Device: Macbook Pro

**Comment by cryos** [comment]
This should be resolved now.
