### ISSUE TITLE
Manual Alignment crashes at end of tilt series (Windows)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1746]
**Describe the bug**
tomviz crashes in manual alignment when aligning the last image to the first image (end of the entire alignment process)

**To Reproduce**
1. Load 180 tilt series
2. "Bin Tilt Images x2"
3. Align last ten images
4. Crashes when returning to first image

NOTE: Must be aligning / shifting or it will not crash.

**Desktop (please complete the following information):**
 - Operating system: Windows 10 64 bit
 - Tomviz version: 1.5.0

**Hardware (please complete the following information):**
Acer intel i5
GForce 940MX

**Comment by Hovden** [comment]
Confirmed on OSX and Windows.

**Comment by alesgenova** [comment]
@Hovden 
I'm still trying to unsuccessfully reproduce it.
Can you give a look at this short video and tell me if I'm doing anything differently?
https://youtu.be/wM-lqC7unNA

**Comment by Hovden** [comment]
Ok. It appears to only occur if you first "Bin Tilt Images x2", then run the alignments. I have updated the  bug procedure above.

**Comment by cryos** [comment]
If you add in the "Bin Tilt Images x2" step I just made this crash on the sample tilt series we distribute on Windows with the 1.5.0 binary.

**Comment by cryos** [comment]
[tomviz-error.txt](https://github.com/OpenChemistry/tomviz/files/2657708/tomviz-error.txt)
is a backtrace from a macOS machine that crashed, and gives some clues as to where this occurs.
