### ISSUE TITLE
Loading state file crashes without output

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1748]
**Describe the bug**
I received a state file and MRC tilt series from a collaborator. I placed the state file and MRC tilt series in the same folder. Then loaded the state file into tomviz. The program eventually crashes without any output.

I tested this on two separate Windows 10 machines one with tomviz 1.4 and the other with a fresh 1.5.0 installation.

I dug into the state file and see these lines:
            "reader": {
                "fileNames": [
                    "../Tomo_CSH_01.mrc"
                ],
                "name": "MRCSeriesReader"

I removed the "../" in front of the file name and the state file loads properly.

I then tried to reproduce the issue and can confirm that saving a state file in a child directory will add this relative "../" path to the state file file loading. 

**To Reproduce**
1. Load a data set. (not the example data sets since their path is known)
2. Save a state file in a new directory created within the directory of the data set:
data set location: ../Desktop/data.mrc
state file location: ../Desktop/newFolder/state1.tvsm
3. Move the state file to the parent directory
data set location: ../Desktop/data.mrc
state file location: ../Desktop/state1.tvsm
4. Load the state file
5. tomviz crashes.

**Expected behavior**
This is especially a problem when a collaborator sends the state file and data file to another collaborator. The directory structure of the sender should not need to be replicated by the sendee. There should be a warning rather than a crash.

Ideally, tomviz should
1. look in the location written in the state file.
2. look in the same directory as the state file. 
3a. Warn the use that the data file can not be found. Tell the user the expected location. Reset tomviz
OR
3b. Give the user the option to find the data set or cancel.

Not sure about 3b is better but I do not know how hard that would be to implement.

**Desktop (please complete the following information):**
 - Operating system: Windows 10
 - Tomviz version:  1.4.0 and 1.5

**Hardware (please complete the following information):**
 - Device: Dell XPS 13; Dell Precision tower
 - Graphics card: Intel card; NVIDIA card

**Comment by cryos** [comment]
Thank you for the report, #1754 fixes the crash, and we will look at improved error handling before closing this issue.
