### ISSUE TITLE
Calibrate example data sets

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1751]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you would like**
Can you add pixel sizes to the example data sets? This would make issues where the pixel and real space coordinates are confused more obvious during development and testing. i.e. #1749 

**Describe alternatives you have considered**
Or dont....

**Comment by psavery** [comment]
I took the Co2P tilt series example from the Sci. data paper, manipulated it a little bit, and tried to calibrate the physical units. Attached is a sample EMD file (~4.8 megabytes unzipped, but github only lets me upload it zipped, I attached zip and gzip copies). I put the operations and my math below.

Original dimensions in pixels (pixel size is ~0.71 nm, according to the paper):
1157 x 1157 x 76

**Resample Operation:** 0.25 x 0.25 x 1.0
New dimensions in pixels: 289 x 289 x 76
New pixel size: 0.71 nm * 1157 px / 289 px = 2.84 nm per pixel

**Crop Operation:** X: 5 - 260, Y: 0 - 255, Z: 0 - 75
New dimensions in pixels: 256 x 256 x 76

**Convert Type Operation:** to UInt8 (to reduce final file size):
Dimensions unchanged

New physical dimensions (calculated via 2.84 nm per pixel * 256 pixels):
727.67 nm by 727.67 nm by 76 slices

Please let me know if any of the math looks wrong, or I should change any of the operations (maybe I could center the image more or something). 

[tilt_sample.emd.zip](https://github.com/OpenChemistry/tomviz/files/2992819/tilt_sample.emd.zip)
[tilt_sample.emd.gz](https://github.com/OpenChemistry/tomviz/files/2992820/tilt_sample.emd.gz)

**Comment by psavery** [comment]
I shifted the volume, and I think these are centered just a little better.

[tilt_sample2.emd.zip](https://github.com/OpenChemistry/tomviz/files/2993091/tilt_sample2.emd.zip)
[tilt_sample2.emd.gz](https://github.com/OpenChemistry/tomviz/files/2993092/tilt_sample2.emd.gz)

**Comment by psavery** [comment]
I made one more change to the tilt sample (I just rounded the physical units to two decimal places). Here is the new one.

I noticed that the Y-axis of the old tomviz tilt series sample appears to be flipped relative to the Y-axis of this new tilt sample (and the original file). Let me know if I need to flip the Y-axis to make it match.

[tilt_sample3.emd.gz](https://github.com/OpenChemistry/tomviz/files/2997566/tilt_sample3.emd.gz)
[tilt_sample3.emd.zip](https://github.com/OpenChemistry/tomviz/files/2997567/tilt_sample3.emd.zip)

**Comment by psavery** [comment]
Here is my recon sample. I made the dimensions match that of the original recon sample as much as possible. The math and operations are pasted below as well.

Original dimensions in pixels (pixel size is ~0.71 nm, according to the paper):
579 x 579 x 579

**Resample Operation:** 0.5 x 0.5 x 0.5
New dimensions in pixels: 290 x 290 x 290
New pixel size: 0.71 nm * 579 px / 290 px = 1.42 nm per pixel

**Crop Operation:** X: 81 - 180, Y: 45 - 260, Z: 15 - 275
New dimensions in pixels: 100 x 216 x 261

**Convert Type Operation:** to UInt8 (to reduce final file size):
Dimensions unchanged

New physical dimensions (calculated via 1.42 nm per pixel * [100, 216, 261] pixels):
141.76 nm by 306.19 nm by 369.98 nm

[recon_sample2.emd.gz](https://github.com/OpenChemistry/tomviz/files/2997599/recon_sample2.emd.gz)
[recon_sample2.emd.zip](https://github.com/OpenChemistry/tomviz/files/2997600/recon_sample2.emd.zip)

**Comment by psavery** [comment]
For the tilt sample, I just noticed that it looks like we deleted the two blank slices for the older sample tilt series datasets. I can also delete them for the new one as well.

**Comment by psavery** [comment]
The two blank slices were deleted.

[tilt_sample4.emd.gz](https://github.com/OpenChemistry/tomviz/files/2998034/tilt_sample4.emd.gz)
[tilt_sample4.emd.zip](https://github.com/OpenChemistry/tomviz/files/2998035/tilt_sample4.emd.zip)

**Comment by psavery** [comment]
Looks to me like reading the emd file is populating some tilt angles with "0" that it shouldn't be. I'll take a quick look at that.

**Comment by psavery** [comment]
I found it. When the EMD format sets the tilt angles, the tilt angles array gets resized too big [here](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/DataSource.cxx#L1168). I'll fix this later today or this weekend.

**Comment by psavery** [comment]
The above issue was fixed in PR #1832.

**Comment by cryos** [comment]
Looking at the [paper](https://www.nature.com/articles/sdata201641), it would seem that the tilt series should go from -75 to +75, there are two blank images which we have deleted. It leads to a gap where we go from 21 to 27 degrees, I think it is better to delete the images rather than leave them in.

**Comment by cryos** [comment]
This is now done, it works in our testing and will be a part of this release.
