### ISSUE TITLE
Viewing two datasets causes UI to crash

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1756]
**Describe the bug**

The program crashes whenever I try to split the screen and load two datasets. 

**To Reproduce**
1. Load one dataset. 
2. Click on: Split horizontal/vertical (both causes it to crash)
3. Load a second dataset.
4. See error: `Segmentation fault: 11`

**Screenshots**

This is what I see before I load the second dataset. 

![image](https://user-images.githubusercontent.com/32110921/49477550-43b34f00-f7eb-11e8-835b-66bf4f7b7db2.png)

After I load a second one the program crashes. 

**Desktop (please complete the following information):**
 - Operating system: macOS 10.14.1
 - Tomviz version: 1.50-4 and 1.40-92

**Hardware (please complete the following information):**
 - Device: Macbook Pro

**Comment by cryos** [comment]
Confirmed, we are missing a check somewhere. If you made that a render view then it will work fine, but leaving it undefined like that. Thanks for reporting, @alesgenova can you look at fixing this. I reproduced it on Linux.
