### ISSUE TITLE
Crash when loading example data from welcome prompt

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1769]
In tomviz 1.5.1, if I click "yes" in the "Would you like to load an example data set and visualization?" welcome prompt it causes tomviz to crash.  I am using Windows 7.

![image](https://user-images.githubusercontent.com/12242066/51063947-3c8e1680-15cb-11e9-95b0-bd148f052bd2.png)

**Comment by alesgenova** [comment]
Thanks for reporting this!
I have a guess on what might be causing it, and a fix is part of a larger startup improvement that we are planning to complete before the next release.
