### ISSUE TITLE
Canceling a Reconstruction Loses Tilt Angles State

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1778]
**Describe the bug**

If a Reconstruction is canceled before running, Tomviz seems to lose its Tilt Angles state. 

**To Reproduce**
1. Load any tilt series.
2. Click on 'Mark Data as Tilt Series'
3. Scroll down to 'Any Python Reconstruction and Cancel'

![image](https://user-images.githubusercontent.com/32110921/51334285-85235500-1a4d-11e9-98ef-9a09abcf9bba.png)

**Expected behavior**

For Tomviz not require to re-mark as Tilt series. 

**Screenshots**

**Desktop (please complete the following information):**
 - Operating system: macOS 10.11
 - Tomviz version: 1.5.1

**Hardware (please complete the following information):**
 - Device: Macbook Pro

**Additional context**

**Comment by psavery** [comment]
@cryos I don't think this has been fixed yet. I can look into this.
