### ISSUE TITLE
Canceling a reconstruction gives Attribute Error

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1798]
**Describe the bug**

If I cancel a reconstruction while it's in the middle of its process and try to rerun it, I get this error: 
AttributeError: 'NoneType' object has no attribute 'size'
Failed to execute the script.

**To Reproduce**
1. Go to any tomography reconstruction (SIRT, TV-Min)
2. Click on Apply (run the reconstruction) then cancel when its in the middle of the process. 
3. Double click the reconstruction in the pipeline, and rerun it. 

**Expected behavior**
Allow the user to rerun the reconstruction with new parameters or reload the previous operations to reach the previous state. 

**Desktop (please complete the following information):**
 - Operating system: macOS 10.14.2
 - Tomviz version: 1.5.1-41-g516e7464

**Hardware (please complete the following information):**
 - Device: Macbook Pro

**Comment by cryos** [comment]
I think this is resolved now, attaching  it to the 1.8.0 milestone. Please reopen if this is still an issue in master/the nighly builds.
