### ISSUE TITLE
Tomviz can't load recent matlab (.mat) v7.3 files. 

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1799]
**Describe the bug**
Tomviz is unable to load the most recent version (v7.3) of matlab (.mat) files. 

**To Reproduce**
1. Load this [dataset](https://drive.google.com/file/d/1uoBpstMxp9vOmP3Lb0if462HrJvGVhpz/view?usp=sharing) into tomviz. 

'Traceback (most recent call last):
  File "/Users/jonathanschwartz/tomviz-build/lib/site-packages/tomviz/io/_internal.py", line 37, in execute_reader
    return obj.read(path)
  File "/Users/jonathanschwartz/tomviz-build/lib/site-packages/tomviz/io/formats/matlab.py", line 27, in read
    mat_dict = scipy.io.loadmat(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 71, in mat_reader_factory
    raise NotImplementedError('Please use HDF reader for matlab v7.3 files')
NotImplementedError: Please use HDF reader for matlab v7.3 files
Error calling the reader'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating system: macOS 10.14.3
 - Tomviz version: 1.5.1-41-g516e7464

**Hardware (please complete the following information):**
 - Device: Macbook Pro

**Additional context**

**Comment by jtschwar** [comment]
Actually, after looking into the [API](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.io.loadmat.html) it looks like scipy.io does not support this file format.

**Comment by psavery** [comment]
It looks like an HDF5 python library such as h5py is needed to read matlab v7.3 files instead of scipy.

Do we want to try to support matlab v7.3 files? If so, we could perhaps do a try/except for the scipy reader, and if it shows up as matlab v7.3, we can try to import h5py and read the file.

@cryos @cjh1

**Comment by cryos** [comment]
For now we might add a try/except and so new files are not supported. We don't have h5py packaged yet.

**Comment by cryos** [comment]
Closing this for now as the scipy support is not there yet and we have an error message at least.
