### ISSUE TITLE
Update ITK Version in Build Instructions

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#1803]
FYI, I don't think Ubuntu 18.04 can build ITK v4.12.0 mentioned in the build instructions. I get the [attached error](https://github.com/OpenChemistry/tomviz/files/2932593/error.txt).

Upgrading to v4.13.0, however, fixes the issue.

I haven't tried v4.13.0 on other OS's, and we probably want to upgrade to an even later version of ITK. So we can probably update it later.

**Comment by cryos** [comment]
ITK is only used in Python operators that need ITK, so you can use most of Tomviz without ITK at all. Good to know about the build issue, but yes I would rather move to ITK 5 once it is released.

**Comment by cryos** [comment]
You fixed this Patrick, marking as closed.
