### ISSUE TITLE
Expand convert to filter for unsigned 8 and 16 bit int

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1805]
We have a convert to float operator, and that is nice for when things are a 64 bit double and you want to move them into 32 bit float. It would be useful to add a data wrangling operator with some user interface, I think this should be in C++ based on the existing cast to float but with more features:

- [x] Cast to unsigned 8/16 bit in and expand to full range (i.e. 0-255 for 8 bit)
- [x] Pick a channel and drop other channels in the case of RGB/multi-component images

The interface would be relatively small, the cast should be templated as it is likely to operate on a large image data, and should perform the addition and multiply in the tight loop. These would end up as data operators. Casting to 8/16 bit is more for performance where volume rendering especially could use a smaller representation to upload as a texture and most (all?) reconstructions output 32 bit floats.

**Comment by psavery** [comment]
These two features were implemented in #1807.

**Comment by cryos** [comment]
This is now resolved.
