### ISSUE TITLE
NPY files written as Fortran order

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1809]
**Describe the bug**
Using the save as and selecting the numpy file (.npy) option saves the data as a Fortran contiguous data set. This is related to #1808. 

The data is ordered (X,Y,num) for tilt series when it should be [num,Y,X]. Also the array.flags variable shows:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

**To Reproduce**
1. Load the example tilt series
2. Save the data as a npy file
3. Load the data into python using np.load
4. array.shape and array.flags show that the data is Fortran Contiguous. 

```python
>> import numpy as np
>> ser = np.load('test.npy')
>> print(ser.shape)
(256, 256, 74)
>> print(ser.flags)
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

**Expected behavior**
The data should be transposed and properly ordered in C-ordering before being saved as a numpy array to keep with the proper conventions in numpy and python.
```python
>> out_array = np.ascontiguousarray(np.transpose(tomviz_array, [2,0,1]))
>> np.save('filename.npy', out_array)
```
Then C_CONTIGUOUS flag is True and shape = (74,256,256)
**Desktop (please complete the following information):**
 - Windows 10
 - Tomviz version: 1.5.1

**Hardware (please complete the following information):**
 - Device: Dell XPS 13

**Comment by ercius** [comment]
Additional comments:
1) Im not sure if the np.transpose() should be [2,0,1] or [2,1,0] to keep the tilt axis properly oriented when importing into external numpy. That should be tested.
2) Reading npy files should also take this into account if tomviz is allowed to load arbitrary npy files. It seems that tomviz should have a spec for what it expects in terms of ndarray shape in a npy file. Im not sure if this is discussed anywhere.

**Comment by cryos** [comment]
This is fixed and will be in the next release.
