### ISSUE TITLE
Passive acquisition slice widget property issues

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1822]
When running passive acquisition there are issues with the slice widget. If only one slice is loaded the panel shows a very negative number. It also doesn't update the number of slices when the volume is updated.

**Comment by cryos** [comment]
Another issue is that the TIFF mock writer outputs of the form -23 for -23 degrees, but just 23 for +23 degrees. This means our regex only sees negative angles, and misses all positive.

**Comment by psavery** [comment]
> Another issue is that the TIFF mock writer outputs of the form -23 for -23 degrees, but just 23 for +23 degrees. This means our regex only sees negative angles, and misses all positive.

This one is fixed by PR #1824.

**Comment by psavery** [comment]
> When running passive acquisition there are issues with the slice widget. If only one slice is loaded the panel shows a very negative number. It also doesn't update the number of slices when the volume is updated.

The min/max number of slices are updated during the passive acquisition via #1825. You can move the slider now as new slices are added.

Do you think it would be nice if the new slices added by passive acquisition were displayed every time one was added? If that were the case, the user could kind of "watch" the new slices being added.

I haven't fully tracked down the very negative number. The slice number is initialized in the header to zero. It looks like it may get a bad slice number calculated [here](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/modules/ModuleSlice.cxx#L493) followed by [here](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/modules/ModuleSlice.cxx#L644) before all of the data is initialized. I could just put a sanity check in [here](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/modules/ModuleSlice.cxx#L251), as `m_slice` is already a very negative number at that point by the time the panel gets added.

**Comment by psavery** [comment]
I added a commit to #1825 that fixes the very negative number through a sanity check. I can still track down why the negative number occurs in the first place if that is needed, let me know.

**Comment by cryos** [comment]
I think the main issues are all resolved at this point, and the passive acquisition is more useful again.
