### ISSUE TITLE
Tilt Series State Lost when Operating on Tilt Series Loaded from EMD Files

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#1833]
**Describe the bug**
If a file that explicitly contains a tilt series is opened up (such as an EMD file), and then an operation is performed such as `Bin Tilt Images 2x`, the tilt series state is forgotten. Many operations seem to do this, including `Bin Tilt Images 2x` (pre-processing operation) and `Invert Data` (data transform).

**To Reproduce**
1. Unzip the attached file, and open it with tomviz. The data should already be recognized as a tilt series.
[tilt_sample4.emd.gz](https://github.com/OpenChemistry/tomviz/files/3000707/tilt_sample4.emd.gz)
2. Perform a `Bin Tilt Images 2x` operation.
3. Notice that the tilt series state is forgotten (for instance, `Mark Data As Tilt Series` is no longer grayed out).

**Expected behavior**
Do not forget the tilt series state after these operations.

**Desktop (please complete the following information):**
 - Operating system: Ubuntu 18.04
 - Tomviz version: 1.5.1-135-g56e21824

**Comment by psavery** [comment]
This bug might only occur for the EMD reader. But it can be looked out for in other readers in the future.

**Comment by cryos** [comment]
I am closing this for now, only the EMD reader brings in angles, we should ensure this works with future readers.
