### ISSUE TITLE
Tomviz is no longer able to build on Mac

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1846]
**Describe the bug**

Now whenever I try to build tomviz I get this error message:

CMake Error at CMakeLists.txt:74 (message):
  Failed to get PARAVIEW_PYTHON_VERSION

-- Configuring incomplete, errors occurred!
See also "/Users/hovdengroup/tomviz-build/CMakeFiles/CMakeOutput.log".

I can provide my cmakeoutput.log if necessary

**To Reproduce**
1. Go to: tomviz-build directory
2. Click on: run: cmake --build .
3. See error

CMake Error at CMakeLists.txt:74 (message):
  Failed to get PARAVIEW_PYTHON_VERSION

-- Configuring incomplete, errors occurred!
See also "/Users/hovdengroup/tomviz-build/CMakeFiles/CMakeOutput.log".

I can provide my cmakeoutput.log if necessary

********Expected behavior***********

**Screenshots**

**Desktop (please complete the following information):**
 - Operating system: macOS Mojave (10.14)
 - Tomviz version: 1.6

**Hardware (please complete the following information):**
 - Device: Macbook Pro and iMac

**Additional context**

**Comment by psavery** [comment]
@jtschwar Yeah, we are currently in the process of upgrading tomviz to use the latest ParaView. This will probably be a work in progress for the next week.

It may work on the mac if you build the master branch of ParaView and use that instead of the older version of ParaView. But we will have greater certainty and perhaps clearer instructions sometime next week.

**Comment by cryos** [comment]
You can develop on the 1.6.0 tag if you want to continue working, this will be resolved soon but if I was you I would just stick to the 1.6.0 tag which is pretty close to master without the changes for ParaView master.

**Comment by jtschwar** [comment]
Sounds good, thanks!

**Comment by jtschwar** [comment]
Checking in on this issue. Still having trouble building the latest tomviz.

**Comment by cryos** [comment]
Yes, you should be able to build against ParaView master now, but we are still iterating on getting everything working. You can see [working builds on the buildbot](https://open.cdash.org/index.php?project=TomViz) machines for all platforms. We have disabled the ParaView plugin for now, and so slice and contour modules are not working in the short term. I am working on solving that. I would still develop on the 1.6.0 tag if I was you, there are no major changes to Tomviz code that would prevent from merging your work.

`git checkout 1.6.0 && git checkout -b working-brach`

would net you a branch on 1.6.0 as a base, and let you continue developing in the short term.

**Comment by cryos** [comment]
Please update ParaView according to BUILD.md (or clone the latest). There is a new flag I recommend using to disable all plugins by default.

**Comment by kevinsmia1939** [comment]
Having the same problem in openSUSE Tumbleweed.
Trying to build Tomviz 1.8.0 against Paraview 5.6.2 yield 
"Failed to get PARAVIEW_PYTHON_VERSION"

The Paraview in openSUSE repository does not have build flag to disable all the plugins, so I guess Paraview must be build from source. Would Paraview 5.8.0 fix this issue?

**Comment by cryos** [comment]
I am afraid that ParaView's public CMake variable API has been changed. This has caused a number of issues for us in development too, I also think we use new API and you can see the SHA we recommend in the tomviz-superbuild tag, or the paraview fork on the open chemistry organization.
