### ISSUE TITLE
Cannot load data with .xyz filetype

### ISSUE THREAD

**Issue by reedyal** [OpenChemistry/tomviz#1864]
**Describe the bug**
When I try to open an xyz atom position file (.xyz), tomviz crashes and displays 'Segmentation fault (core dumped)' on the command line from which I started the program.

**To Reproduce**
1. Select 'File' pulldown menu
2. Select 'Open Data'
3. Choose files of type 'Molecule files (*.xyz)'
4. Open an xyz file
5. Tomviz crashes

**Expected behavior**
I expected tomviz to open and display the data in the xyz file

**Desktop:**
 This happened with tomviz 1.5.1-150 on linux, then was reproduced with the latest version of tomviz (1.6.0-30) on macOS 10.14.5

**Hardware:**
 - Device: iMac

**Additional context**
I tried two files, a large nanoparticle, as well as a single Si 100 unit cell (linked below). 
https://figshare.com/s/3b76f35e9ff5ff9ec9bd

**Comment by cryos** [comment]
I looked into this, and for normal XYZ files that correspond to the [specification](https://en.wikipedia.org/wiki/XYZ_file_format) they open fine. The reader we use is from VTK, and I am afraid that there are so many variations of the format in the wild. It shouldn't segfault, and we should improve the VTK reader, but we are unlikely to be able to support every format. What produces files of this type? XYZ has no native support for unit cells for example.

**Comment by cryos** [comment]
Closing as this is something of a file format issue. I think we should improve the reader not to crash, but that is a bug that needs to be fixed in the VTK reader.
