### ISSUE TITLE
Reconstruction "physical size" not copied over correctly

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1892]
**Describe the bug**
When you do a reconstruction, the physical size from the Y axis needs to be copied over to the new Z-axis. This is not happening correctly. Tomviz instead sets the Z physical size to 2x the number of pixels.

**To Reproduce**
1. Load star tilt series
2. Do weighted backprojection reconstruction
3. Click on the reconstruciton output to check its properties
4. The z physical size is set to 512 (nm). This is 2x the number of pixels along that axis and thus the object looks distorted.

**Expected behavior**
Copy the Y axis physical size (**not the X**) to the Z-axis physical size.

**Screenshots**
![image](https://user-images.githubusercontent.com/15657108/61163824-8f3a8380-a4c5-11e9-99bf-3e0b81ec95d4.png)

**Desktop (please complete the following information):**
 - Operating system: Windows 10
 - Tomviz version: Tomviz 1.6.0

**Hardware (please complete the following information):**
 - Device: Dell XPS 13
 - Graphics card: Intel

**Additional context**
Im going to check the nightlies for all future bugs.

**Comment by ercius** [comment]
Confirmed in nightly 1.6.0-145

**Comment by cjh1** [comment]
Fixed by #1907
