### ISSUE TITLE
Default colormap is bwr.

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1894]
**Describe the bug**
The default colormap is set to bwr. Magma or Viridis is preferred.

**Desktop (please complete the following information):**
 - Operating system: Windows 10
 - Tomviz version: 1.6.0-145

**Comment by cryos** [comment]
This is a weird bug with default settings, persistence, and updates made recently. If you wipe all files it will be the old default, I will change how we initialize the default color map to ensure that this bug doesn't affect the release.

**Comment by jtschwar** [comment]
Following up on this, I've also noticed that the color map automatically switches back to bwr when new data transforms are calculated.

**Comment by cryos** [comment]
The default color map is fixed by #1910
