### ISSUE TITLE
Show axis grid doesn't update automatically with scale

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1900]
**Describe the bug**

1. Load Data and Check 'Show Axes'  on Outline Module. 

![image](https://user-images.githubusercontent.com/32110921/61313444-7503ec80-a7c8-11e9-8255-72b71f2aef6c.png)

2. Click View Menu and Go Down to 'Show Axes Grid'
![image](https://user-images.githubusercontent.com/32110921/61313518-9664d880-a7c8-11e9-801e-95a2dad406ea.png)
 
Results:
![image](https://user-images.githubusercontent.com/32110921/61313533-9fee4080-a7c8-11e9-8440-50e21505ad1a.png)

3. Change the Units and Size to a value that's double from the original amount. 
![image](https://user-images.githubusercontent.com/32110921/61313621-cdd38500-a7c8-11e9-988c-2c15600780cc.png)

4. Delete the data from pipeline, the axis still remains on the screen. 
![image](https://user-images.githubusercontent.com/32110921/61313767-2014a600-a7c9-11e9-9819-500332be30b9.png)

**Expected behavior**
Not to see this doubling of the axes. 

**Desktop (please complete the following information):**
 - Operating system:  macOS 10.11
 - Tomviz version: [e.g. 1.6.0-151]

**Hardware (please complete the following information):**
 - Device: [e.g. Macbook Pro]

**Comment by cryos** [comment]
This is a feature, the outline and its axes/grid are data volume specific, the view axes are going to give axes and a grid for the complete data set. They should double if you choose to show both, but most people should choose between a view global versus data specific axes and grid. When you load a new data set they correctly show you its dimensions.

**Comment by cryos** [comment]
I wonder if we want to offer both, maybe just the data outline is best. I am seeing a few general issues with some visualization modules not seeing updates to the data when others do. I will look into it more.

**Comment by jtschwar** [comment]
@cryos Me and Prof. Hovden agree that offering only the data outline would be best
