### ISSUE TITLE
Crash from Create Preset

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1901]
**Describe the bug**

Creating a Colormap Preset Causes Tomviz to crash. 

![image](https://user-images.githubusercontent.com/32110921/61322627-1fd1d600-a7dc-11e9-9bb2-02dff5908297.png)

**To Reproduce**
1. Go to 'Create Preset'
2. Click on 'Ok'
3. See error

`Segmentation Fault: 11`

**Desktop (please complete the following information):**
 - Operating system: macOS 10.11,
 - Tomviz version: [e.g. 1.6.0-151]

**Hardware (please complete the following information):**
 - Device: [e.g. iMac 2019]
 - Graphics card: [e.g. NVIDIA Quadro 6000]

**Comment by cryos** [comment]
Those buttons will be disabled when no data is loaded, see #1903
