### ISSUE TITLE
Cursor selects slightly wrong location

### ISSUE THREAD

**Issue by Staumrel** [OpenChemistry/tomviz#1904]
**Describe the bug**
Whenever I click with my cursor in my main work screen, it will select about a centimeter above it.  This does not occur on offshoot windows, like if I were to drag the properties menu to the side.  For some reason, this only occurs on my laptop--I have not had issues with my Desktop.

**To Reproduce**
Simply run TomViz's most recent nightly build on my laptop, then try to click anything.

**Expected behavior**
The actually clicked part of TomViz will be a centimeter or so above where I actually clicked.

**Screenshots**
For reference, I clicked the middle circle of the Contour icon and opened up the File menu.
![image](https://user-images.githubusercontent.com/6439265/61383371-87d7f900-a87c-11e9-9123-d2510773f236.png)

**Desktop (please complete the following information):**
 - Operating system: Windows 10
 - Tomviz version: 1.60-145

**Hardware (please complete the following information):**
 - Device: Dell XPS 15"
 - Graphics card: GTX 1050

**Additional context**
I only have this issue with my laptop, not my desktop.  Not sure why this occurs, but it hasn't been a huge issue to work around it.

**Comment by cryos** [comment]
This is a driver/Qt issue I have seen a few times. I am not sure there is anything we can do from the Tomviz side. I think updating your OS/drivers may help.

**Comment by cryos** [comment]
Closing as can't fix.
