### ISSUE TITLE
Manual Tilt Axis Alignment UI doesn't properly initialize

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1906]
**Describe the bug**

The preview screen showing the tilt axis is no longer there. 

**To Reproduce**
1. Go to 'Tomography'
2. Scroll down to 'Tilt Axis Alignment (Manual)

There should be an image of the tilt series with three red lines and a yellow line. 

**Screenshots**

![image](https://user-images.githubusercontent.com/32110921/61505249-29aa3380-a9ac-11e9-928f-92efb01f54da.png)

**Desktop (please complete the following information):**
 - Operating system: macOS 10.11
 - Tomviz version: [e.g. 1.6.0-151]

**Hardware (please complete the following information):**
 - Device: Macbook Pro

**Additional context**

**Comment by cryos** [comment]
That is odd, I do not see this in the 1.6.0-153 build downloaded and run on my macOS machine. It is a Mac Mini running 10.14.5 or on the build machine (running 10.12.6). Why are you running such an ancient version of macOS? We don't have any local 10.10 machines to test, but now that 10.12 is over three years old we might need to bump our minimum.

**Comment by jtschwar** [comment]
My bad, my OS is actually 10.14.5. 
I saw this bug on my MacBook Pro last night but it seems to have gone away now. I'll close this issue but keep an eye out for it for future reference.

**Comment by cryos** [comment]
Thanks, it is great to see all the testing.
