### ISSUE TITLE
Crash from Custom Transform

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1920]
**Describe the bug**

Tomviz crashes whenever I try to use Custom Transform

**To Reproduce**
1. Open any dataset
2. Click on 'Data Transforms'
3. Scroll down to 'Custom Transform'
`Segmentation Fault: 11`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating system: macOS 10.14.6
 - Tomviz version: 1.7.0-49-g012c17ec

**Hardware (please complete the following information):**
 - Device: Macbook Pro and iMac

**Additional context**

**Comment by jtschwar** [comment]
@cjh1 looks like your recent branch fixed this issue, I'm going to close this issue. Thanks chris!!

**Comment by cjh1** [comment]
@jtschwar Excellent, thanks for reporting it.
