### ISSUE TITLE
Gray (grey) scale colormap missing

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1942]
**Describe the bug**
The grayscale colormap is missing. The only colormap close to it is x-ray which is reverse of the grayscale colormap.

**Screenshots**
Available colormaps in Tomviz 1.7.0:
![image](https://user-images.githubusercontent.com/15657108/64297781-41705380-cf29-11e9-96a3-14f9aaccb9f1.png)

**Desktop (please complete the following information):**
 - Operating system: Windows 10
 - Tomviz version: 1.7.0

**Comment by cryos** [comment]
We can add it in for you, are there any others you would like to see added? I think @bnmajor can take care of this.

**Comment by ercius** [comment]
I think gray was the only important one missing. Thanks!

**Comment by cryos** [comment]
This is now in, and will be in the next release.
