### ISSUE TITLE
Child dataset bug in Python Reconstructions

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1952]
**Describe the bug**

Hi, whenever I run any of the python tomography reconstructions I get this error:

`No child dataset named  "" defined in dictionary returned from Python script.`

`Dictionary return from Python script is:
 "{'reconstruction': (vtkCommonDataModelPython.vtkImageData)0x1582208e8}"`

I've seen this error on both the SIRT and WBP projection, but I wouldn't be surprised if it will also occur on ART and TV as well. 

**Screenshots**

![image](https://user-images.githubusercontent.com/32110921/64627199-3439e580-d3bd-11e9-888e-f36aa99182ff.png)

**Desktop (please complete the following information):**
 - Operating system: macOS 10.14.6
 - Tomviz version: 1.70-131-g0b9

**Hardware (please complete the following information):**
 - Device: iMac
 - Graphics card: [e.g. NVIDIA Quadro 6000]

**Comment by cjh1** [comment]
@jtschwar I can recreate this, will look into it.
