### ISSUE TITLE
Don't stride tilt axis for HDF5 files

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#1956]
If the user chooses a stride, the stride is currently applied in all directions.

Don't stride the tilt axis if there is one.

**Comment by cryos** [comment]
Chatting with @ercius we should let the user choose the stride in all three dimensions, and have a check box that defaults to on that uses the same stride in all three dimensions. Hopefully that makes sense, but I think default to checked, only enable the first stride box, uncheck it, and then set the stride in  x, y and z independently.

**Comment by psavery** [comment]
Yes, that sounds good. I will look into adding this.
