### ISSUE TITLE
New menus for tomography and sample data

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#196]
With more and more functions adding into Tomviz, it's better to have a separate menu for tomography-related transforms and sample data generators. See attached figure for details.
![menuui](https://cloud.githubusercontent.com/assets/13088588/9798676/88fedba6-57d0-11e5-8cef-dd6e4e7fb7ca.png)

**Comment by Hovden** [comment]
Looks good to me.

**Comment by mathturtle** [comment]
I have the rearranging/renaming part done on a branch and the custom python sample data almost works (but I think I need to rearrange the code a bit after I get it working so that it is easier to add new ones, so maybe another day or so).

**Comment by Hovden** [comment]
Sounds good!

**Comment by mathturtle** [comment]
Is this done now or are there other reorganizations you would like me to do?

**Comment by yijiang1** [comment]
The last thing I want change right now is to reorganize the code for Tomography menu.
In current version, functions in tomography menu are controlled by three ui labels: "ui.actionAlign", "ui.actionReconstruct", and "ui.actionToggleDataType". As a result, code like  (line 224 in MainWindows.cxx) "ui.menuTomography->insertAction(ui.actionReconstruct, autoAlignAction);" was very confusing to me and it took me a while to figure out how to insert new functions to Tomography menu.

Can we simplify these labels into something like "ui.actionTomography" (similar to "ui.actionClone" for Data Transforms menu)? I would be much easier for developers to add new functions.

**Comment by mathturtle** [comment]
I agree that the current way of creating both the Data Transforms and Tomography menus is confusing to new developers looking at these files.  But actionReconstruct describes what that menu item is doing (which you want in a variable name).  The `insertAction` method is saying 'insert this above the reconstruct action'.  Honestly I'd be in favor of having no predefined actions in either of these menus in the UI file (no `ui.actionX` variables) and constructing the menu as a series of `menuTomography->addAction(...)` calls.  That way the order of the menu items can be read straight from the code as the order they are added.  Look at how I am constructing the Sample Data menu for an example of doing it this way.

@cryos How does this sound?

**Comment by cryos** [comment]
Sounds good to me, and is generally my personal preference too.

**Comment by yijiang1** [comment]
> Honestly I'd be in favor of having no predefined actions in either of these menus in the UI file (no ui.actionX variables) and constructing the menu as a series of menuTomography->addAction(...) calls.

I completely agree and we should do this asap.

**Comment by mathturtle** [comment]
> I completely agree and we should do this asap.

#223
