### ISSUE TITLE
Python syntax highlighting

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#1967]
Syntax highlighting broke when we upgraded ParaView in one of the last releases, I think they removed Pygments or similar. We need to get syntax highlighting working again, ideally in 1.8.0.

**Comment by psavery** [comment]
I was able to get it working on my local build by installing pygments before building ParaView. I think we'll need to do something similar for the build systems.

**Comment by ercius** [comment]
and line numbers? :)

**Comment by psavery** [comment]
This issue is (hopefully) fixed by the PR linked above. We will double-check after it is merged and the new binaries are built.

**Comment by cryos** [comment]
We should verify the packages work and close this bug if they do.

**Comment by cryos** [comment]
This seems to work as expected on all platforms again. We should close this, and follow up with line numbers in a separate issue.
