### ISSUE TITLE
Editing operator at the end of the pipeline causes the whole pipeline to executed

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#1969]

**Comment by cryos** [comment]
We should prioritize getting this fixed before the next release.

**Comment by cjh1** [comment]
@psavery This may effected by your change ( perhaps in a good way :-) )

**Comment by cjh1** [comment]
I think this is actually expected behavior? Unless we store the intermediate dataset we have to re-run everything,

**Comment by cryos** [comment]
Yes, this is likely something we can't avoid unless we store more state of pipeline intermediate steps.
