### ISSUE TITLE
"Mark Data as Volume" does not seem to work

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#1975]
It does not seem to work in either the internal pipeline or the external pipeline, for different reasons.

For the internal pipeline, the "Mark as Volume" operator succeeds, but the data still appears to be a tilt series. You can still perform reconstructions on it, it still has tilt angles, and you can even mark it as a volume again.

![image](https://user-images.githubusercontent.com/9558430/66915964-3dcff200-efe8-11e9-8f97-2da76dc3eb4a.png)

For the external pipeline, we get an exception: `Exception: No script property found. C++ operator are not supported.`

**Comment by cryos** [comment]
We should get this fixed before making the next release.
