### ISSUE TITLE
Histogram / Colormap should not be zoomable

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#198]
The colormap and histogram should not be zoomable, or at least not in the way it functions now.

I find myself losing view of the histogram / colormap because I accidentally zoom on my touchpad.

**Comment by Hovden** [comment]
@mathturtle I say place a comment with the Paraview team letting them know that the colormap zooming is bad and should be turned off or improved. Then we can close this issue.

@utkarshayachit @cryos

**Comment by mathturtle** [comment]
@Hovden I've actually got [this fix](https://gitlab.kitware.com/paraview/paraview/merge_requests/392#note_34966) most of the way through ParaView, just working out the last few issues.

**Comment by mathturtle** [comment]
ParaView is having issues right now (someone merged something that broke most of the builds), so this is taking longer to get my change merged than I thought.

**Comment by mathturtle** [comment]
This should be fixed in the latest binaries.

**Comment by yijiang1** [comment]
Tested on OSX.
