### ISSUE TITLE
Delete (zero) data cube for removing data in volume.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#199]
Jade is preparing a figures using tomviz and has requested a delete volume feature. I think it would be easy.

Graphically it would work just like the crop box, but it would replace the data inside the box with zeros instead of cropping. This can be done with a transparent python routine.

If the crop code is an easily callable function, we may use it in several upcoming python gui's.

**Comment by mathturtle** [comment]
re: crop ui: It is pretty tightly coupled to the crop feature right now.  It doesn't have to be and I can refactor it to be a 'select volume of interest' widget that you could use in your python guis.  If this is a high-ish priority assign it to me and I'll look at it later this week.

**Comment by Hovden** [comment]
@yijiang1 Now that a crop widget (#208) has been added, this feature (deleting selected data) would be a simple introduction to using this selection tool (which we will probably use for background subtraction too).

**Comment by mathturtle** [comment]
I think we'll have to figure out how to make the python operator dialogs non-modal before this will be "simple".  I'll think about how to do this.

**Comment by Hovden** [comment]
To be clear, this can be modal c++ code for now. It will operate just like the crop tool to get bounds then it calls python to delete the data within that range.

We don't need generic python code.

**Comment by mathturtle** [comment]
Sure, it can be modal and will *mostly* still work.  But if the dialog is modal you will only get the six input boxes to type in numbers and not the widget to select the bounds interactively.

**Comment by Hovden** [comment]
You're correct, my statement was wrong. It cannot be modal—my point was that it only needs to run one time and can be a pop-up prompt where the user clicks once for a one time operation.
