### ISSUE TITLE
1.7.0 source download is actually '.tar' instead of '.tar.gz'

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#1998]
The source download on the page [here](https://tomviz.org/downloads/) ([full link](https://github.com/OpenChemistry/tomviz/releases/download/1.7.0/tomviz-1.7.0.tar.gz)) has a `.tar.gz` extension, but it is actually a `.tar` file, not a `.tar.gz` file.

**Comment by cryos** [comment]
I will fix this in the next release
