### ISSUE TITLE
Rotate /Translate Data and Modules in the Visualization

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#20]
Objects need to be rotatable and translatable in the visualization. For example, two datasets, each with their own volume and/or isosurface rendering can be moved and rotated relative to each other. Users can display two datasets side-by-side and rotated them each individually. This probably means that the entire dataset and the visualization modules associated with a single dataset all rotate / translate together.

**Comment by cryos** [comment]
I think we have most of this, if we want to add support for rotation we can track it in a new issue, but translation is now supported, scaling and/or rotation are possible too.
