### ISSUE TITLE
Procedural Sample Datasets are not working

### ISSUE THREAD

**Issue by alesgenova** [OpenChemistry/tomviz#2003]
**Describe the bug**
An error is displayed when trying to create a sample dataset from the `Sample Data` menu.
This applies to the "Constant Dataset", "Random Particles", and "Electron Beam Shape" routines.

See the traceback below:
```
Traceback (most recent call last):
  File "/home/alessandro/Downloads/Tomviz-1.7.0-257-ga09302b/lib/tomviz/site-packages/tomviz/_internal.py", line 232, in wrapped
    dataobject = convert_to_vtk_data_object(args[0])
  File "/home/alessandro/Downloads/Tomviz-1.7.0-257-ga09302b/lib/tomviz/site-packages/tomviz/_internal.py", line 220, in convert_to_vtk_data_object
    raise Exception(msg)
Exception: Cannot convert type to vtkDataObject: <class 'int'>
Failed to execute script.
```

**To Reproduce**
1. Go to 'Sample Data menu'
2. Click on 'Generate constant dataset'
3. See error

**Desktop (please complete the following information):**
 - Operating system: [e.g. Linux, macOS 10.11, Windows 10]
 - Tomviz version: Recent nightly build (`1.7.0-257-ga09302b`)

**Hardware (please complete the following information):**
 - Device: Ubuntu 18.04 workstation
 - Graphics card: AMD

**Comment by psavery** [comment]
I think I should be able to fix this...

**Comment by cjh1** [comment]
@psavery Excellent, thank you.
