### ISSUE TITLE
Azure-pipelines python versions are kind of unstable...

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#2005]
The python versions on the different operating systems are occasionally updated on the VMs. We can specify a version of python to use if we want to avoid always using the latest.

Unfortunately, though, for Windows and Mac, it looks to me that they do not keep the library files (`.lib` and `.dylib`) of older versions of python around when they update. For instance, even if I specify python 3.7 to be used on Windows, it will only ever find the python 3.8 libraries when building ParaView and Tomviz. This was causing the ParaView build to fail until we updated our ParaView sha to a more recent commit.

I posted a bug report about this [here](https://github.com/microsoft/azure-pipelines-tasks/issues/11739). Hopefully, they will start keeping older versions of the libraries around at some point. For now, maybe we should download, unzip, and use specific versions of python, so we don't always need to use the latest?

**Comment by cryos** [comment]
It isn't terrible to try and track the latest Python release, I have updated the SHA in tomvizsuper, and am about to update the one in the superbuild. If you need one to use f2cffe4db37a3129eedeeb4dfd4fddb74f5c312c has Python 3.8 fixes, but avoids their recent API breakage, and I think it is a good point to use for now.

**Comment by psavery** [comment]
That sounds good. We can try to stick with the latest that they have available.

Another difficulty with the updating versions, though, is that, if they update their version (including a patch update such as python 3.7.4 -> 3.7.5), the tomviz build will fail, and we have to force a ParaView re-build to get it working again. We might be able to add the python version to the key [here](https://github.com/OpenChemistry/tomviz/blob/f8baad2dd2abeecbb3701f51d2c18fa9c4fb3791/.azure-pipelines.yml#L49) to get it to re-build ParaView automatically when the version changes, though...

**Comment by cryos** [comment]
Patch versions change infrequently enough that we can probably just trigger it manually.

**Comment by psavery** [comment]
Okay. Just to record more info here: we are currently using the latest python 3.8, and the builds are all working which is good! 

When a new python patch comes out, azure-pipelines may not update all of their VMs with the new python patch at the same time (this happened the last time they changed versions), and we will need to trigger a re-build for each. Triggering a re-build of ParaView is done by making a commit where we change the `v` number in [this key](https://github.com/OpenChemistry/tomviz/blob/master/.azure-pipelines.yml#L46) (there is currently not a way to trigger a re-build through the web UI).

**Comment by cryos** [comment]
Closing, I think this is good documentation, not particularly a Tomviz bug more of an issue with how we do Azure pipelines.
