### ISSUE TITLE
Print messages from docker pipeline immediately

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#2043]
Rather than waiting for the operator to finish...

Or, in some cases, the messages might not get printed at all. Make sure they get printed.

**Comment by HarshalGoyal** [comment]
Hello guys, I am Harshal Goyal , A First year engineering undergraduate (CSE) at Dayananda Sagar University, Bangalore i am willing to participate in GSOC 2020 so can you help me out please

**Comment by cryos** [comment]
This is not an appropriate way to engage in GSoC @HarshalGoyal, please don't spam unrelated issues on GitHub.
