### ISSUE TITLE
In ExternalPython mode, executable name defaults to "true"

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#2046]
This is what it appears like if nothing is currently set for the executable. It might be more intuitive for it to default to "python.exe".

![image](https://user-images.githubusercontent.com/9558430/75283534-12a0af00-57e1-11ea-91c4-d22ababa41b9.png)

**Comment by cryos** [comment]
I see this too, ideally I think it should be empty.

**Comment by psavery** [comment]
This was fixed by #2098.
