### ISSUE TITLE
Active scalars is not saved to the state file

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz#2070]
If you load a file with multiple scalars ([regular_and_sqrt.emd.gz](https://github.com/OpenChemistry/tomviz/files/4314028/regular_and_sqrt.emd.gz), for example), and you change the active scalars, save the state file, and then load the state file back in, it does not remember the active scalars that was previously used.

It does, however, use the color map of the previously selected active scalars, which might have a different range than the other scalars. That example file above produces the following image.

![image](https://user-images.githubusercontent.com/9558430/76345041-06d0e480-62d9-11ea-9311-8437e9da0a95.png)

We should maybe save the active scalars to the state file.

**Comment by cryos** [comment]
Yes, that is a bug, and we should save that as part of the file data source/file reader I think. We will then need to restore that.

**Comment by cryos** [comment]
I think this was fixed wasn't it?

**Comment by psavery** [comment]
It works in the full state files, but not the light ones, unfortunately.
