### ISSUE TITLE
PyBind11 update - 2.2.3 -> 2.5.0?

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#2105]
Took a quick look and we are on 2.2.3, and 2.5.0 is the latest tag. There are changes we will need to fix, not sure if you have time Chris but you know the code best. I saw one note about upgrading for write only properties.

**Comment by cjh1** [comment]
I will take a look

**Comment by cryos** [comment]
PR #2107 addresses this request

**Comment by cryos** [comment]
This is merged
