### ISSUE TITLE
ImportError: libffi.so.6

### ISSUE THREAD

**Issue by WKrauze** [OpenChemistry/tomviz#2111]
**Describe the bug**
When starting tomviz on Linux an error shows stating 
`ImportError: libffi.so.6: cannot open shared object file: No such file or directory`
Tomviz still works (although I don't know to what extent) but now it is impossible to import mat files.
This is probably associated with recent update of libffi as now there is no libffi.so.6, instead there is libffi.so.7. Also, see [here](https://forum.manjaro.org/t/importerror-libffi-so-6-cannot-open-shared-object-file-no-such-file-or-directory/137814/12)

**Screenshots**
![image](https://user-images.githubusercontent.com/8330881/80678242-d9274100-8aba-11ea-9341-745cc5db27c5.png)

**Desktop:**
 - Operating system: Linux Manjaro 20.0
 - Tomviz version: 1.8.0-260

**Comment by psavery** [comment]
@WKrauze I've encountered this error as well.

We are currently building the tomviz Linux binaries on a Docker image based on Debian 8, which reached its end of life in June.

We will try to upgrade the build system and make sure it is using libffi 7 at some point. Until then, building from source might be the best option on Linux.

**Comment by psavery** [comment]
@WKrauze @volpatto This is fixed in our superbuild, and should be a part of the next release (which will hopefully be within the next couple of weeks).

**Comment by volpatto** [comment]
> @WKrauze @volpatto This is fixed in our superbuild, and should be a part of the next release (which will hopefully be within the next couple of weeks).

Great, @psavery! I have been using through `conda`, and I have no problem when using Tomviz from there. But would be great to have it without this "issue" in the Standalone version.
