### ISSUE TITLE
Breaking changes when moving ParaView forward (5.8.0)

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#2118]
We need to update ParaView to fix some compilation issues in newer compilers, but the 5.8.0 tag has a number of breaking changes that must be addressed including renaming/removing libraries that Tomviz depends on (`ParaView::ServerManagerRendering`), and removing at least one of the headers (`vtkSMGlobalPropertiesProxy.h`). I will see if I can dig a little deeper at some point, but leaving it alone for now.

**Comment by psavery** [comment]
As of #2153, we are on ParaView 5.9.
