### ISSUE TITLE
Docker image can not be pulled

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#2120]
**Describe the bug**
Cant pull Docker image.

**To Reproduce**
1. Open tomviz 1.9.0
2. Open example tilt series
3. Change to docker pipeline in Tools
4. Try any operator.
5. I get the following error:
`An error occurred executing 'docker pull tomviz/pipeline', '0'`

**Expected behavior**
Docker image should be downloaded and available to run.

**Desktop (please complete the following information):**
 - Operating system: Windows 10]
 - Tomviz version: 1.9.0

**Hardware (please complete the following information):**
 - Device: Razer 13
 - Graphics card: Intel or Nvidia

**Comment by cryos** [comment]
Windows is the least well tested, do you have Docker installed on that machine? If you go to a console and type `docker pull tomviz/pipeline` does that work? I just double checked and I can pull the image in Linux.

**Comment by ercius** [comment]
@cryos I cant believe I made that mistake. I dont have Docker installed! I think that pretty important. Thanks!
