### ISSUE TITLE
Flatpak Tomviz

### ISSUE THREAD

**Issue by kevinsmia1939** [OpenChemistry/tomviz#2157]
Hello,

I am trying to create Flatpak package for Tomviz and upload to Flathub.
https://www.flatpak.org/

Flathub-builder is what use to build locally Flatpak.

I build dependencies in sequence below.
GLEW 2.2.0
Numpy 1.19.5
TBB 2019_U8
Swig 4.0.2 with flags below.
```
      - --without-pcre
      - --disable-ccache
      - --without-tcl
      - --without-tcl
      - --without-perl5
      - --without-octave
      - --without-scilab
      - --without-java
      - --without-ruby
```
GDCM 3.0.8 Cmake-ninja
```
      - -DGDCM_BUILD_APPLICATIONS=OFF
      - -DGDCM_BUILD_SHARED_LIBS=ON
      - -DCMAKE_BUILD_TYPE=Release
      - -DGDCM_WRAP_PYTHON=ON
      - -DPYTHON_EXECUTABLE=/usr/bin/python3
      - -DGDCM_INSTALL_PYTHONMODULE_DIR=/app/lib/python3.8/site-packages/
      - -DGDCM_USE_VTK=OFF
      - -DGDCM_BUILD_DOCBOOK_MANPAGES:BOOL=OFF
```

CastXML 0.4.3. cmake
```
      - -DCLANG_LINK_CLANG_DYLIB:BOOL=ON
      - -DLLVM_DIR=/usr/lib/sdk/llvm11/lib/cmake/llvm
```

Eigen3 3.3.9 cmake-ninja

Paraview build with cmake from github.com/OpenChemistry/ParaView release v5.9.0 (commit 0aaf903ba3e8d012a608a466f798a041b4aebe17). The build flags were adopt from https://github.com/OpenChemistry/tomviz/blob/master/BUILDING.md.
```
      - -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
      - -DBUILD_TESTING:BOOL=OFF
      - -DPARAVIEW_USE_PYTHON:BOOL=ON
      - -DPARAVIEW_ENABLE_WEB:BOOL=OFF
      - -DPARAVIEW_ENABLE_EMBEDDED_DOCUMENTATION:BOOL=OFF
      - -DPARAVIEW_USE_QTHELP:BOOL=OFF
      - -DPARAVIEW_PLUGINS_DEFAULT:BOOL=OFF
      - -DVTK_SMP_IMPLEMENTATION_TYPE:STRING=TBB
      - -DVTK_PYTHON_VERSION:STRING=3
      - -DVTK_PYTHON_FULL_THREADSAFE:BOOL=ON
      - -DVTK_NO_PYTHON_THREADS:BOOL=OFF
```

ITK release 5.1.2 with cmake, flags also adopt from BUILDING.md.
```
      - -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
      - -DITK_LEGACY_REMOVE:BOOL=ON
      - -DITK_LEGACY_SILENT:BOOL=ON
      - -DModule_ITKBridgeNumPy:BOOL=ON
      - -DBUILD_TESTING:BOOL=OFF
      - -DITK_WRAP_unsigned_short:BOOL=ON
      - -DITK_WRAP_rgb_unsigned_char:BOOL=OFF
      - -DITK_WRAP_rgba_unsigned_char:BOOL=OFF
      - -DITK_BUILD_DEFAULT_MODULES:BOOL=OFF
      - -DITKGroup_Core:BOOL=ON
      - -DITKGroup_Filtering:BOOL=ON
      - -DITKGroup_Segmentation:BOOL=ON
      - -DITKGroup_Nonunit:BOOL=ON
      - -DPython_ADDITIONAL_VERSIONS:STRING=3
      - -DITK_WRAP_PYTHON:BOOL=ON
      - -DBUILD_EXAMPLES:BOOL=OFF
      - -DBUILD_SHARED_LIBS:BOOL=ON
      - -DITK_USE_SYSTEM_LIBRARIES:BOOL=ON
      - -DITK_USE_SYSTEM_CASTXML:BOOL=ON
      - -DITK_USE_SYSTEM_GDCM:BOOL=ON
      - -DITK_USE_SYSTEM_SWIG:BOOL=ON
      - -DITK_USE_SYSTEM_VXL:BOOL=OFF
      - -DITK_FORBID_DOWNLOADS=ON
```

And finally Tomviz build with cmake from github.com/OpenChemistry/tomviz tag:1.9.0 commit: b397df6d40810b97ad3afa221c2fa3e027d20754
` - -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo`

During building of Tomviz, I got this error.
```
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE - Success
-- Found Git: /usr/bin/git (found version "2.30.0") 
-- Determined Source Version : 1.9.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components: OpenGL GLX 
-- Found Python3: /usr/bin/python3.8 (found suitable version "3.8.7", minimum required is "3.8") found components: Interpreter Development.Module Development.Embed 
-- Found Python3: /usr/bin/python3.8 (found version "3.8.7") found components: Interpreter Development Development.Module Development.Embed 
-- Found PythonInterp: /usr/bin/python3.8 (found version "3.8.7") 
-- Found PythonLibs: python3.8
-- pybind11 v2.2.3
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
CMake Error at tomviz/CMakeLists.txt:631 (add_executable):
  Target "tomviz" links to target "ParaView::ServerManagerRendering" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at tomviz/CMakeLists.txt:626 (add_library):
  Target "tomvizlib" links to target "ParaView::ServerManagerRendering" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

```
I suspect that I use OpenChemistry/ParaView version 5.9.0 (commit: 0aaf903ba3e8d012a608a466f798a041b4aebe17) instead of the commit: 98a2eea1af02a45fa6d9b72b97b67f991bcb1f0e (reference in superbuild) , that might fix this issue? 
I will try rebuilding with the commit reference in superbuild (https://github.com/OpenChemistry/tomvizsuper), but it will take very long time to compile again.

**Comment by psavery** [comment]
@kevinsmia1939 We actually made changes recently that are present only on the master branch to make Tomviz compatible with ParaView 5.9.0 (which is what https://github.com/OpenChemistry/ParaView.git on the tomviz/release branch is pointing to).

To build Tomviz 1.9.0, I think you'll need to use the previous sha for https://github.com/OpenChemistry/ParaView.git that we were using, which I think can be found here: https://github.com/OpenChemistry/tomviz-superbuild/pull/317/files

10938cd09bfd2fae80955c4886a4e1cdac782b50

**Comment by cjh1** [comment]
Thanks @psavery

**Comment by cjh1** [comment]
Thanks @psavery

**Comment by kevinsmia1939** [comment]
@psavery 
When I use openchemistry/Paraview commit: 10938cd09bfd2fae80955c4886a4e1cdac782b50
I got error,

```
CMake Error at VTK/Common/Core/CMakeLists.txt:442 (check_symbol_exists):
  Unknown CMake command "check_symbol_exists".
```

If I use
0aaf903ba3e8d012a608a466f798a041b4aebe17 (5.9.0)
74338e7d6058d0d1cf89405b3c8e932f9d4ea921  (master)

It build fine, but I have not check if Tomviz will buld against it.

**Comment by psavery** [comment]
@kevinsmia1939 Unfortunately, there was a bug for building VTK with cmake >= 3.15 that got fixed in later versions of VTK: https://discourse.vtk.org/t/building-vtk-with-cmake-3-15/1370

I'm not really sure what a good solution would be. I guess either use cmake < 3.15, or add `include(CheckSymbolExists)` to the cmake file that has the error.

**Comment by kevinsmia1939** [comment]
@psavery 
I will try to patch the cmake file.
But the upcoming version of Tomviz will build with new cmake and Paraview?

**Comment by psavery** [comment]
Yes that's right. The master branch already builds with ParaView 5.9.0, which uses a VTK that has fixed the CMake issue.

**Comment by kevinsmia1939** [comment]
@psavery 
New release coming anytime soon?

Thanks.

**Comment by kevinsmia1939** [comment]
@psavery 

Good news, I manage to build and run Flatpak Tomviz.
I use master version of Tomviz.
I think Tomviz needs Scipy dependency too.


The left with bugged checker pattern plot is Flatpak Tomviz. The right is binary from Github.
Do you know what might cause this graphics glitch?
https://imgur.com/UJSTa09

**Comment by cjh1** [comment]
@kevinsmia1939 Yes, Tomviz does need scipy. We will probably cut a release in the next couple of months, we could probably cut a release candidate sooner if they can be uploaded to Flathub? Thanks very much for taking a look at this. Not sure what the deal is with checker pattern, they are both using the same graphics driver?

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 Yes, Tomviz does need scipy. We will probably cut a release in the next couple of months, we could probably cut a release candidate sooner if they can be uploaded to Flathub? Thanks very much for taking a look at this. Not sure what the deal is with checker pattern, they are both using the same graphics driver?

I would need to check on that if it running on same graphics driver, it both running locally on the same machine tho. Will have to ask Flatpak experts out there.

**Comment by cjh1** [comment]
@kevinsmia1939 Looks like some files are missing from the repo?

```
(flatpak-builder:2231718): flatpak-builder-ERROR **: 15:50:40.890: Failed to load included manifest (/home/cjh/work/source/org.tomviz.Tomviz/shared-modules/glew/glew.json): Failed to open file “/home/cjh/work/source/org.tomviz.Tomviz/shared-modules/glew/glew.json”: No such file or directory
Trace/breakpoint trap (core dumped)
```

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 Looks like some files are missing from the repo?
> 
> ```
> (flatpak-builder:2231718): flatpak-builder-ERROR **: 15:50:40.890: Failed to load included manifest (/home/cjh/work/source/org.tomviz.Tomviz/shared-modules/glew/glew.json): Failed to open file “/home/cjh/work/source/org.tomviz.Tomviz/shared-modules/glew/glew.json”: No such file or directory
> Trace/breakpoint trap (core dumped)
> ```

II will check but it look like flatpak-builder gone wrong badly. What distro you install it on?

**Comment by kevinsmia1939** [comment]
@cjh1 
Oh I see now, you will need to clone the submodules as well. These submodules are pre-made because it is commonly use. Clone it to the same dir as the .yaml file. 

git clone git://github.com/flathub/shared-modules.git

**Comment by cjh1** [comment]
Ok, should that be a git submodule so it would get clone automatically?

**Comment by cjh1** [comment]
It gets further:

```
(flatpak-builder:2338169): flatpak-builder-WARNING **: 08:08:40.610: Unknown property tags for type BuilderSourceGit
error: org.kde.Sdk/x86_64/5.15 not installed
Failed to init: Unable to find sdk org.kde.Sdk version 5.15
```

I guess I am missing a package? I am running Ubuntu.

**Comment by kevinsmia1939** [comment]
@cjh1

You will need Sdk installed locally on your system to start building it.
For normal user of the apps, they don't need them.

This should do the trick.
`flatpak install org.kde.Platform org.kde.Sdk`

**Comment by kevinsmia1939** [comment]
In summary.

1. Create new working folder.
2. Install flatpak-builder, for Ubuntu, ``sudo apt install flatpak-builder``
3. Install KDE Sdk, choose version 5.15 (system), ``flatpak install org.kde.Platform org.kde.Sdk``
4. Clone sumodules, ``git clone git://github.com/flathub/shared-modules.git``
5. Download org.tomviz.Tomviz.yaml
6. ``flatpak-builder --install --user build org.tomviz.Tomviz.yaml --force-clean``
7. Wait until finish and run with, ``flatpak run org.tomviz.Tomviz``

**Comment by kevinsmia1939** [comment]
I just build Flatpak Paraview, but found graphical glitch similar to Tomviz as well. Is the rendering backend for these graph VTK?
https://imgur.com/undefined

**Comment by kevinsmia1939** [comment]
Hi, I change my mind, would it be ok to for next release to be sooner? Do you do minor release as well?

**Comment by kevinsmia1939** [comment]
@cjh1 

Hello,
It has been quite some time isn't it?
I got Tomviz to build on Flathub now.
This has not been submit to Flathub yet, but if Tomviz is working fine, I will submit it.
Please try it out.
Uninstall any previously install Tomviz.
`flatpak remove tomviz`
You can install with this command.
`flatpak install --user https://dl.flathub.org/build-repo/49259/org.tomviz.Tomviz.flatpakref`

 Please let me know what you think.

**Comment by kevinsmia1939** [comment]
I have publish Tomviz on Flathub.
To address the issue about cloning ParaView openchemistry fork, I fetch upstream paraview and apply any patch from openchem paraview.
