### ISSUE TITLE
Artifacts for combined Contour and volume rendering 

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#216]
Splotchy and periodic artifacts appear in volume renderings under contour renderings.  See the attached example images.

This may also be unique to binary-value datasets, as I was not able to reproduce the problem with the sample data.

![tomvizerror1](https://cloud.githubusercontent.com/assets/12242066/10106799/c95231fc-6384-11e5-975e-33ff7d9ae4d7.png)
![tomvizerror2](https://cloud.githubusercontent.com/assets/12242066/10106802/cc8d7b1a-6384-11e5-9adc-23368e655f70.png)

**Comment by mathturtle** [comment]
@ElliotPadgett This is a limitation in VTK right now.  Translucent surfaces (your contour) and volume rendering do not work well together.  I don't really think we can do anything about this.

**Comment by Hovden** [comment]
We should at least let the VTK team know about the issue. @cryos @utkarshayachit

**Comment by cryos** [comment]
They are well aware of the issue, volume rendering traces rays and only sees opaque geometry, transparent geometry blends all other geometry "behind it" in the scene, you cannot do depth peeling to solve this when combining volumes and transparent geometry unfortunately. We should perhaps consider adding a warning when attempting to combine these, or at least document this limitation. Closing for now.
