### ISSUE TITLE
Slice and orthoslice icons look the same

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#22]
Orthoslice and slice icons should be distinguishable. For the orthogonal slice, it does not make sense in tomviz (or paraview) to show a tilted slice icon since this is not possible. However, this is great for the slice tool that allows any angle of slicing.

Suggested solution: "Orthogonal Slice" icon should show an orthogonal green slice. "Slice" icon should show a non-orthogonal slice with different color (maybe pink or blue?).

**Comment by mathturtle** [comment]
@cryos Do you have any suggestions on where I should get icons for this?  It is a pretty simple fix once I have the icons, but I'm not that good at image editing.

**Comment by cryos** [comment]
Yes - Steve, but I think you handled this over email now. Any icon/image needs in general are best worked on with Steve.
