### ISSUE TITLE
Add new paraview axis grid

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#222]
We need good scale markers for scientific visualization. It looks like the new axis grid implemented in Paraview could address this: http://www.kitware.com/blog/home/post/871

**Comment by mathturtle** [comment]
It turns out that the axis grid breaks volume rendering somehow.  I've reported the bug and they are working on it.

**Comment by mathturtle** [comment]
Ok, that was easy... after hours of searching how to enable it: It's already there!  It is hiding in the view properties panel.  There is a checkbox with no label that has a button to it's right instead.  The button says Edit Axes Grid and can be used to change parameters of the axes grid.  The checkbox turns it on or off.

Note: there is a bug where volume rendering fails when the Axes Grid is enabled and will not work again in that view even if the Axes Grid is turned off.  I have reported it and the volume rendering folks are looking into it right now.

**Comment by mathturtle** [comment]
![checkbox](https://cloud.githubusercontent.com/assets/553788/10404337/f270c848-6e9f-11e5-89b6-625d48e6ee09.png)

This checkbox is the one I mentioned above.

**Comment by mathturtle** [comment]
Ok, it is there... We want to expose it more.  Where does this go?  Menu item?  Button in the toolbars?  I don't think we can edit the buttons directly above the view...
