### ISSUE TITLE
Manual tilt axis incorrect when "vertical" selected

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#2241]
**Describe the bug**
Note: I realize that the screenshots below show 1.9.0. I tested this on 1.10.0 and the I see the same behavior.

The manual tilt axis alignment wizard does not work correctly when the "vertical" tilt axis direction is selected. I generated projections of a test object from +/- 90 degrees to remove any issues with in plane alignments in the screen shots below. The test object is 9 round spheres arranged in a body-centered cubic arrangement. The tilt axis should be horizontal, but I can change that by using the Data Transforms - Rotate command to rotate around the Z-axis.

1) Here is the object with no rotation applied
![Screenshot 2022-04-28 104506](https://user-images.githubusercontent.com/15657108/165816961-ef505243-ed5e-4567-8fa2-2a408b406d1d.png)

2) Here is the object with a 5 degree rotation applied in the pipeline.  The tilt axis is Horizontal. The yellow tilt axis makes sense and the reconstructed slices are correct.
![Screenshot 2022-04-28 104622](https://user-images.githubusercontent.com/15657108/165817075-d01a327a-bb91-4760-ae60-ba769877e8da.png)

3) Here is the object with a 95 degree rotation applied and the tilt axis set as "vertical" and -5 degree rotated tilt axis. The yellow tilt axis is correct but the reconstructed slices are incorrect
![Screenshot 2022-04-28 104707](https://user-images.githubusercontent.com/15657108/165817286-29b4c2bf-0bc1-43ed-9e4c-fe6cb9afc282.png)

4) Here is the object rotated with 95 degree applied and the tilt axis set as vertical. I use a 5 degree rotated tilt axis. The yellow tilt axis is incorrect but the reconstructed slices are correct.
![Screenshot 2022-04-28 104730](https://user-images.githubusercontent.com/15657108/165817471-d4abe16d-03e7-47f7-9ede-a614404503d5.png)

5) Here is the tilt axis wizard and the main window together. I set the tilt axis to -5 degrees and the yellow tilt axis matches the expected direction in the figure. However, the reconstructed slices at the bottom are incorrect. I pressed apply so that the main window on the left updated with the -5 degree rotation applied and this figure *looks correct*.  
![Screenshot 2022-04-28 110111](https://user-images.githubusercontent.com/15657108/165817760-1c9ce567-009e-459c-9012-3bec2e991bba.png)

I ran a reconstruction on the object in step 5 and it worked as expected.

I think that there is an error in the sign of the rotation applied to the reconstructions in the bottom right and bottom left in the tilt axis wizard. This makes alignment with a vertical tilt axis nearly impossible.

**To Reproduce**
I can share the test object and/or python code to create it. It is based on numpy and scipy.radon.

**Expected behavior**
The yellow axis, the reconstructed slices, and the final applied rotation should all agree when the vertical tilt axis is selected.

**Desktop (please complete the following information):**
 - Operating system: Windows 10
 - Tomviz version: 1.9.0 and 1.10.0

**Hardware (please complete the following information):**
 - Device: Dell desktop
 - Graphics card: NVIDIA Quadro

**Comment by psavery** [comment]
@ercius Any chance you still have this example file for me to try out?

**Comment by psavery** [comment]
Here are the two places where the issues are most likely to be:

1. When drawing the vertical line, the way we adjust the regular line is [by subtracting an additional 90 degrees from it](https://github.com/OpenChemistry/tomviz/blob/486c0f38a1ec5f87b23a514194a160445b8d6b1c/tomviz/RotateAlignWidget.cxx#L182-L186).
2. When extracting the sinogram from the tilt series, if the axis is vertical, we [make the x dimension the tilt axis instead of the y dimension](https://github.com/OpenChemistry/tomviz/blob/486c0f38a1ec5f87b23a514194a160445b8d6b1c/tomviz/TomographyTiltSeries.cxx#L82-L87).

**Comment by ercius** [comment]
Here is a gist to recreate that object in python. I actually think this would be useful to add to tomviz as an example data set.

https://gist.github.com/ercius/080a0a224cab67e9c60de282cb76ed92

**Comment by psavery** [comment]
Thank you Peter! And just to clarify one thing: for number 3, you mentioned the slices are incorrect, but for number 4, you mentioned the drawn axis is incorrect. Does this mean there are issues both with the slices and the drawn axis when using a vertical orientation? Or do you think there is an issue with only one of them?
