### ISSUE TITLE
Not possible to enter tilt series angles

### ISSUE THREAD

**Issue by rgmendes13** [OpenChemistry/tomviz#2248]
Everytime that I open a new dataset (stack or individual images) and click on Tomography --> Mark Data as Tilt Series, I am not able to enter the angles. Before a window would open where I could select the angle range/increment or load a file with the angles. This is simply not working anymore.

I already tried deleting and installing tomviz again, but it didn't solve the problem. I notice that when I select Mark Data as Tilt Series, this option will appear as last in the pipeline and it is not possible to edit or open it.

If someone knows what is possibly happening it would help me a lot

regards,

**Comment by cjh1** [comment]
Hi @rgmendes13 , I just tested this on 1.10 and I am able to set the angles. What version and platform are you using?

**Comment by rgmendes13** [comment]
Hi @cjh1, I am also using the 1.10. In fact, a couple of days ago it was working normally and I can't understand why it simply stopped working.
