### ISSUE TITLE
Is there any docs for the python API?

### ISSUE THREAD

**Issue by RupertPaoZ** [OpenChemistry/tomviz#2274]
hello, I am working with tomviz now and I want to process my data with the python API. But I couldn't find the docs for the python API. Actually, now I want to save the 'Volume' results in my pipeline, however the `tomviz.io.Writer.write()` seems not work.

**Comment by psavery** [comment]
Some of the Python docs are [here](https://tomviz.readthedocs.io/en/latest/interactive/). But I'm not sure if there's a way right now to write out a data source via the python API. If we had some way to access the `vtkDataObject`, we could definitely do that.

@cjh1 Do you know?

**Comment by cjh1** [comment]
@psavery Yes, that is the only doc we have for the interactive Python interface. @RupertPaoZ Are you trying to write an operator or using the interactive Python interface to interact with the pipeline?

**Comment by psavery** [comment]
There is a [`tomviz-pipeline`](https://tomviz.readthedocs.io/en/latest/pipelines/#running-pipelines) executable packaged with Python that is designed to process data in batch. Have you looked into that?

The way it works is that you open Tomviz and perform all of the operations needed for a single dataset, then save that state file, and then you can use the `tomviz-pipeline` executable to run that state file and apply the same operators to many data files in batch.
