### ISSUE TITLE
Animation helper "Export movie" button

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#2275]
Add a button to the Animation Helper to open the Export Movie workflow. This would be the same as the "File -- Export movie" command, but more obvious to the user. It would be good to add below "Clear all Animations" so its available on all tabs.

**Comment by psavery** [comment]
I ended up putting it right above "Clear all Animations" instead, since I thought it less likely for users to accidentally push "Clear all Animations" when they intended to export a movie :-). But it is still available on all tabs.
