### ISSUE TITLE
Reconstruction slices saturated in tilt axis alignment wizard

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#2279]
**Describe the bug**
The tilt axis alignment wizard has three reconstructed slices at the bottom. These can be saturated if the values in the reconstructed slices are beyond the range of the original tilt axis histogram. These images do not respond to the histogram range values after the wizard is open.

**To Reproduce**
1. Load example tilt series
2. Convert to float (to avoid overflow)
3. Add a constant of 1000 simulating a constant background value.
4. Open the tilt axis alignment (manual) wizard.

**Expected behavior**
All images in this wizard should be normalized 0-1 before display. We are not worried about quantitive ranges.

**Screenshots**
Result from steps above:
![image](https://user-images.githubusercontent.com/15657108/215633837-3ab2156e-1313-43dd-9c78-f7bced26c4de.png)

Result without added constant.
![image](https://user-images.githubusercontent.com/15657108/215633635-cd8348b3-2046-451f-bf92-0290b86c1005.png)

**Desktop (please complete the following information):**
 - Windows 11
 - Tomviz version: Nightly downloaded 2023/01/30

**Hardware (please complete the following information):**
 - Device: Laptop
 - Graphics card: NVIDIA

**Comment by psavery** [comment]
Just to leave a note here: #2281 does fix this issue as long as there is almost no rotation. It did so by making the color range via the data in the inscribed circle. But when there is rotation, it isn't an inscribed circle as much anymore, so we may need to revisit this if that becomes important.
