### ISSUE TITLE
Crashes when opening data transform script for sample data

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#228]
Tomviz crashes when I try to open the data transform script for sample data. This may be related to #221 

To reproduce the crash:
1. Create a sample dataset.
2. Do a data transform (say "Shift Uniformly").
3. Do another data transform (say "Delete slices").
4. In the Data Transform pipeline (lower left corner), double click the first transform ("Shift Uniformly").
![screen shot 2015-10-06 at 6 04 05 pm](https://cloud.githubusercontent.com/assets/13088588/10324137/5a0c84a8-6c55-11e5-85d0-dbf0b376c718.png)

**Comment by mathturtle** [comment]
Same (or very similar) nasty python stack trace as #221.

**Comment by mathturtle** [comment]
Ok, this is the same problem (python trying to allocate a pointer's worth of memory), but in a different place while trying to import a different module.  This time it is the import of the `pygments` module in the python syntax highlighter that is failing.  This is the module that does the syntax highlighting for the python editor dialog.

**Comment by mathturtle** [comment]
This time I can't just import the module from the python console to get around the issue...  It fails regardless of anything I've tried as long as you follow these steps.  I don't know why these steps are so horrible though... the steps themselves don't show any issues in valgrind, so it has to be something with the program setup?

**Comment by yijiang1** [comment]
The bug no longer happens in version 0.7.0.
