### ISSUE TITLE
Slice tool's orientation arrow cannot be turned off

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#23]
The slice tool displays an arrow perpendicular to its surface and allows the user to change the slices orientation. After a user is done choosing an orientation, they should be able to disable the visibility of the arrow.

Suggested Solution: Add a checkbox in the slice view properties that can disable or enable the orientation arrows visibility.

**Comment by Hovden** [comment]
@robertmaynard any chance you could sneak this feature into our upcoming 0.5 release?

We use your slice tool very often, removing the arrow's visibility will allow us to use it in presentations and figures.

**Comment by mathturtle** [comment]
@robertmaynard isn't on the project anymore. I'll take a look, but I suspect it is too big to get into 0.5 without sacrificing something else.  You'll have to talk to @cryos.

**Comment by Hovden** [comment]
No worries, a user asked me about it yesterday. Thought it would be a really quick fix for Robert.

**Comment by cryos** [comment]
This may be tough, there is some infrastructure missing to display a panel for this... I will take a look, but no promises.
