### ISSUE TITLE
Reconstruction operation in C++

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#239]
Need to provide capabilities to perform reconstruction in C++. For the first pass provide a C++ operation that takes in the image stack, converts it to a float, and passes it to the reconstruction routine. The reconstruction routine will return a float volume. Convert vtkImageData to a C array pointer, show layout/give example of going through values in the volume.

**Comment by cryos** [comment]
Let's do the widget in-place reconstruction first, and then look at C++ operations later perhaps.

**Comment by mathturtle** [comment]
@yijiang1 @cryos Is this enough of an example?  I tried to show how to get the raw data pointer, allocate the output and access the data at an index.  We should talk about the exact signature of your reconstruction function soon so that I will know what input it needs.

```c++
#include "vtkImageData.h"

void ReconstructionAlgorithm(vtkImageData *input, vtkImageData *output)
{
  if (input->GetScalarType() != VTK_FLOAT)
  {
    // print error
    return;
  }
  int extents[6];
  input->GetExtent(extents);
  int xDim = extents[1] - extents[0] + 1;
  int yDim = extents[3] - extents[2] + 1;
  int zDim = extents[5] - extents[4] + 1;
  float *data = static_cast<float*>(input->GetScalarPointer());

  // Creating the output volume and getting a pointer to it
  int outputSize[3] = {100, 100, 100};
  output->SetExtent(0, outputSize[0] - 1, 0, outputSize[1] - 1, 0, outputSize[2] - 1);
  output->AllocateScalars(VTK_FLOAT, 1); // 1 is for one component (i.e. not vector)
  float * outPtr = static_cast<float*>(output->GetScalarPointer());

  // Accessing data:
  for (int z = 0; z < zDim; ++z)
  { 
    for (int y = 0; y < yDim; ++y)
    {
      for (int x = 0; x < xDim; ++x)
      {
        outPtr[z * outputSize[0] * outputSize[1] + y * outputSize[0] + x] =
          data[z * yDim * xDim + y * xDim + x];
        // obviously you want to be a bit more careful about out of bounds access than this...
      } 
    } 
  } 
} 
```

**Comment by yijiang1** [comment]
LGTM. Another basic input the reconstruction function need is the tilt angles.

**Comment by mathturtle** [comment]
Right, tilt angles.  You would do the following:
```c++
#include "vtkFieldData.h"
#include "vtkDataArray.h"

.... // skipping into function from other example
  vtkDataArray *tiltAnglesArray = input->GetFieldData()->GetArray("tilt_angles");
  int numTiltAngles = tiltAnglesArray->GetNumberOfTuples(); // this should be equal to zDim
  double *tiltAngles = static_cast<double*>(tiltAnglesArray->GetVoidPointer(0));
```

I should probably add a helper function to avoid duplicating this get tilt angles code everywhere.  I added one for python, but for C++ they are only accessed in the DataSource so there is no helper yet.

**Comment by yijiang1** [comment]
Cool. I think this is enough for me to start working on reconstruction functions.

**Comment by yijiang1** [comment]
> float *data = static_cast<float*>(input->GetScalarPointer());

Just curious: what would happen if input's type is not float and we run the code above without the type checking part in the beginning? Will it cause Tomviz to crash?

**Comment by mathturtle** [comment]
Probably.  `GetScalarPointer()` returns an address with no type information and the `static_cast` tells the compiler to treat it as a pointer to some floats.  So you will always get a non-null pointer.  But if the underlying data type is not `float`, you will get garbage data.  And if it uses less bytes than `float`, you will read addresses outside the real array bounds which hopefully will crash (it is much easier to debug if it crashes).

**Comment by yijiang1** [comment]
@mathturtle I see. Thanks for the detailed explanation.
I've been getting strange results and crashes using Tiff data (whose type is unsigned char). I think my problem is due to data types. Is there a way to easily change data types (in c++ or Tomviz)?

**Comment by mathturtle** [comment]
Currently no.  The C++ code looks something like this:

```c++
// includes you will need (I'm not sure these are all of them)
#include "vtkPointData.h"
#include "vtkFloatArray.h"

// conversion code
template<typename T>
vtkSmartPointer<vtkFloatArray> convertToFloatT(T *data, int len)
{
  vtkSmartPointer<vtkFloatArray> array = vtkSmartPointer<vtkFloatArray>::New();
  array->SetNumberOfTuples(len);
  float *f = static_cast<float*>(array->GetVoidPointer(0));
  for (int i = 0; i < len; ++i)
  {
    f[i] = (float) data[i];
  }
  return array;
}

vtkSmartPointer<vtkFloatArray> convertToFloat(vtkImageData* image)
{
  vtkDataArray *scalars = image->GetPointData()->GetScalars();
  int len = scalars->GetNumberOfTuples();
  vtkSmartPointer<vtkFloatArray> array;
  switch(scalars->GetType())
  {
  vtkTemplateMacro(array = convertToFloatT(static_cast<VTK_TT*>(array->GetVoidPointer(0)), len);)
  }
  return array;
}

// In your other code:
  vtkSmartPointer<vtkFloatArray> dataAsFloats = convertToFloat(image);
  float *rawData = static_cast<float*>(dataAsFloats->GetVoidPointer(0));
```

There may be a few typos, I haven't tested this.  But this should be the outline for the conversion you want.

**Comment by yijiang1** [comment]
@mathturtle My program crashes when I run the conversion code above : (

**Comment by mathturtle** [comment]
Alright, I'll debug it.  I said it was untested.

**Comment by mathturtle** [comment]
Oops.  Simple typo.  Actually several, it didn't compile at first...  Sorry about that.

```c++
template<typename T>
vtkSmartPointer<vtkFloatArray> convertToFloatT(T *data, int len)
{
  vtkSmartPointer<vtkFloatArray> array = vtkSmartPointer<vtkFloatArray>::New();
  array->SetNumberOfTuples(len);
  float *f = static_cast<float*>(array->GetVoidPointer(0));
  for (int i = 0; i < len; ++i)
  {
    f[i] = (float) data[i];
  }
  return array;
}

// The typo was in here, where it says scalars->GetVoidPointer(0).  The old
// version had 'array' there (and array wasn't created yet, so it was accessing NULL)
vtkSmartPointer<vtkFloatArray> convertToFloat(vtkImageData* image)
{
  vtkDataArray *scalars = image->GetPointData()->GetScalars();
  int len = scalars->GetNumberOfTuples();
  vtkSmartPointer<vtkFloatArray> array;
  switch(scalars->GetArrayType())
  {
  vtkTemplateMacro(array = convertToFloatT(static_cast<VTK_TT*>(scalars->GetVoidPointer(0)), len););
  }
  return array;
}
```
