### ISSUE TITLE
Change Color of Bounding Box

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#24]
User should be able to change the color of the "Outline" bounding box, like they can change the color of the background.  Currently the bounding box is always rendered in white.

**Comment by cryos** [comment]
Using labels is easier than adding [Feature Request], it would be better to use enhancement, bug, question (let us know if some are missing). I think feature request maps perfectly to enhancement.

**Comment by ElliotPadgett** [comment]
I was trying to do that but I don't seem to be able to apply labels.

**Comment by Hovden** [comment]
Nice. Even the small things can add a lot:
![screen shot 2015-06-03 at 4 18 54 pm](https://cloud.githubusercontent.com/assets/6197997/7970472/71195ca8-0a0c-11e5-95f0-36801d8f81bd.png)
