### ISSUE TITLE
Change data type to float when using "Mark As Tilt Series"

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#240]
Since all tomography operations (such as reconstruction, background subtraction) require the dataset to be float. We probably can enforce a data type conversion in the "Mark As Tilt Series" function.

**Comment by cryos** [comment]
Why do you want to do this here, rather than before a reconstruction? It would be ncie to understand your motivation here.

**Comment by yijiang1** [comment]
We are thinking that other operations such as background subtraction (which will result in negative pixel values) also need to convert data type to float, so maybe we can just do a conversion once in "Mark As Tilt Series"?

**Comment by Hovden** [comment]
I've raised a new issue #241 to allow the user to change data type. I think this will address this problem for now and give more capability to tomviz for data processing.

**Comment by cryos** [comment]
I think this is resolved, at least in  some form, by the convert to float operator.
