### ISSUE TITLE
Fast Fourier Transform in C++

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#247]
Is there a FFT library I can use in Tomviz? Some tomography reconstruction functions need it.

**Comment by mathturtle** [comment]
There is pyfftw, but right now that is all we have for FFTs.  Let me talk to @cryos to see what we want to do for this.

**Comment by cryos** [comment]
Yeah, Rob and I spoke about this some time ago. Surveying the field of available FFT libraries there isn't a lot that really fits our licensing model well. As we already have pyfftw we could make FFTW available, it is one of the fastest and they at least offer the option of paid commercial licensing if people want that in the future.

It looks like FFTW is GPLv2+, and so is compatible with the ITK Apache 2 license if we invoke the + and use it under the terms of the GPLv3 (GPLv2 is incompatible with GPLv3 and Apache 2 licenses). We will have to look into packaging this, but in some senses we must already have most of what is needed (with the possible exception of installed headers).

**Comment by Hovden** [comment]
I also saw some FFTs in the ITK and VTK API. They may not be as fast as FFTW, but they might be good.

**Comment by cryos** [comment]
They should be perfect as we can build those APIs using an FFTW backend. We should ensure these are accessible, and can be used.

**Comment by mathturtle** [comment]
I'm halfway through updating the ITK binaries we use to turn on the FFTW-based modules.  Windows is done (I did that at the same time I fixed FFTW for windows).  I have the binaries built for the other platforms, but the superbuild doesn't use the new ones yet.

**Comment by mathturtle** [comment]
So the ITK we have is built with FFTW support now.  We can probably just start requiring ITK in the tomviz build and use that module from ITK directly.  This will make it more difficult to get a new (non-superbuild) tomviz build set up though.

**Comment by cquammen** [comment]
In ITK, there are two FFT backends, the optional FFTW backend you have been discussing, and the VNL FFT implementation. VNL has favorable licensing, but its FFT implementation is much slower than FFTW. 

If an FFT is needed in a C++ module, then it should be no problem to link against the FFT library functions. Do we need the FFT library exposed in Python? If so, the FFT functions in Python-wrapped ITK are exposed as ITK filters that operate on ITK images - the underlying FFT library APIs are not wrapped to my knowledge.

**Comment by mathturtle** [comment]
@cquammen,
@yijiang1 was writing a C++ reconstruction algorithm and wanted an FFT library to call from C++.  We were already providing PyFFTW in the binaries, but it could only be called from python.  So I just changed the builds so that ITK also builds against the FFTW implementation that is a part of those.  This has been done for a while and noone is using it.  I don't know enough about what he was doing to know if this will work though.

**Comment by cquammen** [comment]
Oops, should have read the title again. Looks like there is a pathway to using FFTW in C++. 

@yijiang1 Can we close this issue and open a new one if there are problems accessing FFTW?

**Comment by cryos** [comment]
Yes, closing for now as it looks like there is a reasonable path should we want to use FFTs.
