### ISSUE TITLE
Change default color map

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#248]
The cool-to-warm color map is the default color map, but not very useful for volumetric tomography data.I suggest changing the default color map to gray scale.

**Comment by Hovden** [comment]
Also, issue #44 would make changing the colormap more accessible.

**Comment by cryos** [comment]
Thanks for the reminder, we should make this change before the next release (and make the color map easier to change).

**Comment by Hovden** [comment]
I know gray scale has been advocated. But there are great colormaps that have the same intensity transfer profiles as gray but provide more dynamic range to the human eye (even colorblind people).

Here are the new colormaps used in matplotlib: http://matplotlib.org/1.5.0/users/whats_new.html#new-colormaps

They've been designed by color theorists, a great discussion is given here: https://bids.github.io/colormap/

There are four colormaps released under a CC0 license. I personally like "magma" and "viridis".
