### ISSUE TITLE
XMF/HDF5 file no longer supported

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#249]
tomviz 0.6.1 stable is able to open HDF5 data sets using an XMF file to describe the data structure. This is no longer available as of 0.6.1-128-g1e0125e. I found this data type very useful for more advanced data structures including EMD format. tomviz is still able to write xmf/hdf5 data sets, but then can not read them back in.

**Comment by mathturtle** [comment]
Between 0.6.1 and the current development branch we changed from exposing all of ParaView's readers to exposing only readers that our users cared about.  I am happy to add hdf5/xmf files to this whitelist but I suspect that there may be other problems when data is read in from these formats that is not an image volume.  I'll put up a branch that adds this support back in.

**Comment by cryos** [comment]
I don't think we should worry too much about the side effects at this point, sorry I had forgotten about this use case when we switched to whitelisting. Thanks for reporting this Peter!

**Comment by ercius** [comment]
Thanks for putting this back in. It's really useful as long as you can
figure out how to write the XMF file correctly. I have an example if anyone
is interested.

**Comment by Hovden** [comment]
Closing this for now. In the future we plan to work more on the HDF reader writer for the EMdataset format. Won't make the MRS release.

http://emdatasets.lbl.gov/spec/

**Comment by thomasaarholt** [comment]
Hello. It would be nice to re-introduce hdf5 - over at [Hyperspy](https://github.com/hyperspy/hyperspy) we use that as our default format, and it would be nice to jump in and out with tomviz using it.

**Comment by ercius** [comment]
CMD/HDF5 is working in the most recent full release (0.9.2). I use it very
often. I have not tried the nightlies though.
