### ISSUE TITLE
Color maps not working for "Threshold" module

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#25]
Currently the Threshold module does not respond to a change in its color map, instead always rendering grey.

**Comment by Hovden** [comment]
Elliot, I checked this bug on my machine and there wasn't a problem. Not sure what is going on with your tomviz.

**Comment by ElliotPadgett** [comment]
I tried with some other data and also didn't get the problem.  I'll try to track down what made it break.

**Comment by ElliotPadgett** [comment]
Ok, so I tried a few more configurations and the key thing to trigger the bug seems to be having a volume with only two values in it (e.g. 0 and 1, or 0 and 2).  Once I add a third value it starts to work again.

**Comment by ElliotPadgett** [comment]
Also, I just noticed that switching between "Surface" and something else like "Volume" in the "Representation" dropdown makes it update the color to the global color map assignment even if you have checked "Use separate color map for this module".  If I uncheck and recheck that then the problem seems to go away completely and the color updates as it should.  So it seems like it may be a problem with which buttons trigger the update.

**Comment by Hovden** [comment]
@ElliotPadgett is this still an issue or can we close this?

**Comment by ElliotPadgett** [comment]
Yes, I am still seeing this behavior in a recent nightly build.

**Comment by cquammen** [comment]
Still valid?

**Comment by ElliotPadgett** [comment]
This seems to be working now.
