### ISSUE TITLE
Raw data import defaults

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#250]
I suggest changing the "Data byte order" default value in the raw data import dialog from "bigendian" to "littlendian." Little endian is the most common format for all intel processors on modern linux, mac windows machines. This will cause a lot less confusion among most users. Alternatively, the value could be populated by the value of the current host system.

**Comment by mathturtle** [comment]
@ercius I don't think I can get the value of the current host system easily in the configuration file that specifies the GUI.  But changing the default to little endian shouldn't be hard and I think it makes sense.

@utkarshayachit Any objections to changing this in ParaView or do I need to override the UI for that reader in tomviz?
