### ISSUE TITLE
Smooth surfaces for "Threshold" module

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#26]
Currently the threshold module renders each voxel as a cube.  For some applications this is distracting and aesthetically unappealing, so it would be nice to have the option to render the surfaces smoothly instead.

**Comment by cryos** [comment]
How would a smooth surface of a threshold differ from a contour/isosurface in this sense?

**Comment by ElliotPadgett** [comment]
Say I have a (segmented) volume with materials A and B with intensities 1 and 2 respectively.  I want to draw the surfaces of each material with different colors.  I can draw an isosurface at 1.5 to show B, but once I draw an isosurface at 0.5 to show A, it covers up B!  So if I want to show both at once, an isosurface isn't the way to do it.  

Conveniently, TomViz has a threshold feature which will work.  I can pick a range from 0.9 to 1.1 to show A and one from 1.9 to 2.1 to show B and they don't conflict.  That's nice, but it also shows off my voxels which I might be embarrassed about.  I would really like to be able to do this kind of rendering (a nice feature which not everybody has) but also get smooth edges in the final visualization.

I attached some example screenshots with a toy dataset to illustrate the issue.

![tomvizsurface1](https://cloud.githubusercontent.com/assets/12242066/7466876/c901b4fc-f2b9-11e4-9ca6-1468653dacb7.png)
![tomvizsurface4](https://cloud.githubusercontent.com/assets/12242066/7466877/c904b292-f2b9-11e4-957f-088ac82ded7a.png)
![tomvizsurface3](https://cloud.githubusercontent.com/assets/12242066/7466878/c9071460-f2b9-11e4-8350-42163f3fefae.png)
![tomvizsurface2](https://cloud.githubusercontent.com/assets/12242066/7466879/c909a95a-f2b9-11e4-93f7-3d11e9d2977f.png)

**Comment by cryos** [comment]
So while we never addressed this directly, you can threshold using ITK operators, and you can color by label maps. I think we could make this a little smoother, but I think it should enable the types of workflows you would like. The color by label map offers ways of classifying voxels and then applying that to a contour in a very flexible way. I am going to close this issue, but we may want to circle back to this in the future to think about how we can make workflows like this easier.
