### ISSUE TITLE
Axis Alignment Testing and Polish

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#260]
The axis alignment tool looks good. It needs testing and validation plus a little polish on the UX.

**Comment by Hovden** [comment]
Instructions: Adjust the "Shift Rotation Axis" and the "Tilt Rotation Axis" such that the three reconstructions on the bottom look accurate. The yellow line shows the current axis of rotation. The three vertical red lines show where the displayed reconstructions are taken from. It is often useful to reconstruct different slices of the tomogram by changing the corresponding "Slice No.". When complete, click "Transform Data to Axis of Rotation" button

Widget Title: Determine the Axis of Rotation

@yijiang1

**Comment by yijiang1** [comment]
@mathturtle Could you add the instructions above? I'm not sure how to edit UI in Qt.

**Comment by yijiang1** [comment]
@Hovden The basic UI is finished now.

**Comment by Hovden** [comment]
Great. It appears to be working properly.
