### ISSUE TITLE
Fail to Build ParaView

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#268]
A student in my class wants to help with the project, but he's having trouble building ParaView.
He followed the instructions in the BUILDING.md document, and failed at the very end with this message:

make[2]: *** No rule to make target `/Users/coldatom/Documents/My/ files/Cornell/ PhD/Courses/cpp_project/paraview-build/Applications/ParaView/Documentation/paraview.qch', needed by `Applications/ParaView/Documentation/qrc_paraview_documentation.cxx'.  Stop.

make[1]: *** [Applications/ParaView/Documentation/CMakeFiles/vtkParaViewDocumentation.dir/all] Error 2

make: *** [all] Error 2

He uses OS X El Capitan.

**Comment by mathturtle** [comment]
So I asked around.  Apparently this is a Qt related error.  Where did he install Qt from?  Is the qhelpgenerator program present in the Qt install?

**Comment by cryos** [comment]
Can we just turn off generation of ParaView documentation? I may have missed that in the building document, and they are unlikely to want/need the help documentation being built.

**Comment by mathturtle** [comment]
I think it is only fair to warn you though: (building?) ParaView is not officially supported on El Capitan yet.  @danlipsa tried it and said it is still pretty buggy.  You have to build with Qt5 since Qt4 doesn't support it.  We haven't tested tomviz with Qt5 yet.  You may be able to use our binaries, so I might be able to send you a pre-built Qt4... I'll look into it.

If homebrew has Qt4 support then you may just be missing an option to your brew install qt4 command.

@cryos it isn't the documentation doing it.  It is the help pages within the application (Under the Help menu) and I don't think there is a way to turn them off.

@mathstuf you may be interested in this thread (feel free to unsubscribe if you aren't)

**Comment by coldatom** [comment]
Hi @mathturtle, I am the student @yijiang1 was referring. I used home brew in installing qt -- "brew install qt", but I didn't include any dependencies (such as d-bus, etc.) I am wondering is it the reason why I got error?

**Comment by mathturtle** [comment]
Hmmm. I can't see anything wrong with the brew recipe offhand.  As far as I know you shouldn't need any of the additional options.  Do you have the program `qhelpgenerator` in your brew installed Qt?  It should be in the same directory as qmake.

**Comment by coldatom** [comment]
@mathturtle thanks for quick replies. Yes. I do have the program qhelpgenerator in the same directory as qmake.

**Comment by mathturtle** [comment]
I'm going to try to borrow an El Capitan machine today and try building on it.  For now, my recommendation would be to get the Qt 5 binaries from [the official site](https://www.qt.io/download/) and build ParaView against Qt5.  There may be other issues with that, but it's the best I can do for now.

**Comment by cryos** [comment]
You could try to set QT_HELP_GENERATOR in the CMakeCache.txt (or using cmake-gui, toggle advanced). This is a little flimsier in the way it finds the binary, and so it could get you beyond this point at least.

**Comment by cryos** [comment]
I know tomviz needs some patches to work with Qt 5, so I would advise against trying that route. We held off until ParaView moved forward (but may want to reassess as there are a number of things we would like to use in Qt 5 now).

**Comment by coldatom** [comment]
Many thanks for the help. I set QT_HELP_GENERATOR using cmake-gui and re-complied the paraview, but the same error messages appeared.

**Comment by mathturtle** [comment]
I borrowed @danlipsa's new Mac this morning and I've tracked down the error.  The issue is that qt4 by default has no database backends and something (qhelpgenerator?) is expecting a sqlite plugin to be installed with qt.  It cannot read some database and is failing to generate the help docs.  Installing a qt sqlite plugin will solve this.  I'm looking for how to do this in homebrew (Dan uses macports).

**Comment by mathturtle** [comment]
With macports, the packages you need are:
qt4-mac
qt4-mac-sqlite3-plugin

**Comment by coldatom** [comment]
I installed qt via macports using 
qt4-mac
qt4-mac-sqlite3-plugin

After qt was successfully installed. I typed cmake in the paraview-build directory and 
I got this:
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework  
CMake Error at /usr/local/Cellar/cmake/3.4.0/share/cmake/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  VTK/GUISupport/Qt/CMakeLists.txt:71 (find_package)
-- Configuring incomplete, errors occurred!

**Comment by mathturtle** [comment]
The issue here is that CMake doesn't know where to find Qt when it is installed via macports.  You need to specify QT_QMAKE_EXECUTABLE to point to the qmake in your new Qt install.

**Comment by coldatom** [comment]
I installed qt via macports using 
qt4-mac
qt4-mac-sqlite3-plugin

I specified QT_QMAKE_EXECUTABLE

It took another 10 hours compiling...
 
And the same error messages popped out in the end again...

make[2]: *** No rule to make target `/Users/coldatom/Documents/My/ files/Cornell/ PhD/Courses/cpp_project/paraview-build/Applications/ParaView/Documentation/paraview.qch', needed by `Applications/ParaView/Documentation/qrc_paraview_documentation.cxx'.  Stop.
make[1]: *** [Applications/ParaView/Documentation/CMakeFiles/vtkParaViewDocumentation.dir/all] Error 2
make: *** [all] Error 2

**Comment by mathturtle** [comment]
It looks like homebrew may have updated their formula for qt4 on el capitan.  I was just able to build ParaView fine with their qt4, but a few weeks ago, when I last worked on this I got the error above.

**Comment by Hovden** [comment]
Having trouble finding cmake-gui using brew installation. It was straightforward using port.

**Comment by yijiang1** [comment]
Can tomviz be built on El Capitan now? I need to upgrade my system to run some other applications.

**Comment by cquammen** [comment]
I just built it on a Mac with El Capitan without problem. I am using homebrew's qt4.

**Comment by yijiang1** [comment]
I reinstalled qt4 but got this error when I try to make tomviz:

[  1%] Built target tomviz_automoc
make[2]: *** No rule to make target `/opt/local/lib/libQtGui.dylib', needed by `lib/libtomvizExtensions.dylib'.  Stop.
make[1]: *** [tomviz/pvextensions/CMakeFiles/tomvizExtensions.dir/all] Error 2
make: *** [all] Error 2

**Comment by mathturtle** [comment]
@yijiang, Did your qt4 install into exactly the same place?  If not, you
should probably rerun cmake to build tomviz without CMake's knowledge of
the system being polluted.  Since you upgraded your system, I'd recommend
deleting all your build trees and recompiling since things probably
moved/changed during the upgrade.

Shawn

**Comment by yijiang1** [comment]
> Did your qt4 install into exactly the same place?

I don't think so. I just did "brew install qt"
How can I delete my build trees?

**Comment by mathturtle** [comment]
>
> How can I delete my build trees?
>
Open a terminal, go to the tomviz build directory for your tomviz build and
run `rm -rf *`.  You will have to reconfigure with CMake, but cmake should
get the correct variables for the current system.  You should do this in
the ParaView build tree as well, (and anywhere else that you built
something locally).

Shawn

**Comment by cryos** [comment]
Just a quick heads up - I will be porting to Qt 5 in the coming days, and you will need to rebuild ParaView/tomviz against Qt 5. This should work much better on the Mac, but will be somewhat disruptive in rebuilding two code bases.

**Comment by yijiang1** [comment]
I'm rebuilding everything by following the instructions here: https://github.com/OpenChemistry/tomviz/blob/master/BUILDING.md

When I run 
cmake -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
  -DPARAVIEW_ENABLE_CATALYST:BOOL=OFF \
  -DPARAVIEW_ENABLE_PYTHON:BOOL=ON \
  -DVTK_RENDERING_BACKEND:STRING=OpenGL2 \
  -DVTK_SMP_IMPLEMENTATION_TYPE:STRING=TBB \
  -DPARAVIEW_ENABLE_WEB:BOOL=OFF \
  ../paraview

I get this error:
CMake Error at VTK/CMake/FindTBB.cmake:80 (message):
  Required library TBB not found.
Call Stack (most recent call first):
  VTK/CMake/FindTBB.cmake:273 (findpkg_finish)
  VTK/Common/Core/CMakeLists.txt:48 (find_package)

Where can I find this TBB library? Or do I really need it? Thanks.

**Comment by mathturtle** [comment]
>
> Where can I find this TBB library? Or do I really need it? Thanks.
>
 You don't *realy* need it.  It just makes the contour about 15x faster.
To turn it off, remove the `-DVTK_SMP_IMPLEMENTATION_TYPE:STRING=TBB \'
from your cmake line (you may have to clean the build directory, I don't
know how much state CMake is saving).  As for where to find it, look in the
tomviz/superbuild's versions.cmake file (in the root of the project) and
search for tbb.  It should give you a URL to download the TBB source code
that we use in the superbuild.

**Comment by cryos** [comment]
You could simply look at Intel's site, https://www.threadingbuildingblocks.org/ and they offer downloads, I can add a link to the build instructions. On Linux it will usually be in your package manager, it may be in brew (not on a Mac right now). I think you will generally want it, but as Shawn said it will work without it.

**Comment by cquammen** [comment]
On Mac, it is indeed available in homebrew.

**Comment by Hovden** [comment]
Can we add this download to the build instructions?

Somewhat related topic: I've been having a lot of problems building since
upgrading to El Capitan. My entire macports broke. So, I've switched to
Brew since it seems more popular among those at Kitware. However, I'm
having trouble getting cmake-gui.

**Comment by cquammen** [comment]
I use the regular Mac download of CMake (along with it's GUI) to configure ParaView and tomviz.

**Comment by yijiang1** [comment]
@Hovden 
> My entire macports broke. So, I've switched to
> Brew since it seems more popular among those at Kitware. However, I'm
> having trouble getting cmake-gui.

There is a macports specifically for El Capitan. I don't know how to install cmake-gui using homebrew, but you can do it using macport.

**Comment by cquammen** [comment]
Is this still an ongoing issue, or can it be closed?
