### ISSUE TITLE
Tomviz crashes if user picks a "recently opened" file that has been moved or deleted

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#27]
Picking a data file from the "File>Recently Opened" list that has been moved or deleted crashes Tomviz completely, followed by a "Tomviz quit unexpectedly" message on Mac.  It would be better to warn the user with an error saying that Tomviz could not find the file.

**Comment by cryos** [comment]
This should be resolved by #53, please test and reopen if this is not the case (should be in today's build).
