### ISSUE TITLE
Animations not saved in state file

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#270]
Found when working on #131.

**Comment by mathturtle** [comment]
@cryos @Hovden

**Comment by mathturtle** [comment]
This is more complicated than it appears.  I was going to fix it in my default animation branch, but after talking to Utkarsh I have decided to hold off.  We need to decide what we want from animations first.  ParaView saves the animations letting them refer to proxies.  We don't save many of these proxies, so the save animation code in ParaView is mostly useless to us.

**Comment by cryos** [comment]
Sounds reasonable, I think we want a higher level view of animations.

**Comment by Hovden** [comment]
Sounds good.

**Comment by mathturtle** [comment]
As I mentioned, this is not going to really be reliable until we redo the animation UI to make it less ParaView centric.  Right now it is animating the ParaView proxies directly.  These have no link to their tomviz module and do not have names that can be reliably linked to their tomviz module.

I'm going to try adding a query method to the module 'Are you responsible for this proxy?'.  That might let me do something to reliably save animations...
