### ISSUE TITLE
Default Load State

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#277]
I found new users that try out the software are lost as to where to start. They just want to see something in 3D and start exploring from there.

I suggest we have a default load state, with a simple isosurface visualization of a small dataset. This might be the star particle and a colorful isosurface.

This should be simple, but one issue to worry about, as tomviz progresses, the state files may become more complex and this could cause crashes in future builds.

**Comment by cryos** [comment]
I think we can do that on first load, but we should be careful to make it easy to disable too. You don't want regular users delete the default state every time the application loads, and likely want to offer the option on first load not to show this next time. We already have the sample data to help guide new users, and another option is also popping up a dialog on first load asking if they want to visit a tutorial page.

**Comment by ercius** [comment]
Maybe have a splash screen with options to load a sample dataset and
visualization? Then have a check box that will never show the splash screen
again?

**Comment by cryos** [comment]
Yes, I think something along those lines would be ideal. Not sure if we can realistically help with shared systems, might need some thought there if we want to help.
