### ISSUE TITLE
Add New Matplotlib Colormaps

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#288]
Here are the new colormaps used in matplotlib: http://matplotlib.org/1.5.0/users/whats_new.html#new-colormaps

They've been designed by color theorists, a great discussion is given here: https://bids.github.io/colormap/

There are four colormaps released under a CC0 license. I personally like "magma" and "viridis".

**Comment by mathturtle** [comment]
I have a work in progress branch for this, but I'm going to need to talk to @utkarsh.ayachit when he gets back to figure out the last piece of it.

**Comment by mathturtle** [comment]
The branch for this is merged... I also have a ParaView branch to add these upstream.  We'll have to take them out when that is merged (or we can have duplicates...)
