### ISSUE TITLE
Downsample Dataset

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#29]
Need a datatransform that downsamples the data by factors of 2x, 4x, etc.

Possible solution: Downsampling should not simply read every other datapoint, it should interpolate (most simply, this would be an average of adjacent pixels). This probably means a new dataset will be created in memory - I think this is OK.

**Comment by cryos** [comment]
Just merged #74 that adds some of this, it may need more work to flesh out the features. We still need to improve the UX for these general types of operation, but I think it should offer a good starting point. Let's open new issues with feature enhancement requests, this is not saved to the XML file yet, but we will work on that and other pieces.

**Comment by ElliotPadgett** [comment]
This feature does not work correctly for down-sampling an image stack/ tilt series, where you want to reduce the x and y dimensions but leave the z dimension the same size.

The downsample operation appears to mix data in the z direction, as you can see from the examples below.  Should I open this as a separate issue/bug or should we reopen this?

Original data:
![screenshot from 2015-06-10 16 15 04](https://cloud.githubusercontent.com/assets/12242066/8093015/156a5aa8-0f8c-11e5-876b-9ea4c0aa882b.png)

Downsampled data:
![screenshot from 2015-06-10 16 15 20](https://cloud.githubusercontent.com/assets/12242066/8093018/1b89e2e6-0f8c-11e5-8b9f-54d456622ad0.png)

**Comment by Hovden** [comment]
Yeah. I missed this! The downsampling algorithm is not working correctly. It is interpolating in dimensions that it should not.

Interpolation artifacts are particularly insidious - especially in the reproducibility of scientific data processing. We need to make these methods transparent to the user.

**Comment by cryos** [comment]
Yeah, that looks pretty terrible. Shawn will look into it, we may have missed some settings. Let us see if we can reproduce this with data we have access to, was there any particular parameter, or pretty much anything produced this?

**Comment by Hovden** [comment]
Given the time constraint, we may want to pull this from the 0.5 release and try get anything else we can completed. Using SciPy this can be implemented with 1 line of code in way that is transparent and understood by scientists. We can later work on the improved performance provided by VTK implementation.

**Comment by Hovden** [comment]
SciPy ndimage libraries work well for now. A more generic resampling has been added for future in #152
