### ISSUE TITLE
Manual Image Alignment Widget keyboard shortcuts

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#293]
Can we put text labels for the keyboard shortcuts in the Manual Alignment Widget next to their respective buttons?  This would make it easier for the user to discover them.

**Comment by mathturtle** [comment]
@ElliotPadgett Have you tried this in the latest release (0.7.2)?  I added these labels a while back and I think the change made it into that release.

**Comment by Hovden** [comment]
Looks ok.
