### ISSUE TITLE
2D sobel filter

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#299]
The sobel filter in the Data Transforms menu does not do what a user would want. Scipy's sobel is only a 1D filter, but most image analysis should be done in 2D. See attached python script (TXT format) to calculate a 2D sobel filter on a input data set in tomviz.

[2Dsobel.txt](https://github.com/OpenChemistry/tomviz/files/51270/2Dsobel.txt)

**Comment by ercius** [comment]
Removed a couple of extraneous lines of code. Also, I cast the array to np.float32 before operating to ensure that the values can be stored.
[2Dsobel.txt](https://github.com/OpenChemistry/tomviz/files/51286/2Dsobel.txt)

**Comment by yijiang1** [comment]
> Scipy's sobel is only a 1D filter
You are right. "scipy.ndimage.filters.sobel" calculates an approximation of the gradient of the image along a given direction.

> but most image analysis should be done in 2D
Why can't we do this in 3D? You can do this by simply calling 
```python
result = scipy.ndimage.filters.generic_gradient_magnitude(array, scipy.ndimage.filters.sobel)
```

**Comment by ercius** [comment]
There are two different use cases here:

1 use case is to sobel filter the 3D volumetric data set. I think generic_gradient_magnitude will accomplish this. Thanks for mentioning this.

The other use case is to sobel filter each image separately in a tilt series to aid with automated alignment. In this case you want to loop over all projection images and apply a 2D sobel filter to each image then return the filtered stack. My code implements this second use case.

**Comment by yijiang1** [comment]
I've changed the Sobel filter in "Data Transforms" menu to a 3D transform and added the 2D filter to "Tomography" menu.

**Comment by ercius** [comment]
I think that is a good option. Thanks.

**Comment by yijiang1** [comment]
Tested well on binaries.
