### ISSUE TITLE
Dataset disappear in "Recently Opened" menu

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#300]
I'm not sure if this is intended, but datasets in "Recently Opened" menu can disappear if users click "Cancel" in the "Configure Reader Parameters" UI.

1. Open a dataset in File->Recently Opened
![screen shot 2015-12-03 at 4 44 01 pm](https://cloud.githubusercontent.com/assets/13088588/11575111/5e2533ea-99dd-11e5-9ff5-0ed2f4e04188.png)

2. Click the "Cancel" button in the "Configure Reader Parameters" UI.
![screen shot 2015-12-03 at 4 46 43 pm](https://cloud.githubusercontent.com/assets/13088588/11575147/91e675cc-99dd-11e5-9505-43becbaed64a.png)

3. Now go back to File->Recently Opened and the dataset is gone.

**Comment by mathturtle** [comment]
Sounds like a bug to me.  I had noticed files disappearing from the recently opened menu, but I hadn't figured out the pattern.  Usually when I click cancel it is a misclick.  Nice job figuring this out. I'll take a look at it.
