### ISSUE TITLE
Non-orthoganal slice, point on plane issue

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#308]
The numbers that show up for the point on the plane do not make intuitive sense. I have a 1024x1024x88 sized array and the "point on the plane" for x maximum is 11604.4386892319.

Also, the point on the plane value could be truncated to 1 - 2 decimal points for easier reading and manipulation.

**Comment by mathturtle** [comment]
The point on the plane shows the point in a global coordinate system that is not relative to the image.  It would depend on the file format you read the data in from.  Some file formats store metadata about the position and scale of the image in the world coordinate system.  For others that do not have this, tomviz assumes that one corner of the image is at the origin of the world coordinates and each pixel is one cubic unit.  I am guessing that your file format put the image somewhere else or made it larger and the numbers you are seeing are from that.

Truncating the point to a few decimal places should be relatively easy.

**Comment by ercius** [comment]
It would be useful to know that coordinate system. The metadata from MRC files for example should include the pixel size (in Angstroms), but Im not sure if this is used internally in tomviz. I would assume that the number listed under the "Transformed Dimensions & Range" heading in the data properties window would show if the pixel size is applied. This is not the case for MRC data though.
![image](https://cloud.githubusercontent.com/assets/15657108/11666784/0d625748-9da3-11e5-8ac2-6489b77d1673.png)

It would be useful to know what these coordinates are in case you want to use tomviz to locate an object in the 3D volume, make measurements between objects, or use the number you read out in python to analyze the object somehow.

**Comment by cryos** [comment]
Yes, I think we need to ensure that we are reading this data from the MRC files, and other formats where practical. We need to take another pass at scale data, units, etc, and make sure we are making the best use of the data (and making it easy to edit/tag when the data is missing).

**Comment by mathturtle** [comment]
I know we are reading this data from MRC files.  I remember writing that code.  Assuming I understood the file format specification, we have the metadata.  I agree with @cryos that we should display this better and rework the UI.

@ercius The "Transformed Dimensions and Rage" shows the resulting dimensions after transforms such as downsample, crop, etc. have been applied.  If you have not used transforms to modify the data then this will be the same as the original.

**Comment by ercius** [comment]
@mathturtle Good to know. Thanks!

**Comment by ercius** [comment]
Closed now that the Ruler module is impending (#931)
