### ISSUE TITLE
Make Manual Image Alignment generate python transform

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#310]
The manual alignment widget should generate a python transform to shift the data rather than cloning the data and creating a new shifted data set.

The python script should display the shifts that it is applying.

**Comment by ercius** [comment]
I second this suggestion. All alignment functions should do this if posible

**Comment by cryos** [comment]
The clone was a temporary crutch we needed in Phase I, and it is time to revisit this now that we have fully function C++ and Python operators. Why must it be translated into Python?

If we are to make it editable I think storing the offset values in C++, and displaying them in the dialog would make far more sense than translating them into an essentially opaque text format. We could offer an export to Python feature, but I would rather make this an editable operation in the pipeline that can be opened up in the same dialog if you want to revisit the shifts.

**Comment by ercius** [comment]
One reason to have the data transform pipeline is to make it completely transparent to other researchers what you did with the data. Adding the shifts as a python transform would achieve this goal. I think that this is what you mean by: 'I would rather make this an editable operation in the pipeline." To me, it is irrelevant how the shifts are applied (python or C++), but the list of shifts should be saved with the transform and the shift operation should show up in the transforms list.

**Comment by cryos** [comment]
Great, that makes it clearer. I totally agree on making the list of shifts transparent, and I think that would be better achieved in a slightly different way. We could then make sure it is stored more clearly in the XML state file as a list of shifts for each slice. Translating that to Python (or other languages) would be far easier, and reusing it in the C++ code would also  be simpler.

**Comment by ercius** [comment]
@ElliotPadgett I hope this is what you had in mind as well. Chime in if you have a different view!

**Comment by mathturtle** [comment]
So is there a consensus here?  I think the summary is: make align a C++ operator and have the dialog show the offsets.  Is that right?

**Comment by cryos** [comment]
Yes, and we can add translation of this data to Python/XML/other types as and when required. The dialog should continue as it is, but reload the offsets previously applied if the user edits the operation.

**Comment by ElliotPadgett** [comment]
My one comment is that it would be more flexible if the shifts are associated with a particular transform rather than just having a single list with shifts for each image in the data set.  That way if I wanted to align, then do something like rotate the data, and then apply a second set of shifts to fine-tune (occasionally I want to do this) I can do it.  I'm not sure which way you were thinking of doing it.

**Comment by cryos** [comment]
If this becomes an operation, as stated above, then what you suggest should be possible. You can apply many of the same operation if you wish, and they will be applied in a linear sequence from start to finish.
