### ISSUE TITLE
Copy tilt angles when cloning datasets

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#316]
When users clone a dataset that's marked as tilt series, tomviz should always carry the tilt angles to new dataset.

Right now, this happens only if users choose the "Transformed data only" option. However, it should do the same for "Original data only" and "Original data with transformations". This may be related to #257 

We should treat tilt angles as an intrinsic property of the dataset instead of a transform.

**Comment by mathturtle** [comment]
This is related to #257.  Same issue.  Tilt angles can be a property of the dataset if no transforms have been applied yet.  But what about cases like your 'Generate Tilt Series' transform where a transform converts between the two types?  If you clone the original dataset those tilt angles should not be cloned.  Or if we ever have transforms that modify the original data's tilt angles...

**Comment by yijiang1** [comment]
> But what about cases like your 'Generate Tilt Series' transform where a transform converts between the two types?

Eventually, we want to automatically clone the result whenever a transform changes data's type (volume->tilt series for 'Generate Tilt Series' or tilt series->volume for all reconstruction functions).
We need some python utility functions for accomplishing this.

> Or if we ever have transforms that modify the original data's tilt angles...

Good point! In such cases can we at least copy the tilt angles of the original data?

**Comment by mathturtle** [comment]
What do you think of this?  I'll add a checkbox to the 'Set Tilt Angles' dialog that is on by default for 'Apply to Original Data'.  If the user unselects this the current behavior is used, but if it is selected the tilt angles will be applied to the original data as well.  (Applying them to the original data will also preserve them when a transform is deleted).

**Comment by yijiang1** [comment]
Sounds good to me. However, I still think users always want to copy tilt angles when cloning a tilt series.
What's your opinion? @Hovden
