### ISSUE TITLE
Apple Certification / Trusted Application

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#323]
It is time to start thinking about Apple Certification so tomviz can be treated as a trusted application. Right now the right click open thing is throwing off some users.

**Comment by cryos** [comment]
We have been discussing this internally, and I will see what we can do about getting this fixed. This is an issue largely created by Apple, it will likely make the release process more difficult. I am attaching it to the next release, I think we should solve it before making another release.

**Comment by cquammen** [comment]
Relevant: 

http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Mac_OS_X_Code_Signing

**Comment by cryos** [comment]
Thanks Cory, I will get back to this. I had properly signed app bundles, the missing thing was the developer certificate. I have one now, only one person was able to create this (despite me being marked an admin it was not enough). I should have it for the next bundle - the main challenges were making the Qt frameworks comply with the layout, and getting a developer certificate - no other type works, Apple's site for obtaining these doesn't make it clear that only the organization owner can create developer certs...

**Comment by cryos** [comment]
I will see if I can pull this off, I have the correct certificate type now, but we  have extended what we package a little too.

**Comment by cryos** [comment]
I have made a signed application, and shared it with a few testers locally. Initial results look good, it required some manual fixup of the Qt frameworks, mainly deleting debug versions and prl files. I think we should be able to put out a 1.0 macOS binary that is signed.

**Comment by cryos** [comment]
Marking this as resolved, it seems we have this working and it will feature in the 1.0 release. Thanks to those who tested this, or let me access their machines to test it.

**Comment by cquammen** [comment]
Very cool!
