### ISSUE TITLE
Properties Panel too slim on first launch.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#324]
The properties panel is too slim when the application is first launched. Since this is how the application appears to first time users, we should fix it (just make it wider).

<img width="932" alt="screen shot 2015-12-18 at 10 24 38 am" src="https://cloud.githubusercontent.com/assets/6197997/11900094/9883afa4-a571-11e5-9e43-d4fb667b9f49.png">

**Comment by cryos** [comment]
This should be fixed with #349
