### ISSUE TITLE
Unable to launch Tomviz

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#330]
I'm having trouble launching tomviz, both the build version and the binary version (from dashboards).
Sometime I'm able to open tomviz but it crashes when I mouse over the menus.

@Hovden @ElliotPadgett Can you download the latest binary version and see if you have the same issue? It may be my own computer's fault (for example, my paraview is outdated?) If not, I guess the bug is probably introduced in #321 .

**Comment by Hovden** [comment]
Yes. tomviz crashing 75% of the time at launch (Mac OSX). This was not happening on the previous build.

**Comment by cryos** [comment]
I see that here with the latest master, looking into it now and should hopefully have a patch ready soon. I didn't test #321 as it looked reasonable and I thought @mathturtle had tested it already. In my initial backtrace I see tomviz::ViewMenuManager, so it looks like it may be something with that branch as @yijiang1 said.
