### ISSUE TITLE
Translation alignment tool not modifiable in the data processing pipeline.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#333]
After alignments have been made and they are set into the data pipeline, the user cannot modify them. Users should be able to double click on the alignment in the pipeline and modify the shifts.

**Comment by cryos** [comment]
Agreed, I know we talked about making this possible already, we will prioritize this feature.

**Comment by mathturtle** [comment]
This worked when I pushed the branch... But it conflicted with my other
branch where I added the `hasCustomUI()` function to Operator.  You just
defaulted the `Operator::hasCustomUI()` to false.  But if you override it
to return true on the `TranslationAlignOperator`, this will work.

**Comment by cryos** [comment]
Fixed, we should try to be mindful of conflicts like this. If you are developing both branches, as in this case, just make the second depend on the first (or hold off on submitting the dependent until the parent is merged). I spotted what looked like a bug with parenting too, although in my testing it made no difference.
