### ISSUE TITLE
Error occurred when compile Tomviz using Visual Studio

### ISSUE THREAD

**Issue by linsheng** [OpenChemistry/tomviz#341]
Hi,

We're trying to build Tomviz from source code on windows. We have successfully built ParaView 5.0.0 with VS 2010. Then we compile Tomviz 7.0 and got this error.

```
CMake Error at cmake/CompilerFlags.cmake:14 (message):
Only the MSVC 2013 compiler is supported on windows.
Call Stack (most recent call first):
CMakeLists.txt:8 (include)
```

Then we updated VS2013, but another error occurred:

```
CMake Error at C:/Qt/test/ParaView-v5.0.0-source/VTK/CMake/vtkModuleAPI.cmake:120 (message):
Requested modules not available:

vtkPVServerManagerApplication
Call Stack (most recent call first):
C:/Qt/test/ParaView-v5.0.0-source-build/VTK/VTKConfig.cmake:74 (vtk_module_config)
C:/Qt/test/ParaView-v5.0.0-source-build/ParaViewConfig.cmake:49 (include)
CMakeLists.txt:41 (find_package)
```

Any suggestion on how to resolve this issue?

Thanks,

Lin Sheng

**Comment by mathturtle** [comment]
Hmm. I haven't seen that error before.  I have built ParaView 5.0 with VS2013 and built tomviz against it without errors.  Is this error happening when you are building ParaView or tomviz?  If it is building tomviz, then you have to rebuild ParaView with VS2013.  Unfortunately due to some of Microsoft's design decisions you can't link C++ code built with one version of Visual Studio to C++ code built with another version.

**Comment by cryos** [comment]
I will update the build instructions to make this clearer on Windows, and we will hopefully get support for VS2015 in the near future too. As pointed out you must build all deps with the same version of Visual Studio. It looks like your ParaView build/source tree is bad, I would suggest making a clean build and source tree - vtkPVServerManagerApplication is one of the core ParaView libraries.

**Comment by linsheng** [comment]
Hi mathturtle & cryos, thanks for the reply. What we're trying to do is to build the laster stable version (0.7.2) on windows using Visual Studio but we got different kinds of errors. There're several things we're still not very clear:

1. When build Tomviz 0.7.2, which version of Paraview should we use?
2. Which version of VS do you recommend? 
3. How about the version of Qt? In building document, it suggests Qt 4.8 but I only see Qt4.8 for VS2008 and VS 2010 in Qt's download page.
4. In Paraview's building doc, it says we need to use VS2008 or VS 2010+SP1 and do not use VS2012 and VS2013, so does that mean we have to build Paraview and Tomviz with VS2010?
5. In Tomviz's  building document, it says Intel TBB is a dependency. Do we need to install Intel TBB on windows too?

**Comment by cryos** [comment]
I didn't realize the ParaView documentation said that. We are building/testing our stack with MSVC 2013, including ParaView. If you look at https://open.cdash.org/index.php?project=TomViz&date=2016-02-01 you can see a build on praxis using our superbuild (https://github.com/OpenChemistry/tomviz-superbuild) to build on Windows, and that will also take care of building Qt with MSVC 2013 as far as I remember. You will need to install TBB on Windows, or it can be disabled if you have issues (build option for ParaView).

I hope that makes things a little clearer, if not please let me know. The superbuild really just coordinates building a number of dependencies, including pulling in some prebuilt binaries for Python, ITK, etc.

**Comment by mathturtle** [comment]
I didn't realize the ParaView docs said that either.  I have been building Qt4 from source with VS2013 on windows for our binaries and my local builds.  I can walk you through how to do this if you want.

@cryos Since we merged the Qt5 changes, the superbuild will not build Qt on Windows.

@linsheng To follow @cryos's suggestion about using the superbuild you will have to check out the version of the version of the superbuild that existed before we merged the Qt5 branch and force it to build tomviz 0.7.2 by changing the GIT_TAG of tomviz that is specified in versions.cmake it uses to 'v0.7.2'.

The other option is to just build the development branch 'master', which can be built against the Qt5 binaries from Qt's website using the current superbuild's 'master' branch.

**Comment by cryos** [comment]
That is a good point, we should tag the superbuild, and force that tag to a specific tomviz tag. We can certainly dig out the relevant SHA for the superbuild.

**Comment by linsheng** [comment]
We tried using Tomviz's superbuild and VS2013 to build the project. We get following errors:

```
Error	3	error LNK2019: unresolved external symbol "public: __cdecl pqSGExportStateWizardPage2::pqSGExportStateWizardPage2(class QWidget *)" (??0pqSGExportStateWizardPage2@@QEAA@PEAVQWidget@@@Z) referenced in function "public: void __cdecl Ui_ExportStateWizard::setupUi(class QWizard *)" (?setupUi@Ui_ExportStateWizard@@QEAAXPEAVQWizard@@@Z) [C:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\Plugins\CatalystScriptGenerator\CatalystScriptGeneratorPlugin.vcxproj]	C:\Qt\test\tomviz-superbuild-build\pqCPActionsGroup.obj	paraview
Error	4	error LNK2001: unresolved external symbol "public: __cdecl pqSGExportStateWizardPage2::pqSGExportStateWizardPage2(class QWidget *)" (??0pqSGExportStateWizardPage2@@QEAA@PEAVQWidget@@@Z) [C:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\Plugins\CatalystScriptGenerator\CatalystScriptGeneratorPlugin.vcxproj]	C:\Qt\test\tomviz-superbuild-build\pqCPExportStateWizard.obj	paraview
Error	5	error LNK2001: unresolved external symbol "public: __cdecl pqSGExportStateWizardPage2::pqSGExportStateWizardPage2(class QWidget *)" (??0pqSGExportStateWizardPage2@@QEAA@PEAVQWidget@@@Z) [C:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\Plugins\CatalystScriptGenerator\CatalystScriptGeneratorPlugin.vcxproj]	C:\Qt\test\tomviz-superbuild-build\moc_pqCPExportStateWizard.obj	paraview
Error	6	error LNK2019: unresolved external symbol "public: __cdecl pqSGExportStateWizardPage3::pqSGExportStateWizardPage3(class QWidget *)" (??0pqSGExportStateWizardPage3@@QEAA@PEAVQWidget@@@Z) referenced in function "public: void __cdecl Ui_ExportStateWizard::setupUi(class QWizard *)" (?setupUi@Ui_ExportStateWizard@@QEAAXPEAVQWizard@@@Z) [C:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\Plugins\CatalystScriptGenerator\CatalystScriptGeneratorPlugin.vcxproj]	C:\Qt\test\tomviz-superbuild-build\pqCPActionsGroup.obj	paraview
Error	7	error LNK2001: unresolved external symbol "public: __cdecl pqSGExportStateWizardPage3::pqSGExportStateWizardPage3(class QWidget *)" (??0pqSGExportStateWizardPage3@@QEAA@PEAVQWidget@@@Z) [C:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\Plugins\CatalystScriptGenerator\CatalystScriptGeneratorPlugin.vcxproj]	C:\Qt\test\tomviz-superbuild-build\pqCPExportStateWizard.obj	paraview
Error	8	error LNK2001: unresolved external symbol "public: __cdecl pqSGExportStateWizardPage3::pqSGExportStateWizardPage3(class QWidget *)" (??0pqSGExportStateWizardPage3@@QEAA@PEAVQWidget@@@Z) [C:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\Plugins\CatalystScriptGenerator\CatalystScriptGeneratorPlugin.vcxproj]	C:\Qt\test\tomviz-superbuild-build\moc_pqCPExportStateWizard.obj	paraview
Error	9	error LNK1120: 2 unresolved externals [C:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\Plugins\CatalystScriptGenerator\CatalystScriptGeneratorPlugin.vcxproj]	C:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\bin\RelWithDebInfo\CatalystScriptGeneratorPlugin.dll	preview
```

We have changed GIT_TAG to 'v0.7.2' in versions.cmake. Any suggestion?

**Comment by mathturtle** [comment]
Two possibilities come to mind:
1) What version of the superbuild are you using?  The most recent won't work.  I think you want this commit: `010a8ebeed1a61ff524f56bdbe43c7626da06911`
2) On Windows you have to set CMAKE_BUILD_TYPE to Release for the superbuild to work well.  Some of the precompiled things it uses only come built in Release mode and on Windows you can't link between the two.

**Comment by linsheng** [comment]
@mathturtle, we checked out commit `010a8ebeed1a61ff524f56bdbe43c7626da06911` and set `CMAKE_BUILD_TYPE` to `Release`. The errors we got are:

```
Error	242	error MSB6006: "cmd.exe" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	qt
Error	266	error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' [D:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\VTK\GUISupport\Qt\vtkGUISupportQt.vcxproj]	D:\Qt\test\tomviz-superbuild-build\QtGui4.lib(QtGui4.dll)	paraview
Error	363	error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' [D:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\ThirdParty\QtTesting\vtkqttesting\QtTesting.vcxproj]	D:\Qt\test\tomviz-superbuild-build\QtGui4.lib(QtGui4.dll)	paraview
Error	364	error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' [D:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\VTK\GUISupport\Qt\QVTKWidgetPlugin.vcxproj]	D:\Qt\test\tomviz-superbuild-build\QtGui4.lib(QtGui4.dll)	paraview
Error	484	error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' [D:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\VTK\GUISupport\Qt\vtkGUISupportQt.vcxproj]	D:\Qt\test\tomviz-superbuild-build\QtGui4.lib(QtGui4.dll)	paraview
Error	485	error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' [D:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\ThirdParty\QtTesting\vtkqttesting\QtTesting.vcxproj]	D:\Qt\test\tomviz-superbuild-build\QtGui4.lib(QtGui4.dll)	paraview
Error	486	error LNK1112: module machine type 'X86' conflicts with target machine type 'x64' [D:\Qt\test\tomviz-superbuild-build\paraview\src\paraview-build\VTK\GUISupport\Qt\QVTKWidgetPlugin.vcxproj]	D:\Qt\test\tomviz-superbuild-build\QtGui4.lib(QtGui4.dll)	paraview
Error	487	error MSB6006: "cmd.exe" exited with code 1.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	tomviz
```

It seems that we need to set the right target. Any suggestions?

**Comment by mathturtle** [comment]
I haven't seem that one before.  Which CMake generator did you use?  There are separate generators for 32 bit and 64 bit Visual Studio and the error seems to indicate an issue with 32bit/64bit-ness of files.
