### ISSUE TITLE
Direct fourier recon not working

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#342]
Reconstruction of the sample data for direct fourier is not working.

**Comment by yijiang1** [comment]
It works on my desktop (stable release 0.7.2, windows).
Could you be more specific about your problem?

**Comment by Hovden** [comment]
Sorry about the lack of description. I posted this when demoing the software yesterday. Now, I can't reproduce the problem, but the slices were appearing the exact same in the reconstructed volume. Not sure what was happening.

**Comment by yijiang1** [comment]
> slices were appearing the exact same in the reconstructed volume

Yeah I've never seen this problem before.

If you set all tilt angles to zero, you can get a summation of all the tilt images.
