### ISSUE TITLE
Error when building tomviz with qt5 on Mac

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#344]
I'm getting the following errors when I build latest tomviz. I seems that tomviz is not compatible with my qt5?

[  1%] Automatic moc for target tomviz
[  1%] Built target tomviz_automoc
[  8%] Built target tomvizExtensions
[ 10%] Building CXX object tomviz/CMakeFiles/tomviz.dir/ActiveObjects.cxx.o
In file included from /Users/yijiang/Visualization/tomviz/tomviz/ActiveObjects.cxx:16:
In file included from /Users/yijiang/Visualization/tomviz/tomviz/ActiveObjects.h:19:
In file included from /opt/local/libexec/qt5/lib/QtCore.framework/Headers/QObject:1:
In file included from /opt/local/libexec/qt5/lib/QtCore.framework/Headers/qobject.h:48:
In file included from /usr/local/include/QtCore/qmetatype.h:49:
In file included from /usr/local/include/QtCore/qdatastream.h:46:
/usr/local/include/QtCore/qiodevice.h:68:14: error: base class has incomplete type
    : public QObject
      ~~~~~~~^~~~~~~
/usr/local/include/QtCore/qobjectdefs.h:249:7: note: forward declaration of 'QObject'
class QObject;
      ^
In file included from /Users/yijiang/Visualization/tomviz/tomviz/ActiveObjects.cxx:16:
In file included from /Users/yijiang/Visualization/tomviz/tomviz/ActiveObjects.h:19:
In file included from /opt/local/libexec/qt5/lib/QtCore.framework/Headers/QObject:1:
In file included from /opt/local/libexec/qt5/lib/QtCore.framework/Headers/qobject.h:48:
In file included from /usr/local/include/QtCore/qmetatype.h:49:
In file included from /usr/local/include/QtCore/qdatastream.h:46:
/usr/local/include/QtCore/qiodevice.h:168:5: error: use of undeclared identifier 'd_ptr'
    Q_DECLARE_PRIVATE(QIODevice)
    ^
/usr/local/include/QtCore/qglobal.h:2583:95: note: expanded from macro 'Q_DECLARE_PRIVATE'
    inline Class##Private* d_func() { return reinterpret_cast<Class##Private *>(qGetPtrHelper(d_ptr)); } \
                                                                                              ^
In file included from /Users/yijiang/Visualization/tomviz/tomviz/ActiveObjects.cxx:16:
In file included from /Users/yijiang/Visualization/tomviz/tomviz/ActiveObjects.h:19:
In file included from /opt/local/libexec/qt5/lib/QtCore.framework/Headers/QObject:1:
In file included from /opt/local/libexec/qt5/lib/QtCore.framework/Headers/qobject.h:48:
In file included from /usr/local/include/QtCore/qmetatype.h:49:
In file included from /usr/local/include/QtCore/qdatastream.h:46:
/usr/local/include/QtCore/qiodevice.h:168:5: error: use of undeclared identifier 'd_ptr'
/usr/local/include/QtCore/qglobal.h:2584:113: note: expanded from macro 'Q_DECLARE_PRIVATE'
    inline const Class##Private* d_func() const { return reinterpret_cast<const Class##Private *>(qGetPtrHelper(d_ptr)); } \

...

**Comment by cquammen** [comment]
I suspect your build is pulling in header files from a Qt4 installation. I had similar errors when I had Qt4 installed in the same location as TBB. Can you confirm which version of Qt you have in /usr/local/include?

**Comment by yijiang1** [comment]
I have a bunch of qt-related folders in my /usr/local/include directory:
<img width="528" alt="screen shot 2016-02-11 at 11 23 39 am" src="https://cloud.githubusercontent.com/assets/13088588/12982235/f1625ef2-d0b1-11e5-9832-bc567d58423a.png">

How can I check the version of Qt?

**Comment by cquammen** [comment]
Before you check the version, which Qt are you trying to build against? The one in /usr/local or the one in /opt/local?

**Comment by yijiang1** [comment]
In /opt/local. 
<img width="714" alt="screen shot 2016-02-11 at 11 29 28 am" src="https://cloud.githubusercontent.com/assets/13088588/12982437/bf9b6052-d0b2-11e5-866f-414f8a6abdef.png">

**Comment by cquammen** [comment]
Okay. So the problem is indeed that the header files from the other Qt installation are getting picked up during compilation. The easiest way to remedy this is to get rid of the installation in /usr/local/. If you installed the Qt in /usr/local with a package manager, you should be able to remove it with the same package manager. Otherwise, you will need to manually remove it.

If you cannot remove it because some other software relies on it, then you will have to ensure that the /opt/local path is in the search path before /usr/local. How do you do this? Good question. It may require a change in the CMakeLists.txt for tomviz to list the Qt directories before TBB for instance. This may not be possible to do, and seems brittle. Really the safest way is to remove your undesired Qt.

**Comment by cryos** [comment]
We should try to get the Qt search paths in earlier, I will take a quick look at this too. It would be nice to make it more robust.

**Comment by cquammen** [comment]
Indeed. Qt doesn't help much by not versioning their installation directories.

**Comment by yijiang1** [comment]
I use homebrew to uninstall the old qt4 and now I'm able to build tomviz successfully. 
Problem sovled! Thanks @cquammen

**Comment by cquammen** [comment]
Three cheers!

**Comment by minghuayao** [comment]
> I use homebrew to uninstall the old qt4 and now I'm able to build tomviz successfully.
Problem sovled! Thanks @cquammen
This method cures my problem! Thanks!
