### ISSUE TITLE
Can't import vtk.numpy_interface.dataset_adapter in utils.py

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#345]
I'm getting "ImportError: No module named vtk.numpy_interface.dataset_adapter" when I try to do any python transform.

**Comment by cquammen** [comment]
Could you do the following to help debug this:

Tools menu -> Python Console
In the console, type

`import sys`
`print(sys.path)`

Please report what it says.

**Comment by yijiang1** [comment]
<img width="802" alt="screen shot 2016-02-11 at 5 40 59 pm" src="https://cloud.githubusercontent.com/assets/13088588/12993172/a55b4b24-d0e6-11e5-9bc3-9d56cd85172c.png">

**Comment by cquammen** [comment]
Did you build ParaView with PARAVIEW_ENABLE_PYTHON set to ON?

**Comment by yijiang1** [comment]
Yes.

**Comment by cquammen** [comment]
Hmm, it's odd that none of the ParaView build directories show up in the path. I'll have to think of why that isn't happening.

As a workaround for now, in your terminal window, you can try setting

`export PYTHONPATH=/Users/yijiang/Visualization/paraview-build/lib/site-packages:/Users/yijiang/Visualization/paraview-build/lib/`

modifying the path above to point to your paraview build directory. Then you'll have to launch tomviz from the command line

`cd /Users/yijiang/Visualization/tomviz-build/`
`bin/tomviz.app/Contents/MacOS/tomviz`

**Comment by yijiang1** [comment]
Yeah, adding the path manually fixed my problem.

**Comment by cquammen** [comment]
You shouldn't have to do that, so I wouldn't consider this fixed just yet :-)
