### ISSUE TITLE
3D mouse support

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#350]
Anyone know if Tomviz supports equipment like the [3D mouse from 3DConnexxion](http://www.3dconnexion.com/products/spacemouse/spacenavigator.html)? It looks like an interesting way to interact with visualizations. 

I found [this](http://www.vtk.org/Wiki/VTK/3DConnexion_Devices_Support) in VTK's wiki, but Im not sure if it made it into Tomviz.

**Comment by mathturtle** [comment]
We don't have support at the moment (that I know of).  But I believe there is a ParaView plugin that has support for alternative input devices like this.  I don't know how much work it would be to incorporate that into tomviz.

**Comment by cquammen** [comment]
SpaceNavigator support is indeed available in ParaView with the VR plugin enabled (I added it). However, it would take some work to make it work seamlessly so that you can just plug in the SpaceNavigator. On linux, root access is usually required to access connect to USB devices, so it's not always that easy. But on Mac and Windows it works fairly nicely.

**Comment by Hovden** [comment]
I'll just also throw this into the discussion. Licensing might be the biggest setback though.
https://www.leapmotion.com/

Not sure these add a lot to analysis, but they add a lot to the showmanship and outreach aspect of tomviz and electron tomography.

**Comment by yijiang1** [comment]
I own a leap motion controller and it has no advantage whatsoever compare with a normal mouse.

**Comment by cryos** [comment]
On most Linux distributions they have fixed the permission issue using device IDs and mapping to group permissions, this shouldn't be a major issue. You may need to add a file identifying the device, but that is more a local issue. We could take a look at the VR plugin as it supports a number of devices that our user base might be interested in, not sure what the dependencies/packaging looks like for it though (I don't think ParaView ships with this plugin, maybe Cory knows for sure).

**Comment by cquammen** [comment]
Oh, that's great that the permission issues have been addressed!

Checking my Mac binary installed from paraview.org, no, the VR plugin does not ship with it. VRPN is easy to build, though, so it likely wouldn't be too hard to ship it with tomviz.

**Comment by Hovden** [comment]
If it is easy, I would love to try out the 3D mouse suggested by Peter. I'll order one.

**Comment by ercius** [comment]
I was going to order one too. Let me know if it works and how you like it!

**Comment by Hovden** [comment]
@ercius I tested the 3D mouse without the VR plugin. It works out of the box as an interactive mouse and it can be used to control tomviz. You have to click on and hold on the object to rotate the object (this can be done with a button on the mouse). Although it's scientific motivation is weak, it's definitely an appealing way to demo the tool and marginally better than a mouse. If the user did not have to click to rotate the object it would be the most intuitive way for users to rotate the object.

Anyone have an opinion on how to prioritize this?

**Comment by ercius** [comment]
I just bought one to try it out as well based on this feedback. It might be an intuitive way for users unfamiliar with 3D navigation to look at their data. Ill have to try it out, but using the rotation to rotate the object along the "most vertical" direction would be useful.

I will get back to you on how this might work for novices (and experts).

**Comment by ercius** [comment]
@Hovden I have spent some time with the mouse and I have found it useful. I mostly tested it out in Avizo (hsssss) because it has better support. I was not able to try it in Tomviz since I don't have the VR plugin eanbled.

When looking at a complex object and trying to make 3D measurements I found the mouse very useful because I could position the measurement tool while rotating the object. Usually you have to rotate with the mouse and switch back and forth between rotation and interaction. I think its worth enabling this, and trying to fix the clicking issue. I would not put this high on the priority list though.

**Comment by cryos** [comment]
Thanks for testing this out and providing some feedback @ercius, I will see what we can do about getting this enabled/packaged in our binaries for you. I am afraid it may not make the next release, I will see if I can obtain one to do some testing locally too.
