### ISSUE TITLE
Panels no longer moveable (or too glitchy to use)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#351]
Once a panel, such as the properties panel, has been popped out as a separate window I cannot figure out how to return it to the main panel. The behavior has changed from previous builds—presumably a qt5 issue.

**Comment by cryos** [comment]
This seems to behave as I would expect on Linux, assuming this is Mac, I will take a look there.

**Comment by Hovden** [comment]
Ok, I reloaded the app and it is more responsive. Not sure what is going on. I will try and pin down the diagnoses.

**Comment by cryos** [comment]
Closing this for now, not able to reproduce. Let's reopen if we can come up with a way to reliably reproduce.
