### ISSUE TITLE
Full screen mode has cosmetic glitch (OSX)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#358]
The screen grab shows a repeatable cosmetic glitch when going full screen (OSX)
<img width="1680" alt="screen shot 2016-03-31 at 11 35 49 am" src="https://cloud.githubusercontent.com/assets/6197997/14181440/e0363370-f734-11e5-9bed-39ad9189b87c.png">

**Comment by Hovden** [comment]
I assume this is the same as issue #101. If it's too similar, we can close this.

**Comment by mathturtle** [comment]
Confirmed.  I've seen this in non-fullscreen, but never reproducibly.  I'd mentioned seeing it in OpenChemistry/tomviz-superbuild#101, but since we couldn't reproduce reliably we were ignoring it for now.  But switching the application to fullscreen does seem to have this glitch every time.

**Comment by Hovden** [comment]
Problem is solved in latest OSX release.
