### ISSUE TITLE
SurfaceLIC-related error when building paraview

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#368]
I want to get my tomviz up-to-date (on Mac) and get this error when I build paraview:

<img width="884" alt="screen shot 2016-04-13 at 2 31 56 pm" src="https://cloud.githubusercontent.com/assets/13088588/14504854/82d8c800-0184-11e6-82cc-48734297b0e5.png">

**Comment by cquammen** [comment]
I'm not sure why you are running into this, but please try the following:

cd paraview-build
rm -rf SurfaceLIC
cmake .
make

This should clear out the SurfaceLIC files and generate what is needed prior to the build.

**Comment by mathturtle** [comment]
This looks like the errors you get when qhelpgenerator is not found by the cmake configuration.  There is an option I added that turns all use of qhelpgenerator off.  Try setting the cmake option PARAVIEW_ENABLE_EMBEDDED_DOCUMENTATION to OFF (it defaults to ON).

**Comment by yijiang1** [comment]
@cquammen I tried this but still got the same error.
@mathturtle Setting the cmake option to off avoids the error.

I've successfully built paraview. Now I want to build tomviz, but it seems that I need to have ITK installed?What's the best way to install it properly?

<img width="940" alt="screen shot 2016-04-13 at 3 21 25 pm" src="https://cloud.githubusercontent.com/assets/13088588/14506409/a9145816-018b-11e6-8b0a-24172c27d927.png">

**Comment by mathturtle** [comment]
I think ITK is still optional to build tomviz.  It may not be for much longer if you want FFTs though.  Anyway, I think the easiest way to get it would be to download the version the binaries use [here](http://www.tomviz.org/files/itk-4.9.0-macosx10.9.tar.gz).  You may have to undo some tricks I added for the superbuild.  (If pointing ITK_DIR at it doesn't work, try this):
```sh
cd path_to_extracted
cd lib
mv itk ../tmp
cd ..
rmdir lib
mv tmp lib
```

**Comment by yijiang1** [comment]
@mathturtle Yeah this fixed my problem. Now I'm able to build and run tomviz.
