### ISSUE TITLE
Fix center of rotation to (0,0,0)

### ISSUE THREAD

**Issue by utkarshayachit** [OpenChemistry/tomviz#37]

**Comment by cryos** [comment]
We are going to have to push this back as it is tied to another feature that is targeted for 0.6.

**Comment by mathturtle** [comment]
This really depends on getting #38 done first.  Also, I have a feeling that even with #38 done, when they have tried this they may not like it for the same reason this was tied to #38 in the first place.

**Comment by cryos** [comment]
Consider whether this still makes sense

**Comment by cquammen** [comment]
If this refers to locking down the camera rotation center, I don't think this makes sense. It would prevent one from zooming in on a group of particles and rotating about it, for instance. Instead, the rotation center would be relatively far away, making any rotation very fast and difficult to control, and would effectively prevent you from easily viewing all sides of a subregion of the data.

**Comment by cryos** [comment]
This is an ancient request, and I don't think it is relevant amid all the other changes/update.
