### ISSUE TITLE
Operators QTreeWidget failing with Qt5

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#370]
I found an issue today with the tree widget that shows the operators.  If you double click on a python operator (to see/edit the code) it crashes the application.  The problem appears to be in the itemDoubleClicked signal of QTreeWidget that we are listening to.  It is passing NULL for the item even though one was double clicked on.  Reproduced on OSX and linux just now.

@cryos I can fix the crash with a null check.  But the double clicking on items will still be failing and I haven't had time to get to the root of that.  The tree widget was also displaying no items even when I had created operators on OSX.  Qt5 issue?

**Comment by cryos** [comment]
I will rebuild latest on Linux and see if it is happening here too, thanks for pointing this out.

**Comment by cryos** [comment]
Just merged a trivial fix to restore two columns, seems to be behaving as expected here at least. Getting back to my bigger set of UI changes that will deprecate that widget.
