### ISSUE TITLE
Generating Sample Data Crashes Again

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#373]
Tomviz is back to crashing when a user runs generated sample data.

Repeatable on OSX by running "Sample Data" > "Random Particles".

**Comment by mathturtle** [comment]
I'll take a look at it.

**Comment by Hovden** [comment]
It looks like all the Python routines are not working on my cdash build (OSX). 0.7.2-117-g

**Comment by mathturtle** [comment]
It is just ITK that is broken.  But due to the global import in tomviz.utils, nothing works if ITK is not found.  I'll put up a fix.

**Comment by Hovden** [comment]
Great.
