### ISSUE TITLE
Minor UI Menu reorganization

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#376]
The "visualization" icons should be moved to the left of the top menu. They are used the most and have a stronger relation to the visualization modules panel.
<img width="1305" alt="screen shot 2016-04-21 at 4 16 38 pm" src="https://cloud.githubusercontent.com/assets/6197997/14722967/9436e3e4-07dc-11e6-83da-2d22810909ff.png">

**Comment by cryos** [comment]
Agreed

**Comment by mathturtle** [comment]
@Hovden I noticed that you also moved the 'Move data mode' button over.  Do you want this change as well or just the Visualization modules moved all the way to the left?

Notes to anyone trying to do this: there is no way to tell Qt Designer which order the toolbars go in.  You have to edit the UI file and reorder the <widget> tags for the toolbars.  Their order in the file directly corresponds to their order in the UI and in Designer the first added is the first in the file...

**Comment by Hovden** [comment]
Yes. I think the 'Move data mode' should be next to or included with the axis tools (e.g. show axis, move center, etc.).
