### ISSUE TITLE
Allow moving of objects in the 3D view, interactively as well as using interaction.

### ISSUE THREAD

**Issue by utkarshayachit** [OpenChemistry/tomviz#38]

**Comment by utkarshayachit** [comment]
Note all modules should also move when the data is moved.

**Comment by mathturtle** [comment]
@Hovden @cryos This is another one where I'm not entirely sure how this should work.  From what I recall of our discussions we wanted to move datasets relative to each other and then lock down the center of rotation for the scene to the origin (#37).  Is this still correct?

**Comment by cryos** [comment]
This is fairly independent of the other issue, we need to be able to interactively move datasets relative to each other. For example, if I have two volumes loaded I want to display them both in the same view, then translate and rotate the active volume in the scene (the other volumes would remain static).

**Comment by mathturtle** [comment]
Progress on this: I have a branch that lets you grab *some* representations of datasets and drag the datasets around.  I'm not getting mouse motion events yet though.  It updates when you release the button.  But there are issues with picking that make this very difficult to use.

* Using ParaView's picking neither the orthogonal slice nor the volume rendering can be selected.  And our non-ortho slice is not even a proxy, so ParaView's picking can't pick it at all.  I'm using this right now.
* Using VTK's picking, we still can't pick volumes.  The orthogonal slice can be picked... but it is much harder to take the vtkProp and get the datasource that needs to be moved.

I also found a bug in the orthogonal slice actor: it ignores position set on the actor so even if you move all the others this won't move.  Tracking this down now.

**Comment by mathturtle** [comment]
Waiting on this ParaView bug too for translating slice representations: http://www.paraview.org/Bug/view.php?id=15891

**Comment by mathturtle** [comment]
ParaView bug filed for slice representation refusing to translate:
http://www.paraview.org/Bug/view.php?id=15891

**Comment by cryos** [comment]
Thanks for the updates on issues, we will need to figure out how to support volume picking.

**Comment by cryos** [comment]
We should get a better icon for this.

**Comment by mathturtle** [comment]
We have a better icon now.  Can we close this now or are there other things to fix?  I know the "don't require the datasource to be selected" is still outstanding.

**Comment by cryos** [comment]
I would like to keep this open to track that outstanding tweak, ideally this should be finished before the release is tagged.

**Comment by mathturtle** [comment]
The last PR has been merged and you can move objects whenever the mode is enabled, regardless of what is selected.  Can we close this or are we waiting for something else?
