### ISSUE TITLE
Add camera linking

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#382]
It would be useful to be able to link two camera views together allowing you to compare two reconstructions or visualizations. This would also allow a screen shot with the same view orientation and magnification to be exported easily.

Paraview implements this already, but I do not see the same function in tomviz.

**Comment by cquammen** [comment]
ParaView merge request supporting reading/writing of camera links to state file is at https://gitlab.kitware.com/paraview/paraview/merge_requests/1459.

**Comment by cquammen** [comment]
This is now merged in #1016.
