### ISSUE TITLE
Histogram colormap gets messed up after applying operator

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#383]
I found that if I load a dataset and apply a square root or other operator to it then the histogram will exhibit some very strange behavior (see image).  Reproducable on Linux (haven't tested other platforms).

![tomviz_histogram_point_placement_bug](https://cloud.githubusercontent.com/assets/553788/14986139/93fd135e-1118-11e6-9658-3caae8579e11.png)

@cquammen

**Comment by cquammen** [comment]
Confirmed on Windows 10 and Mac OS X. Will have a look. I probably just need to update the axis for the color bar.
