### ISSUE TITLE
Website: Documentation link at top of page

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#387]
On the homepage place a documentation link at the top menu that links to the documentation on the github page: 

https://github.com/OpenChemistry/tomviz
or
https://github.com/OpenChemistry/tomviz/blob/master/README.md

**Comment by cryos** [comment]
That is just our git repository, I think we should consider something that is more end-user oriented, such as https://www.gitbook.com/ which could then be developed using tools more dedicated to authoring/hosting documentation, or publishing a github site for the project.

**Comment by Hovden** [comment]
gitbook looks like it could be a good solution.

**Comment by cryos** [comment]
https://www.gitbook.com/book/openchemistry/tomviz has the new skeleton, if you have an account on there (or link it to your GitHub profile) I can give you edit permissions.

**Comment by Hovden** [comment]
It's been linked to my github profile:
https://www.gitbook.com/@hovden

**Comment by bdalevin** [comment]
Now that we have a User Guide on github, it would be very useful to link to it from the tomviz website.

**Comment by bdalevin** [comment]
This is the link: https://github.com/OpenChemistry/tomviz/blob/master/docs/TomvizBasicUserGuide.pdf

**Comment by cryos** [comment]
This is linked to from a page on documentation, we should expand the page a littlel too, but I think this at least adds the basics. Sorry it took a while, this slipped my mind.
