### ISSUE TITLE
UI that incorporates new data generated by data transforms

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#392]
Some data transforms may generate new data sets, such as label maps that describe segmented objects. Linking these new data objects to their source in the UI so that the user knows what is being visualized is very important, as is maintaining the link between original and derived data for data provenance.

Here is a mockup of a potential UI to show original data, the transforms applied to it, and visualizations of all original and derived data sets.

![image](https://cloud.githubusercontent.com/assets/360056/15051920/12043c9e-12c9-11e6-9dbb-f9362aac2951.png)

The idea is to convey the linear/hierarchical relationship among original data set and derived data sets. Each data set may be represented with a number of visualization modules.

There are obvious similarities with the Pipeline Browser in ParaView. The key difference is that tomviz would define visualizations for each data set original, and derived.

**Comment by Hovden** [comment]
It looks good from a user design perspective.

Would the data transforms then only apply to the parent dataset, before segmentation?

**Comment by cquammen** [comment]
In my view, a segmentation is just another form of data transform, but it is one that produces new data. With that view, you can just chain the data transforms together as you would do now. After segmentation, you might want a transform that yields a volume measurement, for example, so you could add a volume measurement transform after segmentation.

**Comment by cryos** [comment]
It breaks the model we chose for Tomviz, where we generally keep no mid points, so it is not possible to visualize things in the middle of a pipeline. Does this become an exception, how do we best express that, perhaps it is reasonable.

**Comment by cquammen** [comment]
I'm aware that I may be biased from my work on ParaView, so I'm trying hard to do what is best for tomviz users rather than just revert to what is familiar.

In my image analysis work, I have found it is useful - necessary, even - to visualize mid points, particularly if you have a set of processing steps that you apply to different tomographic reconstructions and something goes wrong in the output. Do we need to provide this capability in tomviz? Not necessarily, but instinctively I want to.

For another perspective, Slicer's model let's you view up to two grayscale images at the same time (orthogonal slices) with a user-settable fade between the grayscale images for comparison purposes, and it lets you view at most one label map with adjustable opacity to show grayscale images (orthogonal slices). We could follow this model by listing label maps associated with a data set and letting you select just one to visualize, rather than having visualizations of the label maps themselves. LabelMap-aware visualization modules could then use this label map as needed.

**Comment by cryos** [comment]
You can view them, but you need to remove the other pipeline objects after them. The memory requirements are an issue when working with real systems, and outside of debugging I am not sure we need to revert the work done here for what appears to be a minority use case.

This may not work as well for multiple segmentation operations, and so like I said it may be worth exploring alternatives, and we had already talked about making this somewhat of a hybrid approach where some operations are stored/cached (such as reconstructions). Many can be recalculated quite quickly as required, and the steps required to do so are stored.

**Comment by cryos** [comment]
Just to add that ITK operations tend to be a little different as they produce generally smaller label maps, most of which do not change the output of the pipeline. We knew going in they were different, and exploring how best to add them more visually to the pipeline is something we knew would take some work. Having multiple label maps seems manageable, but it would be harder to support them operating on mid-steps unless we added fuller cached objects too.

**Comment by Hovden** [comment]
However we decide to handle the segmented data, we might want to handle reconstructions in a similar way. For tomographic reconstruction, we will have a derived dataset where it assumed that the user will not change or will not be allowed to change the data processing steps done to the parent data (tilt series).

**Comment by cquammen** [comment]
How about this?

- List the segmentations under the data set in the Visualization Modules list.
- In visualization modules that support the use of a label map, show a combo box of label maps as a property in the Properties panel

Here's a mockup of what it would look like.

![image](https://cloud.githubusercontent.com/assets/360056/15080259/3008fb68-138b-11e6-90d8-c795a5a387a6.png)

**Comment by Hovden** [comment]
I'd like to think of an approach in line with what @cryos suggested:
"...we had already talked about making this somewhat of a hybrid approach where some operations are stored/cached (such as reconstructions)."

For reconstruction it might work like this:
Tiltseries is loaded, several data transforms are applied, finally a reconstruction is ran. When the reconstruction is complete it appears as an indented dataset (I'll call a "derived dataset") where new transforms can be applied to that derived data. The tiltseries and its applied transforms is cached and locked (no new transforms, only new visualizations allowed). A user would always have the option to clone the original or derived dataset and do more / different things.

For segmentation it might work similarly:
A dataset is loaded and datatransforms are applied. Once a segmentation routine is ran it appears as indented data (i.e. "Labelmap"). The dataset with transforms is locked (no new data transforms) and cached. A user can however apply new dataprocessing routines to the labelmap data. New visualizations can be created for the original data or the labelmap. A user would always have the option to clone the original or labelmap dataset (clone of a labelmap is just the raw data) and do more / different things.

**Comment by mathturtle** [comment]
I like this idea of "locked" transforms.  It prevents some of the corner cases I have been wondering about on the progress bar branch (and in general) when something at the top of the list is edited and everything re-executes.

**Comment by Hovden** [comment]
Here is what I propose:

At the end of a python routine the user can call tomviz utils to set the data one of three ways:
1) utils.set_array() to set the new values in place of existing data
2) utils.clone() to clone the dataset
3) utils.makechild() to lock transforms on the existing dataset and create a new dataset under it (see Cory's picture at the top of this thread)

**Comment by cquammen** [comment]
Could someone provide me a pointer or instructions on performing a reconstruction from a tilt series? It is the use case with which I am least familiar, and knowing the typical workflow for reconstruction will help me contribute to this discussion.

**Comment by cquammen** [comment]
Another use case we should consider includes transforms or operators that produce data tables that we would like to display and save to an output file. For instance, a table of nanoparticle surface areas, volumes, etc.

**Comment by Hovden** [comment]
To demonstrate the simplest workflow:
1) Load tiltseries data (Sample Data > Star nanoparticle (tilt series) )
2) "Tomography > Mark data as tiltseries". Press ok when prompted to enter angles.
3) Run any reconstruction method (e.g. Tomography > Direct Fourier Method)

Normally, there are a lot of alignment steps and normalization transforms that occur between step 2 and 3.

**Comment by cquammen** [comment]
Here's one proposal for what the UI might look like incorporating most of @Hovden's suggestions:

* Dataset
    * Transform 1
    * Transform 2
        * Segmentation A
            * Transform A
            * Transform B
            * Visualization A
    * Visualization 1
    * Visualization 2

Here, the theme is data first, then nested transforms followed by visualizations. Keeping the visualizations in the same column after the transforms helps make it clear that the visualization is associated with the data transformed about it - indenting visualizations relative to the transforms as they are in tomviz 0.9 might confuse them with a "cached" output of a segmentation.

For reconstruction, it would look like:

* Tiltseries
    * Transform 1
    * Transform 2
        * Reconstruction A
            * Transform A
            * Transform B
            * Visualization A
    * Visualization 1
    * Visualization 2

Another option could look like this:

* Dataset
    * Transform 1
    * Transform 2
    * Segmentation A
    * Visualization 1
    * Visualization 2
* Segmentation A
    * Transform A
    * Transform B
    * Visualization A

Here, the cached segmentation gets promoted to the level of a Dataset. We could add an arrow or perhaps some other UI element to convey that the Segmentation listed twice is the same one.

Thoughts @cryos @Hovden @mathturtle ?

**Comment by Hovden** [comment]
I can provide immediate input to how the tomography reconstruction pipeline could work. I think it should look very similar to your proposal. However I would like the visualizations appear before the derived dataset (the child data). Transforms on the parent dataset are locked once a child is made. However visualization are still allowed. To make a child, there should be a python command to simply call the tomvizutils.makechild(dataarray) at the very end of a script.

* Parent Dataset (e.g. a Tiltseries)
    * Transform 1 
    * Transform 2
    * Visualization 1
    * Visualization 2
        * Child Data A (e.g. a reconstruction)
            * Transform A
            * Transform B
            * Visualization A

**Comment by cquammen** [comment]
Thanks @Hovden! That is very useful feedback. I think keeping the visualizations up by the transforms makes a lot of sense.

Now let's suppose that a segmentation produces a table of data values that you want to see, say, one row per object with some information about the object. Where would you like to see that in this outline?

**Comment by Hovden** [comment]
I think there are two aspects to the segmentation. 1) is the creation of indexed values in the volume. 2) is the creation of statistics from a routine.

If it is possible to decouple these things in the workflow / pipeline. It might make things easier. 

Regarding part (2), one approach is to have a new pipeline module—perhaps called "spreadsheet"—that contains spreadsheet data with anything one can fit into it. It falls inline with the datatransforms and can be created from a data transform using tomvizutils.makespreadsheet( python list or array ).

* Parent Dataset (e.g. a volume)
    * Transform 1 
    * Transform 2 (calls create spreadsheet and populates with info)
    * Spreadsheet
    * Transform 3
    * Visualization 1
    * Visualization 2

Part (1) might take a little discussion. But I could imagine the index values created by a segmentation shown as a child dataset.

**Comment by cquammen** [comment]
Regarding (2), could we indent the Spreadsheet result from Transform 2 to indicate it was produced by the transform?

* Parent Dataset (e.g. a volume)
    * Transform 1 
    * Transform 2 (calls create spreadsheet and populates with info)
        * Spreadsheet
    * Transform 3
    * Visualization 1
    * Visualization 2

**Comment by Hovden** [comment]
I like that.

**Comment by cquammen** [comment]
Should we support each transform producing one or more spreadsheets? I would think so.

**Comment by cryos** [comment]
I think what you are proposing sounds good, and inline with some of our previous discussions. I would certainly expect the outputs of the transforms to be indented. I think starting on spreadsheets and then extending to volumes would be great. Clicking on a spreadsheet would support viewing in a spreadsheet or chart view.

It sounds like there is a reasonable agreement on the direction for the simpler creation/display of statistics, and we can then extend to support segmented volumes after this is working.

**Comment by cquammen** [comment]
Great, I'll push forward on the initial UI changes and should have a reasonable first branch to look at soon. I have a much better understanding of the PipelineModel class now and am comfortable changing it to whichever layout we wish.

**Comment by cquammen** [comment]
We need a way to return new data objects created in Python operators to the C++ side. I propose to have the `transform_scalars` function optionally return a dictionary containing the name of an output artifact as the key and the new VTK data object as the value.

**Comment by cryos** [comment]
I didn't notice the proposal to lump all derived data at the end like that, visually I am not sure I see how that will work and offer a reasonable summary of the pipeline. Disconnecting derived data from the operators that produce them also leads to confusion when deleting an operator and seeing what look like disconnected pieces (derived data) disappear.

I could see a possibility of moving the operators producing that data to the end, along with their child data. Something like:

* Parent Dataset (e.g. a Tiltseries)
    * Transform 1 
    * Transform 2
    * Visualization 1
    * Visualization 2
    * Transform 3
        * Child Data A (e.g. a reconstruction from Transform 3)
            * Visualization A

**Comment by cquammen** [comment]
It is in principal possible that Transform 3 modifies the data in the original data set as well as produces child data. In that case, putting the visualizations above Transform 3 would be confusing.

**Comment by cryos** [comment]
Sure, and so I would propose:

* Parent Dataset (e.g. a Tiltseries)
    * Transform 1 
    * Transform 2
    * Transform 3
        * Child Data A (e.g. a reconstruction from Transform 3)
            * Visualization A
    * Visualization 1
    * Visualization 2

As the least confusing solution there, where most people can understand a tree structure, or something I was a little biased towards making it clearer the modules were all children of the operators applied before them:

* Parent Dataset (e.g. a Tiltseries)
    * Transform 1 
    * Transform 2
    * Transform 3
        * Child Data A (e.g. a reconstruction from Transform 3)
            * Visualization A
        * Visualization 1
        * Visualization 2

**Comment by cquammen** [comment]
* Dataset
    * Transform 1
    * Transform 2
        * Segmentation A
            * Transform A
            * Transform B
            * Visualization A
    * Visualization 1
    * Visualization 2

was my initial proposal, which I think matches your first proposal above, so I don't need any convincing. Should we wait until @Hovden weighs in before changing the implementation?

**Comment by cryos** [comment]
No, I think that is one of the options that will cause the least surprise, and be most intuitive under the current pipeline model. As it doesn't affect existing features I think we can proceed on this path for now, as with anything once we have it and are working with it then we may want to make further adjustments. I missed some of the mid-steps in this conversation, but think maintaining the connection of the data producer is important.

**Comment by cquammen** [comment]
Agreed. I'll make that change, which shouldn't be too hard.

**Comment by cquammen** [comment]
I consider this done. Please open additional issues for related bugs.
