### ISSUE TITLE
Cube axes have been removed from ParaView

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#393]
When building against latest ParaView, this warning message appears:

ERROR: In /Users/cory.quammen/src/paraview-tomviz/ParaViewCore/ServerManager/Core/vtkSMNamedPropertyIterator.cxx, line 151
vtkSMNamedPropertyIterator (0x7fd5392c0090): In proxy GeometryRepresentation no property named CubeAxesVisibility was found.

Warning: In /Users/cory.quammen/src/paraview-tomviz/ParaViewCore/ServerManager/Core/vtkSMProxy.cxx, line 2078
vtkSMPVRepresentationProxy (0x7fd538c23680): Missing property with name: CubeAxesVisibility on GeometryRepresentation

CubeAxes were removed from ParaView in commit [a12e85548a1442bdf4d57da7da1937d0b1d234f3](http://www.paraview.org/gitweb?p=ParaView.git;a=commit;h=a12e85548a1442bdf4d57da7da1937d0b1d234f3)

This should probably be replaced with the Axes Grid.

**Comment by cryos** [comment]
Yes, we should get this fixed before the new release. We need to move ParaView forward for some Qt 5 fixes/updates but still want support for axes.

**Comment by cquammen** [comment]
I'm happy to do it. Shouldn't be too much work.

**Comment by cryos** [comment]
Thanks @cquammen!

**Comment by cquammen** [comment]
Merged in PR #395
