### ISSUE TITLE
"Show Axis Grid" makes volume render disappear

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#394]
The axis grid doesn't appear compatible with the volume visualization (tested on OSX)
1) Load dataset and Volume visualization
2) In top menu select "Tools > Show axis grid"
The volume render will disappear / only appear on surfaces of bounding box. After turning off "Show axis grid" volume render remains broken.

**Comment by cquammen** [comment]
Bug confirmed.

**Comment by cquammen** [comment]
This bug also exists in ParaView master.

**Comment by cquammen** [comment]
This is apparently a regression since the 5.0.1 release. I will file a bug for ParaView.

**Comment by cquammen** [comment]
Bug filed: http://www.paraview.org/Bug/view.php?id=16111

**Comment by cquammen** [comment]
Bug in ParaView is now fixed: https://mail.google.com/mail/u/0/#all/1549b1da814fc49f

**Comment by cquammen** [comment]
ParaView's VTK version is being bumped to get the new fix:

https://gitlab.kitware.com/paraview/paraview/merge_requests/777

**Comment by cryos** [comment]
We will have to hold off until we have the rendering issues on Mac figured out to move ParaView/VTK forward for this (or any other) fix.

**Comment by mathturtle** [comment]
As soon as the Linux build on the new build machine finishes and I can test it, I will move ParaView forward.

**Comment by cryos** [comment]
Any update on this issue?

**Comment by cquammen** [comment]
Yes, this is fixed in ParaView master. Not sure if it is in 5.1

**Comment by cryos** [comment]
No, I meant more as in did anyone verify the latest Tomviz build/move ParaView forward, I know it is fixed in ParaView master, @mathturtle was looking at this and I would like to close the issue once verified.

**Comment by cquammen** [comment]
Ah, sorry, no I haven't verified in tomviz.

**Comment by mathturtle** [comment]
I tested it locally on Linux and OSX after I bumped ParaView last week and it was fixed.  I thought I'd commented on here, but apparently not.

**Comment by Hovden** [comment]
Great. We can close #394

Can you look at #421  since the axis grid should be associated with one particular bounding box, not all datasets.
