### ISSUE TITLE
Make "Output Messages" Embeddable as a Panel in Main Program ux

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#396]
The "Output Messages" often gets lost behind the main program or pops up and has to be moved out of the way. This could be avoided by allowing the output window to be embeddable. Also, by having the output window always visible the user is much more likely to see output messages. I would probably default to embedding it as a small box in the lower right of the UI.

This request is similar to #94, which @mathturtle reported as non-trivial.

**Comment by cquammen** [comment]
This is something we want to do in ParaView as well. It isn't on the feature list for 5.1 or 5.2, though, so I'm not sure when to expect it.

**Comment by Hovden** [comment]
Can we throw it a couple upvotes?

**Comment by cquammen** [comment]
I'll talk to one of the developers :-)

**Comment by Hovden** [comment]
Any feedback from ParaView on this?

**Comment by cquammen** [comment]
Alas, this will likely not make it into the 5.1 release, which is coming out in the next month.

**Comment by Hovden** [comment]
My thought is this could provide a temporary solution to the progress bar problem. When python routines are running, we can write terminal output progress bars and messages that are visible to the user. This way it doesn't seem like tomviz has frozen when long python processes are running.

**Comment by mathturtle** [comment]
@Hovden It won't work.  Unless you expect them to run tomviz from a terminal where they can see the output in the terminal.  And since few of our users are on Linux, that is probably unrealistic.  The GUI (including the output window) can't update during the python routine since the python never passes control back to it for event processing.  To do anything about the progress bar problem we have to move python to a background thread.

**Comment by Hovden** [comment]
I see.

**Comment by cquammen** [comment]
I have made some progress on this feature on the ParaView side. Docking the output window (and python console) is now possible. The remaining issue is ironing out problems with test images generated by the ParaView tests. Once that is finished, I have a branch for tomviz with necessary changes to use the newly dockable windows.

**Comment by Hovden** [comment]
@cquammen if this is ready to merge? If this will take significant additional effort, we should change it's priority.

**Comment by cquammen** [comment]
No, it is not ready yet, and will take some effort on the ParaView side.

**Comment by cquammen** [comment]
This is done now and available in a nightly as of a couple days ago.

**Comment by Hovden** [comment]
This is nice. Can we have the "show full messages" box checked by default?

**Comment by cquammen** [comment]
Sure. See here: https://github.com/OpenChemistry/tomviz/pull/1232
