### ISSUE TITLE
Interactive Crop Box appear at incorrect position when viz object has been shifted

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#407]
1) open a dataset, and shift the visualization using the "hand on box" icon.
2) crop dataset

The crop box will appear where the dataset originally was placed, not where it is has been shifted to.

Also applies to Clear Volume Box

**Comment by mathturtle** [comment]
I don't even have to test it... as soon as you pointed it out, I knew it was broken.  Those features don't know about each other.  I'll put up a fix.
