### ISSUE TITLE
Minor cosmetic issue: Pipe line tab name

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#418]
A **very** minor, cosmetic issue. The name of the Pipe lines tab (directly above the word Visualization) has an extra '&' symbol. It currently reads Pipe&lines. See attached screen shot.

![clipboard02](https://cloud.githubusercontent.com/assets/15657108/15980331/a231bfd6-2f1f-11e6-9113-fde602a8b461.jpg)

**Comment by cryos** [comment]
That is strange, and should not be. I will look into it.

**Comment by mathturtle** [comment]
I have checked this while debugging other things on Linux and OSX and haven't found a system that reproduces it yet.

**Comment by Hovden** [comment]
It doesn't appear in last weeks nightly build for OSX

**Comment by ercius** [comment]
I've seen it on Windows for a few releases but never brought it up because
it's so minor. I'll check it on a Mac tomorrow.

**Comment by cryos** [comment]
Need to verify on latest builds

**Comment by Hovden** [comment]
Not present on OSX.

**Comment by mathturtle** [comment]
I can still reproduce this on Windows.  Apparently a Windows bug.  I'll see what I can find.

**Comment by mathturtle** [comment]
So this may be a bug in Qt.  I found [this](https://bugreports.qt.io/browse/QTBUG-12547#) which was closed due to Qt 4.x end of life.  It is possible that the inconsistent behavior for Windows still occurs in Qt5.

**Comment by mathturtle** [comment]
Reported to Qt: https://bugreports.qt.io/browse/QTBUG-54485
