### ISSUE TITLE
Retrieve data from slice and/or orthogonal slice

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#419]
I often want to export the data displayed in the orthogonal slice or (more importantly) the arbitrarily angled slice module as a 2D image (or data set). Is there a way to do this currently or to access the slice data in the tomviz python console? It would be very useful for measurements if this was possible including some sort of way to determine the scale of the data (pixel --> nanometer calibration).

**Comment by Hovden** [comment]
I don't think there is a good way of doing this other than the screen shot.

It's not a good solution, but it wouldn't be hard to write a python routine that writes out an orthogonal slice.

Implementation of scale (pixel -> nm) is long overdue. We should prioritize this.

**Comment by ercius** [comment]
scipy.interpolate has griddata() (unstructured data) and RegularGridInterpolator(). I have it working in 2D but not 3D yet.

It would be great to be able to directly correlate the point/normal values for a non-orthogonal plane in tomviz to where the plane lies within the 3D volume. This is already possible with the orthoSlice since the "slice" value is in volume coordinates. The point displayed in the non-ortho slice properties is in "space" coordinates and not useful outside of tomviz or in a custom tomviz script.

Also, implementing scale (pixel --> nm) and some way of measuring distances is becoming an important missing feature in tomviz. For quantitative work beyond pretty pictures this is a must.
