### ISSUE TITLE
Kill / Abort function for python

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#420]
If a python function hangs for too long, the user should be able to abort.

**Comment by cryos** [comment]
This is surprisingly hard to accomplish. The Python code running in a background thread would need to check for an aborted flag in its tight loops, or we would need to run it in a background process which we could kill. Easiest option is going to be moving to a background thread and making the Python code cooperative.

**Comment by Hovden** [comment]
Could we call a cancel gui or progress bar within Python?

**Comment by cquammen** [comment]
We have cancelling functionality for some transforms. Can we close this issue?

**Comment by yijiang1** [comment]
Yes I think so.
