### ISSUE TITLE
Axis grid should be part of "Outline"

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#421]
The axis grid and its properties should be part of the"outline" visualization module. 

The axis ticks should then match the outline colors. This will solve the problem of white axis ticks on a white background.

Also, it will allow us to add options to the axis grid, like displaying the actual scale (e.g. in nanometers)

This may also be a better approach in Paraview.

**Comment by bdalevin** [comment]
Adding an option to display actual scale in nanometers would be a great addition to the software. It would be particularly helpful for generating figures for publication.

**Comment by cryos** [comment]
This is now the case when the axis grid feature was refactored.
