### ISSUE TITLE
Crashes when most new View panels are created.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#424]
Most View Panel Modes crash:
1) Open tomviz and split view panel
2) Select any view panel other than "Render View"

Solution:
Disable all other view modes and automatically create "Render View" when a panel is split.

**Comment by ercius** [comment]
Do any of the other render modes work?

**Comment by cryos** [comment]
There is a missing null check that should be fixed, that is causing the crash. I think we should improve the dialog too, but am hoping to make some of the other views useful. The code currently assumes all views will have an axes grid, get the proxy, and then use it without checking for null. Many other views do not have the axes grid.

**Comment by cryos** [comment]
#425 fixes the crash, we will look into a better solution to address other issues.

**Comment by mathturtle** [comment]
Didn't #427 finish fixing this?

**Comment by Hovden** [comment]
No longer crashes. I'm ok with closing this issue.
