### ISSUE TITLE
DataPropertiesPanel doesn't update when switching between datasets

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#426]
1) Load two different datasets.
2) Select one of them (not a module) so that the data properties panel is shown
3) Select the other dataset -> the data properties panel still displays the other dataset's information

This only happens when clicking back and forth between the datasets.  If you click on a module in between, then it updates correctly since hiding it and re-showing forces a new paintEvent call which updates the UI.

@cryos

**Comment by cryos** [comment]
Ah yeah, I see it, I will see what I can do - I think we are missing a signal slot connection on data source changed to the properties panel.

**Comment by mathturtle** [comment]
This is fixed by #438.
