### ISSUE TITLE
Add Colormap Buttons to Histogram

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#428]
Histogram UX should have buttons to change colormap. Most of this has already been addressed by @cryos . Just needs the "invert contrast" button.

Also making this issue to keep track of features.

**Comment by cryos** [comment]
I think #430 completes the changes we wanted (for now at least).

**Comment by Hovden** [comment]
Great. Merge and close?

**Comment by cryos** [comment]
Yes, let me know if you think of anything else.
