### ISSUE TITLE
Manual image alignment double-counts shifts

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#434]
If the user uses the manual alignment tool to align the data, then clicks "ok" when finished, tomviz applies the shifts to the data and ALSO keeps the shifts in the manual alignment box.  Then, if they open their alignment operator again to update it, tomviz applies the saved shifts on the already shifted data, making the alignment incorrect.

To work around this the user can build up a stack of manual alignment operations, which is fine, but this issue defeats the purpose of having the alignment operator be editable the way it is.

**Comment by mathturtle** [comment]
You're right, it is broken.  The first set of shifts are the only ones applied if you go back and edit the shifts it doesn't work.  I'll look into it.

**Comment by mathturtle** [comment]
I've pushed a pull request that should fix this (I merged another related change last night for a bug I found when testing this).  @ElliotPadgett can you and/or @yijiang1 test this and see if it fixes what you were seeing please?

**Comment by ElliotPadgett** [comment]
I can test after it comes out in the nightly build.

**Comment by mathturtle** [comment]
Ok, so I tried a different dataset and now I see what you are talking about.  The fix in #437 addresses a related issue, but doesn't address this.  Working on a fix for this now.

**Comment by mathturtle** [comment]
@ElliotPadgett #440 should fix this issue.  Sorry about the confusion earlier.

**Comment by yijiang1** [comment]
@ElliotPadgett I've tested and the bug is fixed now.

**Comment by ElliotPadgett** [comment]
Tested again.  This is now fixed
