### ISSUE TITLE
Image should not freeze when "stop" button is clicked in manual alignment widget

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#439]
In manual alignment widget, the image cannot be changed when the "stop" button is clicked.
We should allow this to happen. The "stop" button should only stop flashing two images.

**Comment by mathturtle** [comment]
Good catch.  Try out the change in #441 and see how that works.

**Comment by ElliotPadgett** [comment]
This looks good now in today's nightly build.
