### ISSUE TITLE
Colormap editor tab in histogram panel

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#44]
In order to make the colormap editor more accessible and useable add a colormap to the histogram panel. Tabs will allow users to jump between the histogram and the colormap editor.

**Comment by Hovden** [comment]
This might also simply be a button. Find a solution that balance the quality of UX design with the difficulty to execute.

**Comment by cquammen** [comment]
Here is the current implementation that enables one to change the opacity function.

![image](https://cloud.githubusercontent.com/assets/360056/13957083/856d72ba-f021-11e5-99bd-83767884119a.png)

I would appreciate your feedback.

Will you want to be able to set colors in the color map?

**Comment by cquammen** [comment]
What do you think of the editor on the top, @Hovden?

**Comment by Hovden** [comment]
I've been having trouble building paraview since tomviz moved up to Qt5. The cmake files do not know how to locate my local Qt5: " By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but CMake did not find one."

Working to resolve this issue so I can test your contribution to the histogram panel.

**Comment by cquammen** [comment]
With Qt4, you would point to your qmake executable and all the other CMake variables would be filled in.

With Qt5, you need to set a couple variables:

`Qt5_DIR`
`Qt5Core_DIR`

On my Mac, `Qt5_DIR` is set to `/Users/cory.quammen/bin/qt5.6/lib/cmake/Qt5` and `Qt5Core_DIR` is set to `/Users/cory.quammen/bin/qt5.6/lib/cmake/Qt5Core`

**Comment by cquammen** [comment]
Once you set these CMake variables, the other should be filled in automatically.

**Comment by Hovden** [comment]
There are a lot of .cmake files in the Paraview build directory. In which one should these qt5 variables be set?

**Comment by cquammen** [comment]
These variables should be set in CMake during configuration, not in any .cmake files in the build directory. I'm not sure how you configure the build with CMake - if you use cmake at the command line and pass it variables on the command line, or if you use cmake-gui or ccmake to set the variables through a UI. However you specified the ParaView_DIR directory is how you should specify the Qt5 variables.

**Comment by Hovden** [comment]
I see. cmake-gui doesn't install with brew, but I can use ccmake, however the location of the correct qt5 sub-directories are not as transparent for my Brew install (I think they are located somewhere in /usr/local/Cellar/qt5/5.6.0/ ).

I can tinker with this more, but to give immediate feedback based on the screenshot:
The opacity curve editor overlayed with the histogram is a smart approach. Does it change for each objects unique colormap? If so, I think you should merge. That way I can get a couple people to try it out (including myself).

**Comment by cquammen** [comment]
Indeed, look under /usr/local/Cellar/qt5/5.6.0/lib/cmake. You should have Qt5, Qt5Core, etc. directories under there.

Yes, the opacity function is unique to each color map, so you may have separate opacity functions for each object. It is really just another view/interface to the opacity function displayed in the "Mapping Data" section in the Properties panel.

I am going to work on color editing controls for the color map now before turning it over to @cryos for review. I should have it wrapped up today.

**Comment by cquammen** [comment]
Pull request #356

**Comment by cquammen** [comment]
@cryos Should we close this issue since the PR was merged? Or wait for additional feedback?

**Comment by cryos** [comment]
No, we can close it and open fresh issues if there is a need for further improvements.

**Comment by mathturtle** [comment]
If you move/click on a color/opacity control point in the new histogram/colormap editor, then one of the control points will stay selected from then until the program closes.  Click outside the widget? Nope, it's still pink.  Delete the control point?  One of the others is now selected.  Should this be a new issue or is this expected?  The built-in PV one seems to work similarly but it only has one point selected between the color control points and the opacity control points.

The only way I've found to unselect them is to change to a colormap that has more control points, select the end one and change back [related: good job guarding your array accesses :)].  This seems to work since the selected index is not valid, if you switch back the end one is selected again.

**Comment by cquammen** [comment]
If we really need the points to be unselected, I could probably make it so. As long as it doesn't cause problems, I'm inclined to leave the behavior as it is.
