### ISSUE TITLE
tomviz crashes when generate tilt series from a tilt series

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#443]
1. Open tomviz and load a dataset.
2. Click "Generate Tilt Series" in Tomography menu. Use default parameters.
3. Open the python script for  "Generate Tilt Series" in the data transform pipeline.
<img width="1280" alt="screen shot 2016-06-22 at 5 16 50 pm" src="https://cloud.githubusercontent.com/assets/13088588/16284000/362ef646-389d-11e6-93ac-a4d90ae1b2ac.png">

4. Click "OK" and tomviz crashes. 
This is because the dataset is already marked as a tilt series and the script calls "utils.mark_as_tiltseries(dataset)" again.

I still think we should treat "Generate Tilt Series" or reconstruction functions differently from regular data transforms. They should just clone the results to a new dataset when finish.

**Comment by ElliotPadgett** [comment]
I agree on the issue of cloning the data.  This makes much more sense from the users point of view.  A tilt series and a reconstruction are totally different types of objects and it doesn't make sense to convert one into the other.

**Comment by mathturtle** [comment]
The crash appears to have been fixed by one of my recent changes (I suspect #440 or #446).  But we should discuss what to do about the other point you raised.

**Comment by Hovden** [comment]
If crash is fixed, we can close this. 

The other point raised is contained in #392

**Comment by yijiang1** [comment]
OK. The bug mentioned in this issue is fixed now.
