### ISSUE TITLE
Orthoslice slider is too coarse

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#449]
When looking at a 512X512X512 reconstruction with an orthoslice visualization the slider takes steps of about 10.  I often want to scroll around in 1 pixel steps around a region of interest, and typing the value is not very convenient.  Is it possible to make the sider have finer control?

**Comment by ercius** [comment]
I think you can use the keyboard arrow keys to take single steps once the
slice slider bar is clicked.

**Comment by Hovden** [comment]
I cannot adjust with the keyboard on OSX. Maybe other OS's treat it different. Keyboard adjustment would address this issue.

This may be an opportunity to also discuss improvement UX on the orthoslice:
<img width="306" alt="screen shot 2016-06-27 at 9 08 46 am" src="https://cloud.githubusercontent.com/assets/6197997/16380760/ee114ce4-3c46-11e6-9e89-30236f518541.png">
1) "Slice Direction" should read "Direction"
2) Value box should be no larger than 5 characters.

This will make more space for the slider and look better. I know this is may be a Paraview request, but it should be easy and beneficial.

**Comment by mathturtle** [comment]
This should be fairly simple now.  I'll just do the same thing I did for the Contour module for the orthoslice.

**Comment by Hovden** [comment]
bump (I'm orthoslicing frequently this week)

**Comment by mathturtle** [comment]
Can this be closed now?

**Comment by ElliotPadgett** [comment]
Still an issue for me. I'm on Mac, and I have a ~400 voxel long dataset and the orthoslice slider jumps 5 slices at a time and there's no easy way to move it with the keyboard except typing in the number.

**Comment by mathturtle** [comment]
Hmmm. I'll try this on a mac and see if it is different there.

**Comment by mathturtle** [comment]
Mac is different.  The slider jumps to where you click on it.  I can make it get keyboard focus when you click on it and then you will be able to use the arrow keys to adjust it.

**Comment by ElliotPadgett** [comment]
Great.  This solves it!
