### ISSUE TITLE
Merge Data Transforms and Visualization Modules Pipeline

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#45]
Merge the datatransform pipeline and the visualization modules pipeline.

The data transforms will appear as objects below the data icon and new transforms will be added below the previous transform. Data transforms will be indented once.

 The visualization modules will appear after the data transforms and indented twice.

**Comment by cryos** [comment]
Sorry about this, I really wanted to get this in but the move to Qt 5 took a lot more time than planned.

**Comment by Hovden** [comment]
No worries. This also ties in with the recent "cached" / "cached transforms" discussed in #392 .

**Comment by cryos** [comment]
![image](https://cloud.githubusercontent.com/assets/42214/16630668/6e85e24c-4389-11e6-9c69-ea4b86766b2b.png)

**Comment by Hovden** [comment]
Looks nice.

Does the title take on the python name title so it can be changed (this is the current behavior)?

Users might accidentally click the x's. Not sure if there is a clean way to handle that scenario.

**Comment by cryos** [comment]
The names are whatever has been defined, I was thinking about the accidental clicks too, I don't see a clean way, we can remove them, but wanted to give you a preview of a working version. I am working on restoring other features such as double clicking on items to edit operators, context menu, etc.

**Comment by Hovden** [comment]
Moving the X's a little to the left so they do not align with the eyes would reduce accidental clicks. It would improve UI but aesthetically it would look a little worse.

**Comment by Hovden** [comment]
Another thought, adding an global eye to the dataset that turns on or off all the eyes on that dataset could help. I suspect that I will accidentally click an X when I am clicking on and off all of the eyes.

**Comment by cryos** [comment]
I am going to mark this as closed, they are now merged. We have some additional bugs for new issues, and we can certainly revisit the UI, layout, etc in other issues as is happening now.
