### ISSUE TITLE
Save as PNG does nothing

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#450]
When I try to save a tilt series or a reconstruction as a PNG the program closes the save dialog as if it were successful but does not produce a file and does not show any error.  I don't know if you can even have image stacks in PNG format, but there should at least be an error message if no saved file is produced.

**Comment by Hovden** [comment]
Yep. This happens on my OSX machine.

**Comment by ercius** [comment]
PNG does not allow for stacks. I suggest removing PNG as an output type for
data.

**Comment by mathturtle** [comment]
@utkarshayachit @cquammen We are directly using ParaView here, is this a problem with ParaView's implementation of the PNGWriter or is it incorrectly reporting which readers support the data type?  Or something else?  I can fairly easily search/replace the filetype containing PNG from the valid file types passed to the dialog, but is that the right way to go here?

**Comment by cryos** [comment]
I agree with @ercius, we should just remove PNG as it does not support the type of output required.

**Comment by Hovden** [comment]
Also, the JPG does not save a stack, but appears to save the first slice. If there is not stack support we should also remove jpg. Not to mention jpg is a questionable format for science.

**Comment by cryos** [comment]
Agreed, JPEG has no stack support I am aware of.
