### ISSUE TITLE
Isosurface render hangs easily when typing in box

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#452]
When using the isosurface visualization module by typing in the value box it easy to cause the program to hang because the visualization tries to update before the user is finished typing.

If the user tries to type in the box and either uses the backspace key or highlights the value and types a new one the program tries to update immediately and will try to draw an isosurface at a very low value with too many triangles, and the program hangs.  This could be fixed by only having it update when the user is done typing in the box.  Is it possible to do that?

**Comment by cryos** [comment]
Agreed, I pointed this out when it was first added and want to make more customized interfaces where we have more granular control over when things happen. There is some work in progress, and we should hopefully have it ready soon.

**Comment by mathturtle** [comment]
My branch to update the Contour UI (#453) fixes this as far as I can tell.  I made it wait until the focus leaves the box (or the user presses Enter) to run the update.
