### ISSUE TITLE
Glitchy zoom on Mac

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#454]
The two finger zoom on mac is glitchy. This has been true for some time, but I noticed a feature in the glitch. When it starts and stops the zoom action (touching the trackpad with two fingers) it will make a two discrete steps of a zoom out (one step upon touching, one step upon releasing). I'm wondering if this behavior can be easily fixed by not having it zoom out upon touch and release. This also explains why it is easy to zoom out but very hard to zoom in.

**Comment by cquammen** [comment]
@Hovden Are you swiping with two fingers, with the two fingers moving together? Or are you spreading your fingers apart to zoom in and pinching to zoom in?

In either case, my zooming in and out seems to work as expected on my MacBook Pro. Two finger swiping is a little jerky, but if I press down to make the track pad click, zooming is much smoother.

Another way to zoom in/out is to hold down the Ctrl key while moving one finger down/up on the track pad. We could potentially disable two-finger zooming if it is not acting consistently across different Mac models.

**Comment by Hovden** [comment]
That's right. Clicking or using the ctrl key behaves normally. But placing two fingers and swiping up or down doesn't work properly. For large datasets, it can become problematic.

**Comment by ElliotPadgett** [comment]
I have similar issues with scrolling on my Mac desktop "magic" mouse.  It
jumps in big discreet steps and sometimes takes steps back from whatever
direction you are trying to go it.  Ctrl-click zooming is well behaved.

**Comment by ElliotPadgett** [comment]
This is working better for me now.  @Hovden what about you?

**Comment by Hovden** [comment]
Yeah. It's pretty good.
