### ISSUE TITLE
Crash when loading a transform after tomographic reconstruction

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#459]
This happens on latest binary.
1. Open tomviz, load a dataset.
2. Mark it as tilt series. Do a reconstruction (e.g. weighted back projection).
3. Now, do a python-based data transform (e.g. rotate).
4. Double-click the transform in pipeline, and tomviz crashes.
<img width="263" alt="screen shot 2016-06-30 at 4 04 03 pm" src="https://cloud.githubusercontent.com/assets/13088588/16502428/5df439b2-3edc-11e6-972f-93611c837daa.png">

Interestingly, tomviz works fine if the tilt series is created by the "Generate Tilt Series" function.

**Comment by mathturtle** [comment]
This should be fixed by #501.

**Comment by Hovden** [comment]
When double clicking, it reruns all the transforms above it before displaying the python code.

**Comment by mathturtle** [comment]
It should do that now... part of the fix in #440, we have to recompute the data just before the operation before showing the operation dialog.  At least in some cases like the alignment widget.... I think I might be able to skip it if the dialog doesn't need it.  Let me try that.

**Comment by mathturtle** [comment]
So that wasn't very hard and it seems to work.  It will help with perceived responsiveness of the application too. I've made it a little bit better by not recomputing if it isn't used.  I added a new commit to #501 to add this.

**Comment by Hovden** [comment]
This issue is fixed in latest OSX build.
