### ISSUE TITLE
Make module and data properties context aware

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#46]
The module and data properties as implemented are confusing, it is not clear which module the module properties refer to, and the connection to the data is loose. We always have a selected data item or module - show an integrated properties dialog that shows the properties for the highlighted item.

**Comment by mathturtle** [comment]
@cryos Do you want me to take a stab at this for 0.6.1?

**Comment by cryos** [comment]
Sure, that would be great.

**Comment by mathturtle** [comment]
Making a new panel that shows one or the other based on the selection isn't too hard, but I don't know exactly what you were planning as far as merging the two.  Which things should be visible in both cases?

**Comment by Hovden** [comment]
There will be a single panel that uses the pipeline for context. When a visualization module is selected in the pipeline, the current  "module properties" panel is displayed in the panel. When a data module is selected in the pipeline, the current "data properties" panel is displayed in the panel.

This was our thought toward reducing the confusion of having a module and data properties panel.

If you have UX ideas to further help the user understand how they are modifying data and module properties, we should try it out.

**Comment by cryos** [comment]
This patch has the expected behavior for me here - please take a look and let me know if you spot any issues.

**Comment by cryos** [comment]
Closing this out, as I said in the pull request we may want to revisit panels in the future but I think this change makes it more obvious what you are looking at and saves space only having one of the other panels visible at any given time.
