### ISSUE TITLE
Add pad data transform

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#464]
We should include a data transform to pad the data with zeros or the edge value to increase the size of the data.  Sometimes this is useful to avoid having part of the object going out of the field of view during shift alignment.

**Comment by Hovden** [comment]
Numpy has a pad image routine: numpy.pad()
http://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html

**Comment by yijiang1** [comment]
@ElliotPadgett @Hovden Should I set the default pad size to 0? Or do you prefer some other numbers?

**Comment by Hovden** [comment]
Zero is fine if you also include some of the other padding options.
