### ISSUE TITLE
Orthogonal slice does not update when the slice No. is changed in property panel

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#468]
This may be related to #453 .
When I change the slice number in property panel
<img width="299" alt="screen shot 2016-07-08 at 4 18 19 pm" src="https://cloud.githubusercontent.com/assets/13088588/16700366/a441edf0-4527-11e6-9c8e-67fb61557559.png">

The the slice in the "RenderView" window no longer update automatically.

**Comment by Hovden** [comment]
Yep. Orthoslice is not moveable on recent release (OSX).

**Comment by ercius** [comment]
Same on Windows 10 in 0.8.0-110. I also get this error message:
`QAbstractItemModel::endInsertRows:  Invalid index ( 2 , 0 ) in model tomviz::PipelineModel(0x219d2b5f830) (:0, )`

**Comment by cquammen** [comment]
The error message is not exclusive to the orthogonal slice: see #477.

**Comment by mathturtle** [comment]
This should be fixed (not the error message, the bug).

**Comment by ercius** [comment]
Orthoslice updates properly using the latest binary on Windows 10.

**Comment by Hovden** [comment]
Yep. Good on OSX too.
