### ISSUE TITLE
Make view properties a dialog

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#47]
Move the view proprties to a dialog as this is confusing, and doesn't seem like a good fit for a panel.

**Comment by mathturtle** [comment]
This is already in a dock widget so that it can be dragged out into its own "dialog".  Would making the widget floating by default be sufficient or do we want a proper dialog?

**Comment by mathturtle** [comment]
The paraview changes to allow a separate dialog are in: https://gitlab.kitware.com/paraview/paraview/merge_requests/155

**Comment by cryos** [comment]
I think we want a dialog for this, yes.

**Comment by mathturtle** [comment]
We also need this change: https://gitlab.kitware.com/paraview/paraview/merge_requests/157
