### ISSUE TITLE
Scientific notation on Histogram y axis

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#470]
Scientific notation should begin at 10000 so it reads 1e+4

This will reduce whitespace on the left side.
<img width="89" alt="screen shot 2016-07-10 at 8 29 47 pm" src="https://cloud.githubusercontent.com/assets/6197997/16717111/21518eca-46dd-11e6-848e-70d0a455949e.png">

**Comment by cquammen** [comment]
Does https://github.com/OpenChemistry/tomviz/pull/476 sufficiently address this issue?

**Comment by Hovden** [comment]
I think so. We will wait to see if people complain about scientific notation. I think it looks better though.
