### ISSUE TITLE
Add single color selection for isosurface contour

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#473]
It would be very convenient to have an interface for selecting a single color for an isosurface rendering.  I think this is most often the preferred method for setting up an isosurface. @mathturtle

**Comment by ElliotPadgett** [comment]
This looks good.  My only comment before closing is that it would be nice if the "Use Solid Color" check box was next to the control to pick the color.  Right now one is at the top and the other at the bottom of the properties panel.

**Comment by ElliotPadgett** [comment]
Also, this may be connected to #565 but the color selected for the contour doesn't get saved and restored in state files.  It remembers that you checked the solid color box (and the opacity) but it reverts the color to white.

**Comment by ElliotPadgett** [comment]
Solid color for contour is now saved, although the icon reverts to showing white instead of the actual color.

**Comment by cryos** [comment]
We should fix that before closing this issue.

**Comment by mathturtle** [comment]
@ElliotPadgett Can you see if #731 fixes this?

**Comment by yijiang1** [comment]
Yes this is fixed by #731 .
