### ISSUE TITLE
Qt error messages when loading image

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#477]
The following error messages are reported in the latest master (439aa1d0f71d92f6c323a1068821275f35bb3391) when loading an image file:

    QAbstractItemModel::endInsertRows:  Invalid index ( 2 , 1 ) in model tomviz::PipelineModel(0x7fa57dd04d80) (:0, )
    QAbstractItemModel::endInsertRows:  Invalid index ( 2 , 0 ) in model tomviz::PipelineModel(0x7fa57dd04d80) (:0, )

A cursory look in `PipelineModel.cxx` did not turn up anything obvious.

**Comment by cryos** [comment]
Yeah, I see it, and will take a look at it soon.

**Comment by cquammen** [comment]
I think I have this bug fixed in #550.

**Comment by cquammen** [comment]
Bug fix merged.
