### ISSUE TITLE
Typing in boxes in tilt axis alignment GUI

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#479]
The tilt axis alignment GUI  immediately updates the reconstructions when typing in any input box. This becomes tedious when for example you want to set the axis shift value to 20. It first shifts to 2, recalculates, then shifts to 20 and recalculates.

Further, the <Enter> keyboard button is connected to the the "Transform" button. I often accidentally press enter when trying to update a value therefore quitting the GUI.

I suggest the enter button is used by the user to update the input box values and clicking the "Transform..." button will exit the GUI. Pressing the arrow buttons next to the input boxes should immediately update the GUI images though.

**Comment by cryos** [comment]
@mathturtle didn't you address this issue in a recent pull request?

**Comment by Hovden** [comment]
No, it was only addressed for the cropping in  #486

The fix used there was:
-  this->connect(ui.startX, SIGNAL(valueChanged(int)),
 +  this->connect(ui.startX, SIGNAL(editingFinished()),

**Comment by cryos** [comment]
Ah, OK - then @mathturtle can you look at adding a similar change there, and see if you can spot anywhere else the same pattern might have been inadvertently used.

**Comment by cryos** [comment]
This should hopefully be resolved, please reopen if not.
