### ISSUE TITLE
Color Map Change in Manual Alignment

### ISSUE THREAD

**Issue by thebner15** [OpenChemistry/tomviz#482]
Would be nice to have ability to change color map within the same window while aligning a tilt series.

**Comment by ercius** [comment]
Also would be useful to be able to control the contrast/brightness of the images.

**Comment by Hovden** [comment]
Yep. We might have to make a separate issue for that one. There is a simple solution for this colormap issue.

**Comment by Hovden** [comment]
Should be solved in #485
