### ISSUE TITLE
Crash when Spread Sheet View is open and state is saved

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#488]
Steps to reproduce:

- launch tomviz
- split the view
- click on SpreadSheet View
- File -> Save State

tomviz crashes with

    * thread #1: tid = 0x2025ea, 0x0000000105628577 libvtkPVServerManagerCore-pv5.1.1.dylib`vtkSMRemoteObject::GetGlobalIDAsString(this=0x0000000000000000) + 23 at vtkSMRemoteObject.cxx:83, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x48)
        frame #0: 0x0000000105628577 libvtkPVServerManagerCore-pv5.1.1.dylib`vtkSMRemoteObject::GetGlobalIDAsString(this=0x0000000000000000) + 23 at vtkSMRemoteObject.cxx:83
       80  	//---------------------------------------------------------------------------
       81  	const char* vtkSMRemoteObject::GetGlobalIDAsString()
       82  	{
    -> 83  	  if (!this->GlobalIDString)
       84  	    {
       85  	    std::ostringstream cname;
       86  	    cname << this->GetGlobalID();

Stack trace is

    frame #0: 0x0000000105628577 libvtkPVServerManagerCore-pv5.1.1.dylib`vtkSMRemoteObject::GetGlobalIDAsString(this=0x0000000000000000) + 23 at vtkSMRemoteObject.cxx:83
    frame #1: 0x00000001000a6a2a tomviz`tomviz::ModuleManager::serialize(this=0x0000000100186270, ns=0x00007fff5fbfd4a0, saveDir=0x00007fff5fbfd418) const + 9274 at ModuleManager.cxx:367
    frame #2: 0x00000001000ecdb5 tomviz`tomviz::SaveLoadStateReaction::saveState(filename=0x000000013d0c2740) + 773 at SaveLoadStateReaction.cxx:113
    frame #3: 0x00000001000ec9d3 tomviz`tomviz::SaveLoadStateReaction::saveState() + 323 at SaveLoadStateReaction.cxx:63
    frame #4: 0x00000001000ec65c tomviz`tomviz::SaveLoadStateReaction::onTriggered(this=0x0000000114a09400) + 44 at SaveLoadStateReaction.cxx:50
    frame #5: 0x000000010298776d QtCore`QMetaObject::activate(QObject*, int, int, void**) + 749
    frame #6: 0x0000000101a7597f QtWidgets`QAction::activate(QAction::ActionEvent) + 303
    frame #7: 0x000000010298776d QtCore`QMetaObject::activate(QObject*, int, int, void**) + 749
    frame #8: 0x000000010298088c QtCore`QObject::event(QEvent*) + 156
    frame #9: 0x0000000101a7e576 QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294
    frame #10: 0x0000000101a80ec0 QtWidgets`QApplication::notify(QObject*, QEvent*) + 5648
    frame #11: 0x0000000102954594 QtCore`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
    frame #12: 0x00000001029551b4 QtCore`QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 596
    frame #13: 0x000000010f1345ce libqcocoa.dylib`QCocoaEventDispatcherPrivate::processPostedEvents() + 190
    frame #14: 0x000000010f134ea1 libqcocoa.dylib`QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 33
    frame #15: 0x00007fff8d6af881 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #16: 0x00007fff8d68efbc CoreFoundation`__CFRunLoopDoSources0 + 556
    frame #17: 0x00007fff8d68e4df CoreFoundation`__CFRunLoopRun + 927
    frame #18: 0x00007fff8d68ded8 CoreFoundation`CFRunLoopRunSpecific + 296
    frame #19: 0x00007fff93da4935 HIToolbox`RunCurrentEventLoopInMode + 235
    frame #20: 0x00007fff93da4677 HIToolbox`ReceiveNextEventCommon + 184
    frame #21: 0x00007fff93da45af HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 71
    frame #22: 0x00007fff89f74efa AppKit`_DPSNextEvent + 1067
    frame #23: 0x00007fff89f7432a AppKit`-[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
    frame #24: 0x00007fff89f68e84 AppKit`-[NSApplication run] + 682
    frame #25: 0x000000010f133d9f libqcocoa.dylib`QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2191
    frame #26: 0x0000000102950811 QtCore`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
    frame #27: 0x0000000102954c05 QtCore`QCoreApplication::exec() + 341
    frame #28: 0x000000010007c3c3 tomviz`main(argc=1, argv=0x00007fff5fbffa18) + 387 at main.cxx:57
    frame #29: 0x00007fff920565ad libdyld.dylib`start + 1
    frame #30: 0x00007fff920565ad libdyld.dylib`start + 1

**Comment by cryos** [comment]
Glad you spotted this, I thought we had found all the issues lurking with this. I want to actually start showing spreadsheet views soon too, once we have numeric data coming out of some of the filters.

**Comment by cquammen** [comment]
I actually caught it during an autosave - after 5 minutes (I think that's the time period) tomviz suddenly crashed when my SpreadSheet view was open. Critical bug to fix ahead of working with the spreadsheet view...
