### ISSUE TITLE
Fatal Crash when moving view panels

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#49]
The crash is recreated simply:

1) Open tomviz and split panel vertical.
2) Move the bottom panel to the top.

**Comment by mathturtle** [comment]
@Hovden does this still happen?

**Comment by Hovden** [comment]
Yeah. Recreating the error can be more easily done if you don't press any visualization button after you split the panel. Then you move it.

**Comment by mathturtle** [comment]
Ok, I can reproduce on our Mac, but on my Linux machine this doesn't happen.

**Comment by mathturtle** [comment]
@cryos Unfortunately on Mac you have to have admin access to run a debugger.

**Comment by mathturtle** [comment]
ParaView patch here:
https://gitlab.kitware.com/paraview/paraview/merge_requests/250

That took a lot longer than I thought to track down...

**Comment by mathturtle** [comment]
Utkarsh has an updated ParaView patch that also fixes this but addresses it at a more basic level:

https://gitlab.kitware.com/paraview/paraview/merge_requests/254
