### ISSUE TITLE
Loading state file does not show transforms in Pipelines

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#491]
Windows 10, tomviz-0.8.0-126... (newest nightly)

1) Apply a transform (invert is a clear transform to apply)
![image](https://cloud.githubusercontent.com/assets/15657108/16816897/081aea5e-48f5-11e6-8684-681f64fa067d.png)
2) Save a state file
3) Load the state file
4) Data loaded and transform is applied
5) Pipelines window shows no transforms and they are no longer editable
![image](https://cloud.githubusercontent.com/assets/15657108/16816924/237d75c8-48f5-11e6-954c-dffc8eab20c5.png)

**Comment by cryos** [comment]
I will look into it, this is likely related to the change I merged on Sunday.

**Comment by cryos** [comment]
Pull request #499 should address this issue, and in local testing does so. We will get it merged, and it should be in the nightly binaries tomorrow.

**Comment by cryos** [comment]
Closing as #499 addresses this, please reopen if you see any remaining issues.
