### ISSUE TITLE
Shift transform is very slow

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#495]
The uniform shift transform applied by the manual tilt axis alignment widget is unnecessarily slow. This is because the default spline order parameter in the ndimage.interpolation.shift() is order = 3.

We are using integer pixel shifts for manual alignment and so interpolation to apply these shifts is unnecessary. I suggest we set order = 0 to significantly improve performance.

**Comment by ercius** [comment]
I recently tested this and the shift is 5x faster with order = 0. I do not think that any data is lost if we only use integer pixel sized shifts.

**Comment by Hovden** [comment]
Ah, I see. I wasn't looking in the right place.

**Comment by Hovden** [comment]
In the file python/Shift3D.py

data_py_return = ndimage.interpolation.shift( data_py, SHIFT )

should become

data_py_return = ndimage.interpolation.shift( data_py, SHIFT, order=0 )

**Comment by cquammen** [comment]
Address in #521.

**Comment by cquammen** [comment]
#521 was merged into master.
