### ISSUE TITLE
Missing Adjust Camera feature in recent nightlies

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#502]
Above the render view for 0.8.0 there used to be a series of options for the camera and object selections:
![image](https://cloud.githubusercontent.com/assets/15657108/16931588/8c10191a-4cf6-11e6-97ae-57f37a5b264c.png)

The newest nightly removed most of these options:
![image](https://cloud.githubusercontent.com/assets/15657108/16931607/a4661866-4cf6-11e6-8163-142fd6d1e228.png)

I found the Adjust Camera feature (button to the right of 3D in above image) very useful:
![image](https://cloud.githubusercontent.com/assets/15657108/16931619/b64d2790-4cf6-11e6-8429-cdac31902c9a.png)

Can we make this available again? Maybe under the View menu alongside (or part of) "View Properties?"

**Comment by Hovden** [comment]
I agree. I noticed a lot of that was removed.

**Comment by cryos** [comment]
I simplified it, but perhaps too much. Feedback on which ones you would like back, or all of them? It is relatively simple to filter the list and whitelist what makes sense in tomviz.

**Comment by Hovden** [comment]
For 0.8.0 let's put back the "3D" and "Adjust Camera". I used those two. There might be other useful ones, but I haven't discovered a use (I will explore in detail later).

**Comment by cryos** [comment]
Closing as this was merged.
