### ISSUE TITLE
Pipeline does not allow collapsing but has arrows indicating it does

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#504]
The pipeline does not allow indented items to be collapsed, but the arrows next to it indicate that it does. We should either remove the arrows or allow indentation.

<img width="314" alt="screen shot 2016-07-19 at 8 13 36 am" src="https://cloud.githubusercontent.com/assets/6197997/16949462/ee0c5d4e-4d88-11e6-91fb-cf8ec21ae3f9.png">

**Comment by cquammen** [comment]
Would you like to be able to collapse them?

**Comment by cryos** [comment]
I think possibly, but there are some odd interactions if we allow that and I disabled it as I expand everything whenever the model changes. I think this one might have to wait. I think right now we should look at how easily they can be removed, and we can revisit this.

**Comment by cryos** [comment]
#526 clears this up for you I think, we can revisit interaction in the future.
![image](https://cloud.githubusercontent.com/assets/42214/17034501/ecc91656-4f50-11e6-9218-23ae45e9cefc.png)

**Comment by cquammen** [comment]
#526 was merged.
