### ISSUE TITLE
Display Problem when opening on Mac

### ISSUE THREAD

**Issue by VeraBeer** [OpenChemistry/tomviz#511]
When opening the newst Tomviz version on Mac it looks "glitshy", see screenshot.

![screen shot 2016-07-13 at 4 06 19 pm](https://cloud.githubusercontent.com/assets/20047722/16967766/be7fe672-4dd8-11e6-9624-ee44e147e4fe.png)

![screen shot 2016-07-13 at 4 11 43 pm](https://cloud.githubusercontent.com/assets/20047722/16967770/c24407f2-4dd8-11e6-97ac-baf1648cc4f8.png)

**Comment by Hovden** [comment]
Woah. Haven't seen that. My version works. Does it always look like that?

**Comment by VeraBeer** [comment]
Yes, always since I downloaded the latest version, all the times slightly different. I know that others had the same.
But forgot to mention, as soon as I scroll or move the mouse it disappears

**Comment by mathturtle** [comment]
It isn't nearly as bad here, but I do see some small glitches like this when I open it on my mac.  For me it is just a black bar on the right of the view.  Then again I don't have other applications using the GPU, and it looks like it is dumping out uninitialized GPU memory to the screen.

**Comment by cquammen** [comment]
I first noticed this when tomviz moved to Qt 5.6. @VeraBeer  Is this from a nightly binary downloaded from http://www.tomviz.org/downloads/ or built on your machine locally?

**Comment by VeraBeer** [comment]
The nightly one

**Comment by ElliotPadgett** [comment]
I see this too on the nightly binary I downloaded today.  Here's an example:
![tomvizglitch](https://cloud.githubusercontent.com/assets/12242066/16968556/9bde8268-4ddd-11e6-8a45-75e074e823ee.png)

**Comment by cquammen** [comment]
FWIW, I am building tomviz against a very recent ParaView master, and I no longer see these rendering issues. I think @utkarshayachit did some recent Qt5-related work to fix this in ParaView and/or VTK.

**Comment by cquammen** [comment]
Update: I still don't usually see this when starting tomviz, but I did just see it one time this morning.

**Comment by cryos** [comment]
Hopefully this is improved now, it seemed to alleviate the obvious issues on some test systems.
