### ISSUE TITLE
Isosurface opacity and specular text entry boxes gone

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#512]
I noticed that that the boxes to type in values for the opacity and specularity of isosurfaces are gone in the latest nightly binary.  I don't know if this is a bug or a design choice but this feature is important for making consistent visualizations for multiple datasets, so it would be nice to get it back.

**Comment by Hovden** [comment]
Yeah. Textboxes missing in OSX.
<img width="295" alt="screen shot 2016-07-19 at 10 41 26 pm" src="https://cloud.githubusercontent.com/assets/6197997/16973487/090b8fba-4e02-11e6-9fd0-61d48f73fd5d.png">

**Comment by cryos** [comment]
This is the custom UI that @mathturtle added, it sounds like you would like text boxes back. I would like to keep the custom UI (and add more of it), but it shouldn't be too difficult to add back the text entry. We are seeking the sweet spot of just enough interface without too much, thanks for the feedback.

**Comment by mathturtle** [comment]
@cquammen I missed you had this assigned, sorry.

**Comment by cquammen** [comment]
No problem, @mathturtle. We should definitely assign issues to ourselves when we begin working on them.

**Comment by cryos** [comment]
Agreed, and if there isn't an issue create one quickly and assign it so we have an overview of what is happening. Fix looks good.

**Comment by cquammen** [comment]
Fix merged into master.
