### ISSUE TITLE
"orbit" animation no longer guesses center

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#513]
In 0.8.0, the "orbit" animation no longer guesses the particle center, (as it did in previous versions,) making it inconvenient to use.

**Comment by Hovden** [comment]
The center shows up as blank and I can't figure out how to use the orbit tool. (OSX) This was working in v7.2

**Comment by mathturtle** [comment]
Orbit tool? This may have to do with the default animation that is set up when you load a dataset.  I can't remember when we added that.  What exactly are you trying to do? (screenshots would help)

**Comment by Hovden** [comment]
Orbit tool is working correctly in the latest build.

**Comment by cquammen** [comment]
Great! Shall we close?
