### ISSUE TITLE
tomviz settings files are stored under a directory named 'Kitware'

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#514]
Should these files be stored in a tomviz directory instead?

**Comment by Hovden** [comment]
Sounds better to me.

**Comment by cryos** [comment]
I think this is just a result of the organization being set, and is not normally seen by any end user. I would drop this to a pretty low priority level as we fix up other things for the release.

**Comment by cquammen** [comment]
Agree that this is minor, but when the organization is changed, it will have the relatively minor effect of resetting tomviz settings for users when they install the version of tomviz that first has the change. Not a big deal, but not fully transparent to the end user if a change is made. Probably better to make it now rather than when everyone is using tomviz. Plus, it's a super quick change.

Addressed in #524.

**Comment by cquammen** [comment]
#524 is merged
