### ISSUE TITLE
Make "Plasma_17" the default colormap.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#520]
Now @mathturtle added clean matplotlib colormaps, I would like to set the "Plasma_17" as default. It looks a lot nicer and has a monotonically increasing intensity. Implementation should have a safety in case a future version fails to load these custom colormaps.

**Comment by Hovden** [comment]
Sorry to add non-bug related features to the stack last minute, would be great to tackle if it's easy. Could move #306 off the stack.

**Comment by cquammen** [comment]
#306 won't be ready for this weekend. But this one is easier to implement. Addressed in #523.

**Comment by cquammen** [comment]
#523 has been merged. Plasma_17 is the new default.
