### ISSUE TITLE
Layout Tweaks

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#530]
The new Pipeline with the Properties Panel is a great improvement.

Can we reduce the width of the right panels and the height of the animation panel. The current build:
<img width="1285" alt="screen shot 2016-07-21 at 10 08 25 pm" src="https://cloud.githubusercontent.com/assets/6197997/17045150/1b7aa642-4f95-11e6-9454-a75b633f9758.png">

A preferred appearance:
<img width="1276" alt="screen shot 2016-07-21 at 10 48 11 pm" src="https://cloud.githubusercontent.com/assets/6197997/17045165/3a65578c-4f95-11e6-8e7a-21bad7742695.png">

**Comment by cryos** [comment]
This was merged, closing.
