### ISSUE TITLE
Tomviz 0.9.0 fails to open on Mac

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#534]
Running Mac OS X 10.10.5.  Opening tomviz 0.9.0 fails and throws this error message:

![tomviz0 9error](https://cloud.githubusercontent.com/assets/12242066/17078683/572296ae-50c7-11e6-9b3e-5f2e04ab6713.png)

**Comment by cryos** [comment]
I am looking into this right now, something went awry with the packaging in the final binary.

**Comment by cryos** [comment]
Updated DMG uploaded that works locally, I would appreciate feedback on it. Still working on getting the singing tool to work with our application.

**Comment by Hovden** [comment]
OSX is working on the new binary.

**Comment by cryos** [comment]
Thanks for the confirmation, closing this issue.
