### ISSUE TITLE
tomviz as Python library?

### ISSUE THREAD

**Issue by magnunor** [OpenChemistry/tomviz#537]
Is it possible to use tomviz as a Python library? Ergo, calling and accessing processing functionality from other programs?

It would be very useful to do `import tomviz` in a program like HyperSpy (https://github.com/hyperspy/hyperspy), and run a multidimensional dataset (for example a tilt-series) from HyperSpy through the tomography processing functions. And having it as a library/module would make this very seamlessly.

**Comment by cquammen** [comment]
This is not currently supported to my knowledge.

**Comment by Hovden** [comment]
This request would really pertain to the VTK libraries, not so much tomviz. It is more likely that we would include hyperspy in tomviz.

**Comment by cryos** [comment]
Sorry I missed this, but I wonder if the opposite might be easier. Tomviz at its core is a tomography application that bundles Python and a number of useful Python modules. We could potentially bundle hyperspy within the Tomviz installer.

**Comment by Hovden** [comment]
Yep. We can create a new issue that requests to include hyperspy. 

My thought is that this would take is in the direction of spectroscopic data and may require future funding.

**Comment by cquammen** [comment]
Shall we close this issue?
