### ISSUE TITLE
Downsample x2 Needs to be Different for Tilt Series Data

### ISSUE THREAD

**Issue by bdalevin** [OpenChemistry/tomviz#539]
When data is marked as Tilt Series Data, Downsample x2 should only scale the data along the X and Y spatial dimensions, and should leave the tilt dimension alone. 
Currently, Downsample x2 acts the same as it does on volume data, scaling along all 3 dimensions, including tilt, which is bad. 

Alternatively this Transform could be disabled for tilt series data, forcing users to use Resample instead.

**Comment by mathturtle** [comment]
@Hovden which approach do you think fits here?  I'm more in favor of changing how it works to only scale in X and Y, but I'm not a scientist... What would make the most sense to you?

**Comment by ercius** [comment]
I would leave this transform as is and add a similar one to the tilt series
menu which does what was requested (xy binning only). That would allow for
both transforms and keep the confusion to a minimum.

**Comment by yijiang1** [comment]
I prefer @ercius 's approach. I can add this to tomviz if no one is working on it.

**Comment by mathturtle** [comment]
AFAIK, noone is working on it.  Go ahead.

**Comment by ercius** [comment]
@yijiang1 I suggest renaming the current transform to indicate it operates on the full volume. "Bin volume x2" for example.

**Comment by bdalevin** [comment]
I've tested this out on the latest build. It works well. I'm happy to close the issue.
