### ISSUE TITLE
Modifying the Crop Transform runs all transforms

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#542]
Tomviz 0.9.0 on Windows 10. Modifying the crop transform causes all other transforms to run twice:
1) Add a rotate transform (for example)
2) Add a crop transform and crop the data
3) Double click on the crop transform to modify it
4) All previous transforms (the rotate transform in this case) are run again before the Crop GUI shows up
5) Crop the data to new values and click OK
6) All previous transforms are run a second time.
This gets very time consuming and I do not think that the process needs to be run twice.

**Comment by mathturtle** [comment]
I know why it does this right now and I'll see if I can restructure it so that it doesn't.
