### ISSUE TITLE
Indicate currently applied colormap

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#544]
I am not able to find a place where the name of the current colormap is indicated. It would be useful to show this. For example, the currently selected preset could be highlighted by default in the Choose Preset window:
![clipboard01](https://cloud.githubusercontent.com/assets/15657108/17379964/904c5e64-5979-11e6-8172-89d12323eace.png)

**Comment by cquammen** [comment]
A potential undesirable aspect of this feature is that as soon as a color map is edited, the current color map will no longer match what was previously selected.

**Comment by Hovden** [comment]
@cquammen raises a good point.

**Comment by ercius** [comment]
Hmm...that is a good point. However, I'm not sure how often users edit color maps. In that situation no preloaded color map would be selected? I'm also perfectly OK with leaving it as is and closing this request. Any preference @hovden?
