### ISSUE TITLE
Crop GUI box highlighting incorrect

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#545]
The GUI for the crop tool highlights (in yellow) the same face of the box regardless of which handle the user is currently changing. Either no box face should be highlighted or the face currently being manipulated should be highlighted. The former could block the view needed to precisely crop something, but the latter nicely shows where the crop ends. I could go either way depending on how its implemented.
![clipboard01](https://cloud.githubusercontent.com/assets/15657108/17380221/f4223520-597a-11e6-91b6-e39ca1bd38b6.png)

**Comment by mathturtle** [comment]
Ok, I can reproduce this.  Now to figure out why...

**Comment by mathturtle** [comment]
I have traced this all the way down to a bug in VTK's OpenGL2 rendering backend where some update call is missing.  I've reported a bug to them https://gitlab.kitware.com/vtk/vtk/issues/16812

So this will take a while to fix, but the process is started now.

**Comment by cquammen** [comment]
Shawn's fix in VTK is available in ParaView now. It appears to have resolved the identified issue as I could not reproduce it in master. Please re-open if you still observe this behavior.
