### ISSUE TITLE
Rotate GUI will not accept negative values

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#546]
The Angle box in the Rotate GUI will not accept negative values. Either typing a negative value like -6.5 or pressing the down arrow to go below 0.0 does not work. Most likely a range check error in QT for the box.
![clipboard01](https://cloud.githubusercontent.com/assets/15657108/17386035/9ac04fd2-599b-11e6-8666-202b14489e37.png)

The user is able to change the ROT_ANGLE variable in the Rotate Transform Python script to achieve negative rotations. Also, the function ndimage.interpolation.rotate() accepts negative angles.

**Comment by mathturtle** [comment]
I think the initial thought must have been that you can put in 270 for -90.  But allowing negative values makes sense, so I've changed the minimum on the range for that spin box.  When the branch is merged, you will be able to use any value in the range [-360, 360].
