### ISSUE TITLE
File Reader, .MRC read support 

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#56]
Need to be able to read .mrc files, a popular format for microscopists doing tomography. Writing is probably not necessary.

**Comment by cryos** [comment]
http://bio3d.colorado.edu/imod/doc/mrc_format.txt is the spec that I found, we need a sample file or two for verification.

**Comment by Hovden** [comment]
@ElliotPadgett can you provide an MRC dataset?

**Comment by ElliotPadgett** [comment]
I've shared some sample data with you on Dropbox, courtesy of Don Werder.  The folder includes a TEM tilt series in an MRC file generated by SerialEM called replica-tilt-series.st. There is also a copy of it with the file extension changed to .mrc.  IMOD and SerialEM appear to use MRC files with a variety of file extensions such as .st, .rec, and .ali, so we should handle that gracefully in the load menu.

**Comment by mathturtle** [comment]
VTK merge request here: https://gitlab.kitware.com/vtk/vtk/merge_requests/387

**Comment by mathturtle** [comment]
Update: I had to rewrite a big chunk of the reader to work with ParaView's parallel server mode.  We don't need this for tomviz, but @utkarshayachit wouldn't approve the vtk merge request until this was done.

**Comment by mathturtle** [comment]
Update: I tracked down the bug that the VTK dashboards were catching.  This should be merged to VTK tomorrow.

**Comment by Hovden** [comment]
The MRC files are not appearing on my current build. Is this ready for testing?

**Comment by cryos** [comment]
I need to build the latest master, but I didn't see the commit that added this as a reader to ParaView's reader.xml - Shawn are you working on that, or is there already a ParaView SHA where this was merged?

**Comment by utkarshayachit** [comment]
Merged: https://gitlab.kitware.com/paraview/paraview/merge_requests/203

**Comment by cryos** [comment]
That is great - we will need to push the ParaView SHA forward to pull this in.

**Comment by ElliotPadgett** [comment]
This looks good to me.
