### ISSUE TITLE
Show Orientation Axis Label Issue (white on white background)

### ISSUE THREAD

**Issue by bdalevin** [OpenChemistry/tomviz#563]
I'm working on some _tomviz_ figures for a Microscopy Today type article that need light backgrounds. 
The trouble is that the show orientation axis labels (x, y, and z) are only displayed as white, so they don't show up on a light background (see example below)
![axis label colour](https://cloud.githubusercontent.com/assets/12704237/17741052/d2ebbf2c-6468-11e6-81fc-a625f7dd510d.PNG)
. 
My suggested solution is that the axis label colour should be tied to the Bounding Box colour.

**Comment by cjh1** [comment]
This should be resolved by #695
