### ISSUE TITLE
User guide for tomviz

### ISSUE THREAD

**Issue by bdalevin** [OpenChemistry/tomviz#571]
I have written a draft user guide for tomviz that runs users through the basics of how to use the software for tomography and visualization. This will improve user-friendliness by helping new users get to grips with the software more quickly.

Is it possible to get the guide put on the web, with a link to it from the tomviz.org website?

Once we figure out how to put the user guide online, is it possible to add a "User Guide" option to the "Help" menu in tomviz that would send users to the online user guide via their internet browser?

**Comment by cryos** [comment]
Can you share what you have with me, and I can look at where best to host it.

**Comment by bdalevin** [comment]
I'll email you the files right away.

**Comment by yijiang1** [comment]
We should put the user guide somewhere in tomviz's website (http://www.tomviz.org/downloads/). General users probably won't check the github page.

**Comment by Hovden** [comment]
We will do that once the guide is in a more complete form.

**Comment by bdalevin** [comment]
I'm going to close the issue. We can look at the best place to host the guide in future, as we add more to it. What we have now is OK as a starting point.
