### ISSUE TITLE
display python errors instead of crashing the program

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#599]
Whenever there is an error in python transform, tomviz should simply display the error message instead of crashing the entire program...

**Comment by cjh1** [comment]
@yijiang1 Can you give an example of the step to recreate this crash ...

**Comment by yijiang1** [comment]
say I run a python script with the following code:
import numpy as np
a = np.array([1,2,3])
a[4] = 0

Normally, python would print out a message saying "IndexError: index 4 is out of bounds for axis 0 with size 3". In tomviz, this would simply crash to program.

It'd be great if tomviz can catch python errors as people often make small mistakes when programming.

**Comment by cjh1** [comment]
@yijiang1 Thanks for the details.

**Comment by cquammen** [comment]
I am unable to reproduce with current master.

I tested the following Python script:

```
def transform_scalars(dataset):
    """Define this method for Python operators that 
    transform the input array"""

    from tomviz import utils
    import numpy as np

    a = np.array([1,2,3])
    a[4] = 0
```

In the Output Messages window (and at the command line), tomviz reports:

`Failed to execute the script. (/Users/cory.quammen/src/tomviz/tomviz/OperatorPython.cxx:351, virtual bool tomviz::OperatorPython::applyTransform(vtkDataObject *))`

and it does not crash.

We should add display of the particular Python error, though, to make debugging easier.

**Comment by cjh1** [comment]
@cquammen Are you not seeing the traceback? I think it would be useful to have that as well? This may have been lost / changed by my work.

**Comment by cquammen** [comment]
Indeed, I do not see the traceback.

**Comment by cjh1** [comment]
Ok, leave this one open and I will take a look.

**Comment by yijiang1** [comment]
> I am unable to reproduce with current master.

Me too. Running the code above doesn't crash my tomviz anymore.
Maybe some recent changes fix this problem?

**Comment by yijiang1** [comment]
> We should add display of the particular Python error, though, to make debugging easier.

Yeah it'd really awesome if tomviz can print out python's error message (like "IndexError: index 4 is out of bounds for axis 0 with size 3" for the example above).
