### ISSUE TITLE
Streak artifacts in volume rending (windows 7)

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#607]
Sometimes there are strong steak artifacts when rotating a data in volume rending.
![artifact](https://cloud.githubusercontent.com/assets/13088588/18686907/bb4872fe-7f4b-11e6-93b6-4966928522e2.png)

This doesn't happen all the time so I don't know how to reproduce it...

**Comment by Hovden** [comment]
Is it only while rotating? Does it look better when you stop?

**Comment by yijiang1** [comment]
Yes the artifacts disappear when I stop rotating.  
Also, I don't see this kind of artifact on Mac.

**Comment by cryos** [comment]
This is likely level of detail artifacts, I can look at reducing how aggressive it is, but there are LOD artifacts.

**Comment by yijiang1** [comment]
Just curious: would the artifacts also depend on which monitor I'm using?

**Comment by cryos** [comment]
They shouldn't, but may be more/less apparent depending on pixel density, resolution, graphics card, VSYNC, etc.

**Comment by Hovden** [comment]
@yijiang1 Is this fixed by the anti-aliasing?

**Comment by cquammen** [comment]
Anti-aliasing isn't intended to and won't fix the streak artifacts.

**Comment by Hovden** [comment]
I believe dithering "i.e. Jitter on" would alleviate this. #851

**Comment by cryos** [comment]
It would be good to hear, I didn't have time to change the default but we will get it in soon. Streak artifacts are usually much larger scale, it sounds more like a level of detail artifact.

**Comment by yijiang1** [comment]
@Hovden Nope, jittering does next to nothing to visualization and artifacts:
![no_jittering](https://cloud.githubusercontent.com/assets/13088588/22596156/75d21c62-e9f8-11e6-9900-8b9881deb7d7.PNG) --> ![with_jittering](https://cloud.githubusercontent.com/assets/13088588/22596160/79743c1a-e9f8-11e6-8a51-de04a17f2648.PNG)

On the other hand, I can't reproduce the steak artifacts in current version. Maybe some recent updates fixed the problem?

**Comment by Hovden** [comment]
I do see a difference in those two images. The one of the right has slightly reduced the pixelation with a grainy texture (it is minor but visible). I am glad that the dithering is conservative / subtle—it is was too strong then I would be more worried about unexpected artifacts.
