### ISSUE TITLE
Add opacity/transparency option to orthogonal slice visualization

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#609]
It would be nice to have an opacity/transparency control for orthogonal slice visualization modules like we have for contour visualizations.

I want to make some visualizations for a publication where I have orthogonal slices shown as 2D images alongside a 3D visualization.  I will make the 2D images in ImageJ, but I would like to indicate where the slices came from in the 3D volume without having orthoslices obscure the 3D visualization.  Having transparent orthogonal slices rendered on the 3D view would be perfect for this.

**Comment by Hovden** [comment]
I believe this was present in older versions of tomviz, it looks like it has been removed in the new interface. If so, we should add it back.

**Comment by Hovden** [comment]
@mathturtle , is turning on the opacity to the orthoslice easy? If so, Elliot is making scientific figures this month.

**Comment by mathturtle** [comment]
Yes it is fairly easy.  I'll put up a branch later.

**Comment by Hovden** [comment]
I understand your concerns, but in some circumstances we have used it in our visualizations.

Primarily, it is useful to make the background (low intensity) transparent. That way, you can create several stacked slices without the background blocking the rest of the image. Also, a transparent contour surface with a slice through the object core can look nice.

**Comment by ElliotPadgett** [comment]
@Hovden @mathturtle 

Actually this has some strange behavior when present with volume render visualizations.  Adding any amount of transparency to the slice causes the entire volume rendering to appear "in front" of the slice.  See the example below.  Can this be fixed? 

This does not appear to be an issue with contour renderings.

![capture1](https://cloud.githubusercontent.com/assets/12242066/18937028/7ec172e8-85ba-11e6-8aff-6e11fde9342e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12242066/18937032/851fb8a2-85ba-11e6-9eae-326737aef2f0.PNG)

**Comment by cryos** [comment]
This is a known issue with the volume rendering, there are some plans to look into fixing it but I am not sure on the timeline. It is not as simple as it sounds due to the way volume rendering, depth peeling, and transparent geometry all render (and getting the interaction right such that the result looks correct).

**Comment by Hovden** [comment]
Ok. Just to keep track of it, we can create an issue on tomviz and ping Paraview.

**Comment by cryos** [comment]
This is a VTK issue, and there are several discussions on the VTK mailing list related to this.
