### ISSUE TITLE
Manual alignment: erroneous jump with button press

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#61]
In the manual alignment widget, after applying a significant shift pressing any key (even ones that should do nothing) causes the image to jump to a location not specified by the user-defined shifts.  I have only observed this starting with unaligned data.

To replicate clearly (with sample star-particle tilt series):  
1) misalign the stack with the cross-correlation auto-align. 
2) open stack in manual alignment widget and begin aligning. 
3) after aligning 5-10 images so that you need to apply a significant shift to align, hold down space (or any other inactive key) on a well-aligned image pair and you will see the image pair appear misaligned again.  

This behavior also happens when doing regular alignment and is confusing, but this is the clearest way to observe it.  The spurious shift appears to be in the direction of user-applied shifts, but maybe 1/2 or less in magnitude.

**Comment by Hovden** [comment]
Marcus @cryos has fixed this issue by disconnecting the timer from the keypresses.

**Comment by cryos** [comment]
This is now fixed.
