### ISSUE TITLE
State files do not restore child data sets

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#616]
Steps to reproduce.
- Start Tomviz
- Load `SMALL_PtCu_NanoParticle.tif`
- Run Data Tranforms -> Binary Threshold, default settings
- File -> Save State
- File -> Reset
- File -> Load State (load saved .tvsm file)

The child data set will not appear in the Pipelines dock widget

**Comment by cquammen** [comment]
More deeply nested trees are not being restored, however.

**Comment by mathturtle** [comment]
Yeah, you still can't restore child datasets' operators or modules.

**Comment by cryos** [comment]
No, things are currently being filtered out if they cannot be restored correctly.

**Comment by cquammen** [comment]
This is basically working correctly as far as I can tell. Operators and Modules are still not restored. I will file a separate issue about that.
