### ISSUE TITLE
Add Otsu Segmentation

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#619]
As just discussed with @cquammen, @cryos , @ElliotPadgett we will add the Otsu method of Segmentation.

To start, we can just add a simple implementation of these algorithms and test them on datasets (for Otsu, user simply specifies the number of classes and any other basic parameters). We can make more advanced graphical interfacing part of another issue.

**Comment by cquammen** [comment]
Branch pushed to #630.

**Comment by cquammen** [comment]
Merged. UI makes it possible to specify number of thresholds to use.
