### ISSUE TITLE
Add Paraview Ruler Tool for Quantitative Analysis of Data

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#621]
Ruler tool in Paraview would let us measure distances in the sample. It is a nice feature we should consider adding.

<img width="1044" alt="screen shot 2016-09-27 at 1 56 48 pm" src="https://cloud.githubusercontent.com/assets/6197997/18885634/7987c6a2-84ba-11e6-9845-1ceacf768795.png">

**Comment by cryos** [comment]
We were just talking about this, @mathturtle it would be a nice addition and I think you said you were working on this feature in ParaView.

**Comment by Hovden** [comment]
Bumping this. Hoping it would be an easy quantitative tool to add.

**Comment by ercius** [comment]
I will bump your bump and think this would be a great tool to add.

**Comment by cryos** [comment]
@mathturtle did some of the work on adding this to ParaView, we will see if we can get this in soon.

**Comment by cjh1** [comment]
@mathturtle Can this now be closed?

**Comment by mathturtle** [comment]
We have the ruler added as a visualization module, so probably.

**Comment by Hovden** [comment]
It would be nice to note what the units are, in this case length = pixels?

**Comment by Hovden** [comment]
-If the ruler reported the voxel values at the start and end points then we could knock off issue #311

Cosmetic comments: 
-Turning the "eye" off does not make the arrow disappear. Thus users must delete all their measurements for visualization.
-There is a large lag between the ruler annotation and arrow when moving points around. If its easy to make the refresh time faster, that would help.

**Comment by mathturtle** [comment]
> -If the ruler reported the voxel values at the start and end points then we could knock off issue #311

Sure I can make it show the end points in the properties panel (and let you manually set them if you want).

> 
> Cosmetic comments:
> -Turning the "eye" off does not make the arrow disappear. Thus users must delete all their measurements for visualization.

This is a ParaView thing, there is a separate toggle for the arrow.  I'll link the two so that the arrow is forced off when the module is hidden.

> -There is a large lag between the ruler annotation and arrow when moving points around. If its easy to make the refresh time faster, that would help.

I'll look at this, but I don't expect there will be anything easy.


Units: whatever the units on the data are (assuming the data spacing is set appropriately).  I'll see if I can set the text on the ruler to include units... I don't know if it is possible or not.

**Comment by Hovden** [comment]
Ruler "Show Line" box becomes re-checked when highlighted in the pipeline.

**Comment by cquammen** [comment]
The "Show Line" problem should be fixed by #1052.

**Comment by cquammen** [comment]
#1052 was merged.
