### ISSUE TITLE
Binary threshold error

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#623]
In today's nightly built. Dataset is a 32-bit tiff stack.  Binary threshold operator makes an empty space in the pipeline and throws the error:
"
Exception encountered while running BinaryThreshold
No ITK type known for vtkFloatArray
"

Seems like a problem with the datatype?

**Comment by cquammen** [comment]
Yep. We'll need to build ITK with float type support by turning ITK_WRAP_float:BOOL on in ITK's CMake configuration.

**Comment by cquammen** [comment]
Odd, that option is on by default. I'll download the binary and take a look.

This will impact other segmentation features work, so prioritizing.

**Comment by cquammen** [comment]
Okay, the ITK that is shipped with the nightly checks out okay. I've discovered a typo in the code that converts from VTK images to ITK images... will submit a patch shortly.

**Comment by cquammen** [comment]
This should be fixed in the next nightly. Please reopen this issue if it is not.
