### ISSUE TITLE
Child visualization not deleted with segmentation object

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#624]
If I make a visualization from an object produced by a binary segmentation module and then delete the segmentation module the visualization module disappears from the pipeline but the visualization does not go away.

<img width="1299" alt="screen shot 2016-09-27 at 2 39 30 pm" src="https://cloud.githubusercontent.com/assets/12242066/18886848/b2658f40-84bf-11e6-810a-8263d961b4ad.png">
<img width="1297" alt="screen shot 2016-09-27 at 2 38 33 pm" src="https://cloud.githubusercontent.com/assets/12242066/18886851/b4ee40f4-84bf-11e6-9b16-19efad2cf81b.png">

**Comment by cquammen** [comment]
Is that the case if you click in the rendering window after removing the Binary Threshold transform?

**Comment by cquammen** [comment]
Nevermind, I can confirm the visualization module still exists.

**Comment by cquammen** [comment]
@ElliotPadgett I have a fix for this in #677. Would you mind trying it out? Thanks in advance.
