### ISSUE TITLE
Expose advanced features in the volume rendering

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#633]
The default rendering using the volume looks like:

![image](https://cloud.githubusercontent.com/assets/42214/18964410/c0fec5c0-8646-11e6-99ab-f847b8380835.png)

Enabling lighting can offer this effect (parameters may need tweaking):

![image](https://cloud.githubusercontent.com/assets/42214/18964431/dc558be2-8646-11e6-98ee-c52e8fd9ffeb.png)

and maximum intensity can show the brightest parts of the interior (these are all using the same opacity/color map)

![image](https://cloud.githubusercontent.com/assets/42214/18964459/fad2717a-8646-11e6-94ee-6dd8d62574c2.png)

**Comment by Hovden** [comment]
Very cool.

**Comment by bdalevin** [comment]
I second that. Very cool.

**Comment by Hovden** [comment]
Bumping this—would love to incorporate this into my talk on the variability of tomography visualization.

**Comment by cryos** [comment]
I cleaned it up more, and pushed a branch. You should be able to try it out, I need to look at save/restore before it is really ready to be merged, and there are likely some corner cases I overlooked.

**Comment by cryos** [comment]
There is certainly more to do, but I think the initial merge request will let you test out the functionality, and we can flesh out the exposed properties in future pull requests.

**Comment by cryos** [comment]
Closing this issue. we can open new issues to track additional features, bugs, etc.
