### ISSUE TITLE
QCoreApplication::postEvent: Unexpected null receiver and four warnings for auto tilt axis align

### ISSUE THREAD

**Issue by yangking91** [OpenChemistry/tomviz#637]
Dear Sir,
I also found that if I open tomviz and close without loading any data, QCoreApplication::postEvent: Unexpected null receiver will pop out. Another thing is when I use automatic tilt axis alignment, four warnings also popped out: Auto Tilt Axis Align:62: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
Auto Tilt Axis Align:66: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
Auto Tilt Axis Align:70: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
Auto Tilt Axis Align:74: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
Do you know what's wrong?
Thank you very much.

Best regards,
Taimin

**Comment by mathturtle** [comment]
For this:
> QCoreApplication::postEvent: Unexpected null receiver

I haven't had time to track down where it is happening, but it is only a warning and you don't have to worry about it.

I don't see the others in my build, but you may have different versions of something from me.  They are deprecation warnings which mean that something we are using will not be supported in a future version of that library.  But you don't have to worry about them now.  Thank you for reporting them though, we will try to figure out what is causing these.

**Comment by yangking91** [comment]
@mathturtle OK, thanks.
