### ISSUE TITLE
Cdash Build Errors

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#639]
https://open.cdash.org/index.php?project=TomViz

**Comment by mathturtle** [comment]
Looks like buildbot didn't realize we had a submodule now.  I'll have to go through and remove the source directories... I know a clean checkout inits submodules.

**Comment by cryos** [comment]
This is because the submodule is not being fetched, I thought @mathturtle said it would fetch submodules without issue - he will look into it soon hopefully.

**Comment by cryos** [comment]
@mathturtle while you are doing that we should ensure updates will init/update any submodules, maybe just add the sync call in too so that we don't need to revisit this should anything move.

**Comment by mathturtle** [comment]
@cryos So the submodule is working and bigmac is working.  Windows has issues finding python, @cjh1 is looking at it.  Our Linux builder needs a newer compiler... which is apparently not an easy thing to get on Debian 7.  But pybind11 and gcc 4.7 don't get along.  We may have to switch which distro we are based on to find one that has an old enough glibc and support for gcc 4.8/4.9.  I am open to suggestions.

**Comment by mathturtle** [comment]
Some discussions with Ben later... CentOS 6 is what ParaView uses for its binaries and I can copy parts of that Dockerfile that Ben has set up for them.  They are using gcc 4.9 which should be new enough.  Our binaries should still run on Debian 7 though, so no problems there.

**Comment by cryos** [comment]
Sounds great, please keep us posted as progress is made.

**Comment by mathturtle** [comment]
So Qt5 and CentOS6 have some issues.  Rather than debug them, I'm just updating our baseline to Debian 8 like you suggested.  Hopefully that just works.

**Comment by cryos** [comment]
Sounds good.

**Comment by mathturtle** [comment]
@cjh1 The windows builds are failing right now, `_wrapping.pyd` is failing to link, saying `cannot open file 'tbb.lib'`.  Do you have any idea why it thinks it needs tbb?

**Comment by cjh1** [comment]
This is all fixed up now thanks to @mathturtle
