### ISSUE TITLE
Non-orthogonal slice OpenGL2 warnings

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#65]
Using the non-orthogonal slice when the widget first appearsh or when moving the slice plane, I get OpenGL warnings:

Warning: In /home/shawn/dev/tomviz/src/paraview/VTK/Rendering/OpenGL2/vtkOpenGLPolyDataMapper.cxx, line 1418
vtkOpenGLPolyDataMapper (0x6219340): line widths above 1.0 are not supported by OpenGL 3.2

**Comment by Hovden** [comment]
This error also occurs when rendering an adjustable box like that of the crop-box.

**Comment by cryos** [comment]
I need to check on the progress on this, it is currently a warning and does render correctly. I will see if we can silence this, and have already raised the fact that we must continue to support lines wider than 1.0.

**Comment by cryos** [comment]
Verified that ParaView master with VTK master (not yet moved forward in ParaView renders correctly with no warnings issued. Once it is moved forward our binaries will take advantage of the fixes merged.

**Comment by cryos** [comment]
Fixed, new SHA for ParaView resolves this.
