### ISSUE TITLE
Crashes when running Python transforms (Build 171-OSX)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#656]
I am not able to run any python transforms (OSX)

1) Open dataset
2) "Data Transforms > Rotate"

Crashes.

**Comment by yijiang1** [comment]
Crashes on window 7 too. 
My local build works fine.

**Comment by mathturtle** [comment]
I'll look into it.

**Comment by mathturtle** [comment]
Update: tomviz.utils and tomviz._internals are failing to import, then it tries to call PyObject_GetAttrString on the NULL object.  Looking further, it seems that these files (in fact all files in `Contents/Python/tomviz`) are installed containing nothing.  They are empty placeholder files.  I'll look at why that is after lunch.  @cjh1 Did you change how the files in the tomviz python module are generated with the pybind11 stuff?

**Comment by cjh1** [comment]
Yes, there where some packaging changes related to the threading support. I can take a look.

**Comment by cjh1** [comment]
@Hovden I think we have fixed this issue, can you try the latest build:

https://open.cdash.org/viewFiles.php?buildid=4585097

**Comment by yijiang1** [comment]
Yep, tomviz doesn't crash on OSX now.

**Comment by cjh1** [comment]
@yijiang1 Thanks for the feedback, I will close this now.
