### ISSUE TITLE
Animation not saving: stops at 200 frames

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#658]
I'm trying to make animations with more than 200 frames, however when saving a movie it stops at 200.

1) File > Save Movie
2) Set number of frames to 500.

Tested on OSX and any build 9.1 or greater.

**Comment by Hovden** [comment]
Fixing this is fairly high priority for me; I am preparing a tomviz talk.

**Comment by mathturtle** [comment]
This is a bug in ParaView, so it may take a while to fix.  But I have found a workaround for you @Hovden.

If you set the maximum frame number *before* doing File -> Save Movie, you can export an animation of up to that many frames.  You can set that in the text field I have outlined in red in this image:
![screenshot_2016-10-06_11-41-10_edited](https://cloud.githubusercontent.com/assets/553788/19159420/6ad6604e-8bba-11e6-9d60-bac76bf37eef.png)

**Comment by Hovden** [comment]
Thank you for the temporary fix. This will allow me to continue working.

**Comment by mathturtle** [comment]
@utkarshayachit figured out what we were doing wrong.  The Save Movie dialog has a setting to select which frames to export (see image below).  This setting is populated based on the initial number of frames and doesn't update when you update the total number of frames.  So you would have to update this option too.  I'm going to look at patching it to automatically update when you update the max number of frames.

![screenshot_2016-10-06_13-54-07_edited](https://cloud.githubusercontent.com/assets/553788/19164089/93ce8bd6-8bcc-11e6-8196-b405150e734f.png)

**Comment by mathturtle** [comment]
The ParaView patch for this has been in for a while.  It should automatically update the frame range when you change the number of frames now.  Can we close?

**Comment by cryos** [comment]
If someone has verified this works in the binaries yes.

**Comment by yijiang1** [comment]
This is fixed on current binaries.
