### ISSUE TITLE
Animator fails to rotate past x-y plane

### ISSUE THREAD

**Issue by bdalevin** [OpenChemistry/tomviz#66]
Simple orbit animation only works around z axis. Around x and y axes, the software tries to flip the image over half way through, and spits out an error message:
Warning: In C:\DBD\matviz-x64\paraview\src\paraview\VTK\Rendering\Core\vtkRenderer.cxx, line 1029
vtkOpenGLRenderer (00000000093D9C80): Resetting view-up since view plane normal is parallel.

**Comment by cryos** [comment]
@utkarshayachit I think this is the bug we looked at while visiting Cornell.

**Comment by bdalevin** [comment]
I have a movie that illustrates the problem perfectly, but can't attach it here. It's only 1 MB, so will try to forward by email.

**Comment by bdalevin** [comment]
I've been doing some more bug testing of the different animator functions (see #154). I have found that the animator only fails to generate a simple vertical orbit for the "Orbit" and "Follow Path" options. A vertical orbit can be achieved if the user chooses the "Interpolate Camera Positions" animation and creates the orbit with camera positions.

**Comment by mathturtle** [comment]
I've dug down and found the code in vtkRenderer and vtkCameraInterpolator2 that needs to be changed, but the details of the change need to be discussed with @utkarshayachit who is on vacation until next week since this will affect ParaView as well.

**Comment by mathturtle** [comment]
I have a ParaView branch [here](https://gitlab.kitware.com/paraview/paraview/merge_requests/514) that addresses this (at least for this specific case).
