### ISSUE TITLE
Simple back projection UI is not visible

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#660]
On my local build (OSX), the simple back projection (c++) UI is not visible during reconstruction.

**Comment by cquammen** [comment]
I could not reproduce on OS X doing the following:

* Launch tomviz
* Sample Data -> Generate Random Particles, accept default parameters
* Tomography -> Generate Tilt Series, accept default parameters
* Tomography -> Simple Back Projection (C++)

Let me know if this is the wrong way to try to reproduce the problem.

**Comment by yijiang1** [comment]
Actually I can't reproduce the bug either on current build. I guess it's somehow fixed in recent changes.

**Comment by cquammen** [comment]
Great! Please reopen if it is a problem in the future.
