### ISSUE TITLE
Consider using the Qt5 JSON classes for interface builder

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#664]
They are very nice, simple API, integrate well with the Qt APIs, and we already require Qt5 (first release they were a part of). It shouldn't be too hard to convert things over, especially while things are still at a relatively early stage.

**Comment by cquammen** [comment]
I don't see a huge advantage to using the QJson* API. The API for [`QJsonValue`](http://doc.qt.io/qt-5/qjsonvalue.html) is really quite similar to jsoncpp's [`Json::Value`](http://jsoncpp.sourceforge.net/class_json_1_1_value.html), e.g.:

| QJsonValue val; | Json::Value val; |
| ------------ | ------------ |
| val.isArray() | val.isArray() |
| val.isBool() | val.isBool() |
| val.isDouble() | val.isDouble() |
| val.isNull() | val.isNull() |
| val.isObject() | val.isObject() |
| val.isString() | val.isString() |
| val.toBool() | val.asBool() |
| val.toDouble() | val.asDouble() |
| val.toInt() | val.asInt() |
| val.toString() | val.asString() |
| val.toArray()[index] | val[index] |

`Json::Value` combines the roles of `QJsonObject`, `QJsonValue`, and `QJsonArray`, so it's a little less clean design-wise, but it's not bad IMO.

**Comment by cryos** [comment]
Totally aware of the API for both, and have used both. I think in Qt-based classes it makes far more sense to use the Qt APIs. They benefit from things such as copy-on-write, and use of QString and QVariant which are more natural to use with Qt widgets. Unless there is a compelling reason to not use it then I think we should migrate to it, just like we use QList, QString, etc in our Qt code.

**Comment by cquammen** [comment]
Completed in #675.

**Comment by cryos** [comment]
Thanks Cory
