### ISSUE TITLE
Changing Perspective View?

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#666]
Question. I'm looking to demonstrate the effect perspective view can have on the visualization of scientific data. How hard would it be to make the perspective view adjustable so I can demonstrate how varying perspective can affect how your data looks?

**Comment by cryos** [comment]
I don't see any existing graphical interface exposing this in ParaView, you can compare orthographic to perspective fairly easily, it would be a little more work to expose some of the low level camera API. I think the main class is http://www.vtk.org/doc/nightly/html/classvtkCamera.html, I can take a better look but it may be simpler to simply write a Python example using VTK's wrapped API.

**Comment by Hovden** [comment]
Ok. Then don't worry about it. Ortho vs. Perspective is enough to make my point.

**Comment by cquammen** [comment]
Developer's note from me stumbling into this setting at a ParaView tutorial I was giving:

The `RenderView` proxy has a `CameraViewAngle` property that could be exposed in the Tomviz UI. It is exposed in ParaView's Adjust Camera dialog, which is accessible by clicking on the camera next to the 2D/3D icon in the toolbar above the view, i.e., the icon on the right below.

![image](https://cloud.githubusercontent.com/assets/360056/20976046/3dffdaa6-bc6f-11e6-96ba-929fb693ec1e.png)

**Comment by cryos** [comment]
Wow, it was hiding in plain sight the whole time. That same button is exposed in Tomviz, and the camera angle does indeed offer what you wanted. Probably far too late, I would never have guessed that box was adjusting the perspective. Thanks for pointing this out @cquammen.

**Comment by cquammen** [comment]
Oh yeah, I didn't think to see that this was exposed in Tomviz. Shall we close this request since this feature is in fact exposed?

**Comment by cryos** [comment]
Sure, I think it would be great to look at improving the dialog at some point to make this a little more obvious, but closing as it is in fact available if quite difficult to find.
