### ISSUE TITLE
Icon Missing on OSX build

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#667]
Tomviz icon no longer appears on OSX.
<img width="333" alt="screen shot 2016-10-07 at 8 07 31 pm" src="https://cloud.githubusercontent.com/assets/6197997/19208587/d0947eec-8cc9-11e6-9a72-167378a34aed.png">

**Comment by mathturtle** [comment]
I saw this on Friday after the builds were fixed.  I don't know why it happens yet, but it started some time last week during the 'tomviz won't build anywhere' mess.  I'm planning to double check the packaging today so I'll look into it as a part of that.
