### ISSUE TITLE
Delete key not working in Pipeline (OSX)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#668]
Pressing the delete key removes many items in the pipeline. However, right clicking selecting delete behaves correctly. This is tested in 0.9.1-307 and 0.9.1-318.

**Comment by yijiang1** [comment]
The delete key works now on latest binary. 
However, the other bug mentioned in #572 still exists.

**Comment by cryos** [comment]
I am tracking down some odd issues with using the arrow keys/delete keys doesn't seem to select what I might normally expect it to. Hopefully I will get to the bottom of it soon, it is quite strange, and something I am seeing in my local build tree.

**Comment by yijiang1** [comment]
This is fixed on latest binary (-403-).
