### ISSUE TITLE
Use of White in Paraview / Tomviz Often Invisible

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#669]
Paraview often chooses white as default for text and lines in the visualization which appears invisible when a white background is used. Since a white background is popular, white should be avoided.

Right now, this affects our crop tool, show axis grid, the orientation axis, etc.

I recommend that Paraview (and tomviz) adopt a new default color. I believe this can be resolved simply if a light gray is chosen in place of white. The current gray we use for our bounding box (#CCCCCC) is visible on both the default background and a white background. In fact, the gray text looks white on the default paraview / tomviz background.

The image below shows the crop tool on a white background. You can also see the default gray used on the bounding box.

<img width="605" alt="screen shot 2016-10-08 at 4 11 57 pm" src="https://cloud.githubusercontent.com/assets/6197997/19215683/b4a63186-8d72-11e6-8e82-6a75d5b8b45d.png">

**Comment by cryos** [comment]
That is a good point, we should work towards this in Tomviz, and put it to the ParaView folks.

**Comment by Hovden** [comment]
This would solve the "show axis grid" problem (#421). Which is something Barnaby will use to create a tomviz figure and I might use in my tomviz talk next week.
