### ISSUE TITLE
Error when running python transform on local build

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#674]
I get this error when I run python script on my local tomviz.

RuntimeError: module compiled against API version 9 but this version of numpy is 7
Failed to execute the script. (:0, )
Traceback (most recent call last):
  File "Bin Volume x2", line 5, in transform_scalars
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/ndimage/__init__.py", line 172, in <module>
    from .filters import *
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/ndimage/filters.py", line 36, in <module>
    from . import _nd_image
ImportError: numpy.core.multiarray failed to import

Do I need to upgrade my python?

**Comment by cquammen** [comment]
Do you have a Python installed via `brew`? If so, my guess is that you are compiling against the numpy in that version, but your system Python is found when running.

A solution is to ensure that you are building against your system Python. In CMake for your ParaView build, try setting the following Python settings:

PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2.7
PYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7
PYTHON_LIBRARY:FILEPATH=/usr/lib/libpython2.7.dylib
PYTHON_UTIL_LIBRARY:FILEPATH=/usr/lib/libutil.dylib

By the way ,I wrestled for a while trying to compile ParaView against my `brew` Python, but I wasn't successful.

**Comment by yijiang1** [comment]
My system Python doesn't have packages like scipy, itk, and pyfftw.
What are the correct ways to install them? Thank.

**Comment by yijiang1** [comment]
Ok I've figured out some solutions.
For numpy:
The system python comes with built-in numpy but it's too old for tomviz. I update it by simply running (on OSX 10.11.6)
`sudo easy_install -U numpy`

For ITK:
I build ITK following the instruction here https://github.com/OpenChemistry/tomviz/blob/master/BUILDING.md and then add the python path in my .bash_profile 
`export PYTHONPATH="/Users/xxx/itk-build/Wrapping/Generators/Python:$PYTHONPATH"`

For scipy:
Should be similar to numpy, but I keep getting this error:
c++: error: unrecognized command line option '-Wshorten-64-to-32'

Don't know how to solve this yet...

**Comment by mathturtle** [comment]
I generally use virtualenv to create a local python environment and then pip install scipy and numpy there.  Then you just add that path to the PYTHONPATH.  I mostly work on Linux, but that approach *should* work on OSX too.

**Comment by yijiang1** [comment]
For some reason (I really don't know what happened...), the scipy error above is gone and everything works now.
