### ISSUE TITLE
linear algebra library

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#688]
Is there a c++ linear algebra library included in tomviz? 
Some advanced tomography reconstruction requires operations such as matrix vector multiplication.

**Comment by cryos** [comment]
We could quite easily add in Eigen, I know it well, and it would be easy to add. It is header only, and expands out to very efficient code and the API is nice and friendly.

**Comment by cjh1** [comment]
pybind11 also has support for wrapping it, which is a bonus if that become necessary.

**Comment by yijiang1** [comment]
Eigen seems a good choice.

**Comment by Hovden** [comment]
We're looking to speed up the reconstruction algorithms. Some are slow (~day).

We could either parallelize Python (threading library needed) or implement them in C++ (requiring linear algebra library). Which would be easier?

**Comment by cryos** [comment]
Adding Eigen is pretty simple, we will just add it to the superbuild. If you want me to put up an example branch to use it I can do that, but you will need to install it locally. I will see if I can put a quick example up tomorrow, this library is great as it is header only, and so there are no additional libraries to take care of. This is probably the easiest path too, I am not that familiar with multithreading in Python.

**Comment by ercius** [comment]
Maybe we can integrate tomopy and/or the Astra toolbox? Their algorithms
are well tested and fast. I've been using them a lot recently. I'm not sure
if they have builds for all platforms though. Windows and Linux only?

**Comment by cryos** [comment]
I have been looking at tomopy, and it looks nice. You have been able to use these in your work with STEM tomography reconstructions? I have not come across Astra.

**Comment by ercius** [comment]
Tomopy is pretty good, but the [Astra-toolbox](http://www.astra-toolbox.com/) is very fast and flexible. Both can be installed in Anaconda pretty easily to try them out. 

You can also call the Astra-toolbox recon algorithms from tomopy which makes setup a little easier in some cases.

Both are parallelized and Astra is GPU capable. Astra seems to be faster in my experience. I have been doing alignment in tomviz, exporting to HDF5, and reconstructing using ASTRA lately. I can send an example python script if you want to try it out.

**Comment by ercius** [comment]
.I forgot to mention that the weighted back projection code in tomopy does not work properly. I think it does not apply any weighting, making the low frequencies overpower the reconstruction. If you are testing out tomopy then try the GRIDREC method. Its quite fast and produces nice results.

**Comment by cryos** [comment]
I would really appreciate that, thanks for providing the links. We can certainly offer Eigen for fast C++ linear algebra. I would really appreciate some example scripts.

**Comment by ercius** [comment]
@Hovden @cryos I sent you an email with a demonstration script and test data for tomopy and ASTRA. If anyone else watching this thread is interested in these files let me know.

**Comment by Hovden** [comment]
@cryos and I discussed this a little over the phone. Most immediately, the focus is on getting a new stable release out. Next week I'll look at tomopy and ASTA with @yijiang1 and get back to you to discuss it further. It sounds like a good idea.

**Comment by ercius** [comment]
This is definitely a more long term part of the project. 

I did more testing and ASTRA is not parallelized for CPU (non-GPU) reconstruction (so called 2D CPU algorithm by ASTRA). tomopy implemented parallel versions of the non-GPU ASTRA algorithms. So, this might be more difficult in practice than I previously thought because you need both tomopy and ASTRA to get the full benefit which is only possible on linux right now.

**Comment by cryos** [comment]
Eigen is in VTK now, and so can be used as other third-party modules are.

**Comment by Hovden** [comment]
@yijiang1
