### ISSUE TITLE
Add "transform description" in property panel

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#691]
It'd be great if we show some descriptions for each transform in the property panel.

For example, if I first select "Orthogonal Slice" in Pipelines and then select a data transform, the Properties panel remains the same, which may be confusing. 
<img width="292" alt="screen shot 2016-10-20 at 3 16 25 pm" src="https://cloud.githubusercontent.com/assets/13088588/19574447/5b14dffe-96d8-11e6-92dd-2ea5cbbd6bde.png">

Instead, we could show something like
<img width="292" src="https://cloud.githubusercontent.com/assets/13088588/19574554/e15552ec-96d8-11e6-9854-75a0135a0637.png">

This is especially useful for complex transforms such as segmentation and tomography.

**Comment by yijiang1** [comment]
Is this easy to do? We'd really like to have this feature.

**Comment by cryos** [comment]
Not as easy as you might think, but I started looking at it. Should have something ready soon.

**Comment by cryos** [comment]
So #720 does some of this, we need to do a little more work to get the JSON descriptions in. I will leave this open to track that, and make sure we do it.

**Comment by cryos** [comment]
I am going to close this, we have added the operator dialog to the panel, and so made it more inline with the other pipeline objects. I think that is a better use of the space, and the description is there (although we are looking at making it into a tooltip/help as it takes up a lot of space in some cases).

**Comment by yijiang1** [comment]
What about making the description an editable text field? Thus users can even add notes to their custom transforms.
