### ISSUE TITLE
flake8 confilcts with "user specified variables" in python

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#702]
To pass user-specified-variables to python script, we require python code to have the format of:
`###variableName###`

On the other hand, running `autopep8 --global-config flake8.cfg --in-place xxx.py` automatically changes the code to 
`# variableName###`

**Comment by cjh1** [comment]
Yup, another reason to move away from templating our python scripts.

**Comment by yijiang1** [comment]
So we will use a different format for user specified variables in python?

**Comment by cjh1** [comment]
The plan is to inject them as members of an Operator instance in the future I think.

**Comment by yijiang1** [comment]
I see. Sounds good to me.

**Comment by cquammen** [comment]
We could also add an `arguments` Python dictionary to the signature of `transform_scalars`.

**Comment by cjh1** [comment]
@cquammen Yes, that is another option.

**Comment by cryos** [comment]
Tried commenting over email, apologies if that shows up later. Short term we should relax or turn off flake8, implement a fix but I don't want it to be rushed for flake8. We discussed some of the options Cory mentioned last week, and there are a number of benefits to moving from text replacement.

**Comment by cjh1** [comment]
@yijiang1 For some reason autopep8 isn't respecting the ```ignore:``` section in flake8.cfg, but running with the following options will prevent it reformatting the comments:

```
autopep8 -i --ignore E262,E261,E265 --global-config flake8.cfg tomviz/python/BinaryErode.py
``` 

Hope that helps, I will update the doc ...

**Comment by yijiang1** [comment]
Yeah this avoids the conflict for now.

**Comment by cryos** [comment]
Thanks for clearing this up in the short term, we will move away from text replacement at some point. It makes it hard to know if a script was changed or has a GUI, and the GUI cannot be shown again...

**Comment by cryos** [comment]
For the short term I think we should turn off flake8, it can be turned back
on but I don't want it to create a false sense of urgency.
