### ISSUE TITLE
State-file-restored volume rendering looks grainy

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#707]
I'm not sure exactly how to describe this problem, but I've found that when I save and restore a state file with a volume rendering the volume rendering can come back looking grainy in comparison to the original (see screenshots below).  New volume renderings created with the same data and pipeline in the restored session look normal.  Any ideas about what is going on here?

Normal:
<img width="1283" alt="screen shot 2016-10-25 at 3 22 46 pm" src="https://cloud.githubusercontent.com/assets/12242066/19700990/82729760-9ac7-11e6-8989-e64230122e01.png">
Grainy:
<img width="1286" alt="screen shot 2016-10-25 at 3 27 48 pm" src="https://cloud.githubusercontent.com/assets/12242066/19701022/9fa1f6e6-9ac7-11e6-9758-a9c1ba704bef.png">

**Comment by cryos** [comment]
I will investigate

**Comment by ercius** [comment]
If you rotate the object does it get smoother?

**Comment by ElliotPadgett** [comment]
Rotating, hiding and reshowing, and editing the color map don't impact the issue.  

I'm not sure what it takes to reproduce it actually.  I tried with the sample data but I don't see the problem there.

**Comment by ElliotPadgett** [comment]
Actually I also get the issue when I load that dataset from the "recently opened" menu, without any state file saving.

**Comment by ElliotPadgett** [comment]
Nevermind, I'm very confused now.  Even if I load that dataset directly in a fresh tomviz session it has the grainy appearance.  

However, something is definitely going wrong because when I load the original state file with the problem I can have two different volume renders from the same data with the same color map which appear different, just like I show above.

I can share the data and the state file if that would help.

**Comment by ElliotPadgett** [comment]
Actually @yijiang1 and I figured out what the real problem is.  I will close this and open a new issue.
