### ISSUE TITLE
Conflit between clang-format-diff.py and travis test

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#709]
Running clang-format-diff.py and travis test sometime give me different results.
For example,
(from travis)
<img width="504" alt="screen shot 2016-10-25 at 4 17 07 pm" src="https://cloud.githubusercontent.com/assets/13088588/19702908/adef7dec-9acf-11e6-87b0-a7ad73d1d3ef.png">

(from clang-format-diff.py)
<img width="462" alt="screen shot 2016-10-25 at 4 20 06 pm" src="https://cloud.githubusercontent.com/assets/13088588/19702911/af1cfc1c-9acf-11e6-8dff-0932400634a9.png">

**Comment by cjh1** [comment]
@yijiang1 What version of clang-format do you have installed? On Travis we are running 3.8

**Comment by yijiang1** [comment]
I downloaded the script here
https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py

**Comment by cjh1** [comment]
That is just the python wrapper around clang-format. Can you run clang-format --version?

**Comment by yijiang1** [comment]
I see. Turns out I'm using clang-format version 3.7. 
What's the best way to install version 3.8? Thanks.

**Comment by cjh1** [comment]
What platform?

**Comment by yijiang1** [comment]
on Mac

**Comment by cjh1** [comment]
I think its available on brew?

**Comment by yijiang1** [comment]
Yes and I can install it by running `brew install homebrew/versions/clang-format38`
Now the conflict is gone.
