### ISSUE TITLE
Volume rendering not updated by new transforms

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#717]
New transforms added to the pipeline do not update volume renderings created before them.  This problem was responsible for the behavior seen in #707. It does not appear to impact all rendering types (e.g. contours). To reproduce this problem:

1) Open the sample reconstruction and create a volume rendering.

<img width="1284" alt="screen shot 2016-10-28 at 3 29 31 pm" src="https://cloud.githubusercontent.com/assets/12242066/19819682/a9ca894a-9d23-11e6-99c6-69f21f3400aa.png">

2)  Apply a transform that should impact the rendering.  For example, here I applied a 10 pixel Gaussian blur.  The rendering changes it's appearance slightly because the colormap is updated for the transformed data, but it is not blurred.

<img width="1281" alt="screen shot 2016-10-28 at 3 30 10 pm" src="https://cloud.githubusercontent.com/assets/12242066/19819685/aea87daa-9d23-11e6-83fe-cf34ae4563ed.png">

3) Create a new volume rendering.  (and hide the old one)  This now correctly shows the transformed (blurred) data.

<img width="1283" alt="screen shot 2016-10-28 at 3 30 30 pm" src="https://cloud.githubusercontent.com/assets/12242066/19819687/b3775bc6-9d23-11e6-9fea-e7ec17f8bfc4.png">

**Comment by cryos** [comment]
Thanks, you have given me more than enough to take a look (the recipe was enough), I can take a look, I suspect this is related to the changes I made to volume rendering.

**Comment by cryos** [comment]
This was merged, and the issue fixed in my tests. Thanks for reporting this, and let me know if you think there are any further issues.

**Comment by ElliotPadgett** [comment]
Looks good.
