### ISSUE TITLE
State files should use relative paths for data

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#72]
State files are storing absolute file paths for data.  If a state file (dir1/state) and data (dir1/data) are packaged in the same directory (dir1), then the entire directory is copied (to dir2) and dir1 is renamed or deleted, opening dir2/state fails and results in an error saying "Initialize: could not open file dir1/data".  Relative file paths should be used instead, so that Tomviz tries to open dir2/data.

This is a key issue for scientific reproducibility, as it prevents state files from being shared across computers.

**Comment by cryos** [comment]
I think we can get to it in 0.6, agreed on the use of relative file paths.

**Comment by ElliotPadgett** [comment]
Is there anything besides data files that needs this done?  Everything else (custom transforms, color maps, etc.) should be contained in the state file, right?

I'm wondering if this can be done entirely in the ModuleManager::serialize function via a file path conversion in the loop over data sources (maybe with an inverse conversion in ModuleManager::deserialize too).

**Comment by Hovden** [comment]
I noticed this is also a top feature request for Paraview: https://paraview.uservoice.com/forums/11350-general/suggestions/2222119-state-file-pvsm-and-relative-paths

**Comment by Hovden** [comment]
tomviz still crashes when moving directory containing the application and a state file (I'm using the OSX cdash build). As Elliot mentioned, we would like to be able to move a directory that contains the application, the data, and the state file to any other machine or directory. This should be possible using relative paths.

To reproduce / test:
1) Move tomviz.app and data into a directory
2) Run tomviz, load data, save state into the local directory
3) Move the directory containing tomviz, data, and save state.
4) Run tomviz in new directory and load state.

**Comment by mathturtle** [comment]
That's probably because the build for the version with the fix included is still in progress...

**Comment by Hovden** [comment]
Gotcha. Will test again on later build.

**Comment by Hovden** [comment]
Loading states with relative paths works well on Mac.

States files can now be distributed with the data for sharing visualization and analysis with other scientists.

Nice job.

**Comment by ElliotPadgett** [comment]
@Hovden @mathturtle Sorry, this still doesn't work for me on either the latest Windows or OSX nightly binaries.  It's still failing the test of changing the name of a higher order directory containing both state file and data.

**Comment by mathturtle** [comment]
What file type are you using to test this?  It could be that one of the readers is doing something funny and I missed it when searching for filenames.

**Comment by ElliotPadgett** [comment]
Raw data.  Let me try with something else.

**Comment by mathturtle** [comment]
Good catch... the raw reader needs to replace the FilePrefix instead of the FileName.

**Comment by ElliotPadgett** [comment]
Looks like it works with TIFF data!

**Comment by mathturtle** [comment]
Here is a patch that addresses this:
https://github.com/OpenChemistry/tomviz/pull/150

@cryos @Hovden

**Comment by ElliotPadgett** [comment]
For Tiff data this works well -- even cross-platform from Windows to OSX.
