### ISSUE TITLE
Check for minimum OpenGL version before opening application

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#745]
There are some reports of issues where it appears the Tomviz application never starts up. I want to add some extra caution by adding some code to our startup, before we show the application, to ensure the machine has at least OpenGL 3.2 and pop up a warning dialog if it does not.

ParaView/VTK should also have some code to check more thoroughly, but I would like to add a little extra checking and do what we can to explain why the application might not work correctly.

**Comment by cryos** [comment]
I would appreciate some testing on this now that it is merged. The main idea is to halt the startup if it looks like the computer doesn't have the required OpenGL version, pop up a warning, and then let them click OK to see if it really doesn't work. There have been a few reports that look like Tomviz has crashed, and I would like to more easily rule out simple stuff like not having a graphics card capable of OpenGL 3.2. VTK/ParaView should also pop up a warning dialog, but I don't see a good way to detect this in our application code and integrate the warning.

**Comment by cryos** [comment]
I am mainly hoping to get tests once the new binaries are build that verify the warning doesn't pop up on your systems.

**Comment by cquammen** [comment]
I got a warning on my year-old Mac about OpenGL 3.2 not being supported.

Graphics driver info reported in ParaView:

OpenGL Vendor - ATI Technologies Inc.
OpenGL Version - 4.1 ATI-1.42.15
OpenGL Renderer - AMD Radeon R9 M370X OpenGL Engine

I wonder if the Qt surface is picking up my Intel Iris Pro? That should support OpenGL 4.1 at least, though, according to https://support.apple.com/en-us/HT202823.

**Comment by cquammen** [comment]
The `QOpenGLContext` reports version 2.1.

**Comment by cryos** [comment]
That is weird, yeah both should support 3.2. Thanks for taking a look, I wonder if this is Mac being lame about offscreen contexts. I thought that would be simplest so that no random widget pops up during initialization.

**Comment by cquammen** [comment]
It might be grouchy about the specific version requested. I wonder if you need to work your way down from requesting version 4.1 to 3.2? I recall having to that for a similar function in a different project years ago.

**Comment by yijiang1** [comment]
The current binary version (539) fails to launch on my Windows 7 with this error:
![tomviz](https://cloud.githubusercontent.com/assets/13088588/20181664/08f10954-a72d-11e6-8f9e-8fa21a315c5d.png)

It works fine on Windows 10 without any error or warring.

**Comment by yijiang1** [comment]
On my Mac (10.11), I also get this warning message:
<img width="421" alt="screen shot 2016-11-07 at 4 43 37 pm" src="https://cloud.githubusercontent.com/assets/13088588/20181768/74ca27d2-a72d-11e6-8c0b-6a445f78fddc.png">

**Comment by mathturtle** [comment]
> The current binary version (539) fails to launch on my Windows 7 with this error:

Is your computer current on windows updates?  Report a separate issue and I'll look at this.

**Comment by cryos** [comment]
The failure to start is an entirely separate issue as Shawn said. I am going to disable this check as it seems at least on Mac there are too many false positives. I will see if I can figure out a more robust way of checking this for the next release.

**Comment by cryos** [comment]
We have added a number of changes in VTK, and I think this has improved. It isn't perfect, but I think it is at least improved. I would like to circle back given a little more time in the future to see if we can pop up a more explicit dialog, mainly impeded by strange behavior on macOS machines.

**Comment by zoetaite** [comment]
Hello...wondering this software has ever been tested in a VDI environment? We are currently migrating some of our Labs over to VMware Horizon View and we use a 3D software Renderer.

![image](https://cloud.githubusercontent.com/assets/28659305/26014145/6b7c99c6-3729-11e7-8b29-36653b2db938.png)

When I click would you like to load an example the application shows an error that tomviz.exe has stopped working.

Problem signature:
  Problem Event Name:	BEX64
  Application Name:	tomviz.exe
  Application Version:	0.0.0.0
  Application Timestamp:	58dbe98f
  Fault Module Name:	StackHash_1dc2
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	0000000000000000
  Exception Code:	c0000005
  Exception Data:	0000000000000008
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	1dc2
  Additional Information 2:	1dc22fb1de37d348f27e54dbb5278e7d
  Additional Information 3:	eae3
  Additional Information 4:	eae36a4b5ffb27c9d33117f4125a75c2


ZT

**Comment by cryos** [comment]
We have not tested in this type of environment, we really need GPU accelerated rendering for best performance. If there is no valid OpenGL we may be able to test out approaches using software rendering.
