### ISSUE TITLE
Advanced version information in about dialog

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#746]
Augment the about dialog to show some advanced version information, such as runtime Qt version, Python, ParaView, VTK, ITK, NumPy, etc where available. This should help make is easier to diagnose issues, and offer something easy to copy and paste more complete system state. I envision adding the same information to the state file so that is is all recorded, helping make even local builds offer more reproducibility.

**Comment by cryos** [comment]
I would favor exporting versions to JSON in the about dialog (maybe copy to clipboard or similar). The state file serves a different purpose, to aid in transparency/reproducibility. I had envisioned gathering all of this information in a small helper function that would populate the about dialog, copy a JSON/simple key-value pair to a clipboard, and enable us to insert more verbose information in the state file.

**Comment by cryos** [comment]
@cquammen The VTK version always says 7.1.0 for me, when I don't think it is. If this is an easy tweak I would fix it, otherwise maybe just drop it and keep the ParaView version for now at least - one is implied by the other as we do not manually move VTK back or forward.

**Comment by cquammen** [comment]
You are technically right that VTK is not at version 7.1.0. As it is unimportant, I think I'll just remove it.

**Comment by cryos** [comment]
Sounds great, I am happy with that. Once that is merged we can close this issue out - it satisfies my initial requirements and can be extended as needed in the future.

**Comment by cryos** [comment]
I am going to close this, #1103 removes the VTK version information as discussed.
