### ISSUE TITLE
Add checkbox to hide the Open GL check warning

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#750]
In the dialog that reports that a sufficient version of OpenGL is not available, add a checkbox that prevents the dialog from popping up in the future. This should prevent annoyance on systems on which Tomviz works fine but which for whatever reason report an insufficient version of OpenGL

**Comment by cryos** [comment]
We can add that, but quite frankly I would much rather improve the detection to be more accurate. The warning on its own will be enough to worry many users, even if they can suppress it. I am more inclined to disable it if it can't accurately detect the correct OpenGL version on all platforms.

**Comment by cquammen** [comment]
I figured you would say that 😃 . I'll close for now.

**Comment by cryos** [comment]
I want our users to have a good experience, and don't want to worry them unnecessarily.
