### ISSUE TITLE
Convert VTKArray to numpy array

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#751]
Is it possible to convert the array returned by `utils.get_array()`  function to a numpy array?

Some scipy functions only work with numpy arrays.

**Comment by cjh1** [comment]
@yijiang1 It does return a numpy array?

```
>>> isinstance(utils.get_array(dataset), numpy.ndarray)
True
```

Is there something in particular that isn't working with scipy?

**Comment by yijiang1** [comment]
Yeah. For example, running
`from scipy import ndimage`
`array = utils.get_array(dataset)`
`ndimage.measurements.center_of_mass(array)`

would give me this error:
  File "/Library/Python/2.7/site-packages/scipy-0.18.1-py2.7-macosx-10.11-intel.egg/scipy/ndimage/measurements.py", line 1289, in center_of_mass
    return [tuple(v) for v in numpy.array(results).T]
TypeError: 'numpy.float64' object is not iterable

**Comment by cjh1** [comment]
@yijiang1 I will investigate this issue

**Comment by yijiang1** [comment]
Thanks. This is not very urgent for me since it's not hard to implement a `measurements.center_of_mass` function.

Also, I notice this difference that may be relevant:
`array = utils.get_array(dataset)`
`print type(array)`
prints out "class 'vtk.numpy_interface.dataset_adapter.VTKArray'"

`array = np.array([1, 2, 3])`
`print type(array)`
prints out "type 'numpy.ndarray'"

**Comment by cryos** [comment]
Is it because it is seeing a double, and we should prefer 32 bit floats? It looks like it is a numpy array but there is an issue with the type.

**Comment by cjh1** [comment]
I don't think its a type issue. I have done a little digging and I think its because the VTK implement of ndarray returns an array when sum(...) is called rather than a scalar, I am trying to figure out why.

**Comment by cjh1** [comment]
The [following](https://gitlab.kitware.com/vtk/vtk/merge_requests/2170) merge request in VTK should resolve this issue. Once it has been merged into VTK and will ensure it gets into ParaView and then into tomviz.

**Comment by cjh1** [comment]
Ok, the VTK change in now in ParaView, I have pushed the super build forward, so tonight's binaries should have the fix.

**Comment by yijiang1** [comment]
Yes this is fixed on current binaries.

**Comment by cjh1** [comment]
Awesome!
