### ISSUE TITLE
View properties and Parallel projection mode more visible to users

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#755]
This request is tangentially related to #666 (spooky).

I just found out that you can change the camera perspective mode by opening the View/View Properties panel and then checking the box next to Camera Parallel Projection. I think this option should be more visible to the user and even possibly replacing the 3D/2D button (the change interaction mode button) at the top of the render window.

The Interaction mode provides a parallel perspective view, but does not allow the user to rotate the object. The Camera Parallel Projection option is much more useful for visualizing data.

I also think that the view properties panel should be more visible because it is also very useful. It should open with the "advanced" option (the gear button in the upper right) turned on. I suggest adding a button above the render window or making it part of the right click context menu (which only currently has Set Background Color).

tomviz0.9.1-274 OSX

**Comment by mathturtle** [comment]
There is a menu items in the View menu that lets you change whether the camera uses Parallel projection or not.  See View => Parallel Projection and View => Orthographic Projection.  We can definitely improve the visibility of some of the more useful options.

**Comment by ercius** [comment]
That works! Sorry I did not see that in the view menu.
