### ISSUE TITLE
Rotate transform is broken in 0-9-2

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#758]
The rotate transform is not working in 0-9-2 on OS X as it is written out from the Tilt Axis Alignment (manual) alignment widget.

Here is the error I get:
```
Failed to execute the script. (:0, )
Traceback (most recent call last):
  File "Rotate", line 22, in transform_scalars
UnboundLocalError: local variable 'rotation_axis' referenced before assignment
```
The user specified variable are not currently set by the widget:
```
#----USER SPECIFIED VARIABLES-----#
    ###rotation_axis###    #Specify Tilt Axis Dimensions x=0, y=1, z=2
    ###rotation_angle###   #Rotate the dataset by an Angle (in degrees)
    #---------------------------------#
...

```
 The user specified variables need to be written into the script. For example:
```
#----USER SPECIFIED VARIABLES-----#
    rotation_axis = 2    #Specify Tilt Axis Dimensions x=0, y=1, z=2
    rotation_angle = -3   #Rotate the dataset by an Angle (in degrees)
    #---------------------------------#
...
```

**Comment by mathturtle** [comment]
@ercius I've tracked it down.  The variable names that had to be substituted in changed and the change didn't update this piece of code to use the new names.  I have pushed a branch that will fix this.

**Comment by ercius** [comment]
@mathturtle Thanks for fixing this so quickly!
