### ISSUE TITLE
 Crop_Data.py is currently not used, needs to be connect with the "SelectVolumeWidget"

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#767]
For Crop_Data.py, we want to connect it with the "SelectVolumeWidget" (see the code for "Background Subtraction (Manual)" in AddPythonTransformReaction.cxx for example).

**Comment by cquammen** [comment]
It appears to me that the CropOperator offers the same functionality intended by `Crop_Data.py`, and it already uses the "SelectVolumeWidget". I suggest the file be removed, but it's not urgent for the 1.0 release.
