### ISSUE TITLE
Crash when closing script window after deleting the transform

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#768]
1. Load a dataset.
2. Do a transform. For example, "Delete Slices".
3. Open the python script by double-clicking it in the pipeline.
<img width="500" alt="screen shot 2016-11-23 at 12 50 50 pm" src="https://cloud.githubusercontent.com/assets/13088588/20572992/cbec154a-b17b-11e6-8eb9-ef9c2cf44c97.png">

4. Go to main window and delete the transform (keeping the script window open).
<img width="500" alt="screen shot 2016-11-23 at 12 51 01 pm" src="https://cloud.githubusercontent.com/assets/13088588/20573006/d7473582-b17b-11e6-8ebb-9e2b8cf49635.png">

5. Go back to the script window, click "OK" or "Cancel". 
6. Tomviz crashes.

**Comment by cquammen** [comment]
Thanks for the report. The script dialog is now closed if the operator is deleted.
