### ISSUE TITLE
Set Scale (in nm, angstroms etc.)

### ISSUE THREAD

**Issue by bdalevin** [OpenChemistry/tomviz#770]
I have a request for a "Set Scale" option. This is for an article Hovden and I are working on. 

Currently, tomviz will display the number of voxels along each axis of the bounding box if you select "Show Axis Grid" under the "View" menu. An example is shown below. 
![show axis](https://cloud.githubusercontent.com/assets/12704237/20576738/275ae364-b18d-11e6-9b0b-67a6cbc132ea.jpg)

It would be very useful if there was a "Set Scale" option in tomviz. "Set Scale" would allow users to tell tomviz the scale of their object in nanometers (or angstroms, or microns etc) per voxel. In the visualization, units of length, instead of voxels, would then be displayed on the bounding box. 

This would be a very powerful tool, allowing researchers to export figures for publication with a meaningful scale bar directly from tomviz.

**Comment by cryos** [comment]
This should already be working, see
![image](https://cloud.githubusercontent.com/assets/42214/20577238/7a64cc8a-b18f-11e6-91fa-957407526188.png)
where I set the units in the data properties to nm, and then are displayed in the axes grid.

**Comment by cryos** [comment]
You may have to settle for 'A' as the Unicode rendering support is a little tricky in the 3D rendering code (there is some there, but we don't do the work to feed the font rendering engine a full font file (we should consider doing this, but for now you are limited to the standard character set).

**Comment by bdalevin** [comment]
Thanks for the quick reply! I've got it working. 
This is a great feature! I'll add it to the next version of the user guide to make sure others can use it too.

Issue solved.
