### ISSUE TITLE
Improve transformation between VTK and ITK image data types

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#778]
The VtkGlue module in ITK provides conversion utilities that give ITK a view of VTK image data without copying. Enable this to reduce memory usage and improve performance.

**Comment by cryos** [comment]
We have talked about this before, but we would rather avoid rebuilding ITK every time we update ParaView/VTK. It would increase our build time quite significantly, and it isn't clear that this is a major bottleneck at this time. Ideally ITK exposes its arrays to numpy views in the same way VTK does, I am guessing there is no ItkGlue module as we are recompiling that anyway...
