### ISSUE TITLE
Add label to progress bar dialog

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#782]
Could we add a label to the progress bar dialog that displays messages and can be updated in python script?
This is very useful for reconstructions which often have several steps. I'd like to print messages such as "Initialization...", "Iteration 1/10" and "Slice 1/256".

**Comment by cjh1** [comment]
@yijiang1 Yes, we could do this. We could add an optional parameter to the update method. So you python code would looks something like:

```python
self.progress.update(10,  message='Iteration 2/10')
```

or we could have a separate method


```python
self.progress.message('Iteration 2/10')
```

**Comment by yijiang1** [comment]
Either ways seems good to me. Thanks!

**Comment by cjh1** [comment]
@cryos Do you have preference? I almost think that update(...) was a bad choice of name. May we should just have properties of the form:

```python
self.progress.value = 10
```


```python
self.progress.message = 'my message ...'
```

**Comment by cryos** [comment]
My take on this is that we don't want to give too much detail (outside of debugging), and I would feed additional detail in as the progress bar title. If we want to support more detail than that then the best method would be to use the status bar of the main window as this is designed to communicate longer messages about the current application state/activities.

I like the proposed API in the previous comment the most.
