### ISSUE TITLE
New Python Operators don't serialize arguments to python scripts

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#784]
We need to save the `QVariantMap` with the arguments out to the xml.  We have some options, but none of them are great:

* Use `QXmlStreamWriter` to write out an xml document, read it back in with `pugixml` and merge the two xmls.
* Use `QJson` to write it to json and store the json in our xml state file.
* Use `QDataStream` to write it to Qt's cross platform binary format, base-64 encode it and include it in the xml that way.

@cryos @cjh1 @cquammen Thoughts?

Most helpful page (second answer):
https://stackoverflow.com/questions/19185853/serialize-a-data-structure-in-text-format-in-c-qt

**Comment by cjh1** [comment]
@mathturtle I'm not sure QXmlStreamWriter helps us here, it doesn't have support for writing QVariant?

**Comment by mathturtle** [comment]
@cjh1 One of the threads I found was using it.  Maybe they had some glue code I missed.

**Comment by cjh1** [comment]
Yes, it probably had a case statement to perform the actual conversion. The QJson approach will also be a 'lossy' conversion as several numeric types would just be mapped to JSON's numeric type. The fourth option that we discussed would be write a conversion routine for the subset of QVariant types we use, which is currently just,  int, double, bool and list. We already have similar code that converts a QVariant to a PyObject [here] (https://github.com/OpenChemistry/tomviz/blob/master/tomviz/PythonUtilities.cxx#L43-L66) which would need to be modified anyway is we broaden the range of type we support, so in a way 'the boat has already floated' ...

**Comment by cryos** [comment]
I think embedding JSON in the XML state file would be best, we already embed Python in their for custom scripts.

**Comment by cryos** [comment]
XML or JSON works for me, I wouldn't worry about the numeric issue as the operator JSON specifies the type that could be used for coercion. I would like to look at this before the next release, and I would like to experiment with a more minimal JSON state file so something that was easy enough to reuse would be nice.

**Comment by cjh1** [comment]
Fixed by #803
