### ISSUE TITLE
Support coloring contours by nearest label map value

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#793]
We wrote a blog post showing this feature off, and it would be great to bring it back. We might want to break this out into more issues but going beyond coloring by the ID I would like to color by radius, volume, surface area, or other calculated values from the connected components label for example.

**Comment by tjcorona** [comment]
This issue is partially addressed by MR #941.

**Comment by cquammen** [comment]
@tjcorona Do you have a set of steps to run in Tomviz to show off the patch in #941, e.g., load data set, apply transform, create contour, set color map range, etc. I'm having trouble getting something reasonable visualized.

**Comment by tjcorona** [comment]
Sure! I just followed your rubric: https://github.com/OpenChemistry/tomviz/pull/823

**Comment by cquammen** [comment]
Another issue: we should disable point-to-cell data and nearest neighbor interpolation when coloring by "This Data".

![image](https://cloud.githubusercontent.com/assets/360056/23527484/20a72f76-ff64-11e6-97bc-e7aea01d24a1.png)

**Comment by tjcorona** [comment]
I agree. Would you like me to put up a MR for it?

**Comment by cquammen** [comment]
Sure. I'm happy to test it.

**Comment by cryos** [comment]
I think we have resolved a lot of issues here, please reopen if I am mistaken.
