### ISSUE TITLE
Cannot save child table datasets to CSV files

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#801]
My guess would be that folks will want this capability.

**Comment by cryos** [comment]
This was resolved in #966

**Comment by cquammen** [comment]
Hmm, #966 was closed because it was a duplicate of this issue. I just tested in recent master whether it was possible to save the table data out to a CSV file and it was not. One can save only the Point, Cell, or Field data from the current DataSource image.

**Comment by cryos** [comment]
Thanks @cquammen, I obviously misread as I was working through stale bugs.

**Comment by cryos** [comment]
This is now resolved.
