### ISSUE TITLE
Progress animation does disappears when its row is selected on Mac

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#802]
When an operator is running, select the operator's row in the Pipelines panel. You cannot see the progress animation.

**Comment by mathturtle** [comment]
Is it just that the progress dialog is behind the main window?  That is a known issue on OSX, dialogs are not kept in front of their parent and it is a bug in Qt (if it is a bug).

**Comment by cquammen** [comment]
No, I mean the little spinning icon in the Pipeline panel, not the progress dialog.

![image](https://cloud.githubusercontent.com/assets/360056/21274225/06fc25dc-c395-11e6-988c-a8fb7d2491c7.png)

**Comment by cjh1** [comment]
I had seen that, not sure why

**Comment by cryos** [comment]
This is now fixed
