### ISSUE TITLE
Histogram remains even after dataset has been removed

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#816]
After removing a dataset from the pipeline its histogram remain. See screenshot below.

![screen](https://cloud.githubusercontent.com/assets/1031053/21896073/0b40f8f6-d8b3-11e6-893f-0ad9434268ca.png)

**Comment by Hovden** [comment]
Yep. Thats been a long standing UX issue. Fixing would improve a users impression of tomviz.
