### ISSUE TITLE
Auto save state and restore when tomviz crashes.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#82]
Tomviz crashes frequently. To alleviate this issue, we should have an auto save state that runs every so often and restores the last known state in the event of a crash. It could prevent a user from losing hours of work.

**Comment by cryos** [comment]
We also need to get recipes to recreate the crashes, and fix the issue. Autosave or not, most people will get frustrated with an application that "crashes frequently". I would like to prioritize getting crash reports so that we can work on fixing the underlying bugs.

**Comment by Hovden** [comment]
Crash reporting would make crashes more transparent and noticed. We'll definitely report re-creatable bug recipes when noticeable. This would just be the ad-hoc "Microsoft Office" solution for everything we don't catch.

**Comment by Hovden** [comment]
Basic use case tested on OSX and Windows 32-bit.
