### ISSUE TITLE
Progress dialog's title changes when adjusting window size on Mac

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#821]
1. Load a dataset, mark it as tilt series.
2. Run a tomography reconstruction, say Direct Fourier Method.
3. As mentioned in  #786, on Mac, status messages are displayed only in status bar and the progress dialog looks like
<img width="506" alt="screen shot 2017-01-16 at 3 45 11 pm" src="https://cloud.githubusercontent.com/assets/13088588/21998579/b87979e6-dc03-11e6-8803-ff510d0be13e.png">
 
4. Now, shrink the window size and status message will show up in the title.
<img width="439" alt="screen shot 2017-01-16 at 3 45 37 pm" src="https://cloud.githubusercontent.com/assets/13088588/21998627/0040e82c-dc04-11e6-9739-5708bb4378de.png">

**Comment by cryos** [comment]
We were aware of this, but it is a macOS/Qt level issue. This is why we added the status bar updates, I am not sure why you are reporting this. I don't see a simple way to force consistency, and I think with the addition of status bar updates gives us a reasonable way of providing updates.

**Comment by yijiang1** [comment]
Ah, sorry I missed this report in #786. I thought this is something new.
