### ISSUE TITLE
It is possible to delete just a child dataset without deleting the producing operator

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz#825]
It is currently possible to delete a child dataset:

* Load SMALL_PtCu_NanoParticle.tiff
* Data Transforms -> Binary Threshold, default parameters
* Click on the child dataset named "Threshold Segmentation" and hit the delete key

The child dataset is deleted. It doesn't seem like this should be possible.

Note that the child data set can be regenerated by clicking on the "Binary Threshold" transform and click Apply in the Properties panel. So it kind of works in a reasonable way.

**Comment by cryos** [comment]
Yes, we should refine some of these pipeline behaviors to be more consistent. Thanks for pointing this out.

**Comment by cquammen** [comment]
Update: it is not longer possible to delete child datasets via the context menu, but it is possible to delete with the delete key.

**Comment by cquammen** [comment]
I must have been confused before. It is possible to delete child datasets via the context menu.

**Comment by cryos** [comment]
This is resolved in master now.
