### ISSUE TITLE
vtkColorTransferFunctionItem doesn't resize after being hidden

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#828]
Steps to recreate:

1. Load SMALL_PtCu_NanoParticle.tif
2. Load MEDIUM_CoP_NanoParticle.tif
3. Remove MEDIUM_CoP_NanoParticle.tif
4. Remove SMALL_PtCu_NanoParticle.tif
5. Load SMALL_PtCu_NanoParticle.tif

The histogram will look like the following screenshot:

![screen](https://cloud.githubusercontent.com/assets/1031053/22073068/4bbe58f6-dd72-11e6-83e4-970c4f0ee0a8.png)

**Comment by cryos** [comment]
Resolved.
