### ISSUE TITLE
Latest Mac build not opening

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#832]
The current cdash build for mac is not executing:
<img width="418" alt="screen shot 2017-01-19 at 10 07 41 am" src="https://cloud.githubusercontent.com/assets/6197997/22111930/2e3565a0-de2f-11e6-91a9-5d7fa51dd880.png">

**Comment by cryos** [comment]
I will look into this now

**Comment by cryos** [comment]
The fixup bundle script that is used as part of the packaging process is failing early with a non-existent dependent library. We are working on tracking down what is causing the issue, we will hopefully have this fixed up soon.

**Comment by cryos** [comment]
This is now fixed, it was an issue with our packaging script and some Qt plugins we were not making use of.
