### ISSUE TITLE
Visualization does not update automatically when changing the values in "Unit and Size"

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#834]
1. Load a dataset. Click View Menu -> Show Axis Grid
<img width="1032" alt="screen shot 2017-01-20 at 11 21 22 am" src="https://cloud.githubusercontent.com/assets/13088588/22156814/f57eaf4e-df02-11e6-8355-0b46de7dd2bc.png">

2. Edit X/Y/Z values in the "Unit and Size" panel. The outline and axis grid do not update automatically.
<img width="1029" alt="screen shot 2017-01-20 at 11 22 41 am" src="https://cloud.githubusercontent.com/assets/13088588/22156898/4aa1f710-df03-11e6-98db-7044a511e2a1.png">

3. I have to redraw outline and axis grid to see the changes.

**Comment by cquammen** [comment]
Are you still planning to work on this one @cjh1 ?

**Comment by cjh1** [comment]
Yes, almost done with it ...
