### ISSUE TITLE
Add support for OME-TIFF

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#836]
This is an open format that we should add support for, it uses a combination of TIFF for binary data and XML for metadata. The format specification is at the following link:

https://www.openmicroscopy.org/site/support/ome-model/ome-tiff/

**Comment by thewtex** [comment]
Note that ITK now has very good support for SCIFIO IO, which has support for most of the OpenMicroscopy formats.

**Comment by cryos** [comment]
I don't want to depend on a Java framework for file IO, it is good to know, but I think for the size of data we are looking at having something read into one memory block in C++ would be preferable. We should investigate how easy it would be to use ITK through the Python interface to load data formats it supports.

**Comment by cryos** [comment]
This was merged a little while back, and we have at least basic support now.
