### ISSUE TITLE
Add support for MetaImage and NRRD Image IO

### ISSUE THREAD

**Issue by thewtex** [OpenChemistry/tomviz#837]
I am having a hard time creating 3D images I can view in tomviz.

Most scientific processing tools, especially the ITK-based ones, have support for MetaImage (.mha) and NRRD (.nrrd) formats. They are N-Dimensional, support a variety of pixel types, and have good support for associated image metadata like the origin, etc. I see ParaView has support for these, so hopefully it would not be too much work to add them to tomviz.

**Comment by cryos** [comment]
I have never heard of these formats, if it is a matter of exposing the ParaView readers it shouldn't be a big deal. We can take a look, but @cjh1 just added support for reading TIFF image stacks, and TIFF volumes have worked well for quite some time. There is also XDMF (HDF5 based) that many people use.

Where are these file formats generated? What domains are you thinking of? It isn't something I have come across as a ParaView developer either.

**Comment by thewtex** [comment]
MetaImage is the most common format I work:

  https://github.com/Kitware/MetaIO

NRRD is pretty common the medical domain:

  http://teem.sourceforge.net/nrrd/format.html

NRRD may not be as applicable to tomviz, but MetaImage is extremely common in the ITK/VTK community.

**Comment by thewtex** [comment]
Confirmed that the TIFF stacks work with the latest Nightly binary :+1: .

Still would like MetaImage support ;-)

**Comment by cryos** [comment]
We will look into it, do you know where some sample files with volumes in them might be? I have seen that library name, but know little else about them. Looking at the links they seem very medical which might explain it :-) We have a simple file reader white list, so it shouldn't take much work to test and add them once we have a sample file.

**Comment by thewtex** [comment]
Thanks for the consideration.

Here's a file from the VTK test suite:

  https://midas3.kitware.com/midas/folder/10149

There are a bunch more:

  https://midas3.kitware.com/midas/search/index?q=.mha

**Comment by cryos** [comment]
So we have MetaIO, it should be in one of the next binaries. We should see if we can do the same for NRRD, https://midas3.kitware.com/midas/search/index?q=.nrrd doesn't show any obvious volumes, is there a good sample file you have to hand there?

**Comment by thewtex** [comment]
Thank you!

Here's a testing dataset for NRRD:

  https://data.kitware.com/#item/588275628d777f4f3f30816e

**Comment by cquammen** [comment]
Just to chime in here - there are restrictions on which kind of Nrrd files ParaView can load - compressed Nrrds cannot be read, for instance. The full list is at: http://www.vtk.org/doc/nightly/html/classvtkNrrdReader.html#details

**Comment by cryos** [comment]
That sounds fine, we aren't going to extend the format in ParaView but if it would be useful to read in volumes from the format with a few lines of code I am all for it.

**Comment by mathturtle** [comment]
@thewtex When I try to read your test dataset I get:
```
ERROR: In /home/shawn/dev/paraview/src/VTK/IO/Image/vtkNrrdReader.cxx, line 401
vtkNrrdReader (0x56499bfe2f90): Unsupported encoding: gzip


ERROR: In /home/shawn/dev/paraview/src/VTK/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkPVCompositeDataPipeline (0x56499bebb9e0): Algorithm vtkNrrdReader(0x56499bfe2f90) returned failure for request: vtkInformation (0x56499bedc910)
  Debug: Off
  Modified Time: 181248
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
```

ParaView just won't read it.  Tomviz segfaults.... I'll look into the crash.

**Comment by mathturtle** [comment]
It looks like we don't check if the reader fails, we just create a DataSource with the empty image... and then the code to make the histogram crashes because it doesn't handle that.

**Comment by thewtex** [comment]
@mathturtle Thanks fro the update and effort.

It sound the crash further in the pipeline is worth a fix for other reasons. 

The lack of gzip support in NRRD is not worth pursuing further -- MetaImage support is good for me.

Thanks for the help on this issue!
