### ISSUE TITLE
Get / Set Tilt Angles in Python

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#84]
In addition to setting the tilt-angles associated with a dataset, we need to be able to get them in Python for reconstruction. Right now they are hard-coded into the reconstruction, but in real life every dataset will have a different set of tilt angles.

It would also be good to set the tilt angles from within Python. There may be reasons to change them.

**Comment by mathturtle** [comment]
I think this is added by my branch last night, #142.

**Comment by Hovden** [comment]
@mathturtle can you show me an example of how to get and set the angles for a dataset within python? Then I can test and close this.

**Comment by mathturtle** [comment]
Given the @yijiang1 is using this in his Delete slices branch #189, I think it can be closed.  For a simple example of how to use this, open a dataset, mark it as a tilt series and create a custom transform.  The python code displayed updates if the dataset is a tilt series to show how to do this.
