### ISSUE TITLE
Volume render unresponsive

### ISSUE THREAD

**Issue by JeremyHorst** [OpenChemistry/tomviz#842]
Hi Team, Love your software.
1. Downloaded nightly build on 2017-01-27 onto a mid-2012 macbook pro (new), loaded data great, 2D views perfect. Add volume render, icon appears, but no rendering. Turned off, tried again with different data set, all that. No dice.
2. Could you please please add in an option for a scale bar?
Peace and Thanks,
Jeremy - UCSF DeRisi Lab

**Comment by Hovden** [comment]
Jeremy,

Thanks for the input. We will look into the rendering. Just a note, I have had issues when OSX is not fully updated. Make sure the "eye" icon is not "off" in the data pipeline (shouldn't be off by default).

We will add features that improve the scientific display of scale as soon as possible.

**Comment by yijiang1** [comment]
> Make sure the "eye" icon is not "off" in the data pipeline (shouldn't be off by default).

The visualization is On when the icon looks like this

<img width="249" alt="screen shot 2017-01-27 at 9 32 47 pm" src="https://cloud.githubusercontent.com/assets/13088588/22393627/6633e102-e4d8-11e6-84cb-4f75cab90909.png">
Off looks like

<img width="251" alt="screen shot 2017-01-27 at 9 32 39 pm" src="https://cloud.githubusercontent.com/assets/13088588/22393626/6184fce0-e4d8-11e6-9b98-1a372197e8c9.png">

We do have a scale bar feature: click View menu and the click "Show Axis Grid".

To edits the labels, first highlight your data in pipeline:
<img width="290" alt="screen shot 2017-01-27 at 9 57 58 pm" src="https://cloud.githubusercontent.com/assets/13088588/22393761/f05d462c-e4db-11e6-80d7-eee372b6c90a.png">

Then, you should see a "Units and Size" section in property panel
<img width="282" alt="screen shot 2017-01-27 at 9 58 03 pm" src="https://cloud.githubusercontent.com/assets/13088588/22393775/3136f576-e4dc-11e6-8b1b-33833444f108.png">

The default X/Y/Z values are the number of voxels in each dimension and default unit is "nm". 
There is a bug in current version: if you edits the "Units and Size" section, you have to refresh visualization (by toggling the eye icons).

**Comment by JeremyHorst** [comment]
Huh. Thanks very much for the quick reply. Do you have a concept of how large a tiff stack can be handled by TomViz? I have 16GB, so thought a 700MB stack would be okay (with minimal other processes running), but I think the problem was simply that the file was too big. I downsized with to ~135MB in imageJ and then bin-2-ed it in tomviz, and it loaded & showed. When it loaded it did so shifted a bit away from the 2D slice and grid box, but that's fine.

Definitely not the eye icon.

I'll keep playing and let you know. Maybe my it was something weird with my computer.

Peace and thanks,
Jeremy

**Comment by cryos** [comment]
I test quite regularly with a 510MB and 909MB TIFF volume, I just took a look at the latest nightly binary with the 909MB stack and it worked fine on the Mac test machine I have. I also test a 1025^3 volume, and just verified the volume rendering there. It is possible you are hitting the limits of your graphics card, which is harder to detect for us. The volume rendering code uploads the volume to the graphics card and uses accelerated rendering techniques but that means there must be enough GPU memory to accommodate the volume.

**Comment by JeremyHorst** [comment]
Thanks very much for your time in looking into this and responding. I used another machine and it worked fine. Sorry about the trouble. Please feel free to close or delete the issue I brought up, or instruct me how to do so.

I do reiterate the issue on the scale bar - it would be sweet to have an unobtrusive scale bar that could hide in a corner, instead of the big encompassing prism.

And thank you again for your efforts putting together this great resource.

Peace and thanks,
Jeremy

**Comment by Hovden** [comment]
Great. We have worked hard to make 3D viz accessible on low performance machines, but for ultimately big datasets will require more resources.

I have added a scale cube to the feature request: https://github.com/OpenChemistry/tomviz/issues/843
