### ISSUE TITLE
Scalecube

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#843]
We should add a scale cube to the volume reader. It would be a small cube that is labeled with its size (e.g. 10nm, 10um, etc.).

**Comment by cryos** [comment]
Isn't this a visual element you are suggesting, not seeing why it would be added to a reader.

**Comment by Hovden** [comment]
Corrected. You are right, it is a visual element—was a typo, meant to say "render".

**Comment by cryos** [comment]
No worries, I wanted to confirm I understood.

**Comment by yijiang1** [comment]
The current axis grid encloses all datasets in rending window.
<img width="514" alt="screen shot 2017-02-02 at 10 45 29 am" src="https://cloud.githubusercontent.com/assets/13088588/22556388/f494d432-e934-11e6-8f00-33195d424247.png">

**Comment by yijiang1** [comment]
A temporary solution is to implement a transform that adds a cube to data set?
<img width="300" alt="screen shot 2017-02-02 at 12 33 43 pm" src="https://cloud.githubusercontent.com/assets/13088588/22560914/49c3ddc2-e944-11e6-9a79-1b04ff667459.png">

**Comment by tjcorona** [comment]
#917

**Comment by cquammen** [comment]
I have a bug to report on this feature. Should we close this issue since #917 is merged in master and open another issue?

**Comment by Hovden** [comment]
@tjcorona I like the scale cube implementation. The most needed feature is the ability to turn on / off the annotation overlay (e.g. "(9nm)^2").

I also prefer to call it a 'scale cube' since that is already used by geologists and anthropologists (http://scaleobjects.com/photographycubes/photography.html)

**Comment by tjcorona** [comment]
@Hovden Thanks for the feedback! Here are the changes you suggested: https://github.com/OpenChemistry/tomviz/pull/988

**Comment by Hovden** [comment]
OK. I think this looks good to close. Moving the cube and changing its color would be obvious next features, but not critical to the functionality.

**Comment by cryos** [comment]
Thanks for the reviews @Hovden, I think this is looking great.
