### ISSUE TITLE
Crash when closing progress message dialog during transform

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#850]
tomviz crashes if I close (by clicking the cross button <img width="22" alt="screen shot 2017-01-31 at 3 39 30 pm" src="https://cloud.githubusercontent.com/assets/13088588/22483492/864ea6a2-e7cb-11e6-9523-025097509c0d.png">) the progress message dialog during a transform.

**Comment by mathturtle** [comment]
We were testing similar things... if you have a transform running and click the X button on the tomviz main window, you end up with a zombie background thread that is stuck in its event loop.  I have #852 to help steer users away from this, but it doesn't actually fix it.

**Comment by yijiang1** [comment]
The latest binary (0.9.3-16-g6b94623) on Mac still crashes when doing tomographic reconstructions.

**Comment by mathturtle** [comment]
The fix for this issue didn't make it into the release.  Did you click the X button on the progress dialog when testing this or did the reconstructions crash without you doing anything?  I'm having trouble making it crash, although I am seeing some errors when trying to run the FFT-based reconstructions.

**Comment by mathturtle** [comment]
Misclicked the 'comment and close button'... oops.

**Comment by yijiang1** [comment]
> Did you click the X button on the progress dialog when testing this

Yes. The reconstruction works fine itself.

I often use Weighed Back Projection for testing (with default parameters).

**Comment by mathturtle** [comment]
It doesn't seem like Qt provides a good way to hide the X button.  At least not without direct platoform-level calls.  There are some flags, but the implementation is free to ignore if the platform doesn't support it.  I have a branch (#886) that should fix the crash though.  But if the operator doesn't support canceling, it will keep running in the background until it finishes.

**Comment by cjh1** [comment]
@yijiang1 I think this can be closed?

**Comment by yijiang1** [comment]
Yup it doesn't crash any more.
