### ISSUE TITLE
Default to Jitter ON

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#851]
I like the volumetric jitter function that was added for reducing aliasing / sampling artifacts. I propose that we turn this on as a default. Thoughts?

**Comment by yijiang1** [comment]
1. What exactly does "jittering" do?
2. I don't see significant changes for the datasets I have (sample data and Elliot's nanoparticles).

**Comment by Hovden** [comment]
For the undersampled datasets (e.g. the start np) you will notice it "washes" out the effects of pixelation slightly. It adds a grainy texture in place of a pixelated texture. This is most noticeable when tomviz heavily downsamples during a users rotation (e.g. load your generate nps at 256^3 and rotate it around).

It is a form of dithering—I haven't looked into the details. Some information here:
http://www.mccauslandcenter.sc.edu/mricrogl/shaders

**Comment by yijiang1** [comment]
This is a 128^3 random data set. With or without jittering look very similar to me.
<img width="300" alt="screen shot 2017-01-31 at 5 26 33 pm" src="https://cloud.githubusercontent.com/assets/13088588/22487320/e494c728-e7da-11e6-8757-e68c75644c62.png">    <img width="300" alt="screen shot 2017-01-31 at 5 26 45 pm" src="https://cloud.githubusercontent.com/assets/13088588/22487321/e56e95a2-e7da-11e6-8dd9-d06aa7808d13.png">

I'm not against setting jittering to default, as long as it's not confusing to inexperienced users.

**Comment by cryos** [comment]
I don't think it has an enormous effect, it was actually on by default and they changed the default last year some time in VTK. I think it would be reasonable to make it default, and that can be reflected in the user interface.

**Comment by cryos** [comment]
This is now merged
