### ISSUE TITLE
Text resolution changes in open file dialog

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#858]
Click menu -> Open
Mouse over different regions, sometimes text resolution changes for about a second.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/13088588/22598674/3d116bd0-ea02-11e6-914d-2bcae350053d.gif)

This is minor but noticeable.

**Comment by cryos** [comment]
To the best of my knowledge this is a native macOS dialog, and we are using it. I see what you mean, but I think it is a macOS bug, and so there is no way we can fix it (you could report it to Apple). If any of our macOS experts know better please let me know, I actually want to make sure we always use the native dialogs where possible as they have better OS integration (favorites, etc), but we lose some control as we must accept what they offer.

**Comment by cryos** [comment]
Closing this for now as this looks like an operating system level dialog bug, updating to Sierra may improve things. Please reopen if it looks like it might be something at the Tomviz level.
