### ISSUE TITLE
Tomviz Icon Missing In 0.5 Windows 7 install

### ISSUE THREAD

**Issue by bdalevin** [OpenChemistry/tomviz#86]
Let's call this a minor branding bug:

Just installed Tomviz 0.5, 64 bit on Windows 7. The tomviz icon is not appearing with the application. 
The install package is probably just missing the .ico file.

**Comment by cryos** [comment]
Thanks for reporting this, I will look into it and get it fixed up.

**Comment by bdalevin** [comment]
Just an update in case it helps: I've just installed 0.5 on the other Windows PC in my lab. The tomviz icon is displayed for the installer (tomviz-0.5.0-Windows-64bit.exe), but not in the installed application (tomviz.exe).

**Comment by cryos** [comment]
I should hopefully have this fixed shortly, just waiting on a Windows binary installer build to verify.

**Comment by cryos** [comment]
Verified this is resolved in the nightly binary, and will be working in the next release.

**Comment by bdalevin** [comment]
Just tested out the binary, and confirmed icon is back!
