### ISSUE TITLE
Crash when closing RenderView window

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#869]
Binary: 0.9.3-16-g6b94623 on Mac
1. Load a data set
2. Close RenderView by clicking the x button:
![picture1](https://cloud.githubusercontent.com/assets/13088588/22715245/14f720b8-ed5e-11e6-8878-3e2674d41a14.png)
3. Crash

**Comment by yijiang1** [comment]
After #871 , clicking the X button no longer crash tomviz.

However, there is a new bug:
After closing the RenderView, information about the dataset still exists in the pipeline. Clicking it can crash tomviz.

**Comment by cryos** [comment]
Yes, we were looking at this, the visualization modules need to be removed if a render view is removed otherwise things will crash. This was the simplest fix, but we will follow up with more fixes to resolve outstanding issues.

**Comment by cryos** [comment]
This should now be resolved.
