### ISSUE TITLE
Can't load datasets to multiple RenderViews

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#870]
Binary: 0.9.3-16-g6b94623 on Mac

When there are multiple RenderViews, dataset l load or generate always show up in the first RenderView.

**Comment by cryos** [comment]
Confirmed, you can add stuff to the views but the data load only works in the first view in master.

**Comment by cryos** [comment]
This has been resolved.

**Comment by yijiang1** [comment]
Binary: 0.9.4-35-g807197b

Sample datasets that are created by python transforms still go to the first RenderView window.

**Comment by cquammen** [comment]
Confirmed in master.

**Comment by cryos** [comment]
So #1018 resolves this second issue, and has been merged. Hopefully this resolves the issue fully, as noted we may want to circle back around to this and refactor some code but I think there are other more pressing issues at this moment.
