### ISSUE TITLE
Tilt axis alignment (manual): change 'enter' and 'return' keys default action

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#872]
Im working with the tilt axis alignment (manual) GUI in the newest release. If you change a number then the GUI does not update until you click somewhere. (This is a known QT issue).

However, my first instinct is to press the 'enter' key to update the GUI. By default this exits the GUI and starts the shift/rotate functions. I constantly have to start this process over due to my own reflexes.

Can you change the default behavior such that 'enter' or 'return' do not accept the current conditions of the GUI?

**Comment by cryos** [comment]
That is a great suggestion, I was looking at the interaction in this dialog today and spotted a few issues. We will see if we can improve it, and make this more intuitive.

**Comment by ercius** [comment]
> I was looking at the interaction in this dialog today and spotted a few issues
Regarding this: It is also not possible to zoom or pan in the left or center reconstruction window. Only the right reconstruction window can be zoomed and panned with the middle mouse button. That is worth fixing if possible.

**Comment by mathturtle** [comment]
I'll look at why those reconstruction slices can't be zoomed.  It is probably something simple.  I'm not sure about the 'enter' thing... I looked at it before and it gets tricky.  You have to grab they key events yourself, and I don't remember where you have to grab them to make it work.
