### ISSUE TITLE
Stop pipeline from executing

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#873]
Is it possible to delete multiple pipeline operators at once without having the pipeline execute between each one?

For example, if you make a mistake in the Tilt Axis Alignment (manual) GUI then you have to delete a rotate and a translate operator before you can try again. Its very slow and inefficient.

**Comment by cryos** [comment]
I will see if we can expose a method of pausing the pipeline, or perhaps selecting multiple operators to delete. Thank you for the feedback, this is not optimal when you want to remove multiple items.
