### ISSUE TITLE
Remove top layout tab UI to reclaim some space

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#874]
We don't really use this feature so it might be nice to get this space back.

**Comment by Hovden** [comment]
I agree that layout / renderview UX could use some optimization. I'm open to ditching the tabs—but wonder the role they might play in stats segmentation work. @cquammen

**Comment by cquammen** [comment]
Do you mean just this part?

![image](https://cloud.githubusercontent.com/assets/360056/22754350/3a347128-ee0d-11e6-8d79-7cba1a261eaf.png)

Or the whole 

![image](https://cloud.githubusercontent.com/assets/360056/22754373/516a80ee-ee0d-11e6-9358-65d1827a2ac1.png)

As @Hovden suggests, we'll need to be able to have multiple views open and we'll want to be able to close them I would imagine, so we'll need layout controls to do that.

**Comment by cryos** [comment]
I just mean the top thing, Layout #1, etc. It is not well integrated, and I think the splits, etc in the RenderView will be more than enough for our use case, and would free up a good chunk of space (i.e. Layout #1, the +, etc would be removed).

**Comment by cquammen** [comment]
Just wanted to clarify. Right, the tab portion shouldn't be necessary for anything we are doing or have planned.

**Comment by cryos** [comment]
Yes, to avoid any confusion, I mean remove this, and all the empty space left to its right on Linux (and to either side of it on macOS).

![image](https://cloud.githubusercontent.com/assets/42214/22755017/6e9ef06c-ee0f-11e6-8e31-3e74f17d09b2.png)

**Comment by cryos** [comment]
I very much want to keep 
![image](https://cloud.githubusercontent.com/assets/42214/22755052/8c9a528c-ee0f-11e6-93f6-f8de31b1ad7d.png)

**Comment by cryos** [comment]
I also want to figure out why the icons are so bad on the Mac! Along with the text.

**Comment by cquammen** [comment]
Here's what I have so far:

![image](https://cloud.githubusercontent.com/assets/360056/23755606/ef14c3d8-04ae-11e7-808d-ac7710951646.png)

There is still some vertical space that could be saved, but it is proving elusive to find out where that space is added.

**Comment by cryos** [comment]
It looks better, shame about the vertical space but I would take this as a step in the right direction.
