### ISSUE TITLE
Histogram colorscale incorrect after transform

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#883]
1) Square root data
2) Histogram colorbar is incorrect:
<img width="1248" alt="screen shot 2017-02-09 at 4 51 35 pm" src="https://cloud.githubusercontent.com/assets/6197997/22804674/0dbf27a6-eee8-11e6-8ee4-109a2834f27e.png">

**Comment by cryos** [comment]
I am not seeing that here, but testing on Linux. There seem to be some issues with the color bar, I will investigate them as I suspect they are related to it not seeing the full length available during the layout phase.

**Comment by Hovden** [comment]
Yeah, I think it this is a recent issue (OSX). I recall ironing out these sort of issues in the past.

**Comment by yijiang1** [comment]
I see this bug on Mac from time to time, although I don't know how to reproduce it yet.

**Comment by cquammen** [comment]
Checking master (eb115beda0ce45ea5e0b27e2249817096bb5ae8d), I see the color bar shrink immediately after Square Root is run, but then the histogram recomputes and the color bar expands to full size again.

**Comment by cryos** [comment]
This is working now after a number of fixes to the color bar/histogram code.
