### ISSUE TITLE
AutoTiltAxisRotationAlignOperator error

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#887]
```python
Traceback (most recent call last):
  File "Auto Tilt Axis Align", line 55, in transform_scalars
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Failed to execute the script. (:0, )

```

**Comment by yijiang1** [comment]
I don't get this error. Which data are you using?

**Comment by cjh1** [comment]
TiltSeries_NanoParticle_doi_10.1021-nl103400a.tif

**Comment by yijiang1** [comment]
Interesting... I can execute the transform with no error.

**Comment by yijiang1** [comment]
What is in line 55?

**Comment by cjh1** [comment]
@yijiang1 I found this issue, its a python 2 vs 3 issue. In python 2 / is integer division, in python 3 its float division. I have push a fix #889, to use the integer division operator, do we have similar usage else where in other operators?

**Comment by yijiang1** [comment]
> do we have similar usage else where in other operators?

I'll take a look.


So all python code should follow python 3's syntax from now on?
I thought tomviz support both 2 and 3.

**Comment by cjh1** [comment]
> I'll take a look.
Thanks


> So all python code should follow python 3's syntax from now on?
> I thought tomviz supports both 2 and 3.
We want the operators to run using python 2 or 3 ( // is supported by both )

**Comment by yijiang1** [comment]
Does the binary version use python 2 or 3?

**Comment by cjh1** [comment]
2 currently, I am running 3, we will move to 3 in the future.

**Comment by yijiang1** [comment]
I see.
I found some other potential errors for python 3:
Line 36 & 44 in Recon_DFT.py
Line 157 & 228 in Recon_DFT_constraint.py

**Comment by cjh1** [comment]
If you want to push the changes to the PR, I can test them on python 3 for you.

**Comment by yijiang1** [comment]
> push the changes to the PR,

Can I push changes directly to your PR ( #889 )? If yes, how should I do it?

**Comment by cjh1** [comment]
Yes, you should be able to: 

```bash
git remote add cjh1	git@github.com:cjh1/tomviz.git
git fetch cjh1
git checkout  887-integer-division
# Commit you changes
git push cjh1 HEAD
```

**Comment by yijiang1** [comment]
I got Permission denied when executing `git fetch cjh1`

**Comment by cjh1** [comment]
Do you have your ssh keys setup?

**Comment by cjh1** [comment]
If you are using https, the url would be https://github.com/cjh1/tomviz.git

**Comment by cjh1** [comment]
Actually looks like your not in right group to push directly to the PR, so I will go ahead a make that changes, sorry about that.

**Comment by cjh1** [comment]
or you can push another PR ...

**Comment by yijiang1** [comment]
> or you can push another PR ...

I can do this
