### ISSUE TITLE
Tilt series sample data missing angles

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#890]
I loaded the sample data  to test some things out with the manual alignment widget. However, the tilt angles are not loaded with this dataset in 0.9.3. This makes it difficult to use as a test data set.

**Comment by yijiang1** [comment]
Are you able to set tilt angles manually?

**Comment by ercius** [comment]
Yes. But I don't know the correct start/stop/step. Its probably 2 degrees per tilt, but the correct values should be loaded automatically.

**Comment by yijiang1** [comment]
I don't think tomviz ever gets tilt angles when loading a data set.
Are tilt angles stored in typical tilt series files?

**Comment by ercius** [comment]
>I don't think tomviz ever gets tilt angles when loading a data set.

This is true.

>Are tilt angles stored in typical tilt series files?

Some data sets store the tilt angles. Sometimes they are stored in a separate file (i.e. filename.rawtlt in FEI's case). 

>For the star nanoparticle tilt series, the tilt angle increment is 2 degree, so the default parameters should work.

I suggest that the test tilt series data set from the pull down menu should load the data and set the tilt angles.  Otherwise the user has to guess the angles which is not ideal for a test dataset.

**Comment by cryos** [comment]
I can look into improving this.

**Comment by mathturtle** [comment]
It shouldn't be too hard to add to the example data if we just want something custom for that dataset (which is what we have to do for now I think).  If someone can find out the correct angles, I can add that.  But I have no idea what the right values should be.

**Comment by cryos** [comment]
This is now resolved in the latest binaries, and works well in my testing.
