### ISSUE TITLE
Create a transform to segment pores

### ISSUE THREAD

**Issue by thewtex** [OpenChemistry/tomviz#896]
To operate on the LARGE_PtCu_NanoParticles.tiff dataset.

**Comment by cquammen** [comment]
@thewtex I'll be looking at this unless you have a solution ready to go.

**Comment by thewtex** [comment]
@cquammen I'm working on it...

**Comment by cquammen** [comment]
@cryos Is there additional work to do on this or can we close it?

**Comment by cquammen** [comment]
And @thewtex of course.

**Comment by thewtex** [comment]
+1 for closing.
