### ISSUE TITLE
Clone child data set

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#909]
I think it could be useful to be able to clone child data (in other words, make it parent).

**Comment by cryos** [comment]
We need to think about what that would mean for the pipeline, we could promote the source to the top level, but what about if the reconstruction was rerun? If we want to do a deep copy of the data, and disconnect it from the rest of the pipeline it is relatively well defined. We could then safely delete the original data/pipeline without any issues, but its relation to the prior pipeline would be unclear.

**Comment by yijiang1** [comment]
> If we want to do a deep copy of the data, and disconnect it from the rest of the pipeline it is relatively well defined

This is what I'm thinking.

**Comment by cryos** [comment]
This is now working.
