### ISSUE TITLE
Display Camera lighting location

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#912]
Reporting where the light is coming from would add transparency to understanding the final visualization. It is hard for me to know where the light is coming from—I think it is coming from underneath the object in surface render.

**Comment by Hovden** [comment]
Bump.

It would be useful to move the lighting location.

**Comment by cquammen** [comment]
Some enhancements to ParaView to greatly improve lighting controls have been merged to ParaView master, and plans to show widgets that represent lights are coming.

**Comment by Hovden** [comment]
@jtschwar Please test out the new lighting features. I will as well.

**Comment by Hovden** [comment]
Bumping this issue again. It would help with a figure I'm putting together.

**Comment by mathturtle** [comment]
I have a branch that adds the ParaView "Lights Inspector" panel to tomviz.  It requires a ParaView update and the panel from ParaView is fairly complex.  This adds it sort of like the animation panel: it is there and you can use it if you want, but we will probably want to redo it at some point.
