### ISSUE TITLE
Slice Tool: Display Angles

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#92]
In the slice tool properties panel, show the user the current angle of the slice plane.

**Comment by mathturtle** [comment]
What format would be the most useful for this?  Angle of the plane doesn't make much sense to me: do you want the normal vector and a point on the plane?  Or something else?

I know, this is a 0.7 issue, but my 0.6 issues are done (pending bug reports) and I have to do something...

**Comment by Hovden** [comment]
Great. 
The normal vector and the point on the plane would work.

**Comment by mathturtle** [comment]
This should be fixed now.  Both the ParaView and tomviz patches are merged.
