### ISSUE TITLE
On Mac, zooming on a volumetric render is very slow.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#93]
Volumetric rendering on the Mac is very slow and can cause the software to become inoperable. It looks like it is incrementally rendering the full resolution throughout the zoom.

**Comment by Hovden** [comment]
The desired zoom behavior can be seen if you hold "command" key and move the mouse up and down.

**Comment by mathturtle** [comment]
@Hovden Are you still seeing this?  I know some improvements to volume rendering were added recently that may have been pulled in with the ParaView update from a few days ago.

**Comment by Hovden** [comment]
For yesterday's cdash build: Things have gotten worse. Once the object is rotated or zoomed in on, the volume render remains downsampled at all times. The downsampled volume viz is fast, but lowres. [Tested on OSX]

Building the newest tomviz now. Also, cdash appears to be down.

The desired behavior can also be shown on the macbook trackpad by clicking with two fingers and moving up and down.
