### ISSUE TITLE
Crash when deleting multiple transforms

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#933]
0.9.3-212-gd7acad9 on Mac

tomviz crashes when deleting multiple data transforms.
One example:
<img width="381" alt="screen shot 2017-02-23 at 1 58 03 pm" src="https://cloud.githubusercontent.com/assets/13088588/23274382/8bd76764-f9d0-11e6-8be9-c6c44fea02dd.png">

**Comment by mathturtle** [comment]
This should also be fixed since the change is merged.
