### ISSUE TITLE
Skip child-dataset-generating transforms when re-executing pipeline

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#937]
tomviz always executes the entire pipeline like this:
<img width="345" alt="screen shot 2017-02-23 at 4 41 55 pm" src="https://cloud.githubusercontent.com/assets/13088588/23280765/7b093224-f9e8-11e6-87c8-49a29c50ade0.png">

I think we should skip transforms that generate child data set.

**Comment by cjh1** [comment]
@yijiang1 Not sure I understand why we could skip running the transform, does the Reconstruction step not working on the output of the Auto Tilt Axis Shift Align?

**Comment by yijiang1** [comment]
In practice, tomographic reconstruction takes hours to finish. By setting reconstructions to child datasets, I want to avoid repeating time-consuming transforms. 

Here is a solution:
Say I have a pipeline like this:
Transform 1
Transform 2
Transform 3 -> Generates a child
Transform 4
Transform 5 -> Generates a child

If I edit Transform 4, tomviz only re-executes Transform 1, 2, 4, 5.
If I edit Transform 1 or 2, tomviz re-executes everything from 1 to 5.

**Comment by cryos** [comment]
I think we should add the option to detach a child data set to avoid this, but I don't think this would be a good default behavior in the general case. If we wanted to "freeze" then we should mark it as such.

**Comment by yijiang1** [comment]
> I think we should add the option to detach a child data set to avoid this,

Sounds good to me.

**Comment by cryos** [comment]
We will prioritize this

**Comment by cryos** [comment]
This is now resolved.
