### ISSUE TITLE
Make Python Shell Window Embeddable as a Panel in Main Program

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#94]
The Python Shell Window is free floating and separate from the main program. It would be nice to be able to embed this into the main program - like the other QT panels. This way people can type python commands directly into the terminal without switching between windows.

**Comment by mathturtle** [comment]
Notes to self: this doesn't look particularly difficult.  Change from using ParaView's pqPythonDialog to a dock widget containing a pqPythonWidget.

**Comment by mathturtle** [comment]
Harder than it looks.  There is some hardcoded singleton stuff with the python dialog in ParaView that is tricky to get around.

**Comment by cquammen** [comment]
This is done now. ParaView made the Python console dockable, so it came along for free with one of the ParaView bumps in the recent past.
