### ISSUE TITLE
Save child data sets in state file

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#953]
Another suggestion about skipping child dataset transforms.

Is possible to save child datasets in state files instead of only their transforms?
If I share a full tomography pipeline (tilt series + reconstruction + segmentation) with other people, I don't want them repeating hour-long reconstructions.

A less elegant solution is to clone the child data before saving  ( #909 ).

**Comment by cryos** [comment]
I think this is something we need to consider, but it is more difficult. We should look into it though, and see what we can do. I don't think saving it in the state file is realistic unless we make the state file a container (such as a zip) as state files are XML and the data is normally saved in a binary format such as TIFF or HDF5.

**Comment by Hovden** [comment]
Child datasets should be treated the same as unsaved data. States that contain unsaved data should tell the user to save the data before saving state.

**Comment by cryos** [comment]
This is resolved in the new pipeline/state file infrastructure - we are able to save and restore child data, transforms, etc.
