### ISSUE TITLE
Web export exception when built with Python 3

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#954]
$ ./bin/tomviz 
Traceback (most recent call last):
  File "/home/marcus/build/tomvizpy3/lib/site-packages/tomviz/web.py", line 31, in web_export
    'phi': range(0, 360, deltaPhi),
TypeError: 'float' object cannot be interpreted as an integer
Failed to execute the script. (:0, )

**Comment by cjh1** [comment]
@jourdain I can take care of this if you like?

**Comment by jourdain** [comment]
Since you are doing the hackathon, go for it.

**Comment by cjh1** [comment]
This is now resolve by #963
