### ISSUE TITLE
Deleting transforms that are still in progress is not properly handled

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#958]
Binary v0.9.3-247-g98a04f1 on Mac

Two issues:
1. tomviz crashes when deleting transforms (from pipeline) that are still in progress.

2. It's possible to have two transforms in progress. 
    1. Load the sample tilt series data set. Mark it as tilt series.
    2. Do a transform.
    3. Start a reconstruction. Before it finishes, delete the previous transform.<img width="400" alt="screen shot 2017-02-28 at 9 52 22 am" src="https://cloud.githubusercontent.com/assets/13088588/23410145/3f0d3b5a-fd9c-11e6-8046-8d19ff58274f.png">
    4. Now, tomviz re-executes the pipeline and there are two transforms running.<img width="400" alt="screen shot 2017-02-28 at 9 52 33 am" src="https://cloud.githubusercontent.com/assets/13088588/23410152/43c75d60-fd9c-11e6-8a83-99a3ac18dbf6.png">

    5. tomviz crashes if I cancel the dialog.

**Comment by Hovden** [comment]
The right click has been prevented but if if you press the delete key to remove the running transform it crashes tomviz.

**Comment by mathturtle** [comment]
@Hovden too many ways to delete things ;) I missed one.

**Comment by Hovden** [comment]
No worries. It's the art of the bug tester—I have leveled up over the years.

**Comment by cjh1** [comment]
I think this is now resolved by #984
