### ISSUE TITLE
New contour prompts warning "Failed to located Property: Categorical Data"

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#962]
Warning appears on OSX build 271.
Load sample dataset, then load contour.

**Comment by tjcorona** [comment]
The contour method uses API from ParaView that has just been put into place. If you update your ParaView, you should be all set.

**Comment by cryos** [comment]
I pushed ParaView forward in https://github.com/OpenChemistry/tomviz-superbuild/pull/160 so that the binaries will contain this update shortly.

**Comment by cryos** [comment]
This should be resolved now.
