### ISSUE TITLE
Investigate possible memory leaks when running pipeline

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#976]

**Comment by cjh1** [comment]
OK, this should now be resolved by the following VTK fix:

https://gitlab.kitware.com/vtk/vtk/merge_requests/2566

This was our heap profile for 10 executions of the invert operator before this fix:

![before](https://cloud.githubusercontent.com/assets/1031053/23723348/d64c4292-0416-11e7-98d3-eb2fd174384d.png)

And this is our profile with the VTK fix:

![after](https://cloud.githubusercontent.com/assets/1031053/23723371/e603da88-0416-11e7-9990-3b371d86b21b.png)

**Comment by cryos** [comment]
Thanks for digging into this @cjh1! I know it has been quite a bit of work, but our limited memory thanks you! Let's make sure we keep track of this and ensure it is in our next release.

**Comment by Hovden** [comment]
Great find. Big impact for serious researchers using tomviz.

**Comment by ercius** [comment]
Excellent work. This will help a lot.

**Comment by cquammen** [comment]
Is this issue ready to be closed?

**Comment by cjh1** [comment]
Yes :+1:
