### ISSUE TITLE
QObject::connect: invalid null parameter (:0, ) when quiting tomviz

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#981]
Binary v0.9.3-311-gaca2d21 on Mac

1. Load sample dataset
2. Quit or reset (File -> Reset) tomviz.
3. Output message prints 
QObject::connect: invalid null parameter (:0, )

**Comment by mathturtle** [comment]
I'm fairly certain I introduced these... I thought I had cleaned them all up, but I guess I missed some.  I'll look into it.
