### ISSUE TITLE
Automatic in-plane rotation finder

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#99]
tomviz should have an automatic routine for determining the rotation of images in a tilt series relative to the tilt axis.  

This will probably be an implementation of Yi's FFT variance minimization algorithm.

**Comment by Hovden** [comment]
I created a label "Reconstruction" to better categorize topics that will be require tomographic expertise. I expect many of these topics will utilize Cornell developed algorithms and approaches toward reconstruction.
